Text_SwordsDanceTeach::
    .string "Buraya pek çok kişi gelmez.\p"
    .string "Eğer burada antrenman yaparsam,\n"
    .string "daha güçlü olacağımı biliyorum.\p"
    .string "Evet, daha güçlü ve daha güçlü…\p"
    .string "Böyle bir hareket öğrenmek\n"
    .string "ister misin?\l"
    .string "Bu KILIÇ DANSI.$"

Text_SwordsDanceDeclined::
    .string "İyi, o da iyi.$"

Text_SwordsDanceWhichMon::
    .string "Tamam, hangi POKéMON'a\n"
    .string "öğretmem gerektiğini seç.$"

Text_SwordsDanceTaught::
    .string "Keşke sürekli daha da güçlü\n"
    .string "olabilsek, öyle değil mi?$"

SevenIsland_Text_IslandSign::
    .string "YEDİNCİ ADA\n"
    .string "Sonsuzluk Adası$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "Bu adalar, adaların yedi tane\n"
    .string "olması nedeniyle SEVII ADALARI\l"
    .string "olarak adlandırılır… En azından\l"
    .string "gençlerin inancı bu yönde.\p"
    .string "Gerçek şu ki, bu adalar yedi günde\n"
    .string "oluştuğu söylendiği için böyle\l"
    .string "adlandırılmış.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "Bu ada, doğal durumuna neredeyse\n"
    .string "dokunulmamış bir şekilde bırakılmış.\p"
    .string "Bu yüzden etrafta dolaşmak biraz\n"
    .string "zor olabilir.$"
