OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "BILL: Merhaba!\n"
    .string "CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "CELIO: BILL!\n"
    .string "Buralara geldiğine inanamıyorum.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "BILL: Kesinlikle!\n"
    .string "Araştırman nasıl gidiyor?\p"
    .string "…Bir saniye bekle.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, bu benim arkadaşım CELIO.\n"
    .string "O bir PC MANYAĞI!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "CELIO, bu {PLAYER}, yükselen\n"
    .string "POKéMON ŞAMPİYONU adayı!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "CELIO, bu {PLAYER},\n"
    .string "şimdiki POKéMON ŞAMPİYONU!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "CELIO: Bu gerçekten etkileyici.\p"
    .string "Söylemek istemiyorum,\n"
    .string "ama dövüşmek için\l"
    .string "hiç yeteneğim yok.\p"
    .string "Neyse ki, tanıştığıma memnun oldum.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "BILL: Hadi, bana anlat.\n"
    .string "Makinen nasıl çalışıyor?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "CELIO: Makine iyi çalışıyor,\n"
    .string "ama çok uzaktayız.\p"
    .string "Bu adadaki PC'ler seninkilerle\n"
    .string "bağlanamıyor, BILL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "BILL: Oh, öyle mi?\n"
    .string "Tamam, bir bakayım.\p"
    .string "…Biraz bekle…\n"
    .string "Çalıştıracağımızı düşünüyorum.\l"
    .string "Yardım edeyim, tamam mı?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, biraz bekler misin?\p"
    .string "…Aslında, bir iyilik isteyebilir\n"
    .string "miyim?\p"
    .string "Bu adanın yanındaki adaya\n"
    .string "İKİNCİ ADA denir.\p"
    .string "Orada bir OYUN KÖŞESİ işleten bir\n"
    .string "adam var.\p"
    .string "O, nadir taşlara ve mücevherlere\n"
    .string "bayılır.\p"
    .string "Biz, bu konuda takıntılıyız.\p"
    .string "Bu yüzden, ona bu METEOR'u\n"
    .string "götürür müsün?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER}, BILL'den METEOR\n"
    .string "kabul etti.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "CELIO: {PLAYER}, eğer\n"
    .string "İKİNCİ ADA'ya gideceksen,\l"
    .string "bunu al lütfen.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "Bu, yerel adalar için feribot\n"
    .string "hizmeti için bir BİLET.\p"
    .string "Bu, BİRİNCİ, İKİNCİ, ÜÇÜNCÜ ADA\n"
    .string "arası seyahat etmene izin verecek.\p"
    .string "Oh, bunu da almalısın.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER}, HARİTA için ek bir sayfa\n"
    .string "aldı!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER}, bir HARİTA aldı!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "BILL: Seni sonra yakalarım!\n"
    .string "Diğer arkadaşa selam söyle!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "Hmm…\p"
    .string "Bunu şöyle deneyelim…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "Oh, hey, {PLAYER}!\p"
    .string "Gördün mü?\n"
    .string "PC'yi çalıştırdık!\p"
    .string "CELIO'ya göstereceğim birkaç şey\n"
    .string "var.\p"
    .string "Biraz daha dolaşabilir misin?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "BILL'in zamanını çok aldığım için\n"
    .string "özür dilerim.\p"
    .string "Ayrıca, ziyaretiniz sırasında\n"
    .string "kötü bir ev sahibi olduğum için\l"
    .string "özür dilerim.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "Normal PC hizmetleri mevcut değil…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "BILL: Oh, hey!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "BILL: Nerede kaldın?\p"
    .string "İyi vakit geçirdin mi?\p"
    .string "Hallettik.\n"
    .string "PC'ler çalışıyor!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "CELIO: İş inanılmaz derecede hızlı\n"
    .string "bitti.\p"
    .string "BILL inanılmaz bir adam…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "BILL: Hayır, hayır! Bana neredeyse\n"
    .string "yapacak bir şey kalmamıştı.\p"
    .string "CELIO, bunu asıl sen başardın.\n"
    .string "Çok şey öğrendin.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "CELIO: Oh, gerçekten mi?\n"
    .string "Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "BILL: Tamamdır.\n"
    .string "Buradaki işim bitti.\l"
    .string "Artık KANTO'ya geri dönmeliyiz.\p"
    .string "CELIO, tekrar görüşürüz.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "CELIO: {PLAYER}, bugün seni yalnız\n"
    .string "gönderdiğimiz için gerçekten\l"
    .string "üzgünüm.\p"
    .string "Söz veriyorum, bir gün bu adaları\n"
    .string "sana gezdireceğim.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "CELIO: Merhaba!\n"
    .string "Her zamanki gibi çok meşgulsün.\p"
    .string "Nasıl gidiyor?\p"
    .string "Şu anda Ağ Makinesini\n"
    .string "modifiye ediyorum.\p"
    .string "Makineyi bitirdiğimde, ilk kullanan\n"
    .string "sen olacaksın, {PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "CELIO: {PLAYER}, nasıl gidiyor?\p"
    .string "Oh, öyle mi?\n"
    .string "Daha fazla POKéMON yakalamışsın.\p"
    .string "Biliyor musun?\n"
    .string "Belki sana faydalı olabilirim.$"
    
OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "Ağ Makinesi'ni\n"
    .string "şu anda değiştiriyorum.\p"
    .string "Onu uzun mesafelerdeki\n"
    .string "takasları yapabilecek şekilde\l"
    .string "değiştiriyorum.\p"
    .string "Bittiğinde, uzaklardaki\n"
    .string "EĞİTİCİLERDEN egzotik POKéMON\l"
    .string "takas edeceksin.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "Ancak, küçük bir pürüz var.\p"
    .string "Bağlantının çalışması için\n"
    .string "Makine'nin özel bir taşa\l"
    .string "ihtiyacı var.\p"
    .string "Bu taşın BİRİNCİ ADA'da olduğu\n"
    .string "söyleniyor, ama henüz bulamadım.\p"
    .string "Kim bilir nerede olabilir.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "Taşı bulmaya çalışıyordum\n"
    .string "hatta ders çalışırken bile.\p"
    .string "Sonuç olarak, ne aramalarımda\n"
    .string "ne de derslerimde ilerleme kaydedemedim…\p"
    .string "BILL'e güvenirsem, araştırmam\n"
    .string "ilerlerdi, eminim.\p"
    .string "Ama bu sefer, işleri kendim\n"
    .string "yapmak istiyorum.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "Oh!\n"
    .string "Bu- bu…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER}, CELIO'ya YAKUT'u\n"
    .string "verdi.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "Teşekkür ederim!\n"
    .string "{PLAYER}, sen harikasın.\p"
    .string "… … …  … … …\p"
    .string "Um… Senden bir büyük iyilik\n"
    .string "daha isteyebilir miyim?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "Bu… Bu garip bir şey değil.\n"
    .string "Lütfen, yardıma ihtiyacım var.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "Taşları incelerken,\n"
    .string "önemli bir şey keşfettim.\p"
    .string "Bu YAKUT ile eşleşen başka bir taş\n"
    .string "daha var.\p"
    .string "Bu diğer taşın SEVII ADALARI'nda\n"
    .string "olduğu söyleniyor.\p"
    .string "{PLAYER}, lütfen, diğer taşı da\n"
    .string "bulmam gerekiyor.\p"
    .string "{PLAYER}, feribot BİLET'ini\n"
    .string "ve HARİTA'nı alabilir miyim?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER}, ÜÇLÜ-BİLET'i geri verdi\n"
    .string "ve PRİZMA BİLET'i aldı.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "HARİTA için\n"
    .string "ekstra bir sayfa alındı!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "Bu benim kendi feribot BİLET'im.\p"
    .string "Seni tüm SEVII ADALARI'na\n"
    .string "götürecek.\p"
    .string "{PLAYER}, lütfen, yardımın olmadan\n"
    .string "bunu yapamam.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER}, CELIO'ya SAFİR'i\n"
    .string "verdi.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "CELIO: İşte bu, YAKUT ile\n"
    .string "eşleşen taş…\p"
    .string "{PLAYER}, bunu almak için\n"
    .string "çok şey yaşadın, değil mi?\p"
    .string "Bana anlatmana gerek yok. Kolay\n"
    .string "olmadığını biliyorum.\p"
    .string "Çok teşekkür ederim!\p"
    .string "Şimdi senin için çalışmamın zamanı!\n"
    .string "Lütfen bana biraz zaman ver.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "Tamam, bu iyi…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "Başardım!\n"
    .string "LANETTE ile bağlantı kurdum!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, başardım!\p"
    .string "HOENN bölgesindeki\n"
    .string "EĞİTİCİLER ile bağlantı kurdum!\p"
    .string "Sonunda, Ağ Makinesi tamamen\n"
    .string "çalışır hale geldi!\p"
    .string "{PLAYER}, hepsi senin sayende!\p"
    .string "Sayende hayalim gerçek oldu…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "Ben…\n"
    .string "Ağlamıyorum.\p"
    .string "Benim için bu kadar yeter!\p"
    .string "{PLAYER}, egzotik POKéMON aramaya\n"
    .string "devam edeceksin, değil mi?\p"
    .string "Sana en iyi şansı diliyorum!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "CELIO: Merhaba!\p"
    .string "{PLAYER}, senin hakkında\n"
    .string "dedikodular duyuyorum.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, en sevdiğin POKéMON\n"
    .string "türü nedir?\p"
    .string "BILL bir POKéMANYAK olduğu için\n"
    .string "her türü seviyor.\p"
    .string "Görünüşe göre, ilk yakaladığı\n"
    .string "POKéMON bir ABRA idi.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "Bu arada, {PLAYER}, sen\n"
    .string "PALLET KASABASI'dansın, değil mi?\p"
    .string "Oranın sessiz ve hoş bir yer\n"
    .string "olduğunu duydum.\p"
    .string "BILL'in memleketi GOLDENROD ŞEHRİ,\n"
    .string "ve ailesi hala orada yaşıyor.\p"
    .string "Oranın oldukça şenlikli,\n"
    .string "canlı bir şehir olduğunu duydum.\p"
    .string "Bir gün oraya gitmek isterim.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, dayanamadığın bir şey\n"
    .string "var mı?\p"
    .string "Görünüşe göre, BILL sütü\n"
    .string "hiç mi hiç sindiremiyor.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "Oh, buraya yabancısın!\n"
    .string "Merhaba! Nereden geldin?\p"
    .string "…PALLET KASABASI?\n"
    .string "Hiç bilmiyorum!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "Bu adada devasa bir volkan var.\p"
    .string "Son zamanlarda patlamadı, bu yüzden\n"
    .string "neden bir yürüyüşün tadını\l"
    .string "çıkarmıyorsun?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "Uzakta yaşayan erkek arkadaşımla\n"
    .string "POKéMON takas edebilmeyi dilerdim…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "Uzakta olan erkek arkadaşımla\n"
    .string "POKéMON takas ettim!\p"
    .string "Herkes bunun için sana\n"
    .string "ve CELIO'ya teşekkür etmemiz\n"
    .string "gerektiğini söylüyor.\p"
    .string "Gerçekten çok teşekkür ederim!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "Ağ Makinesi\n"
    .string "Bağlantı Seviye 0\p"
    .string "…POKéMON Depo Sistemi şuan\n"
    .string "bakım altında…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "Ağ Makinesi\n"
    .string "Bağlantı Seviye 1\p"
    .string "KANTO bölgesi ile\n"
    .string "bağlantı kuruldu.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "Ağ Makinesi\n"
    .string "Bağlantı Seviye 2\p"
    .string "KANTO ve HOENN bölgesi\n"
    .string "ile bağlantı kuruldu.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "ÜÇLÜ-BİLET aldın!$"
