SilphCo_4F_Text_CantYouSeeImHiding::
    .string "Sssst!\n"
    .string "Görmüyor musun, saklanıyorum?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "Ne?\n"
    .string "ROKET TAKIMI gitti mi?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "ROKET TAKIMI, SILPH ŞTİ'nin\n"
    .string "kontrolünü ele geçirdi!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "Ayy!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "Fwahahaha!\n"
    .string "PATRON bu yeri istiyordu!$"

SilphCo_4F_Text_RodneyIntro::
    .string "POKéMON'um bana sadık bir\n"
    .string "hizmetkârdır.$"

SilphCo_4F_Text_RodneyDefeat::
    .string "Olamaz!\n"
    .string "Sizi zayıf POKéMON'lar!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "Kapılar elektronik olarak\n"
    .string "kilitli.\p"
    .string "Kapıları açmak için bir\n"
    .string "ANAHTAR gerekiyor.$"

SilphCo_4F_Text_Grunt2Intro::
    .string "Kaçak tespit edildi!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "Sen kimsin?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "11. kattaki PATRONU\n"
    .string "bilgilendirmeliyim!$"

SilphCo_4F_Text_FloorSign::
    .string "SILPH ŞTİ. GENEL MERKEZİ\n"
    .string "4. KAT$"

