PokemonMansion_1F_Text_TedIntro::
    .string "Sen kimsin?\n"
    .string "Burada kimse olmamalı.$"

PokemonMansion_1F_Text_TedDefeat::
    .string "Auv!$"

PokemonMansion_1F_Text_TedPostBattle::
    .string "Bir anahtar mı dedin?\n"
    .string "Öyle bir şey bilmiyorum.$"

PokemonMansion_1F_Text_JohnsonIntro::
    .string "V-v-vay! Beni korkuttun!\n"
    .string "Seni bir hayalet sandım.$"

PokemonMansion_1F_Text_JohnsonDefeat::
    .string "Tch!\n"
    .string "Asla kazanamıyorum.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
    .string "Burayı tek başıma keşfetmeye\n"
    .string "çıkmıştım, ama ürktüm.\p"
    .string "En iyisi gideyim ben.$"

