SixIsland_GreenPath_Text_JaclynIntro::
    .string "…Ne?\p"
    .string "Evimi hayal ediyordum, ama\n"
    .string "burası mı TELEPORT olduğum yer?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "Büyük bir hata yaptım!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "Çok dalgınım!\p"
    .string "Evime düzgün TELEPORT olmak için\n"
    .string "konsantre olmam lazım!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "YEŞİL YOL\n"
    .string "LABİRENT ÇALI İLERİDE$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "YEŞİL YOL\n"
    .string "Doğa İçin Yeşil Düşün!$"
