FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "BEKÇİ: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah hohee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He hamam heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} ALTIN DİŞ'i\n"
    .string "BEKÇİ'ye verdi.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "BEKÇİ dişlerini taktı!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "BEKÇİ: Teşekkürler, evlat!\n"
    .string "Gerçek bir hayat kurtarıcısın!\p"
    .string "Söylediğim hiçbir şeyi\n"
    .string "anlayamıyorlardı, hiçbir şeyi!\p"
    .string "Utancımdan ofise bile yüzümü\n"
    .string "sokmaya çekiniyordum.\p"
    .string "Buna değdi, sana bir şey vermek\n"
    .string "istiyorum.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "BEKÇİ: Teşekkürler, kızım!\n"
    .string "Gerçek bir hayat kurtarıcısın!\p"
    .string "Söylediğim hiçbir şeyi\n"
    .string "anlayamıyorlardı, hiçbir şeyi!\p"
    .string "Utancımdan ofise bile yüzümü\n"
    .string "sokmaya çekiniyordum.\p"
    .string "Buna değdi, sana bir şey vermek\n"
    .string "istiyorum.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} BEKÇİ'den\n"
    .string "HM04'ü aldı.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "BEKÇİ: HM04, GÜÇ\n"
    .string "hamlesidir.\p"
    .string "Savaş dışında POKéMON'ların\n"
    .string "kayaları oynatmasını sağlar.\p"
    .string "Evet, SAFARI BÖLGESİ'ndeki\n"
    .string "GİZLİ EV'i buldun mu?$"

@ Kullanılmıyor
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "POKéMON fotoğrafları ve fosilleri\n"
    .string "sergileniyor.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Eski POKéMON ürünleri\n"
    .string "sergileniyor.$"
