SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "Dur! Bir söz söyleme!\p"
    .string "Bunu istemiştin!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} BAY PSİŞİK'ten\n"
    .string "TM29 aldı.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "Zaten biliyorsun, değil mi?\n"
    .string "TM29 PSİŞİK.\p"
    .string "Hedefin özel istatistiklerini\n"
    .string "düşürebilecek bir saldırı.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Bunu nereye koyacaksın?\n"
    .string "Yer yok.$"
