RockTunnel_B1F_Text_SofiaIntro::
    .string "Dağlarda kaybolmamak için\n"
    .string "bir yöntem biliyor musun?\p"
    .string "Geçiş işaretleri için dalları\n"
    .string "eğebilirsin.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "Ohhh!\n"
    .string "En iyisini yaptım!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "Eve gitmek istiyorum!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "Hahaha!\n"
    .string "Gücümü yenebilir misin?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "Ayy!\n"
    .string "Kas gücüne yenildim!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "Düşünmekten nefret ettiğim için\n"
    .string "güce önem veriyorum.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "Bir POKéDEX'in var mı?\n"
    .string "Ben de istiyorum.$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "Vay canına!\n"
    .string "Çok kıskandım!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "POKéDEX'ini tamamladığında,\n"
    .string "bana verebilir misin?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "Eee… POKéMON cosplay'i biliyor\n"
    .string "musun?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Eh, bu kadar.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "POKéMON cosplay'i, eğlence için\n"
    .string "POKéMON gibi giyinmektir.\p"
    .string "CLEFAIRY aralarında favoridir.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "POKéMON tekniklerim seni ağlatacak!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "Tamam!\n"
    .string "Sen daha iyi bir teknisyensin!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "Dağlarda çoğunlukla KAYA-tipi\n"
    .string "POKéMON bulacaksın.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "Buraya sık sık gelmiyorum, ama\n"
    .string "sizinle savaşacağım.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "Oh!\n"
    .string "Kaybettim!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "Küçük POKéMON'ları seviyorum.\n"
    .string "Büyükler çok korkutucu!$"

RockTunnel_B1F_Text_EricIntro::
    .string "En iyi atışını yap!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "Vuruldum!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "POKéMON'umu seninkini yenecek\n"
    .string "şekilde yetiştireceğim, çocuk.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Evde POKéMON çizimleri yapıyorum.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "Of…\n"
    .string "Yoruldum…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Ben bir savaşçı değil, sanatçıyım.\n"
    .string "Eve gidip çizime devam edeceğim.$"
