CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Miyav!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "Paranı içeceklere harcama.\n"
    .string "Bunu dene.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Susuzluğa karşı sıcak bir\n"
    .string "ÇAY gibisi yok.$"
    .string "Gerçekten en iyisi.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Sevgili POKéMON'larım bana\n"
    .string "MEOWTH bile para getiriyor!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, merhaba.\n"
    .string "ÇAY'ımı beğendin mi?\p"
    .string "Bu arada, PALLET KASABASI'ndan\n"
    .string "mısın, canım?\p"
    .string "PALLET KASABASI'ndan bir kız,\n"
    .string "adı DAISY, her gün ÇAY içer.\p"
    .string "ÇAY almak için\n"
    .string "CELADON MAĞAZASINA gider.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON KONAĞI\n"
    .string "Yönetici Süiti$"
