CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "Bir POKé FLÜT, uyuyan bir\n"
    .string "POKéMON'u uyandırır.\l"
    .string "Bunu biliyorsun.\p"
    .string "Sadece onların duyabileceği\n"
    .string "bir ses çıkarır.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "FUCHSIA'dan buraya kadar BİSİKLET\n"
    .string "sürdüm.\p"
    .string "BİSİKLET YOLU çok yokuş.\n"
    .string "Bu yüzden çok yorgunum.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "Bir BİSİKLET'im olsaydı,\n"
    .string "BİSİKLET YOLU'na giderdim!$"
