Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "Kız arkadaşımla beraber yeni\n"
    .string "bisikletimle rahat bir turdayım.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "Yeni bisikletlerimizle geziyoruz.\n"
    .string "Birlikte eğleniyoruz.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "Teleskoptan ne göreceğiz bakalım…\p"
    .string "CELADON MAĞAZASI görünüyor!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "Teleskoptan ne göreceğiz bakalım…\p"
    .string "Uzaklarda su üzerinde\n"
    .string "uzun bir yol var.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "Merhaba! Beni tanıyor musun?\n"
    .string "PROF. OAK'ın asistanlarından\l"
    .string "biriyim.\p"
    .string "Eğer POKéDEX'iniz 40 tür hakkında\n"
    .string "veri içeriyorsa, bir ödül\l"
    .string "vermem gerekiyor.\p"
    .string "PROF. OAK bana senin için bir\n"
    .string "PARA TILSIMI emanet etti.\p"
    .string "Öyleyse, {PLAYER}, sana sorayım.\p"
    .string "En az 40 çeşit POKéMON verisi\n"
    .string "topladın mı?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "Harika! {STR_VAR_3} çeşit POKéMON\n"
    .string "yakaladın veya sahip oldun!\p"
    .string "Tebrikler!\n"
    .string "İşte bu senin olsun!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} asistanın verdiği PARA\n"
    .string "TILSIMI'nı aldı.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "PARA TILSIMI, POKéMON'un\n"
    .string "tutabileceği bir eşyadır.\p"
    .string "Eğer POKéMON savaşta kazanırsa,\n"
    .string "daha fazla para kazanırsın.$"
