FuchsiaCity_Text_DidYouTrySafariGame::
.string "SAFARI oyununu denedin mi?\p"
.string "Yalnızca orada yakalanabilen\n"
.string "bazı nadir POKéMON'lar var$"

FuchsiaCity_Text_SafariZoneZooInFront::
.string "SAFARI BÖLGESİ'nin önünde\n"
.string "bir hayvanat bahçesi var$"

FuchsiaCity_Text_WheresSara::
.string "ERIK: SARA nerede?\n"
.string "Burada buluşacağımızı söylemiştim.$"

FuchsiaCity_Text_ItemBallInThere::
.string "Oradaki top şeklindeki eşya…\n"
.string "Onu mu istiyordun?\p"
.string "Ben de!\n"
.string "…Huh? O bir POKéMON mu?$"

FuchsiaCity_Text_CitySign::
.string "FUCHSIA ŞEHRİ\n"
.string "İşte! Tutku Pembesi!$"

FuchsiaCity_Text_SafariZoneSign::
.string "POKéMON CENNETİ\n"
.string "SAFARİ BÖLGESİ$"

FuchsiaCity_Text_SafariGameSign::
.string "SAFARİ OYUNU\n"
.string "POKéMON-U-YAKALA!$"

FuchsiaCity_Text_WardensHomeSign::
.string "SAFARİ BÖLGESİ\n"
.string "BEKÇİ'NİN EVİ$"

FuchsiaCity_Text_SafariZoneOfficeSign::
.string "POKéMON CENNETİ!\n"
.string "SAFARİ BÖLGESİ'ne hoş geldiniz!\l"
.string "SAFARİ BÖLGESİ OFİSİ$"

FuchsiaCity_Text_GymSign::
.string "FUCHSIA ŞEHRİ POKéMON SALONU\n"
.string "LİDER: KOGA\l"
.string "Zehirli Ninja Ustası$"

FuchsiaCity_Text_ChanseySign::
.string "İsim: CHANSEY\n"
.string "Onu yakalamak tamamen şans.$"

FuchsiaCity_Text_VoltorbSign::
.string "İsim: VOLTORB\n"
.string "Şekli aynı bir POKé TOPU.$"

FuchsiaCity_Text_KangaskhanSign::
.string "İsim: KANGASKHAN\p"
.string "Karnındaki kesesinde yavrularını\n"
.string "büyüten bir anne POKéMON.$"

FuchsiaCity_Text_SlowpokeSign::
.string "İsim: SLOWPOKE\p"
.string "Dost canlısı ve çok yavaş\n"
.string "hareket eder.$"

FuchsiaCity_Text_LaprasSign::
.string "İsim: LAPRAS\n"
.string "Denizlerin kralı olarak bilinir.$"

FuchsiaCity_Text_OmanyteSign::
.string "İsim: OMANYTE\n"
.string "Çok nadir bir POKéMON, bir\l"
.string "fosilden yeniden üretildi.$"

FuchsiaCity_Text_KabutoSign::
.string "İsim: KABUTO\n"
.string "Çok nadir bir POKéMON, bir\l"
.string "fosilden yeniden üretildi.$"

FuchsiaCity_Text_Ellipsis::
.string "……$"

Text_SubstituteTeach::
.string "Ah, keşke bir KANGASKHAN bebeği\n"
.string "olsaydım.\p"
.string "Bir bebeğin yerine geçmeyi çok\n"
.string "isterdim…\p"
.string "Ve anne KANGASKHAN'ın karnındaki\n"
.string "keseye sokulmayı.\p"
.string "Ama sadece POKéMON'lar KOPYA\n"
.string "tekniğini kullanabilir…\p"
.string "Bir POKéMON'unuza KOPYA\n"
.string "öğretmemi ister misiniz?$"

Text_SubstituteDeclined::
.string "Oh, gerçekten mi?\n"
.string "KOPYA çok eğlenceli görünüyor…$"

Text_SubstituteWhichMon::
.string "Hangi POKéMON KOPYA öğrenmek?\n"
.string "ister?$"

Text_SubstituteTaught::
.string "Ah, bir KANGASKHAN'ın kesesine\n"
.string "girmek için neler verirdim$"

FuchsiaCity_Text_MyFatherIsGymLeader::
.string "Babam bu şehrin SALON LİDERİ.\p"
.string "Ben de babam gibi ZEHİR türü\n"
.string "POKéMON'lar kullanmak için\l"
.string "çalışıyorum.$"
