ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "Merhaba!\nNasılsın?\p"
    .string "Burada ne yapıyorum diye sorarsan,\n"
    .string "cevap veriyorum: Altın arıyorum!\p"
    .string "Eğer zengin olursam, KANTO'da\n"
    .string "bir ev alacağım.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "Merhaba! Nasılsın?\n"
    .string "Duymuşsun, altın buldum!\p"
    .string "Hatırlıyorsundur, altın arıyordum.\p"
    .string "Mutluluğumu anlatmam imkansız.\n"
    .string "O yüzden sana bunu veriyorum!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "İşte bir KÜLÇE!\p"
    .string "Bilgelik külçesi veremem, o yüzden\n"
    .string "bu külçe işini görecektir!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Hoppala, çantan dolmuş!\n"
    .string "Sonra veririm, merak etme.$"
