ThreeIsland_Text_IslandSign::
    .string "ÜÇÜNCÜ ADA\n"
    .string "Aile Bağlarının Adası$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "Hahoo!\p"
    .string "Bugünden itibaren bu ada\n"
    .string "bize ait!$"

ThreeIsland_Text_GoBackToKanto::
    .string "Gürültünüzü alın gidin!\n"
    .string "KANTO'ya geri dönün hemen!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "Hey, başka yerde ağla.\n"
    .string "Patronumuz yolda.\p"
    .string "Buraya geldiğinde, sana\n"
    .string "unutamayacağın bir motosiklet\l"
    .string "şovu sunacağız!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "N-ne!? Asla!\n"
    .string "Şimdi bu adadan defolun!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "Bunu bana kim yaptırabilir ki?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "Sen patron musun?\n"
    .string "Hemen KANTO'ya geri dön!$"

ThreeIsland_Text_JustGotHerePal::
    .string "Hah?\p"
    .string "Yeni geldim, dostum.\p"
    .string "Bu düşmanlık nedir?\n"
    .string "Çok soğuk davrandın!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "Takipçilerinin motosikletleriyle\n"
    .string "fesatlık çıkardığını biliyor musun?\p"
    .string "Adada bize ne kadar sorun\n"
    .string "çıkardıklarının farkında mısın?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "Hayır, hiç anlamıyorum.\p"
    .string "Şu yere bir bak.\n"
    .string "Eğlenmeyi hiç bilmiyorsun.\p"
    .string "Bu uyuşuk köyü canlandırdığımız\n"
    .string "için bize teşekkür etmelisin.\p"
    .string "Ama eğer ısrar ediyorsan, bizi\n"
    .string "kovmayı dene de görelim.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "Grr… Sizi korkaklar…\n"
    .string "Anca grupça güçlüsünüz…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "Sen, neye bakıyorsun?\n"
    .string "Bilmiyor musun, bu çok kaba.\p"
    .string "Bunun hakkında bir şeyler mi\n"
    .string "yapmak istiyorsun?$"

ThreeIsland_Text_ThatsSmart::
    .string "Bu akıllıca.\n"
    .string "Burnunu bu işlere sokma.$"

ThreeIsland_Text_Biker1Intro::
    .string "Heh, cesaretini sevdim.\n"
    .string "Biraz para kaybedeceksin, ama…$"

ThreeIsland_Text_Biker1Defeat::
    .string "Nee…\n"
    .string "Bu çocuk da ne!?$"

ThreeIsland_Text_Biker1PostBattle::
    .string "Ah, adamım…\n"
    .string "Sakın gülmeye cüret etme!$"

ThreeIsland_Text_Biker2Intro::
    .string "Sen KANTO'dan değil misin?\n"
    .string "Bizim tarafımızda olmalısın!$"

ThreeIsland_Text_Biker2Defeat::
    .string "Dalga geçmeyi kes!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "Sana ne oluyor, bu kadar\n"
    .string "kızmak falan?\p"
    .string "Hiç havalı değil, adamım!$"

ThreeIsland_Text_Biker3Intro::
    .string "Patronu buraya çağırdık,\n"
    .string "ama sen ortalığı karıştırdın!\p"
    .string "Bizi utandırdın, adamım!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … …\n… … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "Patron, hadi ama, bu çocuk\n"
    .string "hakkında bir şeyler\l"
    .string "yapmalısın!$"

ThreeIsland_Text_PaxtonIntro::
    .string "Seni izledim.\n"
    .string "Bu kadarı artık yeter.\p"
    .string "Kimsin sen, onların dostu\n"
    .string "falan mı?\p"
    .string "O zaman onların adına benimle\n"
    .string "savaşacaksın.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "Tamam, yeter!\n"
    .string "İstediğin gibi ayrılacağız!\p"
    .string "Bu sıkıcı adadan kurtulmak\n"
    .string "bizi mutlu bile eder!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "Hımf! Evet, bu köylülerle\n"
    .string "takılmaya devam et!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "Teşekkürler! O serseriler\n"
    .string "bela arıyordu sanki.\p"
    .string "Ah, bak, POKéMON'ların biraz\n"
    .string "yaralanmış.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER}, bir TAM YENİLENME\naldı.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "Ha?\n"
    .string "Çantan dolu.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "Ciddi anlamda etkileyici\n"
    .string "POKéMON'ların var.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "Senin gibi güçlü birinin burada\n"
    .string "yaşaması harika olurdu.\p"
    .string "Umarım en azından bir süre\n"
    .string "burada kalırsın.\p"
    .string "…Şey pardon?\n"
    .string "LOSTELLE'i mi arıyorsun?\p"
    .string "LOSTELLE bir süre önce\n"
    .string "BAĞ KÖPRÜSÜ'ne doğru gitti.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "ÜÇÜNCÜ ADA aslında en kalabalık\n"
    .string "adalardan biridir.\p"
    .string "Yine de, daha az sıkıcı olabilir.\p"
    .string "Ama o MOTOR ÇETESİ gibi serserileri\n"
    .string "burada tekrar görmek istemem.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "DODUO'yu MEYVE ORMANI'nda\n"
    .string "eğiteceğim.\p"
    .string "Evrimleştiğinde, İKİNCİ ADA'da\n"
    .string "bir oyun oynayacağım.$"

ThreeIsland_Text_Doduo::
    .string "DODUO: Cicikk!$"
