CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "BLAINE ve BAY FUJI'nin\n"
    .string "bir fotoğrafı.\p" 
    .string "Omuz omuza vermişler ve\n"
    .string "gülümsüyorlar.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Her gün POKéMON'lar üzerinde\n"
    .string "çalışıyoruz.\p"
    .string "İnsanlar nadir POKéMON'larını\n"
    .string "incelememiz için getirirler.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "LAB'ın kurucusu DR. FUJI'nin\n"
    .string "bir fotoğrafı!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "POKéMON LAB\n"
    .string "Toplantı Odası$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "POKéMON LAB\n"
    .string "Ar-Ge Odası$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "POKéMON LAB\n"
    .string "Test Odası$"
