MtMoon_1F_Text_MarcosIntro::
    .string "WOW!\n"
    .string "Beni şok ettin!\l"
    .string "…Oh, sen sadece bir çocuksun!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Vay!\n"
    .string "Tekrar şok oldum!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Senin gibi çocuklar burada\n"
    .string "karanlıkta dolaşmamalı.$"

MtMoon_1F_Text_JoshIntro::
    .string "Sen de mağarayı keşfetmeye\n"
    .string "mi geldin?$"

MtMoon_1F_Text_JoshDefeat::
    .string "Kaybetmek berbat!\n"
    .string "Çok kötü.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "Kızlara hava atmak için\n"
    .string "buraya kadar geldim.$"

MtMoon_1F_Text_MiriamIntro::
    .string "Vay! Burası düşündüğümden\n"
    .string "daha büyük!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "Kaybettim!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "Buradan nasıl çıkacağım?\n"
    .string "Çok büyük, kaybolabilirim.$"

MtMoon_1F_Text_JovanIntro::
    .string "Ne!\n"
    .string "Bana gizlice yaklaşma!$"

MtMoon_1F_Text_JovanDefeat::
    .string "POKéMON'um işe yaramıyor!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "Daha güçlü POKéMON'lar bulmam\n"
    .string "lazım. Nerede olabilirler?$"

MtMoon_1F_Text_IrisIntro::
    .string "Ne?\n"
    .string "Arkadaşlarımı burada bekliyorum.$"

MtMoon_1F_Text_IrisDefeat::
    .string "Kaybettim mi?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Buraya bazı çok nadir\n"
    .string "fosillerin olduğunu duydum.$"

MtMoon_1F_Text_KentIntro::
    .string "Mağarada şüpheli adamlar var.\n"
    .string "Peki ya sen?$"

MtMoon_1F_Text_KentDefeat::
    .string "Beni yendin!$"

MtMoon_1F_Text_KentPostBattle::
    .string "Onları gördüm!\n"
    .string "ROKET TAKIMI olduklarından eminim!$"

MtMoon_1F_Text_RobbyIntro::
    .string "CERULEAN ŞEHRİ'ne gitmek için\n"
    .string "bu mağaradan geçmen gerek.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "Kaybettim.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT zorlu bir rakip!\n"
    .string "Ama yakalamayı başarırsan\l"
    .string "ona güvenebilirsin.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Dikkatli ol!\n"
    .string "ZUBAT tam bir kan emicidir!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Merhaba, ben AY DAĞI'nda fosil\n"
    .string "bulmak için kazı yapıyorum.\p"
    .string "Bazen, PEWTER SALONU'ndan BROCK\n"
    .string "bana yardım ediyor.$"


