PokemonMansion_B1F_Text_LewisIntro::
    .string "Uh-oh!\n"
    .string "Nerede olduğumu unuttum.$"

PokemonMansion_B1F_Text_LewisDefeat::
    .string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
    .string "Her yerde eşyalar var.\n"
    .string "Buraların sakinleri bırakmış olmalı.$"

PokemonMansion_B1F_Text_IvanIntro::
    .string "Bu yer bir laboratuvar için ideal.\n"
    .string "Ne kadar çok alan var.$"

PokemonMansion_B1F_Text_IvanDefeat::
    .string "Bana bunu neden yaptın?$"

PokemonMansion_B1F_Text_IvanPostBattle::
    .string "Burayı sevdim.\n"
    .string "Çalışmalarım için uygun bir yer.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .string "Günlük: 1 Eylül\n"
    .string "MEWTWO aşırı güçlü.\p"
    .string "Vahşi eğilimlerini\n"
    .string "kontrol edemedik…$"
