SevenIsland_TrainerTower_Text_DarioIntro::
    .string "Yaklaşmanı hissettim.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Pes et…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "Gelecekte birçok kişiyle\n"
    .string "tanışacağını hissediyorum.\p"
    .string "Sizi garip bir gücün\n"
    .string "birleştireceğini düşünüyorum.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "Bu adada, tuhaf POKéMON'lar uyuyor.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "Ne muhteşem bir EĞİTMEN!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "Bu adada, tuhaf POKéMON'lar uyur.\p"
    .string "Onlar seni mi bekliyor?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "EĞİTMEN KULESİ GİRİŞİ\n"
    .string "Zorluğa Katıl, EĞİTMENLER!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "EĞİTMEN KULESİ İLERİDE$"

@ Kullanılmayan metin, belki Trainer Tower'ın kilitli olduğu anlamına geliyor
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "şimdi giremezsin gibi görünüyor‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワー　açık!\n"
    .string "Hemen girelim!$"
