VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "PIKACHU'umun kuyruğuna\n"
    .string "bakar mısın? Çok tatlı!$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hıh! Benim PIKACHU'um\n"
    .string "ondan iki kat sevimli!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "SEEL'imi çok seviyorum!\n"
    .string "Çok tatlı!\p"
    .string "Sarıldığımda, “Kiyuuuh” diye\n"
    .string "ses çıkarıyor!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Amanın!\p"
    .string "SEEL'im ondan çok daha güzel.\n"
    .string "Hem de iki kat!$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Pi! Pikaçuu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kiyoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "POKéMON FAN KULÜBÜ'nün başkanıyım!\p"
    .string "100'den fazla POKéMON'a sahibim!\p"
    .string "POKéMON konusunda çok seçiciyimdir!\n"
    .string "Gerçekten öyleyim!\p"
    .string "Öyleyse…\p"
    .string "POKéMON'larım hakkında konuşmak\n"
    .string "için mi geldin?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Harika!\n"
    .string "O zaman dikkatle dinle!\p"
    .string "Favori RAPIDASH'im…\p"
    .string "…tatlı… sevimli… akıllı…\n"
    .string "ve… muhteşem… öyle değil mi?\l"
    .string "evet… o…\l"
    .string "harika…\l"
    .string "tatlı…\l"
    .string "Uyurken sarıl… sıcak ve\l"
    .string "sevimli… muhteşem…\l"
    .string "büyüleyici…\l"
    .string "…Aman Tanrım! Saat kaç olmuş!\l"
    .string "Sizi çok uzun süre tuttum!\p"
    .string "Dinlediğin için teşekkürler!\n"
    .string "İşte bu senin olsun!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER}, BAŞKAN'dan bir\n"
    .string "BİSİKLET KUPONU aldı.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Bu KUPONU CERULEAN ŞEHRİ'ndeki\n"
    .string "BİSİKLET DÜKKANI'na götür.\p"
    .string "Ücretsiz bir BİSİKLET alabilirsin.\p"
    .string "Endişelenme, favori FEAROW'um\n"
    .string "HER YERE UÇAR.\p"
    .string "Bu yüzden BİSİKLETE ihtiyacım\n"
    .string "yok.\p"
    .string "Umarım keyifli sürüşler yaparsın!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Ah. Hikayemi dinlemek için\n"
    .string "geri dön!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Merhaba, {PLAYER}!\p"
    .string "POKéMON'larım hakkında bilgi\n"
    .string "almak için mi geldin?\p"
    .string "Hayır mı?\n"
    .string "Yazık!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Buna yer açın!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "BAŞKANımız POKéMON konusunda\n"
    .string "çok konuşkan.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Diğer EĞİTMENLER'i kibarca\n"
    .string "dinleyelim!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Eğer biri övünürse, sen de\n"
    .string "övün!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "BAŞKANımız POKéMON'larını\n"
    .string "gerçekten seviyor.\p"
    .string "Ama POKéMON'lar tarafından\n"
    .string "en çok sevilen kişi DAISY, diye\n"
    .string "düşünüyorum.$"
