VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "PIKACHU'umun kuyruğuna bakar\n"
    .string "mısın? Çok tatlı!$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Hıh! Benim PIKACHU'um ondan\n"
    .string "iki kat sevimli!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "SEEL'imi çok seviyorum!\n"
    .string "Çok tatlı!\p"
    .string "Sarıldığımda, “Kiyuuuh” diye\n"
    .string "ses çıkarıyor!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Amanın!\p"
    .string "SEEL'im ondan çok daha güzel.\n"
    .string "Hem de iki kat!$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Pi! Pikaçuu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kiyoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "POKéMON FAN KULÜBÜ'nün başkanıyım!\p"
    .string "100'den fazla POKéMON yetiştirdim!\p"
    .string "POKéMON konusunda çok seçiciyim!\n"
    .string "Cidden öyleyim!\p"
    .string "Öyleyse…\p"
    .string "POKéMON'larım hakkında konuşmak\n"
    .string "için mi geldin?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Harika!\n"
    .string "O zaman dikkatle dinle!\p"
    .string "Favori RAPIDASH'im…\p"
    .string "…tatlı… sevimli… akıllı…\n"
    .string "ve… muhteşemdir.\l"
    .string "Evet… o…\l"
    .string "harika…\l"
    .string "tatlı…\l"
    .string "Uyurken sarılırım… sıcak ve\l"
    .string "sevimlidir… muhteşemdir…\l"
    .string "büyüleyicidir…\l"
    .string "…Aman Tanrım! Saat kaç olmuş!\l"
    .string "Sizi çok uzun süre tuttum!\p"
    .string "Dinlediğin için teşekkürler!\n"
    .string "İşte bu senin olsun!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER}, BAŞKAN'dan bir\n"
    .string "BİSİKLET KUPONU aldı.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Bu kuponu CERULEAN ŞEHRİ'ndeki\n"
    .string "BİSİKLET DÜKKANI'na götür.\p"
    .string "Ücretsiz bir BİSİKLET\nalabilirsin.\p"
    .string "Endişelenme, favori FEAROW'um\n"
    .string "her yere uçar.\p"
    .string "Bu yüzden BİSİKLETE ihtiyacım\n"
    .string "yok.\p"
    .string "Umarım keyifli sürüşler\nyaparsın!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Ah. Hikayemi dinlemek için\n"
    .string "geri dön!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Merhaba, {PLAYER}!\p"
    .string "POKéMON'larım hakkında bilgi\n"
    .string "almak için mi geldin?\p"
    .string "Hayır mı?\n"
    .string "Ne yazık!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Hiç yerin yok!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Başkanımız POKéMON konusunda\n"
    .string "çok konuşkandır.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Diğer EĞİTMENLER'i kibarca\n"
    .string "dinleyelim!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "Eğer biri övünürse, sen de\n"
    .string "övün!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "BAŞKAN POKéMON'larını\n"
    .string "gerçekten çok seviyor.\p"
    .string "Ama POKéMON'lar tarafından en\n"
    .string "çok sevilen kişi DAISY diye\l"
    .string "düşünüyorum.$"
