FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "SAFARI BÖLGESİ bekçisi yaşlı\n"
    .string "ama hala çok aktif.\p"
    .string "Tüm dişleri takmaymış.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm?\n"
    .string "BILL'i tanıyor musun?\p"
    .string "O benim torunum!\p"
    .string "Çocukken bile her şeyi\n"
    .string "toplamaya bayılırdı!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL POKéMON verilerini\n"
    .string "kendi PC'sine kaydeder.\p"
    .string "Sana gösterdi mi?$"
