Route7_EastEntrance_Text_ThirstyOnGuardDuty::
    .string "Nöbet görevindeyim.\n"
    .string "Ama çok susadım!\p"
    .string "Dur, yol kapalı.$"

Route7_EastEntrance_Text_ThatTeaLooksTasty::
    .string "O ÇAY…\n"
    .string "Çok lezzetli görünüyor…$"

Route7_EastEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Ne? Bu içeceği içebilir miyim?\n"
    .string "Teşekkürler!\l"
    .string "… …\l"
    .string "Yudum, yudum…\l"
    .string "… …\l"
    .string "Yutkun…\l"
    .string "SAFFRON ŞEHRİ'ne gitmek\l"
    .string "istiyorsan…\l"
    .string "… …\l"
    .string "Geçebilirsin.\p"
    .string "Bu çayı diğer nöbetçilerle\n"
    .string "paylaşacağım!\l"
    .string "Teşekkürler!$"

Route7_EastEntrance_Text_HiHowsItGoing::
    .string "Merhaba, nasıl gidiyor?$"
