SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .string "Kızım çok bencil.\n"
    .string "Arkadaşı yok denecek kadar az.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .string "Kızım insanları taklit etmeyi\n"
    .string "çok seviyor.\p"
    .string "Bu beni çok rahatsız ediyor.\p"
    .string "Taklit yeteneği ona burada\n"
    .string "TAKLİTÇİ lakabını kazandırdı.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .string "CHANSEY: Çen! Si!$"
