PokemonTower_7F_Text_Grunt1Intro::
    .string "Ne istiyorsun?\n"
    .string "Neden buradasın?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "Pes ediyorum!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "Bunu unutmayacağım!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "Bu yaşlı adam\n"
    .string "SIĞINAĞIMIZA geldi.\p"
    .string "Sonra ROKET TAKIMI'nın\n"
    .string "POKéMON'ları istismar ettiğini\l"
    .string "söylemeye başladı.\p"
    .string "Yani, burada yetişkinler olarak\n"
    .string "konuşuyoruz.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "Lütfen!\n"
    .string "Daha fazla yapma!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "POKéMON'lar para kazanmak için\n"
    .string "iyidir. Neden kullanmayalım?\p"
    .string "İşlerimize karışma!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "Kimseyi kurtaramazsın, çocuk!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "ROKET TAKIMI'na karşı savaşma!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "Bundan kurtulmayacaksın!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "BAY FUJI: Heh?\n"
    .string "Beni kurtarmaya mı geldin?\p"
    .string "Teşekkür ederim. Ama, kendi\n"
    .string "irademle geldim.\p"
    .string "CUBONE'un annesinin ruhunu\n"
    .string "dindirmeye geldim.\p"
    .string "Sanırım MAROWAK'ın ruhu\n"
    .string "sonunda bizi terk etti.\p"
    .string "İlgilendiğin için teşekkür\n"
    .string "ederim.\p"
    .string "Beni takip et, evime gidelim,\n"
    .string "POKéMON EVİ'ne, bu kule'nin\l"
    .string "eteklerinde.$"
