PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Evet, evet.\n"
    .string "Çocuk bileti ¥50.\p"
    .string "Girmek ister misin?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Yine bekleriz!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Evet, ¥50!\n"
    .string "Teşekkürler!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "Yeterli paran yok.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Keyfini çıkar.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Arka kapıdan içeri sızamazsın!\n"
    .string "İyi deneme çocuk, ama olmaz.\p"
    .string "Neyse!\n"
    .string "KEHRİBAR nedir biliyor musun?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "KEHRİBAR, antik bir POKéMON'un\n"
    .string "genetik DNA'sını içerir.\p"
    .string "Bir yerlerde POKéMON'ları\n"
    .string "fosillerden diriltmeye çalışan\l"
    .string "bir LABORATUVAR var.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "KEHRİBAR aslında ağaçlardan akan\n"
    .string "yapışkan bir maddedir.\p"
    .string "Antik zamandan kalma bu madde\n"
    .string "taşlaşarak sertleşmiştir.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "Lütfen etrafı dolaşın$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "Uzun ömrüm için minnettar olmalıyım.\p"
    .string "Hiçbir zaman bir ejderhanın kemiklerini\n"
    .string "göreceğimi düşünmedim!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "Sst! Dinle, bu sırrı birine\n"
    .string "anlatmam gerekiyor.\p"
    .string "Bu KEHRİBAR parçasının POKéMON\n"
    .string "DNA'sı içerdiğini düşünüyorum!\p"
    .string "Eğer POKéMON'lar bundan geri\l"
    .string "getirilebilirse, bilim dünyası\n"
    .string "için büyük bir keşif olurdu.\p"
    .string "Ama meslektaşlarım beni dinlemiyor.\p"
    .string "Bu yüzden bir ricam olacak!\p"
    .string "Lütfen bunu bir POKéMON LAB'ında\n"
    .string "incelet.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER}, adamdan ESKİKEHRİBAR\naldı.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Sst!\n"
    .string "ESKİKEHRİBAR'a mutlaka baktır!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "Bunun için yerin yok.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "Sergide nadir, ilkel POKéMON'ların\n"
    .string "iki adet fosiline sahibiz.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "Açık altın renginde güzel bir\n"
    .string "KEHRİBAR parçası var.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "AERODACTYL Fosili\n"
    .string "İlkel ve nadir bir POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "KABUTOPS Fosili\n"
    .string "İlkel ve nadir bir POKéMON.$"
