SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "Dans et, dans et!\n"
    .string "CHANSEY dans ediyor!\p"
    .string "Sen de katıldın, dansa!\n"
    .string "Dans et, dans et!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "Dans etmek ister misin?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "Hadi, dans et!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} CHANSEY dansı yaptı!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "Ahahahaha!\p"
    .string "Bak, şimdi çok neşelisin!\n"
    .string "Şanslı!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "CHANSEY: Chansi! Chansi!$"
