VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "PIDGEY'im ile kuzeydeki\n"
    .string "SAFFRON'a bir mektup gönderiyorum.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Ciuuuv!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Sevgili Pippi,\n"
    .string "Umarım yakında görüşürüz.\p"
    .string "SAFFRON'un ROKET TAKIMI ile\n"
    .string "sorunlar yaşadığı söyleniyor.\p"
    .string "VERMILION ise şu an güvenli.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "Farklı insanlarla mektup\n"
    .string "alışverişi yapmak istiyorum.\p"
    .string "Mektuplarımı taşımaları için\n"
    .string "PIDGEY'lerimi BİRLİK ODASI'na\l"
    .string "gönderiyorum.$"
