Route18_Text_WiltonIntro::
    .string "Yeni POKéMON için tüm\n"
    .string "çimlik alanları kontrol ederim.$"

Route18_Text_WiltonDefeat::
    .string "Hah!$"

Route18_Text_WiltonPostBattle::
    .string "Keşke bir BİSİKLET'im olsaydı!$"

Route18_Text_RamiroIntro::
    .string "Kurukkoo!\n"
    .string "Bu kuş çağrımı beğendin mi?$"

Route18_Text_RamiroDefeat::
    .string "Seni rahatsız etmem gerekiyordu!$"

Route18_Text_RamiroPostBattle::
    .string "Hafta sonları deniz POKéMON'ları\n"
    .string "toplarım çünkü deniz çok yakın.$"

Route18_Text_JacobIntro::
    .string "Bu benim bölgem!\n"
    .string "Buradan defol!$"

Route18_Text_JacobDefeat::
    .string "Zaten!$"

Route18_Text_JacobPostBattle::
    .string "Bu, POKéMON yakalamak için\n"
    .string "en sevdiğim yer.$"

Route18_Text_RouteSign::
    .string "ROTA 18\n"
    .string "CELADON ŞEHRİ - FUCHSIA ŞEHRİ$"

Route18_Text_CyclingRoadSign::
    .string "BİSİKLET YOLU\n"
    .string "Yaya giremez!$"
