Text_SeismicTossTeach::
    .string "Uzayın sırları...\n"
    .string "Yerin gizemleri...\p"
    .string "Bilmediğimiz o kadar çok şey var ki.\n"
    .string "Ama bu bizi çalışmaya itmeli,\p"
    .string "havlu atmaya değil.\p"
    .string "Tek atman gereken şey...\p"
    .string "SİSMİK ATMA?\n"
    .string "Bir POKéMON'a öğreteyim mi?$"

Text_SeismicTossDeclined::
    .string "Öyle mi?\n"
    .string "Bundan vazgeçmeyeceğinden eminim.$"

Text_SeismicTossWhichMon::
    .string "SİSMİK ATMA'yı öğrenmek\n"
    .string "isteyen POKéMON hangisi?$"

Text_SeismicTossTaught::
    .string "Havlu atmadığın için mutluyum.\n"
    .string "Böyle devam et.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "AY TAŞI mı dedin?\p"
    .string "Nesi özel peki?\n"
    .string "Sıradan bir taş gibi görünüyor.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "20 Temmuz 1969!\p"
    .string "İnsanlık ilk kez aya ayak bastı\n"
    .string "o gün.\p"
    .string "O haberi izleyebilmek için\n"
    .string "renkli televizyon almıştım.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "Bu ay uzay sergisi düzenliyoruz.\n"
    .string "Gelip görmelisin.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "Bir PIKACHU istiyorum!\n"
    .string "Çok tatlı!\p"
    .string "Babamdan biri yakalamasını istedim!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Evet, bir PIKACHU, söz veriyorum!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "Uzay Mekiği$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "AY DAĞI'na düşen bir meteor.\n"
    .string "AY TAŞI olduğuna inanılıyor.$"
