SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Nihayet!\p"
    .string "GİZLİ EV'e ulaşan ilk kişi sensin!\n"
    .string "Büyük açılışımız için bir\l"
    .string "kampanya düzenledim,\l"
    .string "ancak kampanya ödülümüzü kimsenin\l"
    .string "kazanamayacağından endişelenmeye\l"
    .string "başlamıştım.\p"
    .string "Tebrikler!\n"
    .string "Kazandın!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER}, görevli tarafından\p"
    .string "HM03'ü aldı!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "HM03, SÖRF hareketidir.\p"
    .string "POKéMON'lar bu hareket sayesinde\n"
    .string "seni suda taşıyabilecek.\p"
    .string "Ayrıca, bu HM tek kullanımlık\n"
    .string "değil, bu yüzden\l"
    .string "istediğin kadar kullanabilirsin.\p"
    .string "Bu muhteşem ödülü kazandığın\n"
    .string "için çok şanslısın!\p"
    .string "Tebrikler!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "Bu muhteşem ödül için yerin yok!\p"
    .string "Lütfen çantada yer aç ve yine gel.$"
