Route19_Text_RichardIntro::
    .string "Önce egzersiz yapıp\n"
    .string "ısınmam lazım.$"

Route19_Text_RichardDefeat::
    .string "Isındım bile!$"

Route19_Text_RichardPostBattle::
    .string "Teşekkürler, çocuk!\n"
    .string "Artık yüzmeye hazırım.$"

Route19_Text_ReeceIntro::
    .string "Dur! Yavaş ol!\n"
    .string "Kalp krizi geçireceksin!$"

Route19_Text_ReeceDefeat::
    .string "Brr!\n"
    .string "Soğukmuş!$"

Route19_Text_ReecePostBattle::
    .string "TENTACOOL'a dikkat et.\n"
    .string "Acı verici şekilde sokarlar.$"

Route19_Text_MatthewIntro::
    .string "Yüzmeyi çok seviyorum!\n"
    .string "Peki ya sen?$"

Route19_Text_MatthewDefeat::
    .string "Karnım ağrıdı!$"

Route19_Text_MatthewPostBattle::
    .string "Deniz POKéMON'larına karşı\n"
    .string "bile yüzebilirim.$"

Route19_Text_DouglasIntro::
    .string "Ufkun ötesinde ne var?$"

Route19_Text_DouglasDefeat::
    .string "Glup!$"

Route19_Text_DouglasPostBattle::
    .string "Orada birkaç ada görüyorum!\n"
    .string "Haydi, gidelim!$"

Route19_Text_DavidIntro::
    .string "POKéMON yakalamaya dalış\n"
    .string "yaptım, ama olmadı.$"

Route19_Text_DavidDefeat::
    .string "İmdat!$"

Route19_Text_DavidPostBattle::
    .string "Deniz POKéMON'larını yakalamak\n"
    .string "için oltaya ihtiyaç var.$"

Route19_Text_TonyIntro::
    .string "Denize bakmak, başıma gelen\n"
    .string "kötü şeyleri unutturuyor.$"

Route19_Text_TonyDefeat::
    .string "Ayy!\n"
    .string "Travmatik!$"

Route19_Text_TonyPostBattle::
    .string "Denize bakıp başıma gelen\n"
    .string "kötü şeyi unutuyorum!$"

Route19_Text_AnyaIntro::
    .string "Oh, ne güzel bir yolculuk!\n"
    .string "Eğer kazanırsam, bana verir misin?$"

Route19_Text_AnyaDefeat::
    .string "Ayy! Kaybettim!$"

Route19_Text_AnyaPostBattle::
    .string "SEAFOAM ADALARI'na daha çok\n"
    .string "var… FUCHSIA'ya dönmek istiyorum.$"

Route19_Text_AliceIntro::
    .string "Yüzmek harika!\n"
    .string "Ama güneş yanığı değil!$"

Route19_Text_AliceDefeat::
    .string "Çarpıldım!$"

Route19_Text_AlicePostBattle::
    .string "Erkek arkadaşım SEAFOAM ADALARI'na\n"
    .string "kadar yüzmek istedi.$"

Route19_Text_AxleIntro::
    .string "Ahoy ahoy!\n"
    .string "Bu sular tehlikeli!$"

Route19_Text_AxleDefeat::
    .string "Ayy!\n"
    .string "Tehlikeliymiş!$"

Route19_Text_AxlePostBattle::
    .string "A-ayaklarım! Kasıldı!\n"
    .string "Glup glup…$"

Route19_Text_ConnieIntro::
    .string "Arkadaşlarımla buraya kadar\n"
    .string "yüzdüm… Yorgunum…$"

Route19_Text_ConnieDefeat::
    .string "Bitkin düşmüş durumdayım…$"

Route19_Text_ConniePostBattle::
    .string "Denizde bir POKéMON'a binmek\n"
    .string "istersem LAPRAS'ı seçerdim.\p"
    .string "LAPRAS çok büyük, bence beni\n"
    .string "denizde kuru tutar.$"

Route19_Text_RouteSign::
    .string "DENİZ ROTASI 19\n"
    .string "FUCHSIA ŞEHRİ - SEAFOAM ADALARI$"

Route19_Text_LiaIntro::
    .string "LIA: Küçük kardeşime bakıyorum.\n"
    .string "O da yeni bir EĞİTMEN.$"

Route19_Text_LiaDefeat::
    .string "LIA: Küçük kardeşime böyle\n"
    .string "davranamazsın!$"

Route19_Text_LiaPostBattle::
    .string "LIA: Küçük kardeşin var mı?\p"
    .string "Umarım ona bir şeyler\n"
    .string "öğretmeye çalışıyorsundur.$"

Route19_Text_LiaNotEnoughMons::
    .string "LIA: Küçük kardeşimle beraber\n"
    .string "savaşmak istiyorum.\p"
    .string "İki POKéMON'un yok mu?$"

Route19_Text_LucIntro::
    .string "LUC: Büyük ablam bana yüzmeyi\n"
    .string "ve POKéMON eğitmeyi öğretti.$"

Route19_Text_LucDefeat::
    .string "LUC: Vay canına!\n"
    .string "Ablamdan daha güçlüsün!$"

Route19_Text_LucPostBattle::
    .string "LUC: Ablam güçlü ve iyi.\n"
    .string "O harika biri!$"

Route19_Text_LucNotEnoughMons::
    .string "LUC: Ablam olmadan savaşmak\n"
    .string "istemiyorum.\p"
    .string "İki POKéMON'un yok mu?$"
