VictoryRoad_1F_Text_NaomiIntro::
    .string "Benim için yeterince güçlü\n"
    .string "müsün bilmiyorum?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "Yenildim…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "Hiç kimseye yenilmek istemedim,\n"
    .string "hele ki senin gibi küçük birine…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "Güçlü olduğunu görebiliyorum.\n"
    .string "Bakalım ne kadar güçlüsün!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "Bir şansım vardı…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Cık!\n"
    .string "Kabul ediyorum, benden daha iyisin!$"

