SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "Bu taş odanın hakkında bir şey\n"
    .string "biliyor musun?\p"
    .string "Bilmiyorum.$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "Bu gerekli değildi.\n"
    .string "Bu kadar sert davranmana gerek yoktu.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "TANOBY HARABELERİ en az 1.500 yıl\n"
    .string "öncesine dayanıyor.\p"
    .string "Ancak neden inşa edildiği\n"
    .string "hala bir gizem.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "Burada gizemli bir POKéMON'un\n"
    .string "uyuduğu söyleniyor.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "Savaşta çok iyi değilim.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "Buradaki gibi başka harabeler de\n"
    .string "olduğunu duydum.\p"
    .string "Acaba diğer gizemli POKéMON'ların\n"
    .string "dinlenme yerleri mi?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "CLIFFORD bana resim yapmayı\n"
    .string "öğretiyor.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "Burada gürültü yaparsak başımız\n"
    .string "belaya girebilir.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "Eski bir binayı resmetmek\n"
    .string "istediğimi söyledim.\p"
    .string "Beni buraya getirdi.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "Bugün dersimizin yanı sıra,\n"
    .string "odayı görmeye geldik.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "Vay canına, gerçekten sıra dışı.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "Ah, kendi başına POKéMON\n"
    .string "araştırması yapıyorsun…\p"
    .string "Evet, gerçekten çok sıra dışı bir\n"
    .string "kişisin.$"
