CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "MEYVE TOZU'ndan çeşitli ilaçlar yaparım\p"
    .string "İyi bir MEYVE TOZU ile\n"
    .string "her türlü ilacı yapabilirim\p"
    .string "Şimdi söyle bana,\n"
    .string "MEYVELERLE ilgilenir misin?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "Ah, iyi! İşte sana\n"
    .string "tam da aradığın şey.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "POKéMON MERKEZLERİ'nin\n"
    .string "ikinci katında, köşede\l"
    .string "bir şey var. Kablosuz\l"
    .string "Bağlantı Cihazı\l"
    .string "kurmuşlar MEYVE ezmek\l"
    .string "için. İşte burada sen\l"
    .string "giriyorsun. Bir ricam\l"
    .string "olacak, sadece sana\l"
    .string "güvenebilirim. Bana\l"
    .string "MEYVE ezerek toz\l"
    .string "yapabilir misin? Unutma,\l"
    .string "makine POKéMON\n"
    .string "MERKEZLERİ'nin köşesinde.\l"
    .string "Bana MEYVE TOZU getirirsen\l"
    .string "ilaç yapacağım. Unutma,\l"
    .string "MEYVE'leri ez ve tozunu\l"
    .string "bana getir.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "Bana neden yalan söylüyorsun?\p"
    .string "Kaç tane MEYVEN var?\n"
    .string "Hiç yok!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "MEYVE'lere ilgi duymuyor\n"
    .string "musun? Genç, her şeye\l"
    .string "ilgi duymak önemlidir.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "Öks! Bana MEYVE TOZU\n"
    .string "getirdin mi?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "Onu neyle değiştirmek\n"
    .string "istersin?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "Tamam, MEYVE TOZU'nu bir\n"
    .string "{STR_VAR_1} ile değiştireceksin.$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "Hmm? Yeterli MEYVE\n"
    .string "TOZU yok.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "Bu gerçekten iyi bir MEYVE\n"
    .string "TOZU. Mükemmel bir ilaç\n"
    .string "yapacağım. Daha fazla\n"
    .string "MEYVE TOZU değiş-tokuş\n"
    .string "etmek ister misin?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "Tamam, öyleyse. Seni\n"
    .string "tekrar görmeyi umuyorum.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "Eğer MEYVE TOZU\n"
    .string "değiştirmek istersen,\n"
    .string "beni gör.$"
