Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .string "Pek çok POKéMON sadece ormanlarda\n"
    .string "ve mağaralarda yaşar.\p"
    .string "Farklı tür bulmak için her yeri\n"
    .string "aramalısın ve ısrarcı olmalısın.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .string "Yol kenarındaki ince ağaçları\n"
    .string "gördün mü?\p"
    .string "Özel bir POKéMON hareketiyle\n"
    .string "kesilebilirler, öyle duydum.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .string "Evrim-iptal tekniğini biliyor musun?\p"
    .string "Bir POKéMON evrimleşirken, süreci\n"
    .string "durdurabilirsin.\p"
    .string "POKéMON'u oldukları gibi\n"
    .string "yetiştirmek için bir teknik.$"
