Route20_Text_BarryIntro::
    .string "Su burada çok sığ.\n"
    .string "Yüzmek için çok kişi var.$"

Route20_Text_BarryDefeat::
    .string "Çıkış!$"

Route20_Text_BarryPostBattle::
    .string "Keşke POKéMON'umun üstüne\n"
    .string "binebilseydim.\l"
    .string "Eminim yorulmamışsındır.$"

Route20_Text_ShirleyIntro::
    .string "SEAFOAM huzurlu bir kaçamak.\n"
    .string "Tatil için buradayım.$"

Route20_Text_ShirleyDefeat::
    .string "Bırak şu işleri!$"

Route20_Text_ShirleyPostBattle::
    .string "Bu adanın altında\n"
    .string "dev bir mağara var.$"

Route20_Text_TiffanyIntro::
    .string "Dalgalar arasında balıklarla\n"
    .string "yüzmeyi seviyorum.$"

Route20_Text_TiffanyDefeat::
    .string "Auv!$"

Route20_Text_TiffanyPostBattle::
    .string "Benimle yüzmek ister misin?$"

Route20_Text_IreneIntro::
    .string "Tatilde misin sen de?$"

Route20_Text_IreneDefeat::
    .string "Hiç acıma yok!$"

Route20_Text_IrenePostBattle::
    .string "SEAFOAM, uzak geçmişte\n"
    .string "tek bir adaydı.$"

Route20_Text_DeanIntro::
    .string "Bak bu kaslı vücuda!$"

Route20_Text_DeanDefeat::
    .string "Zayıf!$"

Route20_Text_DeanPostBattle::
    .string "Kaslarımı geliştirmek yerine\n"
    .string "POKéMON'larımı geliştirmeliydim!$"

Route20_Text_DarrinIntro::
    .string "Neden bir POKéMON'a binmektesin?\n"
    .string "Yüzmeyi bilmiyor musun?$"

Route20_Text_DarrinDefeat::
    .string "Auv!\n"
    .string "Torpidoya uğradım!$"

Route20_Text_DarrinPostBattle::
    .string "Bir POKéMON'a binmek eğlenceli\n"
    .string "görünüyor!$"

Route20_Text_RogerIntro::
    .string "Buraya kuş POKéMON'umla geldim.$"

Route20_Text_RogerDefeat::
    .string "Aman Tanrım!\n"
    .string "Şimdi ne yapacağım?$"

Route20_Text_RogerPostBattle::
    .string "Kuşlarım çok yorgun.\n"
    .string "Onlar beni geri uçuramayacaklar!$"

Route20_Text_NoraIntro::
    .string "Erkek arkadaşım bana büyük inciler verdi.$"

Route20_Text_NoraDefeat::
    .string "Aman Tanrım!\n"
    .string "İncilerim ondaydı!$"

Route20_Text_NoraPostBattle::
    .string "İncilerim CLOYSTER'ın içinde\n"
    .string "büyür mü?$"

Route20_Text_MissyIntro::
    .string "CINNABAR ADASI'ndan buraya yüzdüm.\n"
    .string "Kolay değildi, inan.$"

Route20_Text_MissyDefeat::
    .string "Çok hayal kırıklığına uğradım!$"

Route20_Text_MissyPostBattle::
    .string "POKéMON'lar, CINNABAR'da terk edilmiş\n"
    .string "bir malikaneye el koydu.\p"
    .string "Artık ona POKéMON MALIKÂNESİ\n"
    .string "diyorlar.$"

Route20_Text_MelissaIntro::
    .string "Batıdaki CINNABAR'da bir POKéMON\n"
    .string "LAB'ı var.\p"
    .string "Babam orada çalışıyor.$"

Route20_Text_MelissaDefeat::
    .string "Dur!\n"
    .string "Beklemen gerekiyordu!$"

Route20_Text_MelissaPostBattle::
    .string "CINNABAR bir volkanik ada.\p"
    .string "Volkan patladığında denizin\n"
    .string "ortasından yükseldiğini duydum.$"

Route20_Text_SeafoamIslands::
    .string "SEAFOAM ADALARI$"

Route20_Text_MistyTrainsHere::
    .string "Güçlü EĞİTMEN ve SU POKéMON'ları\n"
    .string "bu bölgede sık görülür.\p"
    .string "CERULEAN SALONU'ndan MISTY'nin sık sık\n"
    .string "burada antrenman yaptığını söylerler.$"
