SSAnne_Kitchen_Text_BusyOutOfTheWay::
    .string "Sen, küçük çocuk!\n"
    .string "Meşgulüz, kenara çekil!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
    .string "Çöpte garip bir MEYVE gördüm.\n"
    .string "Acaba neydi o?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
    .string "O kadar meşgulüm ki başım dönüyor!\n"
    .string "Önümden çekil!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
    .string "Hım hım hım hım…\p"
    .string "Her gün patates soyuyorum!\n"
    .string "Hım hım…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
    .string "SNORLAX'ı duydun mu?\n"
    .string "O tam bir oburdur.\p"
    .string "Hiçbir POKéMON, SNORLAX kadar\n"
    .string "obur ve uykucu olamaz!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
    .string "Hıçk… Hıçk…\p"
    .string "Sadece soğan soyuyorum\n"
    .string "Hıçk…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
    .string "E-hem!\n"
    .string "Evet, ben şefim!\p"
    .string "Ana yemeğimiz…$"

SSAnne_Kitchen_Text_SalmonDuSalad::
    .string "Somon Salatası!\p"
    .string "Korkarım ki konuklar yine mi balık\n"
    .string "diye şikayet edecek!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
    .string "Mangal Somon!\p"
    .string "Korkarım ki konuklar isyan edecek.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
    .string "Kaliteli Biftek!\p"
    .string "Ama yeterince etim var mı,\n"
    .string "bilmiyorum.$"

