SilphCo_2F_Text_ConnorIntro::
    .string "Yardım edin!\n"
    .string "Ben bir SILPH çalışanıyım.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "Nasıl anladın\n"
    .string "Benim ROKET üyesi olduğumu?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "Hem SILPH hem de ROKET\n"
    .string "TAKIMI için çalışıyorum.$"

SilphCo_2F_Text_JerryIntro::
    .string "Burası yasak bölge!\n"
    .string "Evine dön!$"

SilphCo_2F_Text_JerryDefeat::
    .string "İyiymişsin.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "İçerideki labirentte yolunu\n"
    .string "bulabilir misin? Kolay değil!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "Çocuklar giremez!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "Zorlu çocuk!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "Elmas şeklindeki karolar\n"
    .string "teleport bloklarıdır.\p"
    .string "Bu yüksek teknoloji binanın\n"
    .string "ışınlayıcılarıdır.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "Hey, çocuk!\n"
    .string "Burada ne geziyorsun?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "Hata yaptım!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "SILPH ŞTİ. ile ROKET TAKIMI\n"
    .string "ortak olacak!$"

Text_ThunderWaveTeach::
    .string "Eek!\n"
    .string "Hayır! Dur! Yardım edin!\p"
    .string "O, sen ROKET TAKIMI'ndan değilsin.\n"
    .string "Üzgünüm, öyle sandım…\p"
    .string "Affedebilir misin, eğer sana\n"
    .string "ŞİMŞEK DALGA tekniğini\l"
    .string "öğretirsem?$"

Text_ThunderWaveDeclined::
    .string "Oh…\n"
    .string "Ama ŞİMŞEK DALGA kullanışlı…$"

Text_ThunderWaveWhichMon::
    .string "Hangi POKéMON'a ŞİMŞEK DALGA\n"
    .string "öğretmeliyim?$"

Text_ThunderWaveTaught::
    .string "ŞİMŞEK DALGA hedef POKéMON'u\n"
    .string "felç eder.\p"
    .string "Felç olmuş bir POKéMON savaşırken\n"
    .string "hareket edemeyebilir.\p"
    .string "ELEKTRİK tipi bir saldırıdır, bu\n"
    .string "nedenle bazı POKéMON'lara\n"
    .string "etkili olmayabilir.$"

SilphCo_2F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİSİ\n"
    .string "2. KAT$"

