Route21_South_Text_JackIntro::
	.string "Denizde POKéMON tuttum.$"

Route21_South_Text_JackDefeat::
	.string "Dalışçı!!\n"
	.string "Aşağı!!$"

Route21_South_Text_JackPostBattle::
	.string "Sen POKéMON'unu nerede tuttun?$"

Route21_South_Text_JeromeIntro::
	.string "Şu an bir üçlü yarıştayım.$"

Route21_South_Text_JeromeDefeat::
	.string "Hıh…\n"
	.string "Hııh… hh…$"

Route21_South_Text_JeromePostBattle::
	.string "Bittim! Ama, daha bisiklet ve\n"
	.string "maraton yarışlarım var!$"

Route21_South_Text_RolandIntro::
	.string "Ahh!\n"
	.string "Güneşi ve rüzgarı hisset!$"

Route21_South_Text_RolandDefeat::
	.string "Auv!$\n"
	.string "Kaybettim!$"

Route21_South_Text_RolandPostBattle::
	.string "Kömür gibi yandım!$"

Route21_South_Text_ClaudeIntro::
	.string "Hey, balıkları kaçırma!$"

Route21_South_Text_ClaudeDefeat::
	.string "Üzgünüm! Hiçbir şey\n"
	.string "yakalayamadığım için çok gerginim.$"

Route21_South_Text_ClaudePostBattle::
	.string "Ööf, hiçbir şey yakalayamadım.\n"
	.string "Acaba bu yer devasa bir havuz mu?$"

Route21_South_Text_NolanIntro::
	.string "Bir şey yakalayana kadar\n"
    .string "bana eşlik et.$"

Route21_South_Text_NolanDefeat::
	.string "Zaman geçti.$"

Route21_South_Text_NolanPostBattle::
	.string "Bekle bir dakika!\n"
	.string "Isırdım! Evet!$"

Route21_North_Text_LilIntro::
	.string "LIL: Hı? Bir savaş mı? IAN,\n"
	.string "bunu tek başına yapamaz mısın?$"

Route21_North_Text_LilDefeat::
	.string "LIL: Oh, bak?\n"
	.string "Kaybettik. Şimdi mutlu musun?$"

Route21_North_Text_LilPostBattle::
	.string "LIL: Yorgunum.\n"
	.string "Eve gidemez miyiz?$"

Route21_North_Text_LilNotEnoughMons::
	.string "LIL: Hı? Bir savaş mı?\n"
	.string "Tek başıma uğraşamam.\l"
	.string "İki POKéMON getirir misin?$"

Route21_North_Text_IanIntro::
	.string "IAN: Kız kardeşim yeterince\n"
	.string "egzersiz yapmıyor,\l"
    .string "bu yüzden onu getirdim.$"

Route21_North_Text_IanDefeat::
	.string "IAN: Ah, Kardeşim!\n"
	.string "Kendine gel!$"

Route21_North_Text_IanPostBattle::
	.string "IAN: Hadi, Kardeşim!\p"
	.string "Böyle kilo veremeyeceksin.\n"
	.string "Gel, gidelim!$"

Route21_North_Text_IanNotEnoughMons::
	.string "IAN: İkişerli bir savaş istiyoruz.\n"
	.string "O yüzden iki POKéMON getirebilir misin?$"
