FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "Her yeri geziyorsun, değil mi?\n"
    .string "POKéMON'unu yormuyorsun umarım?\p"
    .string "Bir bakayım…\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "Hmm…\n"
    .string "Anlıyorum, anlıyorum…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "Oh, etkileyici.\n"
    .string "POKéMON'larına iyi bakıyorsun.\p"
    .string "Sanırım sana güvenebilirim.\n"
    .string "Lütfen, bunu al.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER}, adamdan bir YUMURTA\n"
    .string "aldı!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…Maalesef, partinde buna yer yok\n"
    .string "En iyisi başka bir zaman gel.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "Merhaba,\n"
    .string "YUMURTA'yı almaya\l"
    .string "geldin, değil mi?$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "Bu YUMURTA'yı seyahat ederken\n"
    .string "aldım. Sana verdiğime memnunum.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "Merhaba.\n"
    .string "O ne tatlı bir {STR_VAR_2}.\p"
    .string "Bana seyahat ederken tanıştığım\n"
    .string "tatlı bir kızı hatırlatıyor.\p"
    .string "POKéMON'unu nazikçe taramıştı…\p"
    .string "Küçük bir melekti.\p"
    .string "O kızın adı…\n"
    .string "Sanırım DAISY'di.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "Bu, POKéMON'ları eğitmek için\n"
    .string "mükemmel bir ortam.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "POKéMON'ların harika bir\n"
    .string "şekilde büyüyor!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "Bence iyi bir YETİŞTİRİCİ\n"
    .string "olabilirsin.$"
