FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Hahahaha!\p"
    .string "Senin gibi bir çocuk bana meydan\n"
    .string "okumaya cesaret eder mi?\p"
    .string "Bu düşünce beni\n"
    .string "kahkahaya boğuyor!\p"
    .string "Pekala, sana bir ninja ustası\n"
    .string "olarak gerçek korkunun ne olduğunu\l"
    .string "göstereceğim.\p"
    .string "Zehir, yavaş ama kesin bir son\n"
    .string "getirir.\p"
    .string "Uyku ise düşmanları savunmasız\n"
    .string "bırakır.\p"
    .string "POKéMON'ların sinsi zehrine\n"
    .string "karşı hazırlıklı ol!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Hmph!\n"
    .string "Değerini gösterdin!\p"
    .string "İşte!\n"
    .string "RUH ROZETİ senin olsun!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "TOKSİK'e maruz kalan bir\n"
    .string "POKéMON, giderek daha çok\l"
    .string "acı çeker.\p"
    .string "Savaş uzadıkça, hasarı da\n"
    .string "artar!\p"
    .string "Kesinlikle düşmanlarını\n"
    .string "korkutacak!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Şimdi RUH ROZETİ'ne sahipsin,\n"
    .string "POKéMON'larının SAVUNMA'sı artacak.\p"
    .string "Ayrıca savaş dışında\n"
    .ifdef ENG_NAMES
    .string "SURF kullanmana izin verir.\p"
	.else
    .string "SÖRF kullanmana izin verir.\p"
	.endif
    .string "Ah!\n"
    .string "Şunu da al!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} KOGA'dan TM06\n"
    .string "aldı.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "O TM06'nın içinde\n"
    .ifdef ENG_NAMES
    .string "TOXIC var!\p"
    .else
    .string "TOKSİK var!\p"
    .endif
    .string "Bu teknik, dört yüz yıllık\n"
    .string "bir sır.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Buna yer aç, çocuk!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "POKéMON'da önemli olan güç değil,\n"
    .string "bunu anlıyor musun?\p"
    .string "POKéMON'da strateji\n"
    .string "ön plandadır!\p"
    .string "Sana stratejinin gücü nasıl\n"
    .string "yendiğini göstereceğim.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Ne?\n"
    .string "Harika ötesi!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Demek güç ve zekayı\n"
    .string "beraber kullanıyorsun?\p"
    .string "İyi strateji!\p"
    .string "Küçük yaşta bir EĞİTMEN\n"
    .string "için fevkalade.$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Eskiden sihirbazdım.\p"
    .string "Ama ninja olmayı hayal\n"
    .string "ediyordum, bu yüzden bu\l"
    .string "SALON'a katıldım.$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Bittim!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Yenildim, ama yine de\n"
    .string "usta KOGA'nın öğretilerine\l"
    .string "göre eğitimime devam\l"
    .string "edeceğim.$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Özel tekniklerime karşı\n"
    .string "dayanabilir misin?\p"
    .string "Bakacağız!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Beni kandırdın!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Zehir ve uyku tekniklerini\n"
    .string "seviyorum, çünkü savaş\l"
    .string "sonrasında da etkili\l"
    .string "olmaya devam ediyorlar!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Dur!\p"
    .string "Ünlü FUCHSIA SALONU'nun\n"
    .string "görünmez duvarları seni\l"
    .string "sinir etti mi?$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Vay!\n"
    .string "Harikasın!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Beni etkiledin!\n"
    .string "İşte bir ipucu!\p"
    .string "Görünmez duvarların\n"
    .string "aralarındaki boşluklara\l"
    .string "çok dikkatli bak!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Ben de usta KOGA ile ninja\n"
    .string "yolunu öğreniyorum.\p"
    .string "Ninja'ların hayvanları\n"
    .string "kullanma konusunda uzun\l"
    .string "bir geçmişi var!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Öğrenecek çok şeyim var.$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Usta KOGA, ninja\n"
    .string "ailesinden geliyor.\p"
    .string "Peki ya sen, atalarından\n"
    .string "ne öğrendin?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Daha yeteneklisin\n"
    .string "sandığımın!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Işığın olduğu yerde\n"
    .string "gölge de vardır.\p"
    .string "Işık ve gölge!\n"
    .string "Hangi tarafı seçersin?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon adayı!\p"
    .string "FUCHSIA SALONU, hilelerle\n"
    .string "dolu bir yer.\p"
    .string "Görünmez duvarlarla\n"
    .string "kaplı!\p"
    .string "KOGA'ya yakın gibi\n"
    .string "görünüyor, ama aslında\l"
    .string "duvarlarla engelleniyor.\p"
    .string "Onu bulmak için duvarların\n"
    .string "aralarındaki boşlukları\l"
    .string "bulmalısın.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "Ninja'ların hala nasıl\n"
    .string "korkutucu olabildiklerini\l"
    .string "görmek harika!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "FUCHSIA POKéMON SALONU\n"
    .string "LİDER: KOGA\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "FUCHSIA POKéMON SALONU\n"
    .string "LİDER: KOGA\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}, {PLAYER}$"
