SafariZone_West_Text_RestHouse::
    .string "DİNLENME EVİ$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "İSTEK BİLDİRİMİ\p"
    .string "Safari Muhafızının kayıp\n"
    .string "ALTIN DİŞLERİNİ bulun.\l"
    .string "Bir yerlerde burada olmalı.\p"
    .string "Ödül verilecektir!\n"
    .string "İletişim: BEKÇİ$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "Bölge Keşif Kampanyası!\n"
    .string "GİZLİ EV'i bulun!$"

SafariZone_West_Text_AreaSign::
    .string "ALAN 3\n"
    .string "DOĞU: MERKEZ ALAN$"
