VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Ben BALIK GURU'suyum!\p"
    .string "Balık tutmayı çok seviyorum!\n"
    .string "Onsuz yapamam.\p"
    .string "Söyle, sen de balık tutmayı sever misin?$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Harika! Tarzını beğendim.\n"
    .string "Sanırım arkadaş olabiliriz.\p"
    .string "Bunu al ve balık tut, genç dostum!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER}, BALIK GURU'sundan\n"
    .string "bir ESKİ OLTA aldı.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Balık tutmak bir yaşam tarzıdır!\n"
    .string "Güzel bir şiire benzer.\p"
    .string "Denizlerden nehirlerden bahsedelim,\n"
    .string "ve büyük balığı yakala, dostum.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Ah…\n"
    .string "Bu çok üzücü…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Merhaba, {PLAYER}!\p"
    .string "Balık tutmak nasıl gidiyor?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Aman Tanrım!\p"
    .string "Sana güzel bir hediyem vardı, ama\n"
    .string "senin hiç yerin yok!$"
