SSAnne_1F_Room6_Text_TakeAShortRest:
    .string "Yorgun görünüyorsun.\n"
    .string "Kısa bir mola ister misin?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed:
    .string "Herkesin dinlenmiş ve neşeli\n"
    .string "görünmesinden memnunum.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother:
    .string "Üzerine titrememden dolayı\n"
    .string "özür dilerim.\l"
    .string "Erkek kardeşim gibi görünüyorsun…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister:
    .string "Üzerine titrememden dolayı\n"
    .string "özür dilerim.\l"
    .string "Kız kardeşim gibi görünüyorsun…$"

