CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE üç farklı POKéMON'a\n"
    .string "evrimleşebilir.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "Bir e-posta mesajı var.\p"
    .string "… … …\p"
    .string "Üç efsanevi kuş POKéMON\n"
    .string "vardır:\p"
    .string "ARTICUNO, ZAPDOS ve MOLTRES\p"
    .string "Nerede oldukları bilinmiyor.\p"
    .string "CERULEAN yakınlarındaki mağarayı\n"
    .string "araştırmayı planlıyoruz\p"
    .string "Gönderen: POKéMON ARAŞTIRMA TAKIMI…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "Bir kehribar pipo!$"
