Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "Tamam, kemeri altı POKé TOPU ile\n"
    .string "ayarla…\p"
    .string "Evet, şimdi oldu. En fazla,\n"
    .string "altı POKéMON'a sahip olabilirsin.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "ROKET TAKIMI, CERULEAN\n"
    .string "vatandaşlarına saldırıyor…\p"
    .string "ROKET TAKIMI'in haberlerde olmadığı\n"
    .string "gün yok gibi.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "ADAM: Merhaba delikanlı!\n"
    .string "Sana özel bir fırsat sunuyorum!\p"
    .string "Sana gizli bir POKéMON'u sadece\n"
    .string "¥500'e vereceğim - bir MAGIKARP!\p"
    .string "Öyleyse, alacaksın, değil mi?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "ADAM: Merhaba tatlım!\n"
    .string "Sana özel bir fırsat sunuyorum!\p"
    .string "Sana gizli bir POKéMON'u sadece\n"
    .string "¥500'e vereceğim - bir MAGIKARP!\p"
    .string "Öyleyse, alacaksın, değil mi?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER}, inanılmaz bir ¥500\n"
    .string "ödeyerek MAGIKARP'ı aldı…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "Hayır mı? Hayır diyorsun? Sana bir\n"
    .string "iyilik yapıyorum sadece!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "Daha fazla POKéMON için yer\n"
    .string "kalmamış gibi görünüyor.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "Daha fazla paraya ihtiyacın var!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "ADAM: Ben iade yapmam\n"
    .string "Ne aldığını biliyordun!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "Bazen, yanınızda çok fazla POKéMON\n"
    .string "olacak ve daha fazla\l"
    .string "ekleyemeyeceksin\p"
    .string "Böyle bir durumda bazılarını\n"
    .string "herhangi bir PC kullanarak\l"
    .string "saklamalısın.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "Bu bir gazete.$"
