PokemonLeague_BrunosRoom_Text_Intro::
    .string "Ben ELİT DÖRTLÜ'nün BRUNO'suyum!\p"
    .string "Zorlu antrenmanlarla insanlar\n"
    .string "ve POKéMON'lar sınırsız güç\l"
    .string "kazanabilir. Ben savaşan\l"
    .string "POKéMON'larımla yaşadım ve\l"
    .string "antrenman yaptım! Bu asla\l"
    .string "değişmeyecek!\p"
    .string "{PLAYER}!\p"
    .string "Seni üstün gücümüzle ezeceğiz!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "Ben ELİT DÖRTLÜ'nün BRUNO'suyum!\p"
    .string "Zorlu antrenmanlarla insanlar\n"
    .string "ve POKéMON'lar sınırsız güç\l"
    .string "kazanabilir. Ben savaşan\l"
    .string "POKéMON'larımla yaşadım ve\l"
    .string "antrenman yaptım! Bu asla\l"
    .string "değişmeyecek!\p"
    .string "{PLAYER}!\p"
    .string "Seni üstün gücümüzle ezeceğiz!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Neden?\n"
    .string "Nasıl kaybettim?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Görevim tamam.\n"
    .string "Şimdi bir sonraki sınamana hazırsın.$"
