SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "KAPTAN: Ooof…\n"
    .string "Kendimi berbat hissediyorum…\l"
    .string "Mide Bulantısı! Deniz tutması…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER}, kaptanın\n"
    .string "sırtını ovdu!\p"
    .string "Ovala…\n"
    .string "Ovala…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "KAPTAN: Ohoh! Teşekkürler!\n"
    .string "Şimdi çok daha iyi hissediyorum.\p"
    .ifdef ENG_NAMES
    .string "Gizli CUT tekniğimi\n"
    .else
    .string "Gizli KES tekniğimi\n"
    .endif
    .string "görmek ister misin?\p"
    .string "Eğer hasta olmasaydım, sana\n"
    .ifdef ENG_NAMES
    .string "özel CUT tekniğimi\l"
    .else
    .string "özel KES tekniğimi\l"
    .endif
    .string "gösterebilirdim…\p"
    .string "Bunu alabilirsin!\n"
    .string "Bu HM!\p"
    .ifdef ENG_NAMES
    .string "CUT hamlesini POKéMON'una\n"
    .else
    .string "KES hamlesini POKéMON'una\n"
    .endif
    .string "öğret ve dilediğin zaman\l"
    .string "görebilirsin!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER}, kaptandan\n"
    .string "HM01'i aldı!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .ifdef ENG_NAMES
    .string "CUT hareketini kullanarak,\n"
    .else
    .string "KES hareketini kullanarak,\n"
    .endif
    .string "küçük ağaçları kesebilirsin.\p"
    .string "VERMILION ŞEHRİ çevresindeki\n"
    .string "ağaçlarda denemeye ne dersin?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "KAPTAN: …Ohoh!\p"
    .string "Artık hasta olmadığım için,\n"
    .string "zamanı geldi sanırım.\p"
    .string "S.S. ANNE kısa süre içinde\n"
    .string "yola çıkacak!\p"
    .string "Hoşçakalın, buraya geri\n"
    .string "dönüşümüze kadar!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, hayır!\n"
    .string "Bunun için yerin yok!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "İğrenç!\n"
    .string "Buna bakmamalıydım!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Deniz Tutmasını Yenmek…\n"
    .string "KAPTAN bunu okuyor!$"


