SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
.string "KAPTAN: Ooof…\n"
.string "Kendimi berbat hissediyorum…\l"
.string "Mide Bulantısı! Deniz tutması…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
.string "{PLAYER}, kaptanın\n"
.string "sırtını ovdu!\p"
.string "Ovala…\n"
.string "Ovala…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
.string "KAPTAN: Ohoh! Teşekkürler!\n"
.string "Şimdi çok daha iyi hissediyorum.\p"
.string "Gizli KES tekniğimi\n"
.string "görmek ister misin?\p"
.string "Eğer hasta olmasaydım, sana\n"
.string "özel KES tekniğimi\l"
.string "gösterebilirdim…\p"
.string "Bunu alabilirsin!\n"
.string "Bu HM!\p"
.string "KES hareketini POKéMON'una\n"
.string "öğret ve dilediğin zaman\l"
.string "görebilirsin!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
.string "{PLAYER}, kaptandan\n"
.string "HM01'i aldı!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
.string "KES hareketini kullanarak,\n"
.string "küçük ağaçları kesebilirsin.\p"
.string "VERMILION ŞEHRİ çevresindeki\n"
.string "ağaçlarda denemeye ne dersin?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
.string "KAPTAN: …Ohoh!\p"
.string "Artık hasta olmadığım için,\n"
.string "zamanı geldi sanırım.\p"
.string "S.S. ANNE kısa süre içinde\n"
.string "yola çıkacak!\p"
.string "Hoşçakalın, buraya geri\n"
.string "dönüşümüze kadar!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
.string "Oh, hayır!\n"
.string "Bunun için yerin yok!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
.string "İğrenc!\n"
.string "Buna bakmamalıydım!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
.string "Deniz Tutmasını Yenmek…\n"
.string "KAPTAN bunu okuyor!$"


