PalletTown_RivalsHouse_Text_HiBrothersAtLab::
.string "DAISY: DAISY, {PLAYER}!\p"
.string "Kardeşim, {RIVAL}, dışarıda\n"
.string "Dedemin LABORATUVARI'nda.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
.string "DAISY: {PLAYER}, senin ve\n"
.string "{RIVAL}'ın POKéMON savaşı\l"
.string "yaptığını duydum.\p"
.string "Keşke görseydim!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
.string "Dedem sana yapman için\n"
.string "bir görev mi verdi?.\p"
.string "Vay canına, bu tam bir tembellik.\n"
.string "İşte, bu sana yardımcı olur.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
.string "{PLAYER}, DAISY'dan bir\n"
.string "HARİTA aldı.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
.string "Çantanızda buna yer yok.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
.string "HARİTA'yı kullanarak\n"
.string "nerede olduğunu öğrenebilir veya\l"
.string "yerlerin isimlerini kontrol\l"
.string "edebilirsin.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
.string "DAISY: İnsanlar gibi, POKéMON'lar\n"
.string "da canlı varlıklardır.\p"
.string "Yorgun olduklarında, lütfen onlara\n"
.string "dinlenmeleri için zaman tanıyın.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
.string "Bu, KANTO bölgesinin büyük\n"
.string "ölçekli bir haritası.\p"
.string "Çok faydalı olacak!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
.string "Raflar POKéMON hakkında kitaplar\n"
.string "ile dolu.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
.string "DAISY: DAISY, {PLAYER}!\n"
.string "İyi zamanlama.\p"
.string "Çay içmek üzereydim.\n"
.string "Katılmak ister misin?\p"
.string "Ah, ama bak.\n"
.string "POKéMON'ların biraz kirli.\p"
.string "Onlardan birini temizlememi\n"
.string "ister misin?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
.string "POKéMON'ların bakıma ihtiyacı yok mu?\n"
.string "Tamam, o zaman sadece çay içelim.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
.string "Hangi POKéMON'u temizleyeyim?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
.string "DAISY: Tamam, onu kısa sürede\n"
.string "güzel görünmesini sağlayacağım.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
.string "{COLOR DARK_GRAY}{STR_VAR_1} rüya gibi görünüyor…\p"
.string "{COLOR RED}DAISY: Tamam, bitti.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
.string "{FONT_NORMAL}{STR_VAR_1} rüya gibi görünüyor…\p"
.string "{FONT_FEMALE}DAISY: Tamam, bitti.\n"
#endif
.string "Görmüyor musun? Güzel görünmüyor mu?\p"
.string "Kıkır kıkır\n"
.string "Çok tatlı bir POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
.string "Ah, özür dilerim. Dürüst olmak\n"
.string "gerekirse bir YUMURTA'yı\l"
.string "temizleyemem.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
.string "DAISY: POKéMON'larınızı\n"
.string "severseniz, onlar da sizi sever.\p"
.string "Örneğin, {PLAYER}, ilk\n"
.string "POKéMON'unuza bakabilir miyim?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
.string "Seni şu anda aşırı seviyor.\p"
.string "POKéMON'unuz kelimelerle ifade\n"
.string "edilemeyecek kadar mutlu.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
.string "Çok mutlu görünüyor.\p"
.string "{RIVAL}'ın bunu görmesini ve\n"
.string "bir şeyler öğrenmesini isterdim.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
.string "Sana karşı oldukça dostça.\n"
.string "İyi davranmaya devam et!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
.string "Sana ısınıyor.\n"
.string "Aranda güven oluşuyor olmalı.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
.string "Henüz sana alışkın değil.\p"
.string "POKéMON'lar ilk yakalandığında\n"
.string "hepsi temkinlidir.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
.string "{PLAYER}, sana bakışını\n"
.string "beğenmiyorum.\p"
.string "Onunla biraz daha nazik\n"
.string "davranabilir misin?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
.string "…Ehm, bunu söylemek\n"
.string "kolay değil ama…\p"
.string "POKéMON'unuzun size bu kadar\n"
.string "nefret etmesinin bir nedeni var mı?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
.string "“Tatlı ve sevimli CLEFAIRY”$"
