SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "SILPH bitti mi acaba?$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "Bizi kurtardığınız için teşekkürler!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "Buraya kadar!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "Yeterli çaba yoktu!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "Eğer geri dönmezsen…\n"
    .string "Destek çağırabilirim!$"

SilphCo_8F_Text_ParkerIntro::
    .string "Bize sorun çıkarıyorsunuz!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "Ne?\n"
    .string "Kaybettim mi?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "O zaman, SILPH Binası'nın\n"
    .string "labirentini nasıl buldunuz?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "Ben ROKET TAKIMI'nın\n"
    .string "dört kardeşinden biriyim!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "Vay!\n"
    .string "Kardeşler, oh kardeşler!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "Sizi kardeşlerime bırakıyorum.$"

SilphCo_8F_Text_FloorSign::
    .string "SILPH ŞTİ. GENEL MERKEZİ\n"
    .string "8. Kat$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "ROKET TAKIMI'nın PATRONU çok\n"
    .string "acımasız!\p"
    .string "Onun için POKéMON'lar sadece\n"
    .string "kullanılacak birer araç.\p"
    .string "Eğer bu zalim şirketimizi ele\n"
    .string "geçirirse ne olacak?$"

