SSAnne_2F_Room4_Text_LamarIntro::
    .string "Sence güçlü mü yoksa nadir bulunan\n"
    .string "POKéMON mu daha değerli?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "Sizi selamlamalıyım!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "Benim tercihim güçlü ve\n"
    .string "nadir POKéMON'lardan yana.$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "Galiba partiye gelmedin,\n"
    .string "değil mi?$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "Ağırdan al!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "Güçlü POKéMON'larınızı beğendim!\p"
    .string "Onlara sahip olduğunuz için\n"
    .string "size imreniyorum!$"

