SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "Safari'de bulduğunuz her şeyi\n"
    .string "saklayabilirsiniz. Ama hepsini\l"
    .string "birden almaya kalkarsanız zamanınız\l"
    .string "yetmeyebilir.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "Safari'nin en derinine gidin. Bir ödül\n"
    .string "kazanacaksınız!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "EEVEE'm FLAREON'a dönüştü. Ama\n"
    .string "arkadaşımınki VAPOREON oldu. Neden\l"
    .string "acaba?$"
