ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "Merhaba, haberi duydun mu?\p"
    .string "Buradaki PC ağı artık KANTO'daki\n"
    .string "PC'lerle bağlantı kurabiliyor.\p"
    .string "Bunun nasıl mümkün olduğunu\n"
    .string "bilmiyorum, ama muhteşem!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "Bu civarda adalar arasında SÖRF\n"
    .string "yapmak imkansız.\p"
    .string "Akıntılar çok hızlı ve tehlikeli.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "Haydi MEYVE ezelim!\n"
    .string "…Bu MEYVE'leri boşa harcamak\l"
    .string "olmaz mı?\p"
    .string "MEYVE ORMANI'nda her zaman\n"
    .string "yerde MEYVE bulabilirsin.$"
