OneIsland_KindleRoad_Text_MariaIntro::
    .string "Hava muhteşem!\n"
    .string "Savaşmak için mükemmel bir hava!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "Aiyeeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "Lütfen yüzüme su sıçratma!\n"
    .string "Makyajım bozulacak.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "Yanmaya başladım…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "Oh, berbat birisin.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "O şapkanı beğendim.\n"
    .string "Belki ben de takmalıyım…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "Buradan bakıldığında, KÖZ DAĞI\n"
    .string "gökyüzüne yükseliyor.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "Vay canına, çok güçlüsün!$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "Bu bölgelerde gökyüzü sonsuz gibi\n"
    .string "görünüyor.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "Yüzmekten yorulmuştum,\n"
    .string "ama sen beni savaşa çağırdın?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "Hey, ne oluyor?\n"
    .string "Sen gerçekten iyisin!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .ifdef ENG_NAMES
    .string "Sürekli SURF kullanmak yerine,\n"
	.else
    .string "Sürekli SÖRF kullanmak yerine,\n"
	.endif
    .string "biraz yüzmelisin.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "Dur! Bir saniye!\n"
    .string "Galiba büyük bir şey yakaladım!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "Tekrar her şeyi kaybettim…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "Yalnızca kaybetmedim, aynı zamanda\n"
    .string "büyük olan da kaçtı!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "Eğitimime yardım eder misin?\n"
    .string "Lütfen.$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "Senden daha aşağıdayım.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "Yetenekli olduğun çok açık.\n"
    .string "Seni sevdim!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "Eğitim yapmadığımız bir gün bile\n"
    .string "yok!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "Aptal gibi hissediyorum!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "Bundan böyle daha çok çalışacağım!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "Kahvaltıdan önce her sabah,\n"
    .string "bu adanın etrafında yüzüyorum.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "Hıç…\n"
    .string "Hıç…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "Koşmaktan çok yorulmuştum,\n"
    .string "bu yüzden kaybettim…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "Savaş için uygun giyin!\n"
    .string "O saçma kıyafeti çıkar!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "Neden ben?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "Günümüzün dövüş sanatçıları da\n"
    .string "modayı takip ediyor…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "Biliyor musun, doğada her şey\n"
    .string "çok lezzetli.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "Awww, berbat!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "Volkanik bölgelerdeki su\n"
    .string "çok lezzetli.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "Öğle yemeğimiz bizi çok doyurdu,\n"
    .string "bu yüzden biraz egzersiz için\l"
    .string "bizimle savaşır mısın?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "Ter içinde kaldım.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "Ne yapmalıyım?\n"
    .string "Tekrar acıktım.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "KIA: Büyük erkek kardeşim ve ben\n"
    .string "harika bir ikiliyiz!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "KIA: Ne?!\n"
    .string "Buna inanamıyorum!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "KIA: Nasıl olur da erkek\n"
    .string "kardeşimden daha iyisi olabilir?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "KIA: Bizimle savaşmak istiyorsan,\n"
    .string "en az iki POKéMON getirmen gerek.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "MIK: KIA ile birlikteyken\n"
    .string "hiçbir şeyden korkmuyorum!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "MIK: Vay canına!\n"
    .string "Bu çok fazla!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "MIK: KIA ile olan kombinasyonum\n"
    .string "nasıl başarısız olabilir?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "MIK: Hey, bizimle savaşmak ister\n"
    .string "misin? İki veya daha fazla\l"
    .string "POKéMON getir.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "Bu KINDLE YOLU.\n"
    .string "KÖZ DAĞI için düz gidin.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "Kalbinizdeki Ateşi Yakın!\n"
    .string "KÖZ SPA$"
