PokemonTower_4F_Text_PaulaIntro::
    .string "Hayır, hayalet!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Hayalet nerede?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Herhalde rüya görüyordum…$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Bana katıl, lanetlen!\n"
    .string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "Ne!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "Hayaletlerin kimliğini\n"
    .string "belirleyemiyoruz…$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu…\n"
    .string "Bana dokunma!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Huh?\n"
    .string "Kim? Ne?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "Ölen POKéMON'ların ruhu şad olsun…$"
