CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "SÜPER SPREY zayıf POKéMON'ları\n"
    .string "uzak tutuyor…\p"
    .string "Daha güçlü bir SPREY bu.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Uzun gezintiler için\n"
    .string "CANLANDIRICI almalısın!$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "EĞİTMENLER için Üstün Kalite!\p"
    .string "2. Kat: Eğitmen Pazarı$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "LANCE adında bir müşterimiz var.\n"
    .string "O ara sıra gelir.\p"
    .string "Her zaman pelerin alır.\p"
    .string "Acaba… Evinde bir sürü\n"
    .string "aynı pelerinden mi var?$"
