SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "ROKET TAKIMI karmaşa içinde.\n"
    .string "Birisinin içeri sızdığı söyleniyor.\p"
    .string "Sensin, değil mi?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "ROKET TAKIMI kaçtı!\n"
    .string "Kahramanımızsın! Teşekkürler!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Bir çocuğun etrafta\n"
    .string "dolaştığını duydum.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "Bum!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "ROKET TAKIMI ile kavga\n"
    .string "etmek akıllıca değil!$"

SilphCo_5F_Text_BeauIntro::
    .string "Bu katta POKé TOPU\n"
    .string "teknolojisini inceliyoruz.$"

SilphCo_5F_Text_BeauDefeat::
    .string "Aaa!\n"
    .string "Vah!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "Her şeyi yakalamak için\n"
    .string "en iyi POKé BALL'ı geliştirdik.$"

SilphCo_5F_Text_DaltonIntro::
    .string "Neee?\p"
    .string "Burada hiçbir çocuk\n"
    .string "bulunmamalı!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "Aman Tanrım!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "Sadece 5. kattasın.\n"
    .string "PATRON'uma daha çok var!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "ROKET TAKIMI'na biraz saygı\n"
    .string "gösterin!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "Öhö…\n"
    .string "Öhö…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Bana hatırlatıyor ki,\p"
    .string "KOFFING, WEEZING'e dönüşür!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "Bu bir POKéMON RAPORU!\p"
    .string "POKéMON LAB, ilk sanal gerçeklik\n"
    .string "POKéMON'u PORYGON'u yarattı.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "Bu bir POKéMON RAPORU!\p"
    .string "350'den fazla POKéMON hamlesi\n"
    .string "olduğu onaylandı.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "Bu bir POKéMON RAPORU!\p"
    .string "Bazı POKéMON'ların takas\n"
    .string "edildiğinde evrimleştiği onaylandı.$"

SilphCo_5F_Text_FloorSign::
    .string "SILPH ŞTİ. GENEL MERKEZİ\n"
    .string "5. Kat$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Binamızı ele geçiren\n"
    .string "o serseriler…\p"
    .string "PATRON'ları güçlü POKéMON\n"
    .string "arıyormuş.\p"
    .string "Umarım başkanımızdan uzak\n"
    .string "dururlar…$"

