LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "İstatistik artırıcı eşyalar\n"
    .string "arayışındayım.\p"
    .string "POKéMON savaşlarında\n"
    .string "etkilidirler.\p"
    .string "X SALDIRI, X SAVUNMA, X HIZ\n"
    .string "ve X ÖZEL arıyorum.\p"
    .string "Nereden bulabilirim biliyor musun?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "Hiç CANLANDIRICI aldın mı?\p"
    .string "Bayılan tüm POKéMON'ları\n"
    .string "diriltiyor!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "Bazen, bir EĞİTMEN ikilisi\n"
    .string "aynı anda iki POKéMON'la\l"
    .string "seninle savaşabilir.\p"
    .string "Eğer böyle olursa, sen de iki\n"
    .string "POKéMON göndermelisin.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "Son zamanlarda dağlarda bir\n"
    .string "KÜLÇE buldum!\p"
    .string "Kullanışsız bir şeydi ama\n"
    .string "5000¥'ye sattım!$"
