SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "Hmmf!\p"
    .string "Karate'nin USTASIYIM!\n"
    .string "Buradaki LİDER benim!\p"
    .string "Bizi mi sınamak istiyorsun?\n"
    .string "Acımayacağız!\p"
    .string "Haaayk!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "Haa!\n"
    .string "Auv! Yenildim!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "Evet, yenildim!\p"
    .string "Ama lütfen, sembolümüzü\n"
    .string "ödül olarak alma!\p"
    .string "Karşılığında sana değerli bir\n"
    .string "DÖVÜŞ POKéMON'u vereceğim!\p"
    .string "İstediğini seçebilirsin!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "Hmmf!\n"
    .string "Kal ve bizimle karate çalış!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "Haaah!\n"
    .string "Ayakkabılarını çıkar!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "Pes ediyorum!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "USTAMIZI görmelisin!\n"
    .string "Ona kıyasla ben bir hiçim!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "Güçlü olduğunu duydum!\n"
    .string "Bana göster!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "Hakem!\n"
    .string "Bir puan!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "USTAMIZ profesyonel bir dövüşçü.\n"
    .string "Kaybetmeye hazır ol!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "Haaayk!\n"
    .string "Hiçbir şeyden korkmam!\p"
    .string "Her gün antrenman için\n"
    .string "kayaları parçalarım!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "Auv!\n"
    .string "Parmaklarım ezildi!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "Bizi korkutan tek şey\n"
    .string "psişik güçler!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "Haaah!\p"
    .string "Burası DÖVÜŞ DOJOSU!\n"
    .string "İzin almadan girilmez!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "Of!\n"
    .string "Pes ediyorum!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Ülkedeki en iyi savaşçılar\n"
    .string "burada çalışır.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "Güçlü tekme atan\n"
    .string "HITMONLEE'yi ister misin?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "{PLAYER} karate ustasından\n"
    .string "{STR_VAR_1} aldı.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "Güçlü yumruk atan\n"
    .string "HITMONCHAN'i ister misin?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}　カラテ　マスター　から\n"
    .string "{STR_VAR_1}　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Açgözlü olmamak lazım…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "Her yanımız düşmanlarla çevrili!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "Ne ekersen onu biçersin.$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "DÖVÜŞ DOJOSU$"
