Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Bakalım…\n"
	.string "Aman! Sadece {STR_VAR_3}\l"
	.string "tür POKéMON yakalamışsınız!\p"
	.string "{STR_VAR_2}'yı almak için\n"
	.string "{STR_VAR_1} tür gerek.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Oh. Anlıyorum.\p"
	.string "{STR_VAR_2}'yı almak için\n"
	.string "{STR_VAR_1} tür POKéMON yakalayınca\l"
	.string "geri gelin.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ah! Görüyorum ki\n"
	.string "{STR_VAR_2} için yeriniz yok.$"
