@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "Ben GÜNDÜZ BAKIM ADAMI'yım.\p"
	.string "EĞİTMENlerin değerli\n"
	.string "POKéMON'larına bakıyorum.\p"
	.string "POKéMON'unuzu yetiştirmemi\n"
	.string "isterseniz, eşimle konuşun.$"

DayCare_Text_DoYouWantEgg::
	.string "Ah, sizsiniz!\p"
	.string "POKéMON'unuzu yetiştiriyorduk\n"
	.string "ve inanın çok şaşırdık!\p"
	.string "POKéMON'unuz bir YUMURTA yaptı!\p"
	.string "Nasıl oldu bilmiyoruz,\n"
	.string "ama POKéMON'unuz yaptı.\p"
	.string "Onu istiyorsunuz, değil mi?$"

DayCare_Text_YourMonIsDoingFine::
	.string "Ah, sizsiniz! Sizi görmek güzel.\n"
	.string "{STR_VAR_1} çok iyi durumda.$"

DayCare_Text_IllKeepIt::
	.string "O zaman, onu ben tutacağım.\n"
	.string "Teşekkürler!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "Onun için yeriniz yok…\n"
	.string "Yer açınca tekrar gelin.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER}, GÜNDÜZ BAKIM ADAMI'ndan\n"
	.string "YUMURTA aldı.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "Ona iyi bakın.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "Ah, sizsiniz! {STR_VAR_1} ve\n"
	.string "{STR_VAR_2} çok iyi durumda.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "Gerçekten onu tutacağım.\n"
	.string "Bunu istiyorsunuz, değil mi?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "Ben GÜNDÜZ BAKIM KADINI'yım.\p"
	.string "Sizin için POKéMON\n"
	.string "yetiştirebiliriz.\p"
	.string "Bir POKéMON yetiştirmemizi\n"
	.string "ister misiniz?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "Hangi POKéMON'u\n"
	.string "yetiştirelim?$"

DayCare_Text_WellRaiseYourMon::
	.string "Tamam, {STR_VAR_1}'inizi\n"
	.string "bir süre yetiştireceğiz.\p"
	.string "Daha sonra almak için gelin.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "İki POKéMON'unuzu yetiştirebiliriz.\p"
	.string "Bir POKéMON daha\n"
	.string "yetiştirmemizi ister misiniz?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "Kocam sizi arıyordu.$"

DayCare_Text_FineThenComeAgain::
	.string "Oh, peki öyleyse.\n"
	.string "Tekrar gelin.$"

DayCare_Text_NotEnoughMoney::
	.string "Yeterli paranız yok…$"

DayCare_Text_TakeOtherOneBackToo::
	.string "Diğerini de geri alacak mısınız?$"

DayCare_Text_ComeAgain::
	.string "Peki.\n"
	.string "Tekrar gelin.$"

DayCare_Text_GoodToSeeYou::
	.string "Ah, sizsiniz!\n"
	.string "Sizi görmek güzel.\p"
	.string "POKéMON'unuz iyi durumda olmalı!$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "{STR_VAR_1}, {STR_VAR_2} seviye atladı.$"

DayCare_Text_YourPartyIsFull::
	.string "POKéMON partiniz dolu.\n"
	.string "Yer açtıktan sonra beni görün.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "{STR_VAR_1}'inizi geri almak\n"
	.string "istiyorsanız, size\l"
	.string "maliyeti ¥{STR_VAR_2} olacak.$"

DayCare_Text_HeresYourMon::
	.string "Mükemmel!\n"
	.string "İşte POKéMON'unuz.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER},\nGÜNDÜZ BAKIM KADINI'ndan\l"
	.string "{STR_VAR_1}'ini geri aldı.$"

DayCare_Text_YouHaveJustOneMon::
	.string "Ah? Ama sadece bir\n"
	.string "POKéMON'unuz var.\p"
	.string "Başka bir zaman gelin.$"

DayCare_Text_TakeYourMonBack::
	.string "POKéMON'unuzu geri alacak mısınız?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "Bu POKéMON'u bana bırakırsanız,\n"
	.string "neyle savaşacaksınız?\p"
	.string "Başka bir zaman gelin.$"

DayCare_Text_Huh::
	.string "Ha?$"
