gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON ARAŞTIRMA LAB$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dünyadaki tüm POKéMON'lar\n"
	.string "hakkında bir rehber yapmak…\p"
	.string "Bu benim hayalim!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK pek öyle gibi\n"
	.string "görünmeyebilir, ama o POKéMON\l"
	.string "konusunda otoritedir.\p"
	.string "Birçok POKéMON EĞİTMENİ ona\n"
	.string "büyük saygı duyar.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK duyuma göre torunlarıyla\n"
	.string "yaşıyor, DAISY ve {RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Duydum ki OAK senin üzerine\n"
	.string "çok düşüyor, çocuk.\p"
	.string "O yaşlı bunak bir zamanlar sert ve\n"
	.string "yakışıklıydı.\p"
	.string "Ama bu yıllar önceydi.\n"
	.string "O artık eski halinin bir gölgesi.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK yakında kendi radyo\n"
	.string "programını sunacak.\p"
	.string "Programın adı PROF. OAK ile\n"
	.string "POKéMON SEMİNERİ olacak.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Eğer DAISY'e POKéMON'unu\n"
	.string "gösterirsen, seni ne kadar\l"
	.string "sevdiğini söyleyebilir.\p"
	.string "Ara sıra, POKéMON'larına bakım\n"
	.string "bile yapabilir.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ama bence POKéMON'ların en sevdiği\n"
	.string "insan DAISY, bence.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON'u nazikçe tımarlıyordu…\n"
	.string "O küçük bir melekti.\p"
	.string "O küçük kızın ismi…\n"
	.string "Sanırım DAISY idi.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK duyuma göre torunlarıyla\n"
	.string "yaşıyor, DAISY ve {RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PALLET KASABASI'ndan bir kız, adı\n"
	.string "DAISY. Her gün ÇAY keyfi yapar.\p"
	.string "CELADON MAĞAZASI'na ÇAY almak\n"
	.string "için uğrar.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bahar POKéMON YARIŞMASI'nın\n"
	.string "Büyük Şampiyonu PALLET KASABASI\l"
	.string "sakini DAISY OAK!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON SALONU\n"
	.string "LİDERİ: BROCK\l"
	.string "Kaya Gibi Sert POKéMON EĞİTMENİ!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Kaya gibi sert iradem\n"
	.string "POKéMON'larımda da var.\p"
	.string "Hepsi kaya sertliğinde ve gerçek\n"
	.string "cesarete sahipler.\p"
	.string "Bu doğru - POKéMON'larımın hepsi\n"
	.string "KAYA türü!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Burada pek çok ciddi\n"
	.string "POKéMON EĞİTMENLERİ yok.\p"
	.string "Hepsi BÖCEK AVCILARI vesaire\p"
	.string "Biliyorsun, sadece hobiciler.\p"
	.string "Ama PEWTER SALONU'nun BROCK'u hiç\n"
	.string "değilse onlardan farklı.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK çok havalı. Sadece güçlü\n"
    .string "değil, sevilen ve saygı duyulan\l"
    .string "biri. Onun gibi bir SALON\l"
    .string "LİDERİ olmak istiyorum.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Merhaba, ben AY DAĞI'nda fosil\n"
    .string "bulmak için kazı yapıyorum.\p"
    .string "Bazen, PEWTER SALONU'ndan BROCK\n"
    .string "bana yardım ediyor.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK nadiren güler, ama söylenene\n"
	.string "göre gülmeye başlarsa asla durmaz.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON SALONU\n"
	.string "LİDERİ: MISTY\l"
	.string "Maskülen Denizkızı!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Benim politikam, SU tipi\n"
    .string "POKéMON'larla tüm gücüyle\l"
    .string "saldırmaktır!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY, kendini sürekli olarak\n"
    .string "geliştiren bir EĞİTMEN.\p"
    .string "Sana yenilmeyecek!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Güçlü EĞİTMEN ve SU POKéMON'ları\n"
	.string "bu bölgede sık görülür.\p"
	.string "CERULEAN SALONU'ndan MISTY'nin sık sık\n"
	.string "burada antrenman yaptığını söylerler.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bu tepe, ünlü bir buluşma\n"
    .string "noktasıdır.\p"
    .string "SALON LİDERİ MISTY, bu yer için\n"
    .string "büyük umutlar besliyor.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Söylenene göre MISTY ELİT DÖRTLÜ\n"
	.string "üyesi LORELEI'nin büyük hayranı.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON SALONU\n"
	.string "LİDERİ: TĞM. SURGE\l"
	.string "Amerikalı Şimşek!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sana söylüyorum, çocuk, ELEKTRİK\n"
    .string "POKéMON'ları savaşta beni kurtardı!\p"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ordudayken TĞM. SURGE\n"
    .string "benim komutanımdı.\p"
    .string "Çok zorlu eğitim verirdi.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TĞM. SURGE ordudayken her zaman\n"
    .string "tedbirli tavrıyla tanınırdı.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TĞM. SURGE SALON'daki tuzakları\n"
    .string "kendi kurdu.\p"
    .string "Her yere çift kilit yerleştirdi.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rivayete göre TĞM. SURGE\n"
	.string "Amerika'da pilotluk yapıyordu.\p"
	.string "Uçağını çalıştırmak için elektrik\n"
	.string "POKéMON'ları kullanıyordu.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON SALONU\n"
	.string "LİDERİ: ERIKA\l"
	.string "Doğayı Seven Prenses!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Çiçek düzenleme sanatı\n"
	.string "öğrencisiyim.\p"
	.string "POKéMON'larımın hepsi tamamen\n"
	.string "ÇİMEN türüdür.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Liderimiz ERIKA sessiz olabilir,\n"
	.string "ama buralarda ünlüdür.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Burada sadece ÇİMEN tipi POKéMON\n"
	.string "kullanırız.\p"
	.string "Neden mi? Onları ayrıca çiçek\n"
	.string "düzenlemeleri için de kullanırız!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Eğer çekici olmasalardı asla\n"
	.string "POKéMON yakalamazdım.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Eğer CELADON SALONU'na gizlice\n"
	.string "bakarsan, ERIKA'yı sıkça\l"
	.string "uyuklarken görebilirsin.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA ŞEHRİ POKéMON SALON\n"
	.string "LİDERİ: KOGA\l"
	.string "Zehirli Ninja Ustası$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ZEHİR tipi POKéMON'un sürünen\n"
	.string "dehşetine karşı umutsuzluk!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Kaybetmiş olsam bile, ninja ustam\n"
	.string "KOGA'nın öğretilerine göre\l"
	.string "antrenman yapmaya devam edeceğim.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Babam bu şehrin SALON LİDERİ.\p"
	.string "Babam gibi ZEHİR POKéMON'ları\n"
	.string "kullanarak antrenman yapıyorum.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA'nın ilaçlar hakkında geniş\n"
	.string "bir bilgisi varmış.\p"
	.string "POKéMON'larını iyileştirmek için\n"
	.string "kendi ilaçlarını bile hazırlarmış.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFARİ BÖLGESİ çok büyük, değil\n"
	.string "mi?\p"
	.string "FUCHSIA'nın SALON LİDERİ, KOGA, \n"
	.string "sık sık arazide devriye gezer.\p"
	.string "Onun sayesinde, burada güvenle\n"
	.string "oynayabiliyoruz.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON ŞEHRİ POKéMON SALON\n"
	.string "LİDERİ: SABRINA\l"
	.string "PSİŞİK POKéMON ustası!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON ŞEHRİ'ndeki SALON LİDERİ\n"
	.string "kızı biliyor musun?\p"
	.string "PSİŞİK türü POKéMON kullanıyor,\n"
	.string "değil mi?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Küçüklüğümden beri psişik güçlere\n"
	.string "sahibim.\p"
	.string "Her şey umarsızca attığım kaşığın\n"
	.string "bükülmesi ile başladı.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Savaşmayı sevmem, ama istiyorsan,\n"
	.string "sana gücümü göstereceğim!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}İnsanlar diyor ki SABRINA savaş\n"
	.string "sırasında POKéMON'ları ile\l"
	.string "konuşmadan iletişim kurabiliyor.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA henüz yan binadaki KARATE\n"
	.string "USTASI'nı yerle bir etti.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ADASI POKéMON SALON\n"
	.string "LİDERİ: BLAINE\l"
	.string "Asabi Quiz Ustası!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ateşli POKéMON'larım tamamen sert\n"
	.string "ve yoğun ısıyla savaşa hazır!\p"
	.string "Tüm meydan okuyanları yakarlar!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LİDERİMİZ, BLAINE, bir gün\n"
	.string "dağlarda kayboldu.\p"
	.string "Ateşli bir kuş POKéMON'u ortaya\n"
	.string "çıkınca gece çöktü.\p"
	.string "Onun ışığı BLAINE'in sağ salim\n"
	.string "yolunu bulmasını sağladı.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR SALONU'nun BLAINE'i\n"
	.string "değişik bir herif.\p"
	.string "LAB kurulmadan yıllar önce bile\n"
	.string "bu adada yaşıyordu.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE ve BAY FUJI'nin\n"
	.string "bir fotoğrafı.\p"
	.string "Omuz omuza vermiş büyük bir\n"
	.string "gülümsemeyle bakıyorlar.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE kara gözlüklerini sadece\n"
	.string "yeni quiz soruları düşünürken\l"
	.string "çıkarır.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ben ELİT DÖRTLÜ'den LORELEI.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Buz POKéMON konusunda kimse bana\n"
	.string "karşı koyamaz.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nerede doğmuş?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bu adada büyük ve çok güçlü bir\n"
	.string "EĞİTMEN yetişti.\p"
	.string "Eminim sen de tanıyorsundur.\n"
	.string "O ELİT DÖRTLÜ'den LORELEI!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mantıksal, hesaplı ve\n"
	.string "havalı savaş stiliyle LORELEI'nin\l"
	.string "sürpriz bir sırrı var!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LORELEI'nin tonlarca peluş\n"
	.string "oyuncağı olduğunu biliyor muydun?\p"
	.string "DÖRDÜNCÜ ADA'ya her geldiği zaman\n"
	.string "koleksiyonunu büyütür!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Onun LAPRAS'ı, sanırım çocukken\n"
	.string "çocukken karşılaştığı.\p"
	.string "İnanıyorum ki onu ICEFALL\n"
	.string "MAĞARASI'nda yakalamıştı\p"
	.string "Belki de o zamandan beri yanında\n"
	.string "tutuyor.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ben ELİT DÖRTLÜ'den BRUNO!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Dövüş POKéMON'larımla yaşadım ve\n"
	.string "antrenman yaptım!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO'nun ELİT DÖRTLÜ'ye katılma\n"
	.string "amacı onun en iyi EĞİTMENLER ile\l"
	.string "savaşma arzusu.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, benim üstadım,\n"
	.string "SPA'yı ara sıra ziyaret eder.\p"
	.string "Yaralarını iyileştirmek için gelir.\n"
	.string "Hem kendisi hem POKéMON'ları için.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O ELİT DÖRTLÜ'den biri.\n"
	.string "Onun adı BRUNO.\p"
	.string "Rage Şekerçubuklarının bittiğini\n"
	.string "öğrenince büyük hayal kırıklığına\l"
	.string "uğramıştı.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO bile…\n"
	.string "BRAWLY adında biriyle önceleri\l"
	.string "antrenman yapmıştı.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ben ELİT DÖRTLÜ'den AGATHA.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA'nın HAYALET POKéMON'larının\n"
	.string "dayanıklılığı dehşet korkutucu.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O yaşlı bayanın sinirleri\n"
	.string "gerçekten çabuk atıyor.\p"
	.string "O korkunç kadını kızdırmak için\n"
	.string "hiçbir şey yapmaya gerek yok.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Gençliğinde, AGATHA ve PROF. OAK\n"
	.string "en iyi EĞİTMEN olma yolunda\l"
	.string "birbirlerinin rakibiymiş.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Duydum ki OAK senin üzerine\n"
	.string "çok düşüyor, çocuk.\p"
	.string "O yaşlı bunak bir zamanlar sert ve\n"
	.string "yakışıklıydı.\p"
	.string "Ama bu yıllar önceydi.\n"
	.string "O artık eski halinin bir gölgesi.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Örneğin AGATHA'yı ele alalım.\p"
	.string "En yaşlı ELİT DÖRTLÜ üyesi olarak\n"
	.string "rekor kırdı.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ben ELİT DÖRTLÜ'nün lideriyim.\p"
	.string "Bana LANCE, ejderha EĞİTMENİ\n"
	.string "diyebilirsin.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ejderhaların destansı POKéMON'lar\n"
	.string "olduğunu biliyor musun?\p"
	.string "Yakalaması ve yetiştirmesi zordur.\n"
	.string "Ama güçleri muazzamdır.\p"
	.string "Neredeyse yok edilmezler.\n"
	.string "Onlarla ters düşemezsin.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O adaleti temsil eder!\n"
	.string "O çok havalı, ve tutkulu!\l"
	.string "O LANCE, en iyisi!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE adında bir müşterimiz var,\n"
	.string "ara sıra uğrar.\p"
	.string "Bizden sürekli pelerin alır.\p"
	.string "Acaba… Evinde bir sürü aynı\n"
	.string "pelerinlerden mi var?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE'in büyük babasının ünlü\n"
	.string "ejder ustaları klanının yaşlı\l"
	.string "üyelerinden olduğu düşünülüyor.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Duyduğuma göre, LANCE'ın kuzeni\n"
	.string "buradan uzaklarda bir SALON\l"
	.string "LİDERİ imiş.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nihayet, BILL dünyaca ünlü bir\n"
	.string "POKéMANYAK.\p"
	.string "POKéMON Depolama Sistemini\n"
	.string "o icat etti.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL'in çok POKéMON'u var!\n"
	.string "Nadir olanları da topluyor!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O benim torunum!\p"
	.string "Çocukluğundan beri bir şeyleri\n"
	.string "biriktirmeye bayılırdı!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL bir POKéMANYAK, yani her tür\n"
	.string "POKéMON'u sever.\p"
	.string "Görünüşe göre, ilk yakaladığı bir\n"
	.string "ABRA imiş.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL'in memleketi GOLDENROD ŞEHRİ,\n"
	.string "ailesi hala orada yaşıyor.\p"
	.string "Duydum ki çok hareketli, capcanlı\n"
	.string "bir şehirmiş.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Görünüşe göre, BILL sütü\n"
	.string "pek de sindiremiyor.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O çok iyi kalpli.\p"
	.string "Terkedilmiş ve yetim kalmış\n"
	.string "POKéMON'lara sahip çıkar.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bu yaşlı adam SIĞINAĞIMIZA\n"
	.string "fırtına gibi girdi.\p"
	.string "Sonra, ROKET TAKIMI'nın nasıl\n"
	.string "POKéMON'ları istismar ettiğinden\l"
	.string "bahsetti.\p"
	.string "Yani, burada yetişkinler olarak\n"
	.string "konuşuyoruz.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN DERGİSİ\n"
	.string "Aylık Büyük Ödül Çekilişi!\p"
	.string "Katılım formu…\p"
	.string "Gitmiş! Sayfa yırtılmış.\n"
	.string "Başka biri çoktan doldurmuş.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bir rivayete göre…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Duydum ki BAY FUJI buralardan\n"
	.string "değilmiş. Uzaklardan gelmiş.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE ve BAY FUJI'nin\n"
	.string "bir fotoğrafı.\p"
	.string "Omuz omuza vermiş büyük bir\n"
	.string "gülümsemeyle bakıyorlar.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editör: Nazik BAY FUJI röpörtaj\n"
	.string "isteğimizi geri çevirmedi.\p"
	.string "LAVENDER ŞEHRİ'nde çok sevilen ve\n"
	.string "sayılan çok kibar bir adam.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ROKET TAKIMI tüm dünyada POKéMON\n"
	.string "hırsızlığı yapar.\p"
	.string "Onlar suç örgütümüzün işlevi için\n"
	.string "önemli araçlar.\p"
	.string "Ben liderleri GIOVANNI'yim!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}En sevdiğin POKéMON türü?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}O haydutlar binayı ele\n"
	.string "geçirdi…\p"
	.string "PATRON'ları güçlü POKéMON\n"
	.string "aradıklarını söyledi.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi nasıl biri?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ROKET TAKIMI PATRON'u korkunç\n"
	.string "derecede acımasız!\p"
	.string "Ona göre, POKéMON'lar sadece\n"
	.string "kullanılan bir araç.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sığınağımıza hoş geldin!\p"
	.string "ROKET TAKIMI'nın eski şanını geri\n"
	.string "getirene kadar böyle olacak.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Bu kişi ne yapar?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hadi oradan! GIOVANNI VIRIDIAN\n"
	.string "SALON LİDERİ miymiş?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Aile ve arkadaşları?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sen… Sen GIOVANNI'nin oğlu değilsin,\n"
	.string "değil mi?\p"
	.string "Hayır, sen olamazsın.\n"
	.string "GIOVANNI'nin oğlunun saçı kırmızı.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: PROF. OAK\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Neden POKéMON'lar senin için\n"
	.string "bu kadar azimli savaşıyor?\p"
	.string "Çünkü senin onlara karşı olan\n"
	.string "sevgini ve güvenini\l"
	.string "hissederler.\p"
	.string "Bunu asla unutma.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: DAISY\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ben çay molalarımda rahatlarken,\n"
	.string "sen çok geliştin ve güçlendin\p"
	.string "Umarım küçük kardeşime iyi bir\n"
	.string "rakip olmaya devam edersin.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: BROCK\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bu koca dünyada, çokça\n"
	.string "zorlu EĞİTMEN olmalı.\p"
	.string "Antrenman yapmaya devam edelim ve\n"
	.string "daha da güçlenelim!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: MISTY\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Bu SALON'da eğitime\n"
	.string "devam edeceğim.\p"
	.string "Daha iyi olduğumda, dünyayı\n"
	.string "dolaşmayı çok isterim.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}TĞM. SURGE$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: TĞM. SURGE\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, çocuk!\n"
	.string "Savaşımızda beni resmen çarptın!\p"
	.string "Senin gibi yürekli EĞİTMENLER\n"
	.string "olduğunu bilmiyordum.\p"
	.string "Senin hakkında düşüncelerimi\n"
	.string "değiştirdi!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: ERIKA\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Senin gibi güçlü EĞİTMENLER\n"
	.string "olduğu için çok memnunum.\p"
	.string "Bu farkındalık beni daha çok\n"
	.string "çalışmaya motive ediyor.\p"
	.string "Lütfen tekrar uğra.\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: KOGA\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sen ve ben, daha büyük hedefler\n"
	.string "koymalı ve önümüzdeki zorluklar\l"
	.string "için çok çalışmalıyız.\p"
	.string "Şimdi, kızımı eğitmek için gitmeliyim.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: SABRINA\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}İçindeki POKéMON'lara olan\n"
	.string "sevgi…\p"
	.string "O benim psişik güçlerimin bile\n"
	.string "karşı koyamadığı bir güç.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: BLAINE\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ateş POKéMON'larım!\n"
	.string "Daha da güçlü olacaklar!\p"
	.string "Şimdi quiz zamanı! Dünyada kaç çeşit\n"
	.string "ATEŞ türü POKéMON vardır?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: LORELEI\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Yardımın için sana çok teşekkür\n"
	.string "etmeliyim.\p"
	.string "Ama bu savaşlarımızı etkilemez.\p"
	.string "Sonraki sefer daha dikkatli ol!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: BRUNO\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON'larının ve senin süper\n"
	.string "gücünü bizzat deneyimledim.\p"
	.string "Sonraki sefer, belki de kendini\n"
	.string "nasıl eğiteceğini göstermeliyim.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: AGATHA\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Yaşlanınca sakın o yaşlı OAK gibi\n"
	.string "yumuşak olma!\p"
	.string "Benim gibi ol ve savaşa devam et!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: LANCE\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Memleketime dönmeyi\n"
	.string "düşünüyorum.\p"
	.string "EJDER tipi POKéMON'larımı tekrar\n"
	.string "eğitip onları güçlendireceğim.\p"
	.string "Bir gün seni de oraya davet\n"
	.string "etmek isterim.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: BILL\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, merhaba! CELIO senin için çok\n"
	.string "iyi söz ediyor.\p"
	.string "Bunu duymak beni mutlu ediyor.\p"
	.string "Eğer nadir POKéMON yakalarsan\n"
	.string "bana göster, olur mu? Söz!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BAY FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: BAY FUJI\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Kendi POKéMON'larının mutluluğunu\n"
	.string "istemektense…\p"
	.string "…Tüm POKéMON'ların mutluluğunu\n"
	.string "diler misin?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gönderici: GIOVANNI\n"
	.string "Alıcı: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sana söylemek istediğim bir\n"
	.string "şey yok.\p"
	.string "Sadece kendimi geliştirmeye\n"
	.string "odaklanacağım. Başka söz yok.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "PALLET KASABASI$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "ARAŞTIRMA LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "ARAŞTIRMA LAB$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "VIRIDIAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "ARAŞTIRMA LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "ARAŞTIRMA LAB$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "VERMILION ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "SU LABİRENTİ$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "VIRIDIAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "CELADON KONAĞI$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "DÖRDÜNCÜ ADA$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PEWTER ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PEWTER SALONU$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PEWTER ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "ROTA 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "AY DAĞI$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "PEWTER MÜZESİ$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CERULEAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "CERULEAN SALONU$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "CERULEAN SALONU$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "SEAFOAM ADALARI$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CERULEAN BURNU$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CERULEAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "VERMILION ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "VERMILION SALONU$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "VERMILION SALONU$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "VERMILION SALONU$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "VERMILION SALONU$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "VERMILION ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "CELADON ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "CELADON SALONU$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "CELADON SALONU$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "CELADON SALONU$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "CELADON SALONU$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "CELADON MANSION$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCHSIA ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "FUCHSIA SALONU$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "FUCHSIA SALONU$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCHSIA ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCHSIA ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "SAFARI ZONE$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "SAFFRON ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "ÜÇÜNCÜ ADA$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "SAFFRON SALONU$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "SAFFRON SALONU$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "SAFFRON ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "SAFFRON SALONU$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "CINNABAR ADASI$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "CINNABAR SALONU$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "CINNABAR SALONU$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "CINNABAR ADASI$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "CINNABAR SALONU$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "MÜTHİŞ TATİL KÖYÜ$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "DÖRDÜNCÜ ADA$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "BEŞİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "DÖRDÜNCÜ ADA$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "DÖRDÜNCÜ ADA$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "SAFFRON ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "KÖZ SPA$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "İKİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "SEVAULT KANYONU$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "INDIGO PLATOSU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "INDIGO PLATOSU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "YEDİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "ALTINCI ADA$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "POKéMON LİGİ$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "SAFFRON ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CELADON MAĞAZASI$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "INDIGO PLATOSU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "INDIGO PLATOSU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CERULEAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CERULEAN ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCHSIA ŞEHRİ$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "BİRİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "BİRİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "BİRİNCİ ADA$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVENDER KASABASI$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "POKéMON KULESİ$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVENDER KASABASI$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVENDER KASABASI$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "CINNABAR SALONU$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "CINNABAR ADASI$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "ROCKET SIĞINAĞI$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH ŞTİ.$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH ŞTİ.$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "VIRIDIAN SALONU$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "VIRIDIAN SALONU$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "ROCKET DEPOSU$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "YARDIMCI$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "YARDIMCI$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "YARDIMCI$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "KADIN$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "ADAM$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "YAŞLI BAYAN$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "GENÇ ADAM$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "ÇOCUK$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "ADAM$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "GENÇ ADAM$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "DAME$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "TĞM. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "TUCKER$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "DWAYNE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "LOLA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "ADAM$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "GENÇ ADAM$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "İMZA$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "DEREK$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "KADIN$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "FOTOĞRAF$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "YAŞLI ADAM$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "KÜÇÜK KIZ$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "YAŞLI BAYAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "KADIN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "YAŞLI BAYAN$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "KADIN$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "KÜÇÜK KIZ$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "GENÇ ADAM$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "KÜÇÜK ÇOCUK$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "YAŞLI ADAM$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "KÜÇÜK KIZ$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "ROKET TAKIMI$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "DERGİ$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "ADAM$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "FOTOĞRAF$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKéMON GAZETE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "BİLİM ADAMI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "BİLİM ADAMI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "ADAM$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: PEWTER SALONU\n"
	.string "LİDERİ BROCK!\p"
	.string "BROCK nadiren güler, ama söylenene\n"
	.string "göre gülmeye başlarsa asla durmaz.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: CERULEAN SALONU\n"
	.string "LİDERİ MISTY!\p"
	.string "Söylenene göre MISTY ELİT DÖRTLÜ\n"
	.string "üyesi LORELEI'nin büyük hayranı.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: VERMILION SALONU\n"
	.string "LİDERİ TĞM. SURGE!\p"
	.string "Rivayete göre TĞM. SURGE\n"
	.string "Amerika'da pilotluk yapıyordu.\p"
	.string "Uçağını çalıştırmak için elektrik\n"
	.string "POKéMON'ları kullanıyordu.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: CELADON SALONU\n"
	.string "LİDERİ ERIKA!\p"
	.string "Rivayete göre CELADON SALONU'na\n"
	.string "gizlice bakarsanız, ERIKA'yı\l"
	.string "uyuklarken görebilirsiniz.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: FUCHSIA SALONU\n"
	.string "LİDERİ KOGA!\p"
	.string "Söylenene göre KOGA'nın ilaçlar\n"
	.string "hakkında geniş bir bilgisi varmış.\p"
	.string "POKéMON'larını iyileştirmek için\n"
	.string "kendi ilaçlarını bile hazırlarmış.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: SAFFRON SALONU\n"
	.string "LİDERİ SABRINA!\p"
	.string "İnsanlar diyor ki SABRINA savaş\n"
	.string "sırasında POKéMON'ları ile\l"
	.string "konuşmadan iletişim kurabiliyor.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: CINNABAR SALONU\n"
	.string "LİDERİ BLAINE!\p"
	.string "BLAINE kara gözlüklerini sadece\n"
	.string "yeni quiz soruları düşünürken\l"
	.string "çıkarırmış.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet:\n"
	.string "ELİT DÖRTLÜ'den LORELEI!\p"
	.string "Mantıksal, hesaplı ve havalı\n"
	.string "savaş stiliyle bilinen LORELEI'nin\l"
	.string "sürpriz bir sırrı var!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet:\n"
	.string "ELİT DÖRTLÜ'den BRUNO!\p"
	.string "BRUNO'nun ELİT DÖRTLÜ'ye katılma\n"
	.string "amacı onun en iyi EĞİTMENLER ile\l"
	.string "savaşma arzusu.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet:\n"
	.string "ELİT DÖRTLÜ'den AGATHA!\p"
	.string "Gençliğinde, AGATHA ve PROF. OAK\n"
	.string "en iyi EĞİTMEN olma yolunda\l"
	.string "birbirlerinin rakibiymiş.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet:\n"
	.string "ELİT DÖRTLÜ'den LANCE!\p"
	.string "LANCE'in büyük babasının ünlü\n"
	.string "ejder ustaları klanının yaşlı\l"
	.string "üyelerinden olduğu düşünülüyor.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet: PROF. OAK,\n"
	.string "POKéMON araştırmacısı!\p"
	.string "PROF. OAK duyuma göre torunlarıyla\n"
	.string "yaşıyor, DAISY ve {RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Bu yıllar öncesinden kalmış\n"
	.string "bir gazete…\p"
	.string "POKéMON GAZETE\n"
	.string "YARIŞMA Özel!\p"
	.string "Bahar POKéMON YARIŞMASI'nın\n"
	.string "Büyük Şampiyonu PALLET KASABASI\l"
	.string "sakini DAISY OAK!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON GAZETE\p"
	.string "Özel Manşet:\n"
	.string "POKéMON EVİ'nden BAY FUJI!\p"
	.string "Editör: Nazik BAY FUJI röpörtaj\n"
	.string "isteğimizi geri çevirmedi.\p"
	.string "LAVENDER ŞEHRİ'nde çok sevilen ve\n"
	.string "sayılan çok kibar bir adam.$"
