Text_Bookshelf::
  .string "POKéMON kitaplarıyla dolu.$"

Text_NothingButPokemonBooks::
  .string "ほんだなに ならんでいるのは ポケモンの ほん ばかりだ$"

Text_ATownMap::
  .string "BİR ŞEHİR HARİTASI.$"

Text_PokeMartShelf::
  .string "Vay canına! Tonlarca POKéMON şeyi!$"

Text_DishesPlatesNeatlyLinedUp::
  .string "Tabaklar ve bulaşıklar\ndüzgünce dizilmiş.$"

Text_Kitchen::
  .string "Nefis kokuyor! Birileri burada yemek\npişirmiş.$"

Text_Dresser::
  .string "Güzel yapılmış bir şifonyer. Bir sürü\neşya alır.$"

Text_Snacks::
  .string "Burada bir yığın atıştırmalık var.$"

Text_PokemartSign::
  .string "Tüm eşya ihtiyaçlarınız karşılansın!\nPOKéMON MARKET$"

Text_PokecenterSign::
  .string "POKéMON'unuzu İyileştirin!\nPOKéMON MERKEZİ$"

Text_Indigo_UltimateGoal::
  .string "INDIGO PLATOSU\pEĞİTMENLERİN nihai hedefi! POKéMON\nLİG MERKEZİ$"

Text_Indigo_HighestAuthority::
  .string "INDIGO PLATOSU\pEn yüksek POKéMON otoritesi! POKéMON\nLİG MERKEZİ$"

Text_Food::
  .string "Yiyecek her türlü lezzetli şeyle dolu\nolmalıdır.$"

Text_Blueprints::
  .string "Bir çeşit plan. Şemalar ve metinlerle\ndolu.$"

Text_Painting::
  .string "Bu bir POKéMON'un güzel bir resmi.\nİyi hissediyor gibi görünüyor.$"

Text_PowerPlantMachine::
  .string "Bu makine ne olabilir? Onunla\nuğraşmasan iyi olur!$"

Text_Telephone::
  .string "Bu bir telefon. Kullanmasan iyi olur.$"

Text_Computer::
  .string "Hiçbir anlam ifade etmeyen karmaşık\nkelimeler ve sayılar…$"

Text_AdvertisingPoster::
  .string "Her türlü ürün hakkında bir reklam\nafişi.$"

Text_TastyFood::
  .string "Çok lezzetli kokuyor! Mideniz\nguruldayabilir!$"

Text_TrashBin::
  .string "Bunun içinde…\n……\pBurada hiçbir şey yok!$"

Text_Cup::
  .string "Üzerinde POKéMON işareti olan bir\nfincan.$"

Text_PolishedWindow::
  .string "Pencere çok iyi cilalanmış.$"

Text_BeautifulSkyWindow::
  .string "Pencerenin dışında.\pGökyüzü fevkalade güzel görünüyor.$"

Text_BlinkingLights::
  .string "Farklı renklerdeki ışıklar yanıp\nsönüyor.$"

Text_NeatlyLinedUpTools::
  .string "Her türlü alet düzgün bir şekilde\nsıralanmış.$"

Text_ImpressiveMachine::
  .string "Bir çeşit makine. Kesinlikle etkileyici.$"

Text_VideoGame::
  .string "Bu son video oyunu! Kesinlikle\neğlenceli görünüyor!$"

Text_Burglary::
  .string "Burada bariz hırsızlık izleri var.$"

Text_PlayerFacingTVScreen::
  .string "Televizyonda bir POKéMON var!\nEğleniyor gibi görünüyor.$"

