Help_Text_WhatShouldIDo::
	.string "Şu durumda ne yaparım?$"

Help_Text_HowDoIDoThis::
	.string "Şunu nasıl yapacağım?$"

Help_Text_WhatDoesThisTermMean::
	.string "Bu terimin anlamı ne?$"

Help_Text_AboutThisGame::
	.string "Oyun hakkında$"

Help_Text_TypeMatchupList::
	.string "Türlerin güçlü-zayıf yanları$"

Help_Text_Exit::
	.string "ÇIKIŞ$"

Help_Text_Cancel::
	.string "İPTAL$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Belirli durumlarda ne yapacağını\n"
	.string "öğrenmek için birini seç.$"

Help_Text_DescHowDoIDoThis::
	.string "Kullanabileceğin seçeneklerin\n"
	.string "detaylı açıklamaları.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Oyunun içinde çok kullanılan\n"
	.string "terimlerin açıklamaları.$"

Help_Text_DescAboutThisGame::
	.string "Oyun hakkında genel detaylar ve\n"
	.string "bilgiler.$"

Help_Text_DescTypeMatchupList::
	.string "POKéMON türlerinin hangi türlere\n"
	.string "karşı güçlü-zayıf olduğu bilgisi.$"

Help_Text_DescExit::
	.string "YARDIM sisteminden çık.$"

Help_Text_Greetings::
	.string "Merhaba! Burası YARDIM sistemi.\n"
	.string "L veya R tuşlarına basarak istediğin\l"
	.string "zaman burayı açabilirsin.\l"
	.string "Yardım mesajları durumdan duruma\l"
	.string "değişir, bu yüzden buraya sık sık\luğramayı unutma.$"

Help_Text_PlayingForFirstTime::
	.string "İlk kez oynuyorum. Yardım lazım!$"

Help_Text_WhatShouldIBeDoing::
	.string "Ne yapmam gerekiyor?$"

Help_Text_CantGetOutOfRoom::
	.string "Odadan dışarı çıkamıyorum!$"

Help_Text_CantFindPersonIWant::
	.string "Aradığım kişiyi bulamıyorum.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "Herkesle konuştum. Peki şimdi?$"

Help_Text_SomeoneBlockingMyWay::
	.string "Birisi yolumu kapatıyor!$"

Help_Text_ICantGoOn::
	.string "Devam edemiyorum!$"

Help_Text_OutOfThingsToDo::
	.string "Yapacak bir şey bulamıyorum.$"

Help_Text_WhatHappenedToItemIGot::
	.string "Aldığım eşya nereye gitti?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Maceramda ne yapmalıyım?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Yollar ve ormanların farkı ne?$"

Help_Text_HowAreCavesDifferent::
	.string "Mağaraların ne yönden farklı?$"

Help_Text_HowDoIProgress::
	.string "Nasıl ilerleyeceğim?$"

Help_Text_WhenCanIUseItem::
	.string "Eşyalarımı ne zaman kullanabilirim?$"

Help_Text_WhatsABattle::
	.string "Savaş nedir?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Savaşa nasıl hazırlanabilirim?$"

Help_Text_WhatIsAMonsVitality::
	.string "POKéMON'un sağlığı nasıl çalışır?$"

Help_Text_MyMonsAreHurt::
	.string "POKéMON'um yaralandı!$"

Help_Text_WhatIsStatusProblem::
	.string "Durum sorunları nelerdir?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Ya tüm POKéMON'larım bayılırsa?$"

Help_Text_CantCatchMons::
	.string "POKéMON yakalayamıyorum!$"

Help_Text_RanOutOfPotions::
	.string "İksirim kalmadı.$"

Help_Text_CanIBuyPokeBalls::
	.string "POKé TOPU alabilir miyim?$"

Help_Text_WhatsATrainer::
	.string "EĞİTMEN nedir?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "Bir eğitmeni nasıl yenerim?$"

Help_Text_WhereDoMonsAppear::
	.string "POKéMON'lar nerede çıkar?$"

Help_Text_WhatAreMoves::
	.string "POKéMON hamleleri nedir?$"

Help_Text_WhatAreHiddenMoves::
	.string "GİZLİ hamle nedir?$"

Help_Text_WhatMovesShouldIUse::
	.string "Hangi hamleleri kullansam?$"

Help_Text_WantToAddMoreMoves::
	.string "Yeni hamleler istiyorum.$"

Help_Text_WantToMakeMonStronger::
	.string "POKéMON'um güçlensin istiyorum.$"

Help_Text_FoeMonsTooStrong::
	.string "Düşman POKéMON'lar çok güçlü!$"

Help_Text_WhatDoIDoInCave::
	.string "Mağaralarda ne yapmalıyım?$"

Help_Text_NothingIWantToKnow::
	.string "Hiçbir şey öğrenmek istemiyorum!$"

Help_Text_WhatsPokemonCenter::
	.string "POKéMON MERKEZİ nedir?$"

Help_Text_WhatsPokemonMart::
	.string "POKéMON MART nedir?$"

Help_Text_WantToEndGame::
	.string "Oyunu kapatmak istiyorum.$"

Help_Text_WhatsAMon::
	.string "POKéMON nedir?$"

Help_Text_WhatIsThatPersonLike::
	.string "Şu kişi nasıl biri?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "GİZLİ hamle ne işe yarıyor?$"

Help_Text_WhatDoIDoInSafari::
	.string "SAFARİ OYUNU'nda ne yaparım?$"

Help_Text_WhatAreSafariRules::
	.string "SAFARİ OYUNU kuralları nelerdir?$"

Help_Text_WantToEndSafari::
	.string "SAFARİ OYUNU'ndan çıkmak istiyorum!$"

Help_Text_WhatIsAGym::
	.string "Salon nedir?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "You become the main character,\n"
	.string "exploring the world of POKéMON.\l"
	.string "By talking to people and solving\l"
	.string "mysteries, new paths will open to you.\l"
	.string "Strive for the goal together with your\l"
	.string "wonderful POKéMON.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "When you come across another person,\n"
	.string "go up to them and press the A Button.\l"
	.string "That will get them to talk and interact\l"
	.string "with your character. You may also\l"
	.string "examine various items and objects in\l"
	.string "the same way. Talk to people and check\l"
	.string "things often to obtain information.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "On the stairs or the exits of a\n"
	.string "building is a red mat. Move your\l"
	.string "character to stand on top of the\l"
	.string "red mat. Press the {PLUS} Control Pad \l"
	.string "toward the stairs or the exit to\l"
	.string "advance.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "This isn't something you should worry\n"
	.string "about too much.\l"
	.string "Talk to other people, check signs,\l"
	.string "check things, and so on.\l"
	.string "Sometimes, you may need to just move\l"
	.string "to a new town or place.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Try moving on to a new road, town, or\n"
	.string "place.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "There could be something in the town\n"
	.string "or inside a building that is the cause.\l"
	.string "Try talking to the people in the area\l"
	.string "again. If there is a problem that they\l"
	.string "need solved, you may have to help.\l"
	.string "Afterwards, try talking to the person\l"
	.string "blocking your way again.$"

Help_Text_AnswerICantGoOn::
	.string "Try talking to people by going up to\n"
	.string "them and pressing the A Button.\l"
	.string "Also, try checking things like odd trees\l"
	.string "and strange rocks with the A Button.\l"
	.string "Press the {PLUS} Control Pad and try going\l"
	.string "to places that look impassable, too.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Try going to places where you \n"
	.string "haven't visited yet.\l"
	.string "Also, check everything that looks\l"
	.string "suspicious by pressing the A Button.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Any item that you are given by another\n"
	.string "character goes in your BAG.\l"
	.string "The item is automatically sorted and\l"
	.string "placed in one of three pockets.\l"
	.string "For instructions on the BAG's use,\l"
	.string "please refer to the HELP System's\l"
	.string "“How do I do this?” heading.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "If POKéMON are hurt in battle,\n"
	.string "take them to a POKéMON CENTER and\l"
	.string "have them healed by the staff.\l"
	.string "Get in the habit of saving your\l"
	.string "game and recording your progress.\l"
	.string "Stock up on healing items at\l"
	.string "POKéMON MARTS before traveling far.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Forests are basically the same as\n"
	.string "roads but they can be like mazes.\l"
	.string "All forests have a way out, so don't\l"
	.string "give up if you get lost.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Caves are dark and dangerous. Wild\n"
	.string "POKéMON can appear anywhere in them.\l"
	.string "If there is an emergency, rush to a\l"
	.string "POKéMON CENTER or use items.\l"
	.string "New towns await discovery beyond some\l"
	.string "caves, so don't give up.$"

Help_Text_AnswerHowDoIProgress::
	.string "The object of the game is to train\n"
	.string "your POKéMON and move forward.\l"
	.string "You must collect info and solve\l"
	.string "problems. For example, what do you\l"
	.string "need to get around an obstacle?\l"
	.string "What would get that impeding\l"
	.string "person out of the way?$"

Help_Text_AnswerWhenCanIUseItem::
	.string "There are several kinds of items.\n"
	.string "Some can be used only on the field.\l"
	.string "Some are only for use during battle.\l"
	.string "Some can be used anytime.\l"
	.string "Try using an item - if it can't be used,\l"
	.string "you will be alerted.$"

Help_Text_AnswerWhatsABattle::
	.string "In a battle, POKéMON try to reduce\n"
	.string "one another's vitality, expressed as\l"
	.string "HP. If a POKéMON's HP falls to zero,\l"
	.string "it faints, and the other POKéMON\l"
	.string "wins. By winning a battle, POKéMON\l"
	.string "earn EXP. Points, which help them\l"
	.string "level up (grow stronger).$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "First, fully heal the POKéMON in your\n"
	.string "party (the POKéMON with you) at any\l"
	.string "POKéMON CENTER.\l"
	.string "You should also buy healing items for\l"
	.string "emergencies at a POKéMON MART.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "A POKéMON's vitality is expressed in HP.\n"
	.string "If a POKéMON is hurt in battle, HP is\l"
	.string "subtracted. If its HP drops to zero,\l"
	.string "the POKéMON faints.\l"
	.string "Heal hurt or fainted POKéMON at a\l"
	.string "POKéMON CENTER or by using items.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "A POKéMON CENTER is like an inn for\n"
	.string "POKéMON. It will fully heal POKéMON of\l"
	.string "any status problems and fully restore\l"
	.string "their HP using a special machine.\l"
	.string "This service is free, so get in the\l"
	.string "habit of healing your POKéMON often.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "A status problem refers to an ailment\n"
	.string "that is inflicted on a POKéMON by its\l"
	.string "foe's attack. These include burns,\l"
	.string "paralysis, poisoning, sleep, and\l"
	.string "freezing. These can be healed by\l"
	.string "visiting a POKéMON CENTER or using\l"
	.string "the appropriate item.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "If all the POKéMON in your party\n"
	.string "(all the POKéMON with you) faint, you\l"
	.string "lose some MONEY, and you are\l"
	.string "returned home or to a POKéMON\l"
	.string "CENTER. To reduce that chance, visit\l"
	.string "POKéMON CENTERS often. Also, get\l"
	.string "in the habit of saving often.$"

Help_Text_AnswerCantCatchMons::
	.string "If a wild POKéMON escapes from a POKé\n"
	.string "BALL, it's obviously still feisty.\l"
	.string "Try reducing its HP some more, and\l"
	.string "try to weaken it with paralysis or sleep\l"
	.string "before trying to catch it.\l"
	.string "If the POKé BALL rocks for a while,\l"
	.string "the quarry is close to being caught!$"

Help_Text_AnswerRanOutOfPotions::
	.string "There are shops, known as POKéMON\n"
	.string "MARTS, that sell items.\l"
	.string "You will not find POKéMON MARTS on\l"
	.string "roads, in forests, or in caves.\l"
	.string "Stock up on needed items while you are\l"
	.string "visiting a town with a POKéMON MART.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "You may buy POKé BALLS at any\n"
	.string "POKéMON MART in any town.\l"
	.string "You will not find POKéMON MARTS on\l"
	.string "roads, in forests, or in caves.\l"
	.string "Stock up on POKé BALLS while you are\l"
	.string "visiting a town with a POKéMON MART.$"

Help_Text_AnswerWhatsATrainer::
	.string "A TRAINER is a person who raises\n"
	.string "POKéMON through battling.\l"
	.string "TRAINERS will challenge you \l"
	.string "wherever they are - it could be on\l"
	.string "a road, in forests, caves, anywhere.\l"
	.string "If your eyes meet, you have to accept\l"
	.string "their challenge. So be careful!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "To beat a TRAINER in battle, use\n"
	.string "POKéMON that have type advantages\l"
	.string "over the foe's POKéMON. You may also\l"
	.string "use highly trained POKéMON with\l"
	.string "overwhelming power. Outnumbering the\l"
	.string "foe's POKéMON is another obvious\l"
	.string "tactic.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Wild POKéMON will appear in tall grass,\n"
	.string "on roads, and in forests. They will\l"
	.string "appear anywhere in dark caves.\l"
	.string "There are no wild POKéMON or TRAINERS\l"
	.string "in towns, so they are safe places.$"

Help_Text_AnswerWhatAreMoves::
	.string "POKéMON may learn up to four different\n"
	.string "techniques, or moves. There is a great\l"
	.string "variety of moves including attacks and\l"
	.string "those with special effects. The kinds\l"
	.string "of moves that can be learned vary\l"
	.string "for each POKéMON. Some moves\l"
	.string "can be learned from machines.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "HIDDEN moves are those that are\n"
	.string "especially important for your\l"
	.string "adventure. To use such a move outside\l"
	.string "of battle, open the “POKéMON” MENU\l"
	.string "and make the POKéMON that knows the\l"
	.string "move use it. A fainted POKéMON may use\l"
	.string "a HIDDEN move outside of battle.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Select “FIGHT,” and the MENU of moves\n"
	.string "will appear. Consider the type\l"
	.string "matchups, and use the most effective\l"
	.string "moves. You can check the effects of\l"
	.string "moves by opening “POKéMON,”\l"
	.string "picking a POKéMON, opening “SUMMARY,”\l"
	.string "then opening “POKéMON SKILLS.”$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "The most a POKéMON can learn is four\n"
	.string "moves. They are learned as the\l"
	.string "POKéMON levels up. It can also be\l"
	.string "taught a move using a TM (Technical\l"
	.string "Machine) or HM (Hidden Machine).\l"
	.string "There are also people who teach moves.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "The key to making your POKéMON\n"
	.string "strong is to battle and win often.\l"
	.string "The EXP. (Experience) Points earned\l"
	.string "by winning battles accumulate to\l"
	.string "level up POKéMON that participated in\l"
	.string "them. Battle wild POKéMON often to\l"
	.string "level up your party.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "If your foes are too strong, try\n"
	.string "leveling up your POKéMON some more.\l"
	.string "Go back the way you came and battle\l"
	.string "wild POKéMON to level up your party.\l"
	.string "You may also battle TRAINERS whom you\l"
	.string "have not battled before.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Unlike roads and forests, wild POKéMON\n"
	.string "can appear anywhere in caves.\l"
	.string "If your POKéMON are hurt in a cave,\l"
	.string "rush to a POKéMON CENTER or use items\l"
	.string "to heal them right away. It is very\l"
	.string "dangerous to force your luck in caves.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Trust your own knowledge and power.\n"
	.string "Believe in yourself and find your way!$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "A POKéMON CENTER is identified by its\n"
	.string "red roof and a “P.C” sign. Every\l"
	.string "POKéMON CENTER offers such services as\l"
	.string "fully healing POKéMON and free PC use,\l"
	.string "making it essential for your travels.\l"
	.string "On the upper floor are facilities for\l"
	.string "linking with friends and others.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "A POKéMON MART is identified by its\n"
	.string "blue roof and a “MART” sign.\l"
	.string "Items can be bought and sold at any\l"
	.string "POKéMON MART. Some MARTS carry items\l"
	.string "that are available only in their towns.$"

Help_Text_AnswerWantToEndGame::
	.string "You can safely end your game by\n"
	.string "selecting “SAVE” on the MENU.\l"
	.string "Once you have saved, the game can be\l"
	.string "safely turned off. When the game is\l"
	.string "turned back on, you can resume from\l"
	.string "where you last saved.$"

Help_Text_AnswerWhatsAMon::
	.string "POKéMON are living beings about which\n"
	.string "many mysteries still remain. You may\l"
	.string "see them in grass, the sea, and caves.\l"
	.string "They appear to obey the wishes of the\l"
	.string "TRAINERS that caught them.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Use the FAME CHECKER among the\n"
	.string "KEY ITEMS in your BAG.\l"
	.string "It may give you a hint, so try it out.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "A HIDDEN move is taught to a POKéMON\n"
	.string "using an HM (Hidden Machine).\l"
	.string "A HIDDEN move is important for helping\l"
	.string "your adventure. For example, one is\l"
	.string "used to light up dark caves. Another\l"
	.string "cuts down small trees. There is one\l"
	.string "for traveling on water, and so on.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Try to catch wild POKéMON by throwing\n"
	.string "the special SAFARI BALLS.\l"
	.string "You may keep any item you find, too.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "Your SAFARI GAME ends once you have\n"
	.string "traveled a certain distance or thrown\l"
	.string "all your SAFARI BALLS.\l"
	.string "Open the MENU to check the remaining\l"
	.string "number of steps and SAFARI BALLS.$"

Help_Text_AnswerWantToEndSafari::
	.string "If you would like to cut your SAFARI\n"
	.string "GAME short, open the MENU and select\l"
	.string "“RETIRE” at the top of the list.$"

Help_Text_AnswerWhatIsAGym::
	.string "POKéMON GYMS are operated by the\n"
	.string "POKéMON LEAGUE and are training\l"
	.string "facilities for TRAINERS. They are all\l"
	.string "across the land in cities and towns.\l"
	.string "Each one is headed by a LEADER, who\l"
	.string "is a very skilled TRAINER. Beat the\l"
	.string "LEADER to collect a BADGE.$"

Help_Text_UsingPokedex::
	.string " Using “POKéDEX”$"

Help_Text_UsingPokemon::
	.string " Using “POKéMON”$"

Help_Text_UsingSummary::
	.string "  Using “SUMMARY”$"

Help_Text_UsingSwitch::
	.string "  Using “SWITCH”$"

Help_Text_UsingItem::
	.string "  Using “ITEM”$"

Help_Text_UsingBag::
	.string " Using “BAG”$"

Help_Text_UsingAnItem::
	.string "  Using an item$"

Help_Text_UsingKeyItem::
	.string "  Using a key item$"

Help_Text_UsingPokeBall::
	.string "  Using a POKé BALL$"

Help_Text_UsingPlayer::
	.string " Using “{PLAYER}”$"

Help_Text_UsingSave::
	.string " Using “SAVE”$"

Help_Text_UsingOption::
	.string " Using “OPTION”$"

Help_Text_UsingPotion::
	.string "    Using a POTION$"

Help_Text_UsingTownMap::
	.string "    Using the TOWN MAP$"

Help_Text_UsingTM::
	.string "    Using a TM$"

Help_Text_UsingHM::
	.string "    Using an HM$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Using a move outside of battle$"

Help_Text_RidingBicycle::
	.string "    Riding the BICYCLE$"

Help_Text_EnteringName::
	.string "Entering a name$"

Help_Text_UsingPC::
	.string "Using a PC$"

Help_Text_UsingBillsPC::
	.string " Using “{STR_VAR_1}'S PC”$"

Help_Text_UsingWithdraw::
	.string "  Using “WITHDRAW”$"

Help_Text_UsingDeposit::
	.string "  Using “DEPOSIT”$"

Help_Text_UsingMove::
	.string "  Using “MOVE”$"

Help_Text_MovingItems::
	.string "  Moving items$"

Help_Text_UsingPlayersPC::
	.string " Using “{PLAYER}'s PC”$"

Help_Text_UsingWithdrawItem::
	.string "  Using “WITHDRAW ITEM”$"

Help_Text_UsingDepositItem::
	.string "  Using “DEPOSIT ITEM”$"

Help_Text_UsingMailbox::
	.string "  Using “MAILBOX”$"

Help_Text_UsingProfOaksPC::
	.string " Using “PROF. OAK'S PC”$"

Help_Text_OpeningMenu::
	.string "Opening the MENU$"

Help_Text_UsingFight::
	.string " Using “FIGHT”$"

Help_Text_UsingPokemon2::
	.string " Using “POKéMON”$"

Help_Text_UsingShift::
	.string "  Using “SHIFT”$"

Help_Text_UsingSummary2::
	.string "  Using “SUMMARY”$"

Help_Text_UsingBag2::
	.string " Using “BAG”$"

Help_Text_ReadingPokedex::
	.string " Reading the “POKéDEX”$"

Help_Text_UsingHomePC::
	.string "Using the PC at home$"

Help_Text_UsingItemStorage::
	.string "Using the Item Storage System$"

Help_Text_UsingWithdrawItem2::
	.string "  Using “WITHDRAW ITEM”$"

Help_Text_UsingDepositItem2::
	.string "  Using “DEPOSIT ITEM”$"

Help_Text_UsingMailbox2::
	.string "Using the MAILBOX$"

Help_Text_UsingRun::
	.string " Using “RUN”$"

Help_Text_RegisterKeyItem::
	.string "  “REGISTER” a key item$"

Help_Text_UsingBall::
	.string " Using “BALL”$"

Help_Text_UsingBait::
	.string " Using “BAIT”$"

Help_Text_UsingRock::
	.string " Using “ROCK”$"

Help_Text_UsingHallOfFame::
	.string " Using “HALL OF FAME”$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Select “POKéDEX” on the MENU.\n"
	.string "{CIRCLE_2} Choose POKéMON using commands such\n"
	.string "   as “POKéMON LIST,”\n"
	.string "   “HABITATS OF POKéMON,” and\n"
	.string "   “SEARCH.”\n"
	.string "{CIRCLE_3} Select a POKéMON to obtain detailed\n"
	.string "   information.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Select “POKéMON” on the MENU.\n"
	.string "{CIRCLE_2} Choose a POKéMON in your party.\n"
	.string "{CIRCLE_3} Select “SUMMARY,” “SWITCH,”\n"
	.string "   or “ITEM.”$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “POKéMON INFO”\n"
	.string "   “POKéMON SKILLS”\n"
	.string "   “KNOWN MOVES”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Choose the POKéMON you want to\n"
	.string "   switch around.\n"
	.string "{CIRCLE_2} Select “SWITCH.”\n"
	.string "{CIRCLE_3} Select the POKéMON to switch with\n"
	.string "   the first one.\n"
	.string "The POKéMON at the left of the screen\n"
	.string "will be the first one out in a battle.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Select “ITEM.”\n"
	.string "{CIRCLE_2} Select whether you want to “GIVE”\n"
	.string "   an item to the POKéMON to hold,\n"
	.string "   or “TAKE” an item it is holding.\n"
	.string "A POKéMON can hold no more than one\n"
	.string "item!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Select “BAG” on the MENU.\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “POKé BALLS”\n"
	.string "   Press up or down to select an item.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Select the “ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   item.\n"
	.string "Some items may not be used depending\n"
	.string "on the place and/or situation.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Select the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a key item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   key item.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} While battling a wild POKéMON,\n"
	.string "   select the BAG's “POKé BALLS”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a POKé BALL.\n"
	.string "{CIRCLE_3} Select “USE” to throw the selected\n"
	.string "   POKé BALL.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Select “{PLAYER}” on the MENU.\n"
	.string "{CIRCLE_2} Your TRAINER CARD is displayed face\n"
	.string "   up with basic information. Press the\n"
	.string "   A Button to turn the CARD over.\n"
	.string "{CIRCLE_3} A variety of data can be found on\n"
	.string "   the reverse side of the CARD.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Select “SAVE” on the MENU.\n"
	.string "{CIRCLE_2} Select “YES” and your progress is\n"
	.string "   recorded in the save file.\n"
	.string "Once the game is saved, you may turn\n"
	.string "off the game. Your game can be resumed\n"
	.string "from where you saved.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Select “OPTION” on the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an optional item, then\n"
	.string "   press left or right to alter the\n"
	.string "   settings.\n"
	.string "{CIRCLE_3} Select “CANCEL” or press the\n"
	.string "   B Button after making changes.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Select “POTION” in the “ITEMS”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_4} Select “USE.”\n"
	.string "{CIRCLE_5} Select the POKéMON to be healed.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Press left or right to open the\n"
	.string "   “KEY ITEMS” POCKET, then press\n"
	.string "   up or down to select “TOWN MAP.” \n"
	.string "{CIRCLE_4} Select “USE” to open the TOWN MAP.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Open the “KEY ITEMS” POCKET in the\n"
	.string "   “BAG.”\n"
	.string "{CIRCLE_3} “OPEN” the TM CASE.\n"
	.string "{CIRCLE_4} Select and “USE” a TM.\n"
	.string "{CIRCLE_5} Select a POKéMON that can learn the\n"
	.string "   move in the TM.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Open the “KEY ITEMS” POCKET in the\n"
	.string "   “BAG.”\n"
	.string "{CIRCLE_3} “OPEN” the TM CASE.\n"
	.string "{CIRCLE_4} Select and “USE” an HM.\n"
	.string "{CIRCLE_5} Select a POKéMON that can learn it.\n"
	.string "HMs are hard to remove, so be careful!$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Select “POKéMON.”\n"
	.string "{CIRCLE_3} Select a POKéMON that knows an\n"
	.string "   HM move. The usable HM move(s)\n"
	.string "   will be shown in blue. Select and\n"
	.string "   use the desired move to destroy an\n"
	.string "   obstacle, fly, surf, etc.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Open the MENU. Open the\n"
	.string "   “KEY ITEMS” POCKET in the “BAG”\n"
	.string "   and select the “BICYCLE.”\n"
	.string "{CIRCLE_2} The BICYCLE can be ridden by\n"
	.string "   selecting “USE.” You may also\n"
	.string "   “REGISTER” it for instant use by\n"
	.string "   pressing SELECT.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Move the cursor to the letter you\n"
	.string "   want with the {PLUS} Control Pad, then\n"
	.string "   press the A Button to enter it.\n"
	.string "{CIRCLE_2} Press the B Button to back up.\n"
	.string "{CIRCLE_3} Press SELECT to switch between\n"
	.string "   uppercase and lowercase letters.\n"
	.string "{CIRCLE_4} Press the A Button on “OK.”$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Go to any POKéMON CENTER, go up\n"
	.string "   to the PC, then press the A Button.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Select “{STR_VAR_1}'S PC” on the PC.\n"
	.string "{CIRCLE_2} Select from one of the top three\n"
	.string "   MENU items to access the POKéMON\n"
	.string "   Storage System.\n"
	.string "If you catch a POKéMON when you have\n"
	.string "six in your party, the POKéMON is sent\n"
	.string "automatically to a BOX in the System!$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Select a POKéMON in the open BOX\n"
	.string "   with the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “WITHDRAW” to remove the\n"
	.string "   POKéMON from the BOX and add it to\n"
	.string "   your party.\n"
	.string "You may not withdraw a POKéMON if you\n"
	.string "already have six POKéMON with you!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Select a POKéMON in your party with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “DEPOSIT.”\n"
	.string "{CIRCLE_3} Select the BOX, then press the\n"
	.string "   A Button to store the POKéMON.\n"
	.string "If you have only one POKéMON with you,\n"
	.string "it may not be stored!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Select a POKéMON in the open BOX.\n"
	.string "{CIRCLE_2} Pick up the POKéMON by selecting\n"
	.string "   “MOVE” and move it anywhere with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} Move the POKéMON to the BOX name\n"
	.string "   and press left or right to move it\n"
	.string "   to another BOX.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Faintly shown POKéMON can be made\n"
	.string "   to hold an item by selecting it and\n"
	.string "   pressing the A Button.\n"
	.string "{CIRCLE_2} Clearly shown POKéMON can be made\n"
	.string "   to give the item they are holding to\n"
	.string "   another POKéMON, or return the item\n"
	.string "   to the BAG with the A Button.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Select “{PLAYER}'s PC” on the PC.\n"
	.string "{CIRCLE_2} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”\n"
	.string "You may store things in your own PC\n"
	.string "if your BAG is full. You may also\n"
	.string "withdraw items stored in your PC.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Select “WITHDRAW ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   POKéMON to hold.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is more than one \n"
	.string "   item to be deposited, enter the\n"
	.string "   quantity with the {PLUS} Control Pad,\n"
	.string "   then press the A Button.$"

Help_Text_HowToUseMailbox::
	.string "When MAIL is taken from a POKéMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select “{PLAYER}'S PC” on the PC.\n"
	.string "{CIRCLE_2} Select “MAILBOX” to read MAIL or\n"
	.string "   make a POKéMON hold MAIL.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Select “PROF. OAK'S PC” on the PC.\n"
	.string "{CIRCLE_2} PROF. OAK will evaluate your\n"
	.string "   POKéDEX.\n"
	.string "His evaluations should give you hints\n"
	.string "for catching more POKéMON!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Press START.\n"
	.string "{CIRCLE_2} The MENU will open on the right.\n"
	.string "{CIRCLE_3} Depending on the situation, the MENU\n"
	.string "   may feature different headings.\n"
	.string "The MENU will not open in certain\n"
	.string "situations such as when talking, doing\n"
	.string "something, battling, etc.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Select “FIGHT.”\n"
	.string "{CIRCLE_2} Select one of the moves shown,\n"
	.string "and that move will be used!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Select “POKéMON.”\n"
	.string "{CIRCLE_2} Select the POKéMON in your party\n"
	.string "   that you want to use.\n"
	.string "{CIRCLE_3} If you have two or more POKéMON\n"
	.string "   with you, they may be switched by\n"
	.string "   selecting “SHIFT.” Check POKéMON\n"
	.string "   data by selecting “SUMMARY.”$"

Help_Text_HowToUseShift::
	.string "This command switches the POKéMON in\n"
	.string "battle with another one in your party.\n"
	.string "{CIRCLE_1} Select the POKéMON to be sent out.\n"
	.string "{CIRCLE_2} Select “SHIFT.”\n"
	.string "{CIRCLE_3} The selected POKéMON will switch\n"
	.string "   places with the POKéMON in battle!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “POKéMON INFO”\n"
	.string "   “POKéMON SKILLS”\n"
	.string "   “KNOWN MOVES”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Select “BAG.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “POKé BALLS”\n"
	.string "   Press up or down to select an item.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} POKéMON that you have caught are\n"
	.string "   identified by a POKé BALL mark on\n"
	.string "   the POKéDEX list.\n"
	.string "{CIRCLE_2} A caught POKéMON will provide a\n"
	.string "   large amount of data.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} Select “AREA” to display the TOWN\n"
	.string "   MAP with the POKéMON's habitat(s).$"
	.else
	.string "{CIRCLE_3} Select “NEXT DATA” to display the\n"
	.string "   TOWN MAP with its habitat(s).$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Go up to the PC at home, then press\n"
	.string "   the A Button.\n"
	.string "{CIRCLE_2} The PC will turn on.\n"
	.string "{CIRCLE_3} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Select “WITHDRAW ITEM” to withdraw\n"
	.string "   an item stored on your PC.\n"
	.string "{CIRCLE_2} Select “DEPOSIT ITEM” to put \n"
	.string "   an item from your BAG into your PC.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Select “WITHDRAW ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   POKéMON to hold.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is nothing in the BAG, this\n"
	.string "   command can't be used!$"

Help_Text_HowToUseMailbox2::
	.string "When MAIL is taken from a POKéMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select MAIL by name to read it or\n"
	.string "   make a POKéMON hold it.$"

Help_Text_HowToUseRun::
	.string "You may not “RUN” from a TRAINER\n"
	.string "battle!\n"
	.string "{CIRCLE_1} You may “RUN” from a wild POKéMON.\n"
	.string "{CIRCLE_2} Your chance of escape is improved\n"
	.string "   if your POKéMON in battle is fast.$"

Help_Text_HowToRegisterKeyItem::
	.string "You may “REGISTER” a key item for\n"
	.string "instant use by pressing SELECT!\n"
	.string "{CIRCLE_1} Open the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Select the key item, then select\n"
	.string "   “REGISTER.”$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} Select to throw the special POKé\n"
	.string "   BALL used only in the SAFARI ZONE.\n"
	.string "When wild POKéMON appear, throw lots\n"
	.string "of SAFARI BALLS to catch them!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} Select to throw the special food\n"
	.string "   used only in the SAFARI ZONE.\n"
	.string "It is POKéMON food rolled up into\n"
	.string "a ball for easy eating. When BAIT is\n"
	.string "thrown, the wild POKéMON may get\n"
	.string "attracted by it, and may not flee!$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} Select to throw a rock lying on\n"
	.string "   the ground in the SAFARI ZONE.\n"
	.string "Throwing a rock at a POKéMON may \n"
	.string "make it run away, but it becomes easier\n"
	.string "to catch!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Select “HALL OF FAME” on the PC.\n"
	.string "{CIRCLE_2} The POKéMON that have entered the\n"
	.string "   HALL OF FAME can be examined.$"

Help_Text_HP::
	.string "CAN$"

Help_Text_EXP::
	.string "EXP. {LEFT_PAREN}EXP. Puanı{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "HAMLELER$"

Help_Text_Attack::
	.string "SALDIRI$"

Help_Text_Defense::
	.string "SAVUNMA$"

Help_Text_SpAtk::
	.string "ÖZ. SLD$"

Help_Text_SpDef::
	.string "ÖZ. SVN$"

Help_Text_Speed::
	.string "HIZ$"

Help_Text_Level::
	.string "Sv. {LEFT_PAREN}Seviye{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TÜR$"

Help_Text_OT::
	.string "OE {LEFT_PAREN}OT{RIGHT_PAREN}$"

Help_Text_Item::
	.string "EŞYA$"

Help_Text_Ability::
	.string "YETENEK$"

Help_Text_Money::
	.string "PARA$"

Help_Text_MoveType::
	.string "HAMLE TÜRÜ$"

Help_Text_Nature::
	.string "DOĞA$"

Help_Text_IDNo::
	.string "ID No.$"

Help_Text_PP::
	.string "PP$"

Help_Text_Power::
	.string "GÜÇ$"

Help_Text_Accuracy::
	.string "İSABET$"

Help_Text_FNT::
	.string "BYL$"

Help_Text_Items::
	.string "EŞYA$"

Help_Text_KeyItems::
	.string "ANAHTAR EŞYA$"

Help_Text_PokeBalls::
	.string "POKé TOPLARI$"

Help_Text_Pokedex::
	.string "POKéDEX$"

Help_Text_PlayTime::
	.string "PLAY TIME$"

Help_Text_Badges::
	.string "ROZET$"

Help_Text_TextSpeed::
	.string "YAZI HIZI$"

Help_Text_BattleScene::
	.string "ANİMASYON$"

Help_Text_BattleStyle::
	.string "SAVAŞ STİLİ$"

Help_Text_Sound::
	.string "SES$"

Help_Text_ButtonMode::
	.string "TUŞ MODU$"

Help_Text_Frame::
	.string "ÇERÇEVE$"

Help_Text_Cancel2::
	.string "İPTAL$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "HM$"

Help_Text_HMMove::
	.string "HM HAMLESİ$"

Help_Text_Evolution::
	.string "EVRİM$"

Help_Text_StatusProblem::
	.string "DURUM SORUNU$"

Help_Text_Pokemon::
	.string "POKéMON$"

Help_Text_IDNo2::
	.string "ID No.$"

Help_Text_Money2::
	.string "PARA$"

Help_Text_Badges2::
	.string "ROZET$"

Help_Text_DefineHP::
	.string "HP indicates a POKéMON's vitality.\n"
	.string "If a POKéMON's HP drops to zero, it\l"
	.string "faints and is unable to battle.\l"
	.string "So, the key in battle is to try to\l"
	.string "reduce the foe's HP to zero.\l"
	.string "If your POKéMON are hurt, restore their\l"
	.string "HP at a POKéMON CENTER or use items.$"

Help_Text_DefineEXP::
	.string "EXP. Points stands for “Experience\n"
	.string "Points.” POKéMON gain EXP. Points by\l"
	.string "participating in winning battles.\l"
	.string "When a POKéMON accumulates sufficient\l"
	.string "EXP. Points, it levels up. The EXP. Bar\l"
	.string "indicates accumulated EXP. Points.\l"
	.string "It returns to zero upon leveling up.$"

Help_Text_DefineMoves::
	.string "POKéMON may learn up to four different\n"
	.string "moves. There are many kinds of moves\l"
	.string "including attacks and those with\l"
	.string "special effects. The kinds of moves\l"
	.string "that can be learned vary for each\l"
	.string "POKéMON. Some moves can be learned\l"
	.string "from items.$"

Help_Text_DefineAttack::
	.string "ATTACK indicates the power of an\n"
	.string "offensive move. The higher this stat,\l"
	.string "the more powerful the move.\l"
	.string "It is applied for the following move\l"
	.string "types: NORMAL, ZEHİR, YER,\l"
	.string "UÇUŞ, BÖCEK, DÖVÜŞ, KAYA, HAYALET,\l"
	.string "and ÇELİK.$"

Help_Text_DefineDefense::
	.string "DEFENSE indicates the resistance a\n"
	.string "POKéMON has against physical attacks.\l"
	.string "The higher this stat, the less damage\l"
	.string "sustained from a foe's physical hit.$"

Help_Text_DefineSpAtk::
	.string "SP. ATK (Special Attack) indicates the\n"
	.string "power of a special attack move.\l"
	.string "The higher this stat, the more powerful\l"
	.string "the special attack move.\l"
	.string "It is applied for the following move\l"
	.string "types: ATEŞ, SU, ELEKTRİK, ÇİMEN,\l"
	.string "BUZ, PSİŞİK, EJDERHA, and KARANLIK.$"

Help_Text_DefineSpDef::
	.string "SP. DEF (Special Defense) indicates\n"
	.string "the resistance a POKéMON has against\l"
	.string "special attacks.\l"
	.string "The higher this stat, the less damage\l"
	.string "sustained from a foe's special attack.$"

Help_Text_DefineSpeed::
	.string "SPEED indicates the agility of a\n"
	.string "POKéMON. If this stat exceeds the foe's\l"
	.string "in battle, the POKéMON can make a move\l"
	.string "before its slower opponent.$"

Help_Text_DefineLevel::
	.string "Lv. (Level) indicates the growth and\n"
	.string "strength of a POKéMON.\l"
	.string "In general, when a POKéMON levels up,\l"
	.string "its stats such as HP, ATTACK, and\l"
	.string "DEFENSE rise, making it stronger.\l"
	.string "POKéMON may learn a new move upon\l"
	.string "leveling up.$"

Help_Text_DefineType::
	.string "POKéMON and moves are classified by\n"
	.string "type. Every type has advantageous and\l"
	.string "disadvantageous matchups against\l"
	.string "other types. For example, like a rock-\l"
	.string "paper-scissors game, the SU type is\l"
	.string "strong against the ATEŞ type and weak\l"
	.string "against the ÇİMEN type.$"

Help_Text_DefineOT::
	.string "OT stands for “Original TRAINER,”\n"
	.string "the first TRAINER to have caught the\l"
	.string "selected POKéMON.\l"
	.string "Even if the POKéMON is traded, the OT\l"
	.string "name will remain unchanged.$"

Help_Text_DefineItem::
	.string "All POKéMON can be made to hold one\n"
	.string "item each. Some items will be used by\l"
	.string "the POKéMON automatically in certain\l"
	.string "situations. To make a POKéMON hold an\l"
	.string "item, select the item from the BAG and\l"
	.string "“GIVE” it to the POKéMON.$"

Help_Text_DefineAbility::
	.string "All POKéMON have a special ABILITY.\n"
	.string "There are many different kinds of these\l"
	.string "abilities, some used in battle, some\l"
	.string "elsewhere. The abilities differ from\l"
	.string "species to species. Some species may\l"
	.string "have more than one kind of ability.$"

Help_Text_DefineMoney::
	.string "Whenever you win a battle against a\n"
	.string "TRAINER, you are given prize money.\l"
	.string "Save up your prize money so you can\l"
	.string "enjoy shopping at POKéMON MARTS!$"

Help_Text_DefineMoveType::
	.string "Moves are also classified by types.\n"
	.string "If a POKéMON of a certain type uses\l"
	.string "a move of the same type, the move's\l"
	.string "power is boosted. If the move's type\l"
	.string "has a matchup advantage against the\l"
	.string "target, its effectiveness is also\l"
	.string "boosted.$"

Help_Text_DefineNature::
	.string "All POKéMON have a personality,\n"
	.string "or “NATURE.” The POKéMON's\l"
	.string "nature appears to affect how the\l"
	.string "POKéMON will grow upon leveling up.$"

Help_Text_DefineIDNo::
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a TRAINER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original TRAINER.\l"
	.string "The ID No. does not change even if the\l"
	.string "POKéMON is traded.$"

Help_Text_DefinePP::
	.string "PP stands for “Power Points.”\n"
	.string "It indicates the number of times a\l"
	.string "certain move can be used in battle.\l"
	.string "Like HP, PP can be restored by visiting\l"
	.string "a POKéMON CENTER or using certain\l"
	.string "items.$"

Help_Text_DefinePower::
	.string "POWER indicates the strength of an\n"
	.string "attack. The higher this number, the\l"
	.string "greater the damage that can be\l"
	.string "inflicted on the foe!$"

Help_Text_DefineAccuracy::
	.string "ACCURACY indicates the probability of\n"
	.string "the move hitting the foe.\l"
	.string "The higher this number, the more likely\l"
	.string "the move will strike the target.$"

Help_Text_DefineFNT::
	.string "FNT stands for “fainted.”\n"
	.string "A POKéMON faints if its HP is reduced\l"
	.string "to zero. It becomes incapable of taking\l"
	.string "part in battle.\l"
	.string "Restore a fainted POKéMON at a POKéMON\l"
	.string "CENTER, or use an item.$"

Help_Text_DefineItems::
	.string "Ordinary items bought at any POKéMON\n"
	.string "MART are placed in the ITEMS POCKET.\l"
	.string "Items may be used, given to a POKéMON\l"
	.string "to hold, or tossed out as garbage.$"

Help_Text_DefineKeyItems::
	.string "Important items that you find or \n"
	.string "receive from people are placed in the\l"
	.string "KEY ITEMS POCKET.\l"
	.string "Key items may be used, or registered\l"
	.string "for use instantly with SELECT. Once\l"
	.string "registered, the item can be used\l"
	.string "without opening the MENU and BAG.$"

Help_Text_DefinePokeBalls::
	.string "POKé BALLS, which are used for\n"
	.string "catching wild POKéMON, are placed in\l"
	.string "the POKé BALLS POCKET.\l"
	.string "POKé BALLS may be bought at POKéMON\l"
	.string "MARTS. They may be used, given to a\l"
	.string "POKéMON to hold, or tossed out as\l"
	.string "garbage.$"

Help_Text_DefinePokedex::
	.string "This indicates the number of species of\n"
	.string "POKéMON you have caught and/or\l"
	.string "evolved to fill the POKéDEX.\l"
	.string "Try hard to catch all sorts of\l"
	.string "POKéMON!$"

Help_Text_DefinePlayTime::
	.string "This is the total amount of time that\n"
	.string "you have played this game.$"

Help_Text_DefineBadges::
	.string "The POKéMON LEAGUE BADGES that you\n"
	.string "have won are registered and shown.\l"
	.string "Earn BADGES by defeating GYM LEADERS\l"
	.string "in various cities and towns.$"

Help_Text_DefineTextSpeed::
	.string "You can adjust how quickly the text is\n"
	.string "displayed. Choose one: SLOW, MID,\l"
	.string "or FAST.$"

Help_Text_DefineBattleScene::
	.string "You can choose to turn the battle\n"
	.string "animation ON or OFF.$"

Help_Text_DefineBattleStyle::
	.string "You can choose whether or not a\n"
	.string "TRAINER can switch a POKéMON after\l"
	.string "it has made its foe faint.\l"
	.string "Set to “SHIFT” if you would like the\l"
	.string "chance to switch a POKéMON after it\l"
	.string "has made its foe faint.$"

Help_Text_DefineSound::
	.string "You can choose between MONO and\n"
	.string "STEREO sound output.$"

Help_Text_DefineButtonMode::
	.string "Set to “HELP” to display help messages\n"
	.string "by pressing the L or R Button.\l"
	.string "Set to “LR” to enable the switching\l"
	.string "of the POKéDEX pages and BAG POCKETS\l"
	.string "using the L and R Buttons.\l"
	.string "Set to “L=A” to make the L Button\l"
	.string "work the same as the A Button.$"

Help_Text_DefineFrame::
	.string "You may choose the design of the frame\n"
	.string "around certain menus. Try them out and\l"
	.string "see what you like.$"

Help_Text_DefineCancel2::
	.string "The settings will be changed to the\n"
	.string "selections shown in red, and you will\l"
	.string "return to the MENU.$"

Help_Text_DefineTM::
	.string "A TM (Technical Machine) is a device\n"
	.string "used to teach a move to a POKéMON.\l"
	.string "There are many different kinds.\l"
	.string "Moves can be taught only to those\l"
	.string "POKéMON capable of using them.\l"
	.string "A TM breaks after a single use.$"

Help_Text_DefineHM::
	.string "An HM (Hidden Machine) is a device used\n"
	.string "to teach a HIDDEN move to a POKéMON.\l"
	.string "A HIDDEN move can be taught only to\l"
	.string "those POKéMON capable of using it.\l"
	.string "Unlike a TM, an HM can be used over\l"
	.string "and over. A HIDDEN move can be tough\l"
	.string "for a POKéMON to forget.$"

Help_Text_DefineHMMove::
	.string "HIDDEN moves are those that are\n"
	.string "especially important for your\l"
	.string "adventure. To use such a move outside\l"
	.string "of battle, open the “POKéMON” MENU\l"
	.string "and make the POKéMON that knows the\l"
	.string "move use it. A fainted POKéMON may use\l"
	.string "a HIDDEN move outside of battle.$"

Help_Text_DefineEvolution::
	.string "Among POKéMON, there are some that\n"
	.string "undergo major changes (evolution) upon\l"
	.string "growing to certain levels. Evolution\l"
	.string "causes a POKéMON to alter form, change\l"
	.string "its name, and perhaps change the moves\l"
	.string "it may learn. Some POKéMON evolve\l"
	.string "due to reasons other than leveling up.$"

Help_Text_DefineStatusProblem::
	.string "Status problems include:\n"
	.string "Sleep: Can't use moves.\l"
	.string "Poison: Causes steady HP loss.\l"
	.string "Paralysis: May prevent moves.\l"
	.string "Burn: HP loss and lowers ATTACK.\l"
	.string "Freeze: Can't use moves.\l"
	.string "These can be healed with items, etc.$"

Help_Text_DefinePokemon::
	.string "POKéMON is a name given to describe\n"
	.string "wondrous creatures that inhabit all\l"
	.string "corners of this world.\l"
	.string "People raise POKéMON to be their pets,\l"
	.string "use them for battling, and so on.$"

Help_Text_DefineIDNo2::
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a TRAINER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original TRAINER.\l"
	.string "The ID No. does not change even if the\l"
	.string "POKéMON is traded.$"

Help_Text_DefineMoney2::
	.string "Whenever you win a battle against a\n"
	.string "TRAINER, you are given prize money.\l"
	.string "Save up your prize money so you can\l"
	.string "enjoy shopping at POKéMON MARTS!$"

Help_Text_DefineBadges2::
	.string "This indicates the number of POKéMON\n"
	.string "LEAGUE BADGES that you have won.\l"
	.string "Earn BADGES by defeating GYM LEADERS\l"
	.string "in various cities and towns.$"

Help_Text_TheHelpSystem::
	.string "The HELP System$"

Help_Text_TheGame::
	.string "The game$"

Help_Text_WirelessAdapter::
	.string "Wireless Adapter$"

Help_Text_GameFundamentals1::
	.string "Game fundamentals 1$"

Help_Text_GameFundamentals2::
	.string "Game fundamentals 2$"

Help_Text_GameFundamentals3::
	.string "Game fundamentals 3$"

Help_Text_WhatArePokemon::
	.string "What are POKéMON?$"

Help_Text_DescTheHelpSystem::
	.string "The help messages change depending on\n"
	.string "how much you have progressed in the\l"
	.string "game. They are designed to support you\l"
	.string "when you need them. If there is\l"
	.string "anything that you don't understand,\l"
	.string "please look up the HELP System!$"

Help_Text_DescTheGame::
	.string "You become the main character to\n"
	.string "explore the world of POKéMON!\l"
	.string "By talking to people and solving\l"
	.string "mysteries, new paths will open to you.\l"
	.string "Strive for the goal together with your\l"
	.string "wonderful POKéMON!$"

Help_Text_DescWirelessAdapter::
	.string "This game communicates over a wireless\n"
	.string "link using the Wireless Adapter.\p"
	.string "Go wireless anywhere, anytime, and\n"
	.string "with anybody!\p"
	.string "Try playing with the Wireless Adapter\n"
	.string "always attached!$"

Help_Text_DescGameFundamentals1::
	.string "Visit every city and town, travel every\n"
	.string "road, explore every cave, and face\l"
	.string "every challenge as you strive to\l"
	.string "become the greatest TRAINER of\l"
	.string "POKéMON!$"

Help_Text_DescGameFundamentals2::
	.string "On your adventure, you will be faced\n"
	.string "with many obstacles. Every obstacle\l"
	.string "can be overcome by doing something\l"
	.string "or by solving mysteries. Some obstacles\l"
	.string "are affected by something that happens\l"
	.string "far away.$"

Help_Text_DescGameFundamentals3::
	.string "Some of the obstacles in your way can\n"
	.string "be removed once your POKéMON learn\l"
	.string "specific moves.$"

Help_Text_DescWhatArePokemon::
	.string "POKéMON are wondrous creatures that\n"
	.string "are shrouded in mystery. You may meet\l"
	.string "them all over the world…in tall\l"
	.string "grass, caves, the sea, and more.\l"
	.string "They appear to grow obedient to the\l"
	.string "TRAINERS that caught them.$"

Help_Text_UsingTypeMatchupList::
	.string "Tür güçlü-zayıf yönleri (Matchup List)$"

Help_Text_OwnMoveDark::
	.string "Hamle türü: KARANLIK$"

Help_Text_OwnPokemonDark::
	.string "POKéMON türü: KARANLIK$"

Help_Text_OwnMoveRock::
	.string "Hamle türü: KAYA$"

Help_Text_OwnPokemonRock::
	.string "POKéMON türü: KAYA$"

Help_Text_OwnMovePsychic::
	.string "Hamle türü: PSİŞİK$"

Help_Text_OwnPokemonPsychic::
	.string "POKéMON türü: PSİŞİK$"

Help_Text_OwnMoveFighting::
	.string "Hamle türü: DÖVÜŞ$"

Help_Text_OwnPokemonFighting::
	.string "POKéMON türü: DÖVÜŞ$"

Help_Text_OwnMoveGrass::
	.string "Hamle türü: ÇİMEN$"

Help_Text_OwnPokemonGrass::
	.string "POKéMON türü: ÇİMEN$"

Help_Text_OwnMoveGhost::
	.string "Hamle türü: HAYALET$"

Help_Text_OwnPokemonGhost::
	.string "POKéMON türü: HAYALET$"

Help_Text_OwnMoveIce::
	.string "Hamle türü: BUZ$"

Help_Text_OwnPokemonIce::
	.string "POKéMON türü: BUZ$"

Help_Text_OwnMoveGround::
	.string "Hamle türü: YER$"

Help_Text_OwnPokemonGround::
	.string "POKéMON türü: YER$"

Help_Text_OwnMoveElectric::
	.string "Hamle türü: ELEKTRİK$"

Help_Text_OwnPokemonElectric::
	.string "POKéMON türü: ELEKTRİK$"

Help_Text_OwnMovePoison::
	.string "Hamle türü: ZEHİR$"

Help_Text_OwnPokemonPoison::
	.string "POKéMON türü: ZEHİR$"

Help_Text_OwnMoveDragon::
	.string "Hamle türü: EJDERHA$"

Help_Text_OwnPokemonDragon::
	.string "POKéMON türü: EJDERHA$"

Help_Text_OwnMoveNormal::
	.string "Hamle türü: NORMAL$"

Help_Text_OwnPokemonNormal::
	.string "POKéMON türü: NORMAL$"

Help_Text_OwnMoveSteel::
	.string "Hamle türü: ÇELİK$"

Help_Text_OwnPokemonSteel::
	.string "POKéMON türü: ÇELİK$"

Help_Text_OwnMoveFlying::
	.string "Hamle türü: UÇUŞ$"

Help_Text_OwnPokemonFlying::
	.string "POKéMON türü: UÇUŞ$"

Help_Text_OwnMoveFire::
	.string "Hamle türü: ATEŞ$"

Help_Text_OwnPokemonFire::
	.string "POKéMON türü: ATEŞ$"

Help_Text_OwnMoveWater::
	.string "Hamle türü: SU$"

Help_Text_OwnPokemonWater::
	.string "POKéMON türü: SU$"

Help_Text_OwnMoveBug::
	.string "Hamle türü: BÖCEK$"

Help_Text_OwnPokemonBug::
	.string "POKéMON türü: BÖCEK$"

Help_Text_HowToUseTypeMatchupList::
	.string "Hamlenin türü ve hedef POKéMON\n"
	.string "türüne bağlı olarak hamlenin hedef\l"
	.string "üzerindei etkisi değişir:\l"
	.string "{CIRCLE_DOT}: Süper etkili! (x2)\l"
	.string "{TRIANGLE}: Pek etkili değil (x0.5)\l"
	.string "{BIG_MULT_X}: Hiç etkili değil (x0)\l"
	.string "(Diğer türler için etki değişmez.)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: PSİŞİK, HAYALET\p"
	.string "   {TRIANGLE}: DÖVÜŞ, KARANLIK, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: DÖVÜŞ, BÖCEK\p"
	.string "   {TRIANGLE}: HAYALET, KARANLIK\p"
	.string "   {BIG_MULT_X}: PSİŞİK$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, BUZ, UÇUŞ, BÖCEK\p"
	.string "   {TRIANGLE}: DÖVÜŞ, YER, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, ÇİMEN, DÖVÜŞ,\n"
	.string "       YER, ÇELİK\p"
	.string "   {TRIANGLE}: NORMAL, ATEŞ, ZEHİR, UÇUŞ$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: DÖVÜŞ, ZEHİR\p"
	.string "   {TRIANGLE}: PSİŞİK, ÇELİK\p"
	.string "   {BIG_MULT_X}: KARANLIK$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: BÖCEK, HAYALET, KARANLIK\p"
	.string "   {TRIANGLE}: DÖVÜŞ, PSİŞİK$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: NORMAL, BUZ, KAYA, KARANLIK, ÇELİK\p"
	.string "   {TRIANGLE}: ZEHİR, UÇUŞ, PSİŞİK, BÖCEK\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: UÇUŞ, PSİŞİK\p"
	.string "   {TRIANGLE}: BÖCEK, KAYA, KARANLIK$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, YER, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, ÇİMEN, ZEHİR, UÇUŞ,\n"
	.string "       BÖCEK, EJDERHA, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, BUZ, ZEHİR, UÇUŞ, BÖCEK\p"
	.string "   {TRIANGLE}: SU, ELEKTRİK, ÇİMEN, YER$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: PSİŞİK, HAYALET\p"
	.string "   {TRIANGLE}: KARANLIK, ÇELİK\p"
	.string "   {BIG_MULT_X}: NORMAL$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: HAYALET, KARANLIK\p"
	.string "   {TRIANGLE}: ZEHİR, BÖCEK\p"
	.string "   {BIG_MULT_X}: NORMAL, DÖVÜŞ$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, YER, UÇUŞ, EJDERHA\p"
	.string "   {TRIANGLE}: ATEŞ, SU, BUZ, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, DÖVÜŞ, KAYA, ÇELİK\p"
	.string "   {TRIANGLE}: BUZ$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, ELEKTRİK, ZEHİR, KAYA,\n"
	.string "       ÇELİK\p"
	.string "   {TRIANGLE}: ÇİMEN, BÖCEK\n"
	.string "   {BIG_MULT_X}: UÇUŞ$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, ÇİMEN, BUZ\p"
	.string "   {TRIANGLE}: ZEHİR, KAYA\p"
	.string "   {BIG_MULT_X}: ELEKTRİK$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, UÇUŞ\p"
	.string "   {TRIANGLE}: ELEKTRİK, ÇİMEN, EJDERHA\p"
	.string "   {BIG_MULT_X}: YER$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: YER\p"
	.string "   {TRIANGLE}: ELEKTRİK, UÇUŞ, ÇELİK$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN\p"
	.string "   {TRIANGLE}: ZEHİR, YER, KAYA, HAYALET\p"
	.string "   {BIG_MULT_X}: ÇELİK$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: YER, PSİŞİK\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, ZEHİR, BÖCEK$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: EJDERHA\p"
	.string "   {TRIANGLE}: ÇELİK$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: BUZ, EJDERHA\p"
	.string "   {TRIANGLE}: ATEŞ, SU, ELEKTRİK, ÇİMEN$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {TRIANGLE}: KAYA, ÇELİK\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: DÖVÜŞ\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: BUZ, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, SU, ELEKTRİK, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, DÖVÜŞ, YER\n"
	.string "   {TRIANGLE}: NORMAL, ÇİMEN, BUZ, UÇUŞ,\l"
	.string "       PSİŞİK, BÖCEK, KAYA, HAYALET,\l"
	.string "       EJDERHA, KARANLIK, ÇELİK\l"
	.string "   {BIG_MULT_X}: ZEHİR$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, DÖVÜŞ, BÖCEK\p"
	.string "   {TRIANGLE}: ELEKTRİK, KAYA, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ELEKTRİK, BUZ, KAYA\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, BÖCEK\p"
	.string "   {BIG_MULT_X}: YER$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, BUZ, BÖCEK, ÇELİK\p"
	.string "   {TRIANGLE}: ATEŞ, SU, KAYA, EJDERHA$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, YER, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, ÇİMEN, BUZ, BÖCEK, ÇELİK$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, YER, KAYA\p"
	.string "   {TRIANGLE}: SU, ÇİMEN, EJDERHA$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ELEKTRİK, ÇİMEN\p"
	.string "   {TRIANGLE}: ATEŞ, SU, BUZ, ÇELİK$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Karşı POKéMON üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, PSİŞİK, KARANLIK\p"
	.string "   {TRIANGLE}: ATEŞ, DÖVÜŞ, ZEHİR,\n"
	.string "       UÇUŞ, HAYALET, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Düşman saldırısının üzerinde etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, UÇUŞ, KAYA\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, YER$"

