Help_Text_WhatShouldIDo::
	.string "Bu durumda ne yapmalıyım?$"

Help_Text_HowDoIDoThis::
	.string "Bunu nasıl yapacağım?$"

Help_Text_WhatDoesThisTermMean::
	.string "Bu terim ne anlama geliyor?$"

Help_Text_AboutThisGame::
	.string "Bu oyun hakkında$"

Help_Text_TypeMatchupList::
	.string "Tür Eşleşme Listesi$"

Help_Text_Exit::
	.string "ÇIKIŞ$"

Help_Text_Cancel::
	.string "İPTAL$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Zorlu durumlarda ipucu almak için\n"
	.string "seçin.$"

Help_Text_DescHowDoIDoThis::
	.string "Çeşitli işlemler için ayrıntılı\n"
	.string "talimatlar verilmiştir.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Oyunda görünen terimler için\n"
	.string "ayrıntılı açıklamalar verilmiştir.$"

Help_Text_DescAboutThisGame::
	.string "Oyun hakkında detaylı açıklamalar\n"
	.string "verilmiştir.$"

Help_Text_DescTypeMatchupList::
	.string "POKéMON tür eşleşmeleri ve\n"
	.string "hamleler listelenmiştir.$"

Help_Text_DescExit::
	.string "YARDIM sisteminden çıkmak için seçin.$"

Help_Text_Greetings::
	.string "Merhaba! Burası YARDIM sistemi.\n"
	.string "Ne zaman ihtiyacın olursa L veya R\l"
	.string "tuşuna basarak gelebilirsin.\l"
	.string "Yardım mesajları duruma göre\l"
	.string "değişebilir.\l"
	.string "Bu yüzden lütfen sık sık kontrol edin.$"

Help_Text_PlayingForFirstTime::
	.string "İlk defa oynuyorum. Yardım edin!$"

Help_Text_WhatShouldIBeDoing::
	.string "Ne yapmam gerekiyor?$"

Help_Text_CantGetOutOfRoom::
	.string "Odadan dışarı çıkamıyorum!$"

Help_Text_CantFindPersonIWant::
	.string "İstediğim kişiyi bulamıyorum.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "Herkesle konuştum. Peki şimdi?$"

Help_Text_SomeoneBlockingMyWay::
	.string "Birisi yolumu tıkıyor!$"

Help_Text_ICantGoOn::
	.string "Devam edemiyorum!$"

Help_Text_OutOfThingsToDo::
	.string "Yapacak bir şeyim kalmadı.$"

Help_Text_WhatHappenedToItemIGot::
	.string "Aldığım eşyaya ne oldu?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Maceramın temelleri nelerdir?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Yollar ver ormanlar nasıl farklıdır?$"

Help_Text_HowAreCavesDifferent::
	.string "Mağaralar nasıl farklıdır?$"

Help_Text_HowDoIProgress::
	.string "Nasıl ilerlerim?$"

Help_Text_WhenCanIUseItem::
	.string "Ne zaman eşya kullanabilirim?$"

Help_Text_WhatsABattle::
	.string "Savaş nedir?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Savaşlara nasıl hazırlanırım?$"

Help_Text_WhatIsAMonsVitality::
	.string "Bir POKéMON'un canlılığı nedir?$"

Help_Text_MyMonsAreHurt::
	.string "POKéMON'larım yaralandı!$"

Help_Text_WhatIsStatusProblem::
	.string "Durum problemi nedir?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Tüm POKéMON'larım bayılırsa ne olur?$"

Help_Text_CantCatchMons::
	.string "POKéMON yakalayamıyorum!$"

Help_Text_RanOutOfPotions::
	.string "Hiç İKSİR'im kalmadı.$"

Help_Text_CanIBuyPokeBalls::
	.string "POKE TOPLARI alabilir miyim?$"

Help_Text_WhatsATrainer::
	.string "EĞİTMEN nedir?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "EĞİTMEN'e karşı nasıl kazanırım?$"

Help_Text_WhereDoMonsAppear::
	.string "POKéMON'lar nerede çıkar?$"

Help_Text_WhatAreMoves::
	.string "POKéMON hamleleri nedir?$"

Help_Text_WhatAreHiddenMoves::
	.string "GİZLİ hamleler nelerdir?$"

Help_Text_WhatMovesShouldIUse::
	.string "Hangi hamleleri kullanmalıyım?$"

Help_Text_WantToAddMoreMoves::
	.string "Daha fazla hamle istiyorum.$"

Help_Text_WantToMakeMonStronger::
	.string "POKéMON'umu güçlendirmek istiyorum.$"

Help_Text_FoeMonsTooStrong::
	.string "Rakip POKéMON çok güçlü!$"

Help_Text_WhatDoIDoInCave::
	.string "Mağarada ne yaparım?$"

Help_Text_NothingIWantToKnow::
	.string "Bilmem gereken bir şey yok!$"

Help_Text_WhatsPokemonCenter::
	.string "POKéMON MERKEZİ nedir?$"

Help_Text_WhatsPokemonMart::
	.string "POKéMON MARKET nedir?$"

Help_Text_WantToEndGame::
	.string "Oyunu bitirmek istiyorum.$"

Help_Text_WhatsAMon::
	.string "POKéMON nedir?$"

Help_Text_WhatIsThatPersonLike::
	.string "O kişi nasıl biri?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "GİZLİ hamleler ne işe yarar?$"

Help_Text_WhatDoIDoInSafari::
	.string "SAFARİ OYUNU'nda ne yapılır?$"

Help_Text_WhatAreSafariRules::
	.string "SAFARİ OYUNU kuralları nelerdir?$"

Help_Text_WantToEndSafari::
	.string "SAFARİ OYUNU'ndan çıkmak istiyorum!$"

Help_Text_WhatIsAGym::
	.string "SALON nedir?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "POKéMON dünyasını ana karakter\n"
	.string "olarak keşfediyorsun.\l"
	.string "İnsanlarla konuşup gizemleri çözerek\l"
	.string "sana yeni kapılar açılacak.\l"
	.string "Muhteşem POKéMON'ların ile en iyi\l"
	.string "olmak için çabala.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "Başka biriyle karşılaştığın zaman,\n"
	.string "onlara git ve A tuşuna bas.\l"
	.string "Böylece onlarla konuşup iletişime\l"
	.string "geçeceksin. Ayrıca farklı eşyaları\l"
	.string "ve objeleri aynı şekilde\l"
	.string "inceleyebilirsin. Bilgi almak için\l"
	.string "insanlarla konuş ve objelere bak.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "Merdivenler veya kapıların önünde\n"
	.string "kırmızı halı vardır. Karakterini\l"
	.string "kırmızı halının önüne getir.\l"
	.string "{PLUS} tuşu ile kapıya ya da \l"
	.string "merdivenlere yürüyerek oradan\l"
	.string "ayrılabilirsin.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "Bu pek endişeleneceğin bir şey\n"
	.string "değil.\l"
	.string "Başka insanlarla konuş, tabelalara\l"
	.string "bakın ve keşfet.\l"
	.string "Bazen, başka bir şehire veya yere\l"
	.string "gitmen gerekebilir.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Başka bir rota, şehir ya da yere\n"
	.string "gitmeyi dene.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "Nedeni şehirdeki ya da binalardaki\n"
	.string "bir şey olabilir.\l"
	.string "Bölgedeki insanlarla tekrar konuşmayı\l"
	.string "dene. Eğer çözmeleri gereken bir\l"
	.string "problem varsa, yardım etmen\l"
	.string "gerekebilir. Sonrasında, yolunu\l"
	.string "engelleyen kişiyle tekrar konuş.$"

Help_Text_AnswerICantGoOn::
	.string "İnsanların yanına gidip A tuşu ile\n"
	.string "konuşmayı dene\l"
	.string "Ayrıca, A tuşu ile garip ağaç ve\l"
	.string "kayaları kontrol et.\l"
	.string "{PLUS} tuşlarına basarak geçilemeyecek\l"
	.string "yerleri de deneyebilirsin.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Daha önce gitmediğin yerleri\n"
	.string "ziyaret edebilirsin.\l"
	.string "Ayrıca, şüpheli her türlü şeyi\l"
	.string "A tuşu ile kontrol et.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Başka bir karakterin verdiği bir\n"
	.string "eşya otomatikmen ÇANTA'ya gider.\l"
	.string "Bu eşya otomatik sıralanır ve üç\l"
	.string "cepten birine yerleştirilir.\l"
	.string "ÇANTA kullanımı için, lütfen Yardım\l"
	.string "Sisteminin “Bunu nasıl yapacağım”\l"
	.string "kısmına bak.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "Eğer POKéMON savaşta yaralanırsa,\n"
	.string "onları POKéMON MERKEZİ'ne götür ve\l"
	.string "iyileşmesini sağla.\l"
	.string "Oyunu kaydetmeyi alışkanlık edin.\l"
	.string "Uzak yolculuklardan önce POKéMON\l"
	.string "MARKET'ten eşya depola.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Ormanlar yollar ile aynı düzendedir\n"
	.string "ancak bazen labirent gibi olabilir.\l"
	.string "Tüm ormanların çıkışı vardır, bu yüzden\l"
	.string "kaybolduğun zaman pes etme.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Mağaralar karanlık ve tehlikelidir.\n"
	.string "Vahşi POKéMON'lar her yerden çıkabilir.\l"
	.string "Eğer acil durum varsa, çabucak bir\l"
	.string "POKéMON MERKEZİ'ne git ya da eşya\l"
	.string "kullan. Mağaraların ucunda yeni \l"
	.string "şehirler keşfedilmeyi bekliyor,\l"
	.string "pes etme.$"

Help_Text_AnswerHowDoIProgress::
	.string "Oyunun amacı POKéMON eğitmek ve\n"
	.string "devam etmektir.\l"
	.string "Sorunları çözmek için bilgi\l"
	.string "toplamalısın. Örneğin, bir engeli\l"
	.string "aşmak için ne yapman gerekir?\l"
	.string "Bu yolunu kesen adam nasıl\l"
	.string "oradan ayrılabilir?$"

Help_Text_AnswerWhenCanIUseItem::
	.string "Farklı çeşit eşyalar vardır.\n"
	.string "Bazıları gezerken kullanılır.\l"
	.string "Bazıları sadece savaşlarda.\l"
	.string "Bazıları ise her zaman ve her yerde.\l"
	.string "Eşyayı kullanmayı dene- eğer\l"
	.string "kullanamazsan uyarı mesajı alırsın.$"

Help_Text_AnswerWhatsABattle::
	.string "Bir savaşta, POKéMON'lar birbirlerinin\n"
	.string "canını azaltmaya çalışırlar. Eğer\l"
	.string "POKéMON'un CAN'ı sıfıra düşerse bayılır\l"
	.string "ve diğer POKéMON kazanır. Bir savaşı\l"
	.string "kazanarak POKéMON'lar EXP. kazanır.\l"
	.string "Bu da onların seviye atlamasına\l"
	.string "(güçlenmesine) yardımcı olur.$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "İlk olarak, partinizdeki (yanınızdaki)\n"
	.string "POKéMON'ları herhangi bir\l"
	.string "POKéMON MERKEZİ'nde iyileştirin.\l"
	.string "Ayrıca, acil durumlar için bir POKéMON\l"
	.string "MARKET'inden iyileştirme eşyaları\l"
	.string "satın almalısınız.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "Bir POKéMON'un canı CAN ile gösterilir.\n"
	.string "Eğer bir POKéMON savaşta yara alırsa,\l"
	.string "CAN'ı azalır. Sıfıra düşerse,\l"
	.string "POKéMON bayılır.\l"
	.string "Yaralı veya bayılmış POKéMON'ları\l"
	.string "POKéMON MERKEZİ'nde ya da eşya\l"
	.string "kullanarak iyileştirin.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "POKéMON MERKEZİ, POKéMON'lar için\n"
	.string "bir han gibidir. Özel bir makine ile\l"
	.string "POKéMON'ları tamamen iyileştirir ve\l"
	.string "herhangi bir durum sorununu giderir.\l"
	.string "Bu hizmet ücretsizdir, bu yüzden\l"
	.string "POKéMON'larınızı sık sık iyileştirin.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "Durum sorunu, bir POKéMON'a rakibinin\n"
	.string "saldırısıyla verilen bir rahatsızlıktır.\l"
	.string "Bunlar arasında yanık, felç, zehir,\l"
	.string "uyku ve donma bulunur. Bunlar, bir\l"
	.string "POKéMON MERKEZİ'ni ziyaret ederek veya\l"
	.string "uygun eşyayı kullanarak\l"
	.string "iyileştirilebilir.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "Partinizdeki (yanınızdaki) tüm\n"
	.string "POKéMON'lar bayılırsa, biraz PARA\l"
	.string "kaybedersiniz ve evinize veya bir\l"
	.string "POKéMON MERKEZİ'ne geri dönersiniz.\l"
	.string "Bu ihtimali azaltmak için sık sık\l"
	.string "onları iyileştirin ve ayrıca.\l"
	.string "sık sık kaydetme alışkanlığı edinin.$"

Help_Text_AnswerCantCatchMons::
	.string "Eğer vahşi POKéMON bir POKé TOPU'ndan\n"
	.string "kaçarsa, hala çok hareketli demektir.\l"
	.string "CANını biraz daha azaltmayı deneyin ve\l"
	.string "yakalamaya çalışmadan önce onu felç\l"
	.string "veya uyku ile zayıflatmaya çalışın.\l"
	.string "Eğer POKéTOPU bir süre sallanıyorsa,\l"
	.string "av yakalanmaya yakındır!$"

Help_Text_AnswerRanOutOfPotions::
	.string "POKéMON MARKET olarak bilinen,\n"
	.string "eşya satan dükkanlar vardır.\l"
	.string "POKéMON MARKET'ini yollarda,\l"
	.string "ormanlarda veya mağaralarda\l"
	.string "bulamazsınız. Bir kasabaya\l"
	.string "ziyaret ederken ihtiyaç duyduğunuz\l"
	.string "eşyaları stoklayın.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "Herhangi bir kasabadaki herhangi bir\n"
	.string "POKéMON MARKETİ'nden POKéTOPU\l"
	.string "satın alabilirsiniz. POKéMON\l"
	.string "MARKETLERİ'ni yollarda, ormanlarda\l"
	.string "veya mağaralarda bulamazsınız.\l"
	.string "Bir kasabaya ziyarette bulunurken\l"
	.string "POKéTOPU stoklayın.$"

Help_Text_AnswerWhatsATrainer::
	.string "EĞİTMEN, POKéMON'ları savaşarak\n"
	.string "yetiştiren kişidir. EĞİTMENLER size\l"
	.string "nerede olurlarsa olsun meydan okurlar.\l"
	.string "Bu bir yol, mağara, her yer olabilir.\l"
	.string "Göz göze gelirsen, onların meydan\l"
	.string "okumasını kabul etmek zorundasın.\l"
	.string "Bu yüzden dikkatli ol!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "Bir EĞİTMEN'i yenmek için, rakibin\n"
	.string "POKéMON'larına karşı avantajlı\l"
	.string "tiplere sahip POKéMON'lar kullanın.\l"
	.string "Ayrıca, çok güçlü, iyi eğitilmiş\l"
	.string "POKéMON'lar kullanabilirsiniz. Rakibin\l"
	.string "POKéMON'larından sayıca fazla olmak\l"
	.string "da başka bir taktik.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Vahşi POKéMON'lar uzun otlarda,\n"
	.string "yollarda ve ormanlarda ortaya çıkar.\l"
	.string "Karanlık mağaralarda her yerde\l"
	.string "belirirler. Kasabalarda vahşi\l"
	.string "POKéMON veya EĞİTMEN yoktur, bu\l"
	.string "yüzden buralar güvenli yerlerdir.$"

Help_Text_AnswerWhatAreMoves::
	.string "POKéMON'lar en fazla dört farklı\n"
	.string "teknik veya hareket öğrenebilirler.\l"
	.string "Saldırılar ve özel etkiler içeren büyük\l"
	.string "çeşitlilikte hareketler vardır. Hangi\l"
	.string "hareketlerin öğrenilebileceği her\l"
	.string "POKéMON için farklıdır. Bazı hareketler\l"
	.string "makinelerden öğrenilebilir.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "GİZLİ hamleler, maceranız için önemli\n"
	.string "hamlelerdir. Bu tür bir hareketi savaş\l"
	.string "dışında kullanmak için, “POKéMON”\l"
	.string "menüsünden hamleyi bilen POKéMON'un\l"
	.string "kullanmasını sağlayın.\l"
	.string "Bayılmış bir POKéMON savaş dışında\l"
	.string "bir GİZLİ hamle kullanabilir.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "“SALDIR”ı seçin ve hareketlerin menüsü\n"
	.string "görünecek. Tür eşleşmelerini düşünün\l"
	.string "ve en etkili hareketleri kullanın.\l"
	.string "Hareketlerin etkilerini “POKéMON”u\l"
	.string "açıp, bir POKéMON seçerek,\l"
	.string "“ÖZET”i açarak ve ardından\l"
	.string "“POKéMON YETENEKLERİ”ni açarak\l"
	.string "kontrol edebilirsiniz.$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "Bir POKéMON'un öğrenebileceği en fazla\n"
	.string "hareket sayısı dört. POKéMON seviye\l"
	.string "atladıkça hareketler öğrenilir.\l"
	.string "Ayrıca bir TM (Teknik Makine) veya\l"
	.string "HM (Gizli Makine) kullanarak\l"
	.string "hareket öğretilebilir. Ayrıca hareket\l"
	.string "öğreten insanlar da vardır.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "POKéMON'unuzu güçlendirmenin anahtarı,\n"
	.string "sık sık savaşmak ve kazanmaktır.\l"
	.string "Savaş kazanarak kazanılan EXP. Puanı\l"
	.string "savaşlara katılan POKéMON'ların\l"
	.string "seviye atlamasına yardımcı olur.\l"
	.string "Partinizi seviye atlatmak için sık sık\l"
	.string "vahşi POKéMON'larla savaşın.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "Eğer rakipleriniz çok güçlü ise,\n"
	.string "POKéMON'larınızı biraz daha seviye\l"
	.string "atlatmayı deneyin. Geldiğiniz yere\l"
	.string "geri dönün ve partinizi seviye atlatmak\l"
	.string "için vahşi POKéMON'larla savaşın.\l"
	.string "Ayrıca, daha önce savaşmadığınız\l"
	.string "EĞİTMENLER ile de savaşabilirsiniz.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Yollar ve ormanlardan farklı olarak,\n"
	.string "vahşi POKéMON mağaralarda her yerde\l"
	.string "belirir. POKéMON'larınız bir mağarada\l"
	.string "yaralanırsa, hemen bir POKéMON MERKEZİ'ne\l"
	.string "koşun veya eşyalar kullanarak onları\l"
	.string "hemen iyileştirin. Mağaralarda şansınızı\l"
	.string "zorlamak çok tehlikelidir.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Kendi bilginize ve gücünüze güvenin.\n"
	.string "Kendinize inanın ve yolunuzu bulun!$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "Bir POKéMON MERKEZİ, kırmızı çatısı ve\n"
	.string "“P.C” tabelası ile tanınır. Her\l"
	.string "POKéMON MERKEZİ, POKéMON'ları tamamen\l"
	.string "iyileştirme ve ücretsiz bilgisayar\l"
	.string "kullanımı gibi hizmetler sunar, bu da\l"
	.string "onu yolculuklarınız için vazgeçilmez\l"
	.string "kılar. Üst katta arkadaşların ve\l"
	.string "diğerleri ile bağlantı kurabilirsin.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "Bir POKéMON MARKETİ, mavi çatısı ve\n"
	.string "“MARKET” tabelası ile tanınır.\l"
	.string "Herhangi bir POKéMON MARKETİ'nde\l"
	.string "eşya alınıp satılabilir. Bazıları\l"
	.string "yalnızca kendi kasabalarında\l"
	.string "bulunan eşyalar taşır.$"

Help_Text_AnswerWantToEndGame::
	.string "MENÜ'den “KAYDET”i seçerek\n"
	.string "oyununuzu güvenli bir şekilde\l"
	.string "sonlandırabilirsin.\l"
	.string "Bir kez kaydettikten sonra, oyun\l"
	.string "güvenli bir şekilde kapatılabilir.\l"
	.string "Oyun tekrar açıldığında, en son\l"
	.string "kaydettiğin yerden devam edebilirsin.$"

Help_Text_AnswerWhatsAMon::
	.string "POKéMON'lar, EĞİTMENLER tarafından\n"
	.string "savaşlarda kullanılan ve eğitilen\l"
	.string "garip yaratıklardır. POKéMON'ların\l"
	.string "birçok farklı tipi vardır ve bazı\l"
	.string "tipler diğerlerine karşı avantaj\l"
	.string "veya dezavantaja sahiptir.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "ÇANTA'da ANAHTAR EŞYA bölümünde\n"
	.string "ŞANIMSAYICI'yı kullanın.\l"
	.string "Size bir ipucu verebilir, bu yüzden\l"
	.string "denemekten çekinmeyin.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "GİZLİ hamleler, bir HM (Gizli Makine)\n"
	.string "kullanarak POKéMON'a öğretilir.\l"
	.string "GİZLİ hamleler, maceranızda ilerlemek\l"
	.string "için önemlidir. Örneğin karanlık\l"
	.string "karanlık mağaraları aydınlatma,\l"
	.string "küçük ağaçları kesme, su seyahati\l"
	.string "ve daha fazlası.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Özel SAFARİ TOPLARI atarak vahşi\n"
	.string "POKéMON'ları yakalamayı deneyin.\l"
	.string "Ayrıca bulduğunuz her eşyayı\l"
	.string "da saklayabilirsiniz.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "SAFARİ OYUNUNUZ belirli bir mesafe\n"
	.string "kat ettiğinizde veya tüm SAFARİ\l"
	.string "TOPLARI'nı attığınızda sona erer.\l"
	.string "Kalan adım sayısını ve SAFARİ TOPLARI'nı\l"
	.string "kontrol etmek için MENÜ'yü açın.$"

Help_Text_AnswerWantToEndSafari::
	.string "SAFARİ OYUNUNUZU kısa kesmek isterseniz,\n"
	.string "MENÜ'yü açın ve listenin en üstünde\l"
	.string "“AYRIL”ı seçin.$"

Help_Text_AnswerWhatIsAGym::
	.string "POKéMON SALONLARI, POKéMON LİGİ'nin\n"
	.string "işlettiği ve EĞİTMENLER için eğitim\l"
	.string "tesisleridir. Ülke genelindeki şehir\l"
	.string "ve kasabalarda bulunurlar.\l"
	.string "Her birinin başında, çok yetenekli\l"
	.string "bir EĞİTMEN olan BİR LİDER bulunur.\l"
	.string "LİDER'i yenin ve bir ROZET toplayın.$"

Help_Text_UsingPokedex::
	.string " “POKéDEX” kullanımı$"

Help_Text_UsingPokemon::
	.string " “POKéMON” kullanımı$"

Help_Text_UsingSummary::
	.string "  “ÖZET” kullanımı$"

Help_Text_UsingSwitch::
	.string "  “DEĞİŞ” kullanımı$"

Help_Text_UsingItem::
	.string "  “EŞYA” kullanımı$"

Help_Text_UsingBag::
	.string " “ÇANTA” kullanımı$"

Help_Text_UsingAnItem::
	.string "  Eşya kullanmak$"

Help_Text_UsingKeyItem::
	.string "  Anahtar eşya kullanmak$"

Help_Text_UsingPokeBall::
	.string "  POKé TOPU kullanmak$"

Help_Text_UsingPlayer::
	.string " “{PLAYER}”ı yönetmek$"

Help_Text_UsingSave::
	.string " “KAYIT” kullanımı$"

Help_Text_UsingOption::
	.string " “AYAR” kullanımı$"

Help_Text_UsingPotion::
	.string "    İKSİR kullanmak$"

Help_Text_UsingTownMap::
	.string "    HARİTA kullanmak$"

Help_Text_UsingTM::
	.string "    TM kullanmak$"

Help_Text_UsingHM::
	.string "    HM kullanmak$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Savaş dışında hamle kullanmak$"

Help_Text_RidingBicycle::
	.string "    BİSİKLET sürmek$"

Help_Text_EnteringName::
	.string "İsim girmek$"

Help_Text_UsingPC::
	.string "PC kullanmak$"

Help_Text_UsingBillsPC::
	.string " “{STR_VAR_1}'ın PC'sini kullanmak”$"

Help_Text_UsingWithdraw::
	.string "  “AL” kullanımı$"

Help_Text_UsingDeposit::
	.string "  “DEPOLA” kullanımı$"

Help_Text_UsingMove::
	.string "  “HAREKET” kullanımı$"

Help_Text_MovingItems::
	.string "  Eşyaları değiştirme$"

Help_Text_UsingPlayersPC::
	.string " “{PLAYER}'ın PC'sini kullanma”$"

Help_Text_UsingWithdrawItem::
	.string "  “EŞYA AL” kullanımı$"

Help_Text_UsingDepositItem::
	.string "  “EŞYA DEPOLA” kullanımı$"

Help_Text_UsingMailbox::
	.string "  “POSTA” kullanımı$"

Help_Text_UsingProfOaksPC::
	.string " “PROF. OAK'ın PC'si kullanımı”$"

Help_Text_OpeningMenu::
	.string "MENÜ'yü açmak$"

Help_Text_UsingFight::
	.string " “SALDIR” kullanımı$"

Help_Text_UsingPokemon2::
	.string " “POKéMON” kullanımı$"

Help_Text_UsingShift::
	.string "  “DEĞİŞ” kullanımı$"

Help_Text_UsingSummary2::
	.string "  “ÖZET” kullanımı$"

Help_Text_UsingBag2::
	.string " “ÇANTA” kullanımı$"

Help_Text_ReadingPokedex::
	.string " “POKéDEX” okuma$"

Help_Text_UsingHomePC::
	.string "Evdeki PC'yi kullanma$"

Help_Text_UsingItemStorage::
	.string "Eşya Depolama Sistemi kullanımı$"

Help_Text_UsingWithdrawItem2::
	.string "  “EŞYA AL” kullanımı$"

Help_Text_UsingDepositItem2::
	.string "  “EŞYA DEPOLA” kullanımı$"

Help_Text_UsingMailbox2::
	.string "POSTA kullanımı$"

Help_Text_UsingRun::
	.string " “KOŞ” kullanımı$"

Help_Text_RegisterKeyItem::
	.string "  Bir eşyayı “KAYIT” etme$"

Help_Text_UsingBall::
	.string " “TOP” kullanımı$"

Help_Text_UsingBait::
	.string " “YEM” kullanımı$"

Help_Text_UsingRock::
	.string " “TAŞ” kullanımı$"

Help_Text_UsingHallOfFame::
	.string " “ŞÖHRET SALONU” kullanımı$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Menüde “POKéDEX”i açın.\n"
	.string "{CIRCLE_2} Aşağıdaki komutlarla POKéMON seçin:\n"
	.string "   “POKéMON LİSTESİ,”\n"
	.string "   “POKéMON HABİTATLARI,” ve\n"
	.string "   “ARA.”\n"
	.string "{CIRCLE_3} Detaylı bilgi için POKéMON'u\n"
	.string "   seçin.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Menüde “POKéMON”u seçin.\n"
	.string "{CIRCLE_2} Elinizdeki bir POKéMON'u seçin.\n"
	.string "{CIRCLE_3} “ÖZET,” “DEĞİŞ,” ya da\n"
	.string "   “EŞYA”yı seçin.$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} “ÖZET”i seçin.\n"
	.string "{CIRCLE_2} {PLUS} tuşlarıyla aşağıdaki\n"
	.string "   bilgilere bakabilirsiniz:\n"
	.string "   “POKéMON VERİSİ”\n"
	.string "   “POKéMON YETENEK”\n"
	.string "   “HAMLELER”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Yer değişeceğiniz POKéMON'u\n"
	.string "   seçin.\n"
	.string "{CIRCLE_2} “DEĞİŞ”e basın.\n"
	.string "{CIRCLE_3} İlk olacak POKéMON ile\n"
	.string "   değiştirin.\n"
	.string "En soldaki POKéMON savaşlarda\n"
	.string "ilk olarak çıkacaktır.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} “EŞYA”yı seçin\n"
	.string "{CIRCLE_2} “VER”e basarak POKéMON'a\n"
	.string "   eşya verebilir, ya da “AL”a\n"
	.string "   basarak tuttuğu eşyayı alabilirsin.\n"
	.string "Bir POKéMON bir eşyadan daha fazla\n"
	.string "taşıyamaz!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Menüde “ÇANTA”yı seçin.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile sağ sola basarak\n"
	.string "   aşağıdaki menüleri gezebilirsin:\n"
	.string "   “EŞYA”\n"
	.string "   “ANAHTAR EŞYA”\n"
	.string "   “POKé TOPU”\n"
	.string "   Yukarı/aşağı ile eşya seçebilirsin.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} “EŞYA” cebini seçin.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   basarak eşya seçebilirsin.\n"
	.string "{CIRCLE_3} “KULLAN”a basarak eşyayı\n"
	.string "   kullanabilirsin.\n"
	.string "Bazı eşyalar duruma ya da yerine göre\n"
	.string "kullanılamayabilir.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} “ANAHTAR EŞYA” cebini seçin.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   basarak anahtar eşya seçebilirsin.\n"
	.string "{CIRCLE_3} “KULLAN”a basarak eşyayı\n"
	.string "   kullanabilirsin.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} Vahşi POKéMON ile savaşırken,\n"
	.string "   ÇANTA menüsünden “POKé TOPU” cebini\n"
	.string "   seç.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   basarak bir POKé TOPU seçin.\n"
	.string "{CIRCLE_3} “KULLAN”a basarak seçtiğin\n"
	.string "   POKé TOPU'nu atabilirsin.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Menüde “{PLAYER}”ı seçin.\n"
	.string "{CIRCLE_2} EĞİTMEN KARTIN bilgilerinle\n"
	.string "   birlikte gözükecektir. A tuşu ile\n"
	.string "   KARTI ters çevirebilirsin.\n"
	.string "{CIRCLE_3} KARTIN arka tarafında çeşitli\n"
	.string "   bilgiler bulunur.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Menüde “KAYDET”i seçin.\n"
	.string "{CIRCLE_2} “EVET”e basarak oyundaki\n"
	.string "   ilerlemeni kaydedebilirsin.\n"
	.string "Oyun kaydedildikten sonra oyunu\n"
	.string "kapatabilirsin. Oyunun kaldığın yerden\n"
	.string "devam edecektir.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Menüde “AYARLAR”ı seçin..\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   giderek istediğin ayarı seçebilir,\n"
	.string "   sonra sağ ve sola basarak istediğin\n"
	.string "   ayarı değiştirebilirsin.\n"
	.string "{CIRCLE_3} “İPTAL” tuşu ile veya B tuşu\n"
	.string "   ile ayarlardan çıkabilirsin.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Menüyü açın.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   basarak “ÇANTA”'yı seçin\n"
	.string "{CIRCLE_3}  “EŞYA” bölümünden “İKSİR”i\n"
	.string "   seçin.\n"
	.string "{CIRCLE_4} “KULLAN”a basın\n"
	.string "{CIRCLE_5} İyileştirmek istediğiniz POKéMON'u\n"
	.string "   seçin.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Menüyü açın.\n"
	.string "{CIRCLE_2} {PLUS} tuşları ile yukarı aşağı\n"
	.string "   basarak “ÇANTA”'yı seçin\n"
	.string "{CIRCLE_3} Sağ ve sola basarak “ANAHTAR\n"
	.string "   EŞYA” cebini açın, ardından yukarı\n"
	.string "   veya aşağı gelerek “HARİTA”yı seçin. \n"
	.string "{CIRCLE_4} “KULLAN”a basarak açabilirsin.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Menüyü açın.\n"
	.string "{CIRCLE_2} “ÇANTA”da “ANAHTAR EŞYA”\n"
	.string "   cebine gelin.\n"
	.string "{CIRCLE_3} TM KASASI'nı “AÇ”.\n"
	.string "{CIRCLE_4} İstediğin TM'yi “KULLAN”.\n"
	.string "{CIRCLE_5} Hamleyi öğrenmesini istediğin\n"
	.string "   POKéMON'u seç.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Menüyü açın.\n"
	.string "{CIRCLE_2} “ÇANTA”da “ANAHTAR EŞYA”\n"
	.string "   cebine gelin.\n"
	.string "{CIRCLE_3} TM KASASI'nı “AÇ”.\n"
	.string "{CIRCLE_4} İstediğin HM'yi “KULLAN”.\n"
	.string "{CIRCLE_5} Öğrenmesini istediğin POKéMON'u\n"
	.string "seç. HM unutması zordur, bu yüzden dikkatli ol!$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Menüyü açın.\n"
	.string "{CIRCLE_2} “POKéMON”u seçin.\n"
	.string "{CIRCLE_3} HM hamlesi bilen POKéMON'u\n"
	.string "   seçin. Kullanılabilecek hamleler\n"
	.string "   mavi renk ile gösterilir. İstenilen\n"
	.string "   hamleyi kullanarak bir engeli keser,\n"
	.string "   yüzebilir, uçabilirsin vs..$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Menüyü açın. “ÇANTA”da\n"
	.string "   “ANAHTAR EŞYA” cebine gelip\n"
	.string "   “BİSİKLET”i seçin.\n"
	.string "{CIRCLE_2} “KULLAN”a basarak BİSİKLET\n"
	.string "   sürebilirsin. Ayrıca\n"
	.string "   “ATA” ile SELECT tuşuna atayarak\n"
	.string "   kolayca kullanabilirsin.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} {PLUS} yön tuşları ile\n"
	.string "   istediğin harfi seçip A tuşu ile\n"
	.string "   harfi girebilirsin.\n"
	.string "{CIRCLE_2} B tuşu ile geri gidebilirsin.\n"
	.string "{CIRCLE_3} SELECT tuşu ile büyük veya\n"
	.string "   küçük harf seçebilirsin.\n"
	.string "{CIRCLE_4} “TAMAM” butonu ile bitirebilirsin.$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} POKéMON MERKEZİ'ne gidip PC'nin\n"
	.string "   önüne gel ve A tuşuna bas.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} “{STR_VAR_1}'in PC”sini seç.\n"
	.string "{CIRCLE_2} POKéMON Depolama Sistemi'ne\n"
	.string "   erişmek için menülerden birini seç.\n"
	.string "Eğer yanında 6 POKéMON'dan fazla varsa,\n"
	.string "yeni yakaladığın otomatikmen sistemdeki\n"
	.string "KUTU'lardan birine yollanır!$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} {PLUS} yön tuşlarını kullanarak\n"
	.string "   bir POKéMON seçin.\n"
	.string "{CIRCLE_2} “AL” tuşuna basarak KUTU'dan\n"
	.string "   POKéMON seçip yanınıza\n"
	.string "   alabilirsiniz.\n"
	.string "Eğer 6 POKéMON'un var ise\n"
	.string "daha fazla POKéMON alamazsın!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} {PLUS} yön tuşlarını kullanarak\n"
	.string "   partinizden bir POKéMON seçin.\n"
	.string "{CIRCLE_2} “DEPOLA”yı seçin.\n"
	.string "{CIRCLE_3} KUTU seçtikten sonra\n"
	.string "   A tuşu ile POKéMON'u depolayın.\n"
	.string "Eğer tek POKéMON'un varsa,\n"
	.string "onu depolayamazsın!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Açık KUTU'dan bir POKéMON seç.\n"
	.string "{CIRCLE_2} “TAŞI” seçeneği ile POKéMON\n"
	.string "    seç ve {PLUS} yön tuşları ile\n"
	.string "   istediğin yere götür.\n"
	.string "{CIRCLE_3} KUTU ismine gelerek sağ ve sol\n"
	.string "   tuşları ile farklı KUTU'lara\n"
	.string "   taşıyabilirsin.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Şeffaf gösterilen POKéMON'ları\n"
	.string "   seçip onlara A tuşu ile bir eşya\n"
	.string "   verebilirsin.\n"
	.string "{CIRCLE_2} Tamamen gösterilen POKéMON'ları\n"
	.string "   seçip tuttukları eşyayı başka bir\n"
	.string "   POKéMON'a verebilir veya eşyayı tekrar\n"
	.string "   A tuşu ile ÇANTA'ya koyabilirsin.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} “{PLAYER}'ın PC'si”ni aç.\n"
	.string "{CIRCLE_2} “DEPOLAMA” veya\n"
	.string "   “POSTA K.” seç.\n"
	.string "Eğer ÇANTA doluysa kendi PC'ne\n"
	.string "eşya koyabilirsin. Ayrıca depolanan\n"
	.string "eşyaları geri alabilirsin.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} “EŞYA AL”ı seçin.\n"
	.string "{CIRCLE_2} Alınacak eşyayı seçin.\n"
	.string "{CIRCLE_3} Eşya artık alınabilir ve\n"
	.string "   ÇANTA'da EŞYA cebine koyulabilir.\n"
	.string "   Ayrıca tutması için bir POKéMON'a\n"
	.string "   verilebilir.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} “EŞYA DEPOLA”yı seçin.\n"
	.string "{CIRCLE_2} {PLUS} yön tuşları ile koymak\n"
	.string "   istediğiniz eşyayı seçin.\n"
	.string "{CIRCLE_3} Eğer birden fazla eşya koymak\n"
	.string "   isterseniz, miktarı {PLUS} yön tuşları\n"
	.string "   ile seçtikten sonra, A tuşuna basarak\n"
	.string "   onaylayabilirsiniz.$"

Help_Text_HowToUseMailbox::
	.string "Bir POKéMON'dan MEKTUP alınırsa,\n"
	.string "POSTA KUTUSU'na taşınır. Eğer hiç\n"
	.string "MEKTUP yoksa POSTA K. kullanılamaz.\n"
	.string "{CIRCLE_1} “{PLAYER}'ın PC'si”ni seçin.\n"
	.string "{CIRCLE_2} “POSTA K.”nu seçerek MEKTUP\n"
	.string "   okuyabilir veya bir POKéMON'a\n"
	.string "   verebilirsin.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} “PROF. OAK'ın PC'si”ni seçin.\n"
	.string "{CIRCLE_2} PROF. OAK, POKéDEX'inizi\n"
	.string "   değerlendirecektir.\n"
	.string "Önerileri size daha fazla POKéMON\n"
	.string "yakalamak için ipucu verir!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} START'a basın.\n"
	.string "{CIRCLE_2} Sağ tarafta MENÜ açılacaktır.\n"
	.string "{CIRCLE_3} Duruma göre, MENÜ'de farklı\n"
	.string "   butonlar bulunabilir.\n"
	.string "MENÜ yürüme, savaşma, bir iş yapma\n"
	.string "gibi durumlar sırasında açılamaz.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} “SALDIR”ı seçin\n"
	.string "{CIRCLE_2} Gösterilen hamlelerden birini\n"
	.string "seçin ve kullanın!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} “POKéMON”u seçin\n"
	.string "{CIRCLE_2} Kullanmak istediğiniz POKéMON'u\n"
	.string "   seçin.\n"
	.string "{CIRCLE_3} Eğer iki veya daha fazla\n"
	.string "   POKéMON'unuz varsa, “DEĞİŞ”e basarak\n"
	.string "   onu savaşa sokabilirsiniz. “ÖZET” ile\n"
	.string "   POKéMON verisine bakabilirsiniz.$"

Help_Text_HowToUseShift::
	.string "Bu komut savaştaki POKéMON'unuzu\n"
	.string "partinizdeki bir başkasıyla değiştirir.\n"
	.string "{CIRCLE_1} Göndereceğiniz POKéMON'u seçin.\n"
	.string "{CIRCLE_2} “DEĞİŞ”e basın.\n"
	.string "{CIRCLE_3} Seçilen POKéMON savaştaki\n"
	.string "   ile yer değiştirir!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} “ÖZET”e basın\n"
	.string "{CIRCLE_2} {PLUS} yön tuşları ile sağ ve sola\n"
	.string "   basarak aşağıdakilere bakabilirsiniz:\n"
	.string "   “POKéMON VERİSİ”\n"
	.string "   “POKéMON YETENEK”\n"
	.string "   “HAMLELER”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} “ÇANTA”yı seçin\n"
	.string "{CIRCLE_2} {PLUS} yön tuşları ile sağ ve sola\n"
	.string "   basarak aşağıdakilere bakabilirsiniz:\n"
	.string "   “EŞYA”\n"
	.string "   “ANAHTAR EŞYA”\n"
	.string "   “POKé TOPU”\n"
	.string "   Eşya seçmek için yukarı ve aşağı basın.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} Yakalanan POKéMON'lar POKéDEX\n"
	.string "   listesinde POKé TOPU simgesi ile\n"
	.string "   gösterilir.\n"
	.string "{CIRCLE_2} Yakalanan POKéMON geniş çapta\n"
	.string "   veri içerir.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} “BÖLGE”yi seçerek HARİTA'da\n"
	.string "   POKéMON'un habitatını görebilirsin.$"
	.else
	.string "{CIRCLE_3} “SONRAKİ”yi seçerek HARİTA'da\n"
	.string "   POKéMON'un habitatını görebilirsin.$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Evdeki PC'nin önüne geçip, A\n"
	.string "   tuşuna basın.\n"
	.string "{CIRCLE_2} PC açılacaktır.\n"
	.string "{CIRCLE_3} “EŞYA DEPOLA” veya\n"
	.string "   “POSTA K.” seçebilirsiniz.$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} “EŞYA AL”ı seçerek depolanan\n"
	.string "   bir eşyayı alabilirsin.\n"
	.string "{CIRCLE_2} “EŞYA DEPOLA”yı seçerek ÇANTA'da\n"
	.string "   bulunan bir eşyayı koyabilirsin.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} “EŞYA AL”ı seçin.\n"
	.string "{CIRCLE_2} Alınacak eşyayı seçin.\n"
	.string "{CIRCLE_3} Eşya artık alınabilir ve\n"
	.string "   ÇANTA'da EŞYA cebine koyulabilir.\n"
	.string "   Ayrıca tutması için bir POKéMON'a\n"
	.string "   verilebilir.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} “EŞYA DEPOLA”yı seçin.\n"
	.string "{CIRCLE_2} {PLUS} yön tuşları ile koymak\n"
	.string "   istediğiniz eşyayı seçin.\n"
	.string "{CIRCLE_3} Eğer hiçbir eşyanız yoksa,\n"
	.string "   bu komut kullanılamaz!$"

Help_Text_HowToUseMailbox2::
	.string "Bir POKéMON'dan MEKTUP alınırsa,\n"
	.string "POSTA KUTUSU'na taşınır. Eğer hiç\n"
	.string "MEKTUP yoksa POSTA K. kullanılamaz.\n"
	.string "{CIRCLE_1} MEKTUP seçerek okuyabilir\n"
	.string "   ya da bir POKéMON onu taşıyabilir.$"

Help_Text_HowToUseRun::
	.string "Bir EĞİTMEN savaşında “KAÇ”\n"
	.string "kullanamazsın!\n"
	.string "{CIRCLE_1} Vahşi POKéMON'lardan “KAÇ”abilirsin.\n"
	.string "{CIRCLE_2} Eğer POKéMON'un hızlı ise savaştan\n"
	.string "   kaçma şansın artar..$"

Help_Text_HowToRegisterKeyItem::
	.string "Bir anahtar eşyayı SELECT tuşuna kolay\n"
	.string "kullanım için “ATA”yabilirsin!\n"
	.string "{CIRCLE_1} “ANAHTAR EŞYA” cebini açın.\n"
	.string "{CIRCLE_2} Eşyayı seçin, ardından “ATA”\n"
	.string "   butonunu seçin.$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} SAFARİ BÖLGESİ'ne özel\n"
	.string "   POKé TOPU'nu atmak için seçin.\n"
	.string "Vahşi POKéMON göründüğünde, onları\n"
	.string "yakalamak için bolca SAFARİ TOPU atın!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} SAFARİ BÖLGESİ'ne özel\n"
	.string "   yiyecek atmak için seçin.\n"
	.string "Bu, kolay yemeleri için top haline\n"
	.string "getirilmiş POKéMON yiyeceğidir. YEM\n"
	.string "atıldığında, vahşi POKéMON buna\n"
	.string "etkilenebilir ve kaçmayabilir!$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} SAFARİ BÖLGESİ'nde yerdeki\n"
	.string "   bir taşı atmak için seçin.\n"
	.string "Bir POKéMON'a taş atmak onu\n"
	.string "kaçırabilir, ancak yakalamayı\n"
	.string "kolaylaştırır!$"


Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} PC'de “ŞÖHRET SALONU”nu seç.\n"
	.string "{CIRCLE_2} ŞÖHRET SALONU'na giren\n"
	.string "   POKéMON'lar incelenebilir.$"

Help_Text_HP::
	.string "CAN$"

Help_Text_EXP::
	.string "EXP. {LEFT_PAREN}EXP. Puanı{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "HAMLELER$"

Help_Text_Attack::
	.string "SALDIRI$"

Help_Text_Defense::
	.string "SAVUNMA$"

Help_Text_SpAtk::
	.string "ÖZ. SLD$"

Help_Text_SpDef::
	.string "ÖZ. SVN$"

Help_Text_Speed::
	.string "HIZ$"

Help_Text_Level::
	.string "Sv. {LEFT_PAREN}Seviye{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TÜR$"

Help_Text_OT::
	.string "OE$"

Help_Text_Item::
	.string "EŞYA$"

Help_Text_Ability::
	.string "YETENEK$"

Help_Text_Money::
	.string "PARA$"

Help_Text_MoveType::
	.string "HAMLE TÜRÜ$"

Help_Text_Nature::
	.string "DOĞA$"

Help_Text_IDNo::
	.string "ID No.$"

Help_Text_PP::
	.string "PP$"

Help_Text_Power::
	.string "GÜÇ$"

Help_Text_Accuracy::
	.string "İSABET$"

Help_Text_FNT::
	.string "BAY$"

Help_Text_Items::
	.string "EŞYALAR$"

Help_Text_KeyItems::
	.string "ANAHTAR EŞYA$"

Help_Text_PokeBalls::
	.string "POKé TOPLARI$"

Help_Text_Pokedex::
	.string "POKéDEX$"

Help_Text_PlayTime::
	.string "OYUN SÜRESİ$"

Help_Text_Badges::
	.string "ROZETLER$"

Help_Text_TextSpeed::
	.string "YAZI HIZI$"

Help_Text_BattleScene::
	.string "ANİMASYON$"

Help_Text_BattleStyle::
	.string "SAVAŞ TÜRÜ$"

Help_Text_Sound::
	.string "SES$"

Help_Text_ButtonMode::
	.string "TUŞ MODU$"

Help_Text_Frame::
	.string "ÇERÇEVE$"

Help_Text_Cancel2::
	.string "İPTAL$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "HM$"

Help_Text_HMMove::
	.string "HM HAMLESİ$"

Help_Text_Evolution::
	.string "EVRİM$"

Help_Text_StatusProblem::
	.string "DURUM PROBLEMİ$"

Help_Text_Pokemon::
	.string "POKéMON$"

Help_Text_IDNo2::
	.string "ID No.$"

Help_Text_Money2::
	.string "PARA$"

Help_Text_Badges2::
	.string "ROZETLER$"

Help_Text_DefineHP::
	.string "CAN POKéMON'un canlılığını temsil eder.\n"
	.string "Eğer POKéMON'un canı sıfıra inerse,\l"
	.string "bayılır ve savaşamaz duruma gelir.\l"
	.string "Yani savaşın anahtarı, düşmanın CAN\n"
	.string "puanını sıfıra indirmeye çalışmaktır.\l"
	.string "POKéMON'lar yaralanırsa, CAN'larını bir\l"
	.string "POKéMON MERKEZİ'nde veya eşyayla yenileyin$"

Help_Text_DefineEXP::
	.string "EXP. Puanı, “Deneyim Puanı”\n"
	.string "anlamına gelir. POKéMON'lar savaşları\l"
	.string "kazanarak EXP. Puanı kazanır.\l"
	.string "Bir POKéMON yeterli EXP. Puanı\l"
	.string "biriktirdiğinde, seviye atlar. EXP.\l"
	.string "Çubuğu, biriken EXP. Puanlarını\l"
	.string "gösterir. Seviye atlayınca sıfırlanır.$"

Help_Text_DefineMoves::
	.string "POKéMON'lar en fazla dört farklı\n"
	.string "hamle öğrenebilir. Saldırılar ve\l"
	.string "özel etkileri olanlar dahil birçok tür\l"
	.string "hamle vardır. Öğrenilebilecek hamleler\l"
	.string "her POKéMON için farklılık gösterir.\l"
	.string "Bazı hamleler eşyalardan öğrenilebilir.$"

Help_Text_DefineAttack::
	.string "SALDIRI, saldırı hareketinin gücünü\n"
	.string "gösterir. Bu istatistik ne kadar\l"
	.string "yüksekse, hareket o kadar güçlü olur.\l"
	.string "Şu hareket türleri için uygulanır:\l"
	.string "NORMAL, ZEHİR, YER, UÇUŞ,\l"
	.string "BÖCEK, DÖVÜŞ, KAYA, HAYALET,\l"
	.string "ve ÇELİK.$"

Help_Text_DefineDefense::
	.string "SAVUNMA, bir POKéMON'un fiziksel\n"
	.string "saldırılara karşı direncini gösterir.\l"
	.string "Bu istatistik ne kadar yüksekse,\l"
	.string "düşmanın fiziksel saldırısından o\l"
	.string "kadar az hasar alır.$"

Help_Text_DefineSpAtk::
	.string "ÖZ. SLD (Özel Saldırı),\n"
	.string "hareketinin gücünü gösterir.\l"
	.string "Bu istatistik ne kadar yüksekse, özel\l"
	.string "saldırı hareketi o kadar güçlü olur.\l"
	.string "Şu hareket türleri için uygulanır:\l"
	.string "ATEŞ, SU, ELEKTRİK, ÇİMEN,\l"
	.string "BUZ, PSİŞİK, EJDER ve KARA.$"

Help_Text_DefineSpDef::
	.string "ÖZ. SVN (Özel Savunma), bir\n"
	.string "POKéMON'un özel saldırılara karşı\l"
	.string "direncini gösterir.\l"
	.string "Bu istatistik ne kadar fazlaysa,\l"
	.string "rakibin özel saldırısından\l"
	.string "o kadar az hasar alır.$"

Help_Text_DefineSpeed::
	.string "HIZ, bir POKéMON'un çevikliğini\n"
	.string "gösterir. Bu istatistik rakipten\l"
	.string "yüksekse, POKéMON savaşta rakibinden\l"
	.string "önce hareket edebilir.$"

Help_Text_DefineLevel::
	.string "Sv. (Seviye), bir POKéMON'un gelişim\n"
	.string "ve gücünü gösterir.\l"
	.string "Genel olarak, bir POKéMON seviye\l"
	.string "atladığında, CAN, SALDIRI ve SAVUNMA\l"
	.string "gibi istatistikleri artar, bu da onu\l"
	.string "daha güçlü yapar.\l"
	.string "POKéMON seviye atladığında yeni bir\l"
	.string "hareket öğrenebilir.$"

Help_Text_DefineType::
	.string "POKéMON ve hareketler türe göre\n"
	.string "sınıflandırılır. Her türün diğer\l"
	.string "türlere karşı avantajlı ve dezavantajlı\l"
	.string "eşleşmeleri vardır. Örneğin, taş-kağıt\l"
	.string "makas oyununda olduğu gibi, SU türü\l"
	.string "ATEŞ türüne karşı güçlü, ÇİMEN\l"
	.string "türüne karşı zayıftır.$"

Help_Text_DefineOT::
	.string "OE, “Orijinal EĞİTMEN” anlamına gelir,\n"
	.string "seçilen POKéMON'u yakalayan ilk\l"
	.string "EĞİTMEN'dir.\l"
	.string "POKéMON takas edilse bile OE adı\l"
	.string "değişmeyecektir.$"

Help_Text_DefineItem::
	.string "Tüm POKéMON'lar birer eşya taşıyabilir.\n"
	.string "Bazı eşyalar belirli durumlarda\l"
	.string "POKéMON tarafından otomatik olarak\l"
	.string "kullanılır. Bir POKéMON'a eşya\l"
	.string "taşıtmak için ÇANTA'dan eşya seçin\l"
	.string "ve POKéMON'a “VER”in.$"

Help_Text_DefineAbility::
	.string "Tüm POKéMON'ların özel bir YETENEĞİ\n"
	.string "vardır. Bu yeteneklerin birçok çeşidi\l"
	.string "vardır, bazıları savaşta, bazıları\l"
	.string "başka yerlerde kullanılır. Yetenekler\l"
	.string "türe göre değişir. Bazı türlerin birden\l"
	.string "fazla yetenek çeşidi olabilir.$"

Help_Text_DefineMoney::
	.string "Bir EĞİTMEN'e karşı savaş kazanınca\n"
	.string "ödül parası alırsınız.\l"
	.string "Ödül paranızı biriktirerek POKéMON\l"
	.string "MARKET'ten alışverişin keyfini çıkarın!$"

Help_Text_DefineMoveType::
	.string "Hamleler de türüne göre sınıflandırılır.\n"
	.string "Belirli türdeki bir POKéMON, aynı türde\l"
	.string "bir hareket kullandığında, hareketin\l"
	.string "gücü artar. Hamle türü hedefe karşı\l"
	.string "avantaja sahipse, gücü daha da artar.$"

Help_Text_DefineNature::
	.string "Tüm POKéMON'ların bir kişiliği veya\n"
	.string "“DOĞA”sı vardır. POKéMON'un doğası,\l"
	.string "seviye atladığında nasıl gelişeceğini\l"
	.string "etkiler.$"

Help_Text_DefineIDNo::
	.string "ID No., özel olarak size, bir EĞİTMEN\n"
	.string "olarak atanmış özel bir numaradır.\l"
	.string "OE adı ile birlikte, ID No., Orijinal\l"
	.string "EĞİTMEN'i tam olarak tanımlamak için\l"
	.string "kullanılır.\l"
	.string "ID No., POKéMON takas edilse bile\l"
	.string "değişmez.$"

Help_Text_DefinePP::
	.string "PP “Power Points” (Güç Puanları)\n"
	.string "anlamına gelir. Bir hareketin savaşta\l"
	.string "kaç kez kullanılabileceğini gösterir.\l"
	.string "CAN gibi, PP de bir POKéMON MERKEZİ'ni\l"
	.string "ziyaret ederek veya belirli eşyaları\l"
	.string "kullanarak geri kazanılabilir.$"

Help_Text_DefinePower::
	.string "GÜÇ, bir saldırının gücünü gösterir.\n"
	.string "Bu sayı ne kadar yüksekse, düşmana\l"
	.string "verilebilecek hasar o kadar büyük olur!$"

Help_Text_DefineAccuracy::
	.string "KESİNLİK, hareketin düşmana\n"
	.string "isabet etme olasılığını gösterir.\l"
	.string "Bu sayı ne kadar yüksekse, hareketin\l"
	.string "hedefi vurma olasılığı o kadar fazladır.$"

Help_Text_DefineFNT::
	.string "BAY, “baygın” anlamına gelir.\n"
	.string "Bir POKéMON'un CAN'ı sıfıra düşerse\l"
	.string "bayılır ve savaşta yer alamaz.\l"
	.string "Bir POKéMON'u canlandırmak için bir\l"
	.string "POKéMON MERKEZİ'ne gidin veya bir eşya\l"
	.string "kullanın.$"

Help_Text_DefineItems::
	.string "Herhangi bir POKéMON MARKET'ten alınan\n"
	.string "sıradan eşyalar, EŞYA cebine\l"
	.string "yerleştirilir.\l"
	.string "Eşyalar kullanılabilir, bir POKéMON'a\l"
	.string "verilebilir veya çöp olarak atılabilir.$"

Help_Text_DefineKeyItems::
	.string "İnsanlardan bulduğunuz veya aldığınız\n"
	.string "önemli eşyalar, ANAHTAR EŞYA cebine\l"
	.string "yerleştirilir.\l"
	.string "Önemli eşyalar kullanılabilir veya\l"
	.string "kullanım için SELECT tuşuna\l"
	.string "atanabilir. Bir kez atanırsa, eşya\n"
	.string "MENÜ ve ÇANTA açılmadan kullanılabilir.$"

Help_Text_DefinePokeBalls::
	.string "Vahşi POKéMON'ları yakalamak için\n"
	.string "kullanılan POKé TOPU, POKé TOPU\l"
	.string "cebine yerleştirilir.\l"
	.string "POKé TOPLARI, POKéMON MARKET'ten\n"
	.string "alınabilir. Kullanılabilir, bir POKéMON'a\l"
	.string "verilebilir veya çöp olarak atılabilir.$"

Help_Text_DefinePokedex::
	.string "Bu, yakaladığınız ve/veya evrimleşen\n"
	.string "POKéMON türlerinin sayısını gösterir.\l"
	.string "POKéDEX'i doldurun. Çeşitli türde\n"
	.string "POKéMON yakalamak için çabalayın!$"


Help_Text_DefinePlayTime::
	.string "Bu oyun oynadığınız toplam süreyi\n"
	.string "gösterir.$"

Help_Text_DefineBadges::
	.string "Kazanmış olduğunuz POKéMON LİGİ\n"
	.string "ROZETLERİ ve gösterilmektedir. Şehir\l"
	.string "ve kasabalardaki SALON LİDERLERİ'ni\l"
	.string "yendiğinizde ROZET kazanırsınız.$"

Help_Text_DefineTextSpeed::
	.string "Metnin ne kadar hızlı gösterileceğini\n"
	.string "ayarlayabilirsiniz. Birini seçin:\l"
	.string "YAVAŞ, ORTA, veya HIZLI.$"

Help_Text_DefineBattleScene::
	.string "Savaş animasyonlarını AÇIK veya\n"
	.string "KAPALI olarak ayarlayabilirsiniz.$"

Help_Text_DefineBattleStyle::
	.string "Bir EĞİTMEN'in, rakibini bayılttıktan\n"
	.string "sonra bir POKéMON değiştirme seçeneği\l"
	.string "olup olmadığını seçebilirsiniz.\l"
	.string "Rakibini bayılttıktan sonra bir POKéMON\l"
	.string "değiştirme şansı istiyorsanız, “DEĞİŞ”\l"
	.string "olarak ayarlayın.$"

Help_Text_DefineSound::
	.string "MONO ya da STEREO ses çıkışını\n"
	.string "ayarlayabilirsin.$"

Help_Text_DefineButtonMode::
	.string "Yardım mesajlarını görüntülemek için\n"
	.string "L veya R Düğmesine basarak “YARDIM”\l"
	.string "olarak ayarlayın.\l"
	.string "POKéDEX sayfalarını ve ÇANTA CEP'lerini\l"
	.string "L ve R Düğmelerini kullanarak\l"
	.string "değiştirmek için “LR” olarak ayarlayın.\l"
	.string "L Düğmesini A Düğmesiyle aynı işlevde\l"
	.string "çalıştırmak için “L=A” olarak ayarlayın.$"

Help_Text_DefineFrame::
	.string "Belirli menülerin etrafındaki çerçeve\n"
	.string "tasarımını seçebilirsiniz. Deneyin ve\l"
	.string "hangi tasarımı beğendiğinizi görün.$"

Help_Text_DefineCancel2::
	.string "Ayarlar kırmızı renkte gösterilen\n"
	.string "seçimlere değiştirilecek ve MENÜ'ye\n"
	.string "geri döneceksiniz.$"

Help_Text_DefineTM::
	.string "TM (Teknik Makine), bir POKéMON'a\n"
	.string "hareket öğretmek için kullanılan bir\l"
	.string "cihazdır.Birçok farklı türü vardır.\l"
	.string "Hamleler sadece bu onları kullanabilen\l"
	.string "POKéMON'lara öğretilebilir.\l"
	.string "Bir TM, tek kullanımlık olduğundan\l"
	.string "kullanıldıktan sonra kırılır.$"

Help_Text_DefineHM::
	.string "HM (Gizli Makine), bir POKéMON'a\n"
	.string "GİZLİ bir hamle öğretmek için\l"
	.string "kullanılan bir cihazdır.\l"
	.string "TM'nin aksine, bir HM tekrar tekrar\l"
	.string "kullanılabilir. Bir POKéMON'un GİZLİ\l"
	.string "hareketi unutması zor olabilir.$"

Help_Text_DefineHMMove::
	.string "GİZLİ hamleler, maceranız için\n"
	.string "önemli olanlardır. Bu hamleleri\l"
	.string "savaş dışında kullanmak için,\l"
	.string "“POKéMON” MENÜSÜNÜ açın ve hamleyi\l"
	.string "bilen POKéMON'un kullanmasını sağlayın.\l"
	.string "Baygın bir POKéMON, savaş dışı bile\l"
	.string "GİZLİ hamle kullanabilir.$"

Help_Text_DefineEvolution::
	.string "POKéMON'lar arasında bazıları belirli\n"
	.string "seviyeye ulaştıklarında büyük değişiklik\l"
	.string "(evrim) geçirir. Evrim, bir POKéMON'un\l"
	.string "şeklini, isminin değişmesine ve belki de\l"
	.string "öğrenebileceği hamlelerin değişmesine\l"
	.string "neden olur. Bazı POKéMON'lar seviyeden\l"
	.string "farklı nedenlerle evrim geçirir.$"

Help_Text_DefineStatusProblem::
	.string "Durum sorunları şunları içerir:\n"
	.string "Uyku: Hareketleri kullanamaz.\l"
	.string "Zehir: Sürekli CAN kaybına neden olur.\l"
	.string "Paraliz: Hareketleri engelleyebilir.\l"
	.string "Yanma: CAN ve SALDIRI gücü kaybı.\l"
	.string "Donma: Hareketleri kullanamaz.\l"
	.string "Eşyalar vb. ile tedavi edilebilir.$"

Help_Text_DefinePokemon::
	.string "POKéMON, bu dünyanın her köşesinde\n"
	.string "yaşayan harika yaratıkları tanımlamak\l"
	.string "için verilen bir isimdir.\l"
	.string "İnsanlar POKéMON'ları evcil hayvan\l"
	.string "olarak besler, onları savaşmak için\l"
	.string "kullanır ve daha birçok şey yapar.$"

Help_Text_DefineIDNo2::
	.string "ID No., size EĞİTMEN olarak özel\n"
	.string "olarak atanmış bir numaradır.\l"
	.string "OE adı ile birlikte ID No., Orijinal\l"
	.string "EĞİTMEN'i kesin olarak tanımlamak için\l"
	.string "kullanılır.\l"
	.string "POKéMON takas edilse bile ID değişmez.$"

Help_Text_DefineMoney2::
	.string "Bir EĞİTMEN'e karşı savaş kazandığınızda\n"
	.string "ödül parası alırsınız. Paralarınızı\l"
	.string "biriktirin, böylece POKéMON\l"
	.string "MARKET'inden alışveriş yapabilirsin!$"

Help_Text_DefineBadges2::
	.string "Bu, kazandığınız POKéMON LİGİ ROZET\n"
	.string "sayısını gösterir. Çeşitli\l"
	.string "şehirlerdeki ve kasabalardaki SALON\l"
	.string "LİDER'lerini yenerek ROZET kazanın.$"

Help_Text_TheHelpSystem::
	.string "YARDIM sistemi$"

Help_Text_TheGame::
	.string "Oyun$"

Help_Text_WirelessAdapter::
	.string "Kablosuz Adaptör$"

Help_Text_GameFundamentals1::
	.string "Oyun temelleri 1$"

Help_Text_GameFundamentals2::
	.string "Oyun temelleri 2$"

Help_Text_GameFundamentals3::
	.string "Oyun temelleri 3$"

Help_Text_WhatArePokemon::
	.string "POKéMON nedir?$"

Help_Text_DescTheHelpSystem::
	.string "Yardım mesajları, oyunda ne kadar\n"
	.string "ilerlediğinize bağlı olarak değişir.\l"
	.string "İhtiyacınız olduğunda sizi desteklemek\l"
	.string "için tasarlandılar. Anlamadığınız\l"
	.string "bir şey varsa, LÜTFEN Yardım Sistemine\l"
	.string "bakın!$"

Help_Text_DescTheGame::
	.string "Ana karakter olarak POKéMON dünyasını\n"
	.string "keşfetmeye başlıyorsunuz!\l"
	.string "İnsanlarla konuşarak ve gizemleri\l"
	.string "çözerek, yeni yollar size açılacak.\l"
	.string "Harika POKéMON'unuzla birlikte hedefe\l"
	.string "ulaşmak için çabalayın!$"

Help_Text_DescWirelessAdapter::
	.string "Bu oyun, Kablosuz Adaptör kullanarak\n"
	.string "kablosuz bağlantı üzerinden iletişim kurar.\p"
	.string "Her yerde, her zaman ve herkesle\l"
	.string "kablosuz oynayın!\p"
	.string "Kablosuz Adaptör'ü daima bağlı tutarak\l"
	.string "oynamayı deneyin!$"

Help_Text_DescGameFundamentals1::
	.string "Her şehri ve kasabayı ziyaret edin,\n"
	.string "her yolu gezin, her mağarayı keşfedin ve\l"
	.string "POKéMON'un en büyük EĞİTMENİ olmak için\l"
	.string "her zorluğun üstesinden gelin!$"

Help_Text_DescGameFundamentals2::
	.string "Maceranızda birçok engelle karşılaşacaksınız.\n"
	.string "Her engel, bir şey yaparak veya gizemleri\l"
	.string "çözerek aşılabilir. Bazı engeller,\l"
	.string "uzaklarda meydana gelen bir olaydan\l"
	.string "etkilenir.$"

Help_Text_DescGameFundamentals3::
	.string "Yolunuzdaki bazı engeller, POKéMON'unuz\n"
	.string "belirli hareketleri öğrendiğinde\l"
	.string "kaldırılabilir.$"

Help_Text_DescWhatArePokemon::
	.string "POKéMON, gizemlerle dolu harika\n"
	.string "varlıklardır. Onlarla dünyanın\l"
	.string "dört bir yanında… uzun otların\l"
	.string "arasında, mağaralarda, denizde ve\l"
	.string "daha birçok yerde karşılaşabilirsiniz.\l"
	.string "Yakaladıkları EĞİTMENLERE itaatkar\l"
	.string "oldukları görülüyor.$"

Help_Text_UsingTypeMatchupList::
	.string "Tür Eşleşme Listesi Kullanımı$"

Help_Text_OwnMoveDark::
	.string "Kendi hamle türü: KARA$"

Help_Text_OwnPokemonDark::
	.string "Kendi POKéMON türü: KARA$"

Help_Text_OwnMoveRock::
	.string "Kendi hamle türü: KAYA$"

Help_Text_OwnPokemonRock::
	.string "Kendi POKéMON türü: KAYA$"

Help_Text_OwnMovePsychic::
	.string "Kendi hamle türü: PSİŞİK$"

Help_Text_OwnPokemonPsychic::
	.string "Kendi POKéMON türü: PSİŞİK$"

Help_Text_OwnMoveFighting::
	.string "Kendi hamle türü: DÖVÜŞ$"

Help_Text_OwnPokemonFighting::
	.string "Kendi POKéMON türü: DÖVÜŞ$"

Help_Text_OwnMoveGrass::
	.string "Kendi hamle türü: ÇİMEN$"

Help_Text_OwnPokemonGrass::
	.string "Kendi POKéMON türü: ÇİMEN$"

Help_Text_OwnMoveGhost::
	.string "Kendi hamle türü: HAYALET$"

Help_Text_OwnPokemonGhost::
	.string "Kendi POKéMON türü: HAYALET$"

Help_Text_OwnMoveIce::
	.string "Kendi hamle türü: BUZ$"

Help_Text_OwnPokemonIce::
	.string "Kendi POKéMON türü: BUZ$"

Help_Text_OwnMoveGround::
	.string "Kendi hamle türü: YER$"

Help_Text_OwnPokemonGround::
	.string "Kendi POKéMON türü: YER$"

Help_Text_OwnMoveElectric::
	.string "Kendi hamle türü: ELEKTRİK$"

Help_Text_OwnPokemonElectric::
	.string "Kendi POKéMON türü: ELEKTRİK$"

Help_Text_OwnMovePoison::
	.string "Kendi hamle türü: ZEHİR$"

Help_Text_OwnPokemonPoison::
	.string "Kendi POKéMON türü: ZEHİR$"

Help_Text_OwnMoveDragon::
	.string "Kendi hamle türü: EJDER$"

Help_Text_OwnPokemonDragon::
	.string "Kendi POKéMON türü: EJDER$"

Help_Text_OwnMoveNormal::
	.string "Kendi hamle türü: NORMAL$"

Help_Text_OwnPokemonNormal::
	.string "Kendi POKéMON türü: NORMAL$"

Help_Text_OwnMoveSteel::
	.string "Kendi hamle türü: ÇELİK$"

Help_Text_OwnPokemonSteel::
	.string "Kendi POKéMON türü: ÇELİK$"

Help_Text_OwnMoveFlying::
	.string "Kendi hamle türü: UÇUŞ$"

Help_Text_OwnPokemonFlying::
	.string "Kendi POKéMON türü: UÇUŞ$"

Help_Text_OwnMoveFire::
	.string "Kendi hamle türü: ATEŞ$"

Help_Text_OwnPokemonFire::
	.string "Kendi POKéMON türü: ATEŞ$"

Help_Text_OwnMoveWater::
	.string "Kendi hamle türü: SU$"

Help_Text_OwnPokemonWater::
	.string "Kendi POKéMON türü: SU$"

Help_Text_OwnMoveBug::
	.string "Kendi hamle türü: BÖCEK$"

Help_Text_OwnPokemonBug::
	.string "Kendi POKéMON türü: BÖCEK$"

Help_Text_HowToUseTypeMatchupList::
	.string "Hamle türüne ve rakip POKéMON\n"
	.string "türüne bağlı olarak, saldırı\l"
	.string "etkileri şu şekildedir:\l"
	.string "{CIRCLE_DOT}: Süper etkili!\l"
	.string "{TRIANGLE}: Pek etkili değil\l"
	.string "{BIG_MULT_X}: Hiç etkili değil\l"
	.string "(Diğer eşleşmeler için fark yok.)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: PSİŞİK, HAYALET\p"
	.string "   {TRIANGLE}: DÖVÜŞ, KARA, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	
	.string "   {CIRCLE_DOT}: DÖVÜŞ, BÖCEK\p"
	.string "   {TRIANGLE}: HAYALET, KARA\p"
	.string "   {BIG_MULT_X}: PSİŞİK$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, BUZ, UÇUŞ, BÖCEK\p"
	.string "   {TRIANGLE}: DÖVÜŞ, YER, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, ÇİMEN, DÖVÜŞ,\n"
	.string "       YER, ÇELİK\p"
	.string "   {TRIANGLE}: NORMAL, ATEŞ, ZEHİR, UÇUŞ$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: DÖVÜŞ, ZEHİR\p"
	.string "   {TRIANGLE}: PSİŞİK, ÇELİK\p"
	.string "   {BIG_MULT_X}: KARA$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: BÖCEK, HAYALET, KARA\p"
	.string "   {TRIANGLE}: DÖVÜŞ, PSİŞİK$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: NORMAL, BUZ, KAYA, KARA, ÇELİK\p"
	.string "   {TRIANGLE}: ZEHİR, UÇUŞ, PSİŞİK, BÖCEK\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: UÇUŞ, PSİŞİK\p"
	.string "   {TRIANGLE}: BÖCEK, KAYA, KARA$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, YER, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, ÇİMEN, ZEHİR, UÇUŞ,\n"
	.string "       BÖCEK, EJDER, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, BUZ, ZEHİR, UÇUŞ, BÖCEK\p"
	.string "   {TRIANGLE}: SU, ELEKTRİK, ÇİMEN, YER$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: PSİŞİK, HAYALET\p"
	.string "   {TRIANGLE}: KARA, ÇELİK\p"
	.string "   {BIG_MULT_X}: NORMAL$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: HAYALET, KARA\p"
	.string "   {TRIANGLE}: ZEHİR, BÖCEK\p"
	.string "   {BIG_MULT_X}: NORMAL, DÖVÜŞ$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, YER, UÇUŞ, EJDER\p"
	.string "   {TRIANGLE}: ATEŞ, SU, BUZ, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, DÖVÜŞ, KAYA, ÇELİK\p"
	.string "   {TRIANGLE}: BUZ$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, ELEKTRİK, ZEHİR, KAYA,\n"
	.string "       ÇELİK\p"
	.string "   {TRIANGLE}: ÇİMEN, BÖCEK\n"
	.string "   {BIG_MULT_X}: UÇUŞ$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, ÇİMEN, BUZ\p"
	.string "   {TRIANGLE}: ZEHİR, KAYA\p"
	.string "   {BIG_MULT_X}: ELEKTRİK$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, UÇUŞ\p"
	.string "   {TRIANGLE}: ELEKTRİK, ÇİMEN, EJDER\p"
	.string "   {BIG_MULT_X}: YER$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: YER\p"
	.string "   {TRIANGLE}: ELEKTRİK, UÇUŞ, ÇELİK$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN\p"
	.string "   {TRIANGLE}: ZEHİR, YER, KAYA, HAYALET\p"
	.string "   {BIG_MULT_X}: ÇELİK$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: YER, PSİŞİK\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, ZEHİR, BÖCEK$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: EJDER\p"
	.string "   {TRIANGLE}: ÇELİK$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: BUZ, EJDER\p"
	.string "   {TRIANGLE}: ATEŞ, SU, ELEKTRİK, ÇİMEN$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {TRIANGLE}: KAYA, ÇELİK\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: DÖVÜŞ\p"
	.string "   {BIG_MULT_X}: HAYALET$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: BUZ, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, SU, ELEKTRİK, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, DÖVÜŞ, YER\n"
	.string "   {TRIANGLE}: NORMAL, ÇİMEN, BUZ, UÇUŞ,\l"
	.string "       PSİŞİK, BÖCEK, KAYA, HAYALET,\l"
	.string "       EJDER, KARA, ÇELİK\l"
	.string "   {BIG_MULT_X}: ZEHİR$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, DÖVÜŞ, BÖCEK\p"
	.string "   {TRIANGLE}: ELEKTRİK, KAYA, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ELEKTRİK, BUZ, KAYA\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, BÖCEK\p"
	.string "   {BIG_MULT_X}: YER$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, BUZ, BÖCEK, ÇELİK\p"
	.string "   {TRIANGLE}: ATEŞ, SU, KAYA, EJDER$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: SU, YER, KAYA\p"
	.string "   {TRIANGLE}: ATEŞ, ÇİMEN, BUZ, BÖCEK, ÇELİK$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, YER, KAYA\p"
	.string "   {TRIANGLE}: SU, ÇİMEN, EJDER$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ELEKTRİK, ÇİMEN\p"
	.string "   {TRIANGLE}: ATEŞ, SU, BUZ, ÇELİK$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Rakip POKéMON'a etkisi:\p"
	.string "   {CIRCLE_DOT}: ÇİMEN, PSİŞİK, KARA\p"
	.string "   {TRIANGLE}: ATEŞ, DÖVÜŞ, ZEHİR,\n"
	.string "       UÇUŞ, HAYALET, ÇELİK$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Düşman hamlesinin kendi POKéMON'una\p"
	.string "etkisi:\p"
	.string "   {CIRCLE_DOT}: ATEŞ, UÇUŞ, KAYA\p"
	.string "   {TRIANGLE}: ÇİMEN, DÖVÜŞ, YER$"

