Trade_Text_LookingForMonWannaTradeForMon::
  .string "Bir {STR_VAR_1} arıyorum!\pBenim {STR_VAR_2}'m ile takas etmek\nister misin?$"

Trade_Text_AwwOhWell::
  .string "Awww! Ah, şey…$"

Trade_Text_WhatThatsNoMon::
  .string "Ne? Bu {STR_VAR_1} değil!$"

Trade_Text_HeyThanks::
  .string "Hey, teşekkürler!$"

Trade_Text_IsntMyOldMonGreat::
  .string "Eski {STR_VAR_2}'m harika değil mi?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
  .string "Merhabalar! Elinizde bir {STR_VAR_1}\nvar mı?\pBenim {STR_VAR_2}'m için takas\nyapmayı kabul eder misiniz?$"

Trade_Text_WellIfYouDontWantTo::
  .string "Eğer istemiyorsan zorlayamam.$"

Trade_Text_ThisIsntMon::
  .string "Hmmm? Bu bir {STR_VAR_1} değil.\pBir tane alırsan beni düşün.$"

Trade_Text_Thanks::
  .string "Teşekkürler!$"

Trade_Text_HasTradedMonGrownStronger::
  .string "Size takas ettiğim {STR_VAR_2} daha da\ngüçlendi mi?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
  .string "Merhaba! Elinizde {STR_VAR_1} var mı?\pBenim {STR_VAR_2} ile takas etmek\nister misiniz?$"

Trade_Text_ThatsTooBad::
  .string "Bu çok kötü.$"

Trade_Text_ThisIsNoMon::
  .string "…Bu {STR_VAR_1} değil.\pEğer bir tane bulursan, benimle takas\net.$"

Trade_Text_ThanksYoureAPal::
  .string "Teşekkürler, sen bir dostsun!$"

Trade_Text_HowIsMyOldMon::
  .string "Eski {STR_VAR_2}'m nasıl? Benim\n{STR_VAR_1}'im harika gidiyor!$"

