gOtherText_NewName::
    .string "YENİ İSİM$"

gNameChoice_Green::
    .string "GREEN$"

gNameChoice_Red::
    .string "RED$"

gNameChoice_Leaf::
    .string "LEAF$"

gNameChoice_Fire::
    .string "FIRE$"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string "KAZ$"

gNameChoice_Toru::
    .string "TORU$"

gNameChoice_Ash::
    .string "ASH$"

gNameChoice_Kene::
    .string "KENE$"

gNameChoice_Geki::
    .string "GEKI$"

gNameChoice_Jak::
    .string "JAK$"

gNameChoice_Janne::
    .string "JANNE$"

gNameChoice_Jonn::
    .string "JONN$"

gNameChoice_Kamon::
    .string "KAMON$"

gNameChoice_Karl::
    .string "KARL$"

gNameChoice_Taylor::
    .string "TAYLOR$"

gNameChoice_Oscar::
    .string "OSCAR$"

gNameChoice_Hiro::
    .string "HIRO$"

gNameChoice_Max::
    .string "MAX$"

gNameChoice_Jon::
    .string "JON$"

gNameChoice_Ralph::
    .string "RALPH$"

gNameChoice_Kay::
    .string "KAY$"

gNameChoice_Tosh::
    .string "TOSH$"

gNameChoice_Roak::
    .string "ROAK$"

gNameChoice_Omi::
    .string "OMI$"

gNameChoice_Jodi::
    .string "JODI$"

gNameChoice_Amanda::
    .string "AMANDA$"

gNameChoice_Hillary::
    .string "HILLARY$"

gNameChoice_Makey::
    .string "MAKEY$"

gNameChoice_Michi::
    .string "MICHI$"

gNameChoice_Paula::
    .string "PAULA$"

gNameChoice_June::
    .string "JUNE$"

gNameChoice_Cassie::
    .string "CASSIE$"

gNameChoice_Rey::
    .string "REY$"

gNameChoice_Seda::
    .string "SEDA$"

gNameChoice_Kiko::
    .string "KIKO$"

gNameChoice_Mina::
    .string "MINA$"

gNameChoice_Norie::
    .string "NORIE$"

gNameChoice_Sai::
    .string "SAI$"

gNameChoice_Momo::
    .string "MOMO$"

gNameChoice_Suzi::
    .string "SUZI$"

gControlsGuide_Text_Intro::
    .string "Emülatör ayarlarından klavye-buton\n"
    .string "eşleştirmelerini yapmanızı öneririz.$"

gControlsGuide_Text_DPad::
    .string "Karakteri yönlendirir.\n"
    .string "Ayrıca farklı seçenekler arasında\n"
    .string "seçim yapmaya yarar.$"

gControlsGuide_Text_AButton::
    .string "Seçeneği onaylamaya ve\n"
    .string "objeleri incelemeye yarar.$"

gControlsGuide_Text_BButton::
    .string "Seçeneği iptal etmeye ve\n"
    .string "çıkmaya yarar.$"

gControlsGuide_Text_StartButton::
    .string "Bu butona basarak menüyü\n"
    .string "açabilirsiniz.$"

gControlsGuide_Text_SelectButton::
    .string "Çantadaki atanmış bir eşyayı\n"
    .string "kolayca kullanmaya yarar.$"

gControlsGuide_Text_LRButtons::
    .string "Eğer oyun sırasında yardıma\n"
    .string "ihtiyacınız olursa L veya R\n"
    .string "butonuna basabilirsiniz.$"

gOakSpeech_Text_AskPlayerGender::
    .string "O hâlde söyle bana. Erkek misin?\n"
    .string "Yoksa kız mı?$"

gPikachuIntro_Text_Page1::
    .string "Pokémon AteşKızılı ve YaprakYeşili\n"
    .string "Çeviri Yönetmeni: Gökhan Perçem\n"
    .string "Yardımcı Çevirmen: Emirhan Yılmaz\n"
    .string "\n"
    .string "Çeviriden memnun kaldıysanız veya\n"
    .string "bir sorunla karşılaştıysanız\n"
    .string "Discord kanalımıza uğrayabilirsiniz.\n"
    .string "Link: discord.gg/aHJMKXkafz$"

gPikachuIntro_Text_Page2::
    .string "Girmek üzere olduğun dünyada\n"
    .string "kahraman olarak büyük bir\n"
    .string "macera seni bekliyor.\n"
    .string "\n"
    .string "İnsanlarla konuş ve her yerde\n"
    .string "etrafını kolaçan et.\n"
    .string "Her kaynaktan bilgi ve ipucu topla.$"

gPikachuIntro_Text_Page3::
    .string "Maceran boyunca her türlü insanla\n"
    .string "etkileşime girmeni ve kahramanını\n"
    .string "geliştirmeni umuyoruz.\n"
    .string "Bu bizim en büyük hedefimiz.\n"
    .string "\n"
    .string "A butonuna bas ve maceran\n"
    .string "başlasın!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Merhaba!\n"
    .string "Tanıştığıma memnun oldum!\p"
    .string "POKéMON dünyasına hoş geldin!\p"
    .string "Benim adım OAK.\p"
    .string "İnsanlar genelde bana POKéMON\n"
    .string "PROFESÖRÜ demeyi tercih ederler.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Bu dünya…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…dört bir yanı POKéMON adı verilen\n"
    .string "canlılarla kuşatılmıştır.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Bazı insanlara göre POKéMON'lar\n"
    .string "evcil hayvanlardır, bazıları\lda POKéMON'ları savaştırır.\p"
    .string "Ben ise…\p"
    .string "POKéMON'ları uzmanlık alanım\nolarak görüyorum.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Her şeyden önce, bana biraz\n"
    .string "kendinden bahset.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Hadi isminle başlayalım.\n"
    .string "İsmin nedir?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Pekâlâ…\n"
    .string "Demek adın {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "Bu benim torunum.\p"
    .string "İkiniz bebekliğinizden beri\n"
    .string "birbirinize rakipsiniz.\p"
    .string "…Ee, adı neydi ki onun?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Rakibinin adı, neydi ki?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Ee, {RIVAL}, değil mi?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Doğru! Hatırladım şimdi!\n"
    .string "İsmi {RIVAL} idi!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Kendi POKéMON efsanen başlamak\n"
    .string "üzere!\p"
    .string "Rüyalar ve maceralarla dolu\n"
    .string "POKéMON dünyası seni bekliyor!\lHaydi başlayalım!$"
