Text_ObtainedTheX::
  .string "{STR_VAR_2} alındı!$"

Text_BagIsFull::
  .string "Çanta dolu...$"

Text_PutItemAway::
  .string "{PLAYER}, {STR_VAR_2} eşyasını\n{STR_VAR_3} cebine yerleştirdi.$"

Text_FoundOneItem::
  .string "{PLAYER}, bir {STR_VAR_2} buldu!$"

Text_TooBadBagFull::
  .string "Olamaz!\nÇANTA dolu...$"

Text_FoundXCoins::
  .string "{PLAYER}, {STR_VAR_1} {STR_VAR_2}\nbuldu!$"

Text_PutCoinsAwayInCoinCase::
  .string "{PLAYER}, jetonları JETON KASASINA\nkoydu.$"

Text_CoinCaseIsFull::
  .string "Olamaz!\nJETON KASASI dolu.$"

Text_NothingToPutThemIn::
  .string "Çok kötü!\nBunu koyacak yer yok...$"

Text_FoundXItems::
  .string "{PLAYER}, {STR_VAR_1} adet\n{STR_VAR_2} buldu!$"

Text_ObtainedTheDecor::
  .string "{STR_VAR_2} alındı!$"

Text_NoRoomForAnotherDecor::
  .string "Olamaz!\n{STR_VAR_2} için yer kalmadı...$"

Text_DecorTransferredToPC::
  .string "{STR_VAR_2} bilgisayara aktarıldı.$"

