Text_BootedUpPC::
	.string "{PLAYER} bilgisayarı açtı.$"

Text_AccessWhichPC::
	.string "Hangi bilgisayara erişmek istiyorsun?$"

Text_AccessedSomeonesPC::
	.string "Birinin bilgisayarına erişildi.$"

Text_OpenedPkmnStorage::
	.string "POKéMON Depolama Sistemi açıldı.$"

Text_AccessedPlayersPC::
	.string "{PLAYER}'ın bilgisayarına erişildi.$"

Text_AccessedBillsPC::
	.string "BILL'in bilgisayarına erişildi.$"
