Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} transfer edildi\n"
    .string "Birinin bilgisayarına.\p"
    .string "{STR_VAR_1} KUTUSU'na\n"
    .string "yerleştirildi.$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} transfer edildi\n"
    .string "BILL'in bilgisayarına.\p"
    .string "{STR_VAR_1} KUTUSU'na\n"
    .string "yerleştirildi.$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "Birinin bilgisayarındaki\n"
    .string "{STR_VAR_3} KUTUSU doluydu.\p"
    .string "{STR_VAR_2} transfer edildi\n"
    .string "{STR_VAR_1} KUTUSU'na.$"

Text_MonSentToBoxBillsBoxFull::
    .string "BILL'in bilgisayarındaki\n"
    .string "{STR_VAR_3} KUTUSU doluydu.\p"
    .string "{STR_VAR_2} transfer edildi\n"
    .string "{STR_VAR_1} KUTUSU'na.$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER}, {STR_VAR_1}\n"
    .string "aldı!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "POKéMON için daha fazla yer yok!\p"
    .string "POKéMON KUTULARI dolu ve\n"
    .string "daha fazlasını kabul edemez!$"
