Pokedude_Text_SpeedierBattlerGoesFirst::
  .string "POKé DUDE: Savaşçılardan daha hızlı\nolan ilk saldırıyı yapar.$"

Pokedude_Text_MyRattataFasterThanPidgey::
  .string "Görünüşe göre RATTATA'm PIDGEY'den\ndaha hızlıymış.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
  .string "Savaşçılar sırayla saldırır ve\nbirbirlerinin HP'sini azaltır.$"

Pokedude_Text_MyRattataWonGetsEXP::
  .string "RATTATA'm düşmanın HP'sini sıfıra\nindirdi, yani kazandı!\pSavaşa katılan POKéMON'lar EXP. Puanı\nkazanır.\pBir POKéMON yeterince EXP. Puanı\ntopladığında, seviye atlar.\pSeviye atlamak POKéMON'unuzu\neskisinden daha güçlü yapar.$"

Pokedude_Text_UhOhRattataPoisoned::
  .string "POKé DUDE: Uh-oh... RATTATA'm\nzehirlenmiş...\pEğer bir POKéMON zehirlenirse, sürekli\nolarak HP kaybeder.$"

Pokedude_Text_HealStatusRightAway::
  .string "Bir POKéMON bir durum sorunu\ngeliştirirse, onu hemen iyileştirin.$"

Pokedude_Text_UsingItemTakesTurn::
  .string "Yine de bir POKéMON üzerinde bir eşya\nkullanmak bir tur harcar.\pŞimdi sıra rakipte!$"

Pokedude_Text_YayWeManagedToWin::
  .string "Yaşasın! Kazanmayı başardık!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
  .string "POKé DUDE: BUBBLE hareketi SU tipi bir\nsaldırıdır.\pHedeflenen ODDISH, ÇİM/POİSON tipi bir\nPOKéMON'dur.\pSU tipi saldırı ÇİM tipi POKéMON\ntarafından emilir...\pSonuç olarak, hareket çok etkili olmaz\nve normal hasarın yalnızca yarısını\lverir.$"

Pokedude_Text_GrassEffectiveAgainstWater::
  .string "Uh-oh, bu iyi değil!\pAz önce gördüğün ABSORB saldırısı ÇİM\ntipi bir harekettir.\pPOLIWAG ise SU tipi bir POKéMON.\pYani, ABSORB süper etkili hale gelir ve\nhasarı iki katına çıkarır.$"

Pokedude_Text_LetsTryShiftingMons::
  .string "Bu eşleşmede kazanmak kolay\nolmayacak.\pHadi POKéMON'u kaydırmayı deneyelim!$"

Pokedude_Text_ShiftingUsesTurn::
  .string "POKéMON'u içeri ve dışarı kaydırmak bir\ntur harcar.\pŞimdi sıra rakipte.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
  .string "BUTTERFREE bir BUG/SİNEK tipi\nPOKéMON'dur.\pBu POKéMON'a karşı, ÇİM tipi bir\nsaldırı...\p...BUG tipi bir POKéMON'a normalin\nsadece yarısı kadar hasar verir...\p...Ayrıca, bir UÇAN tip POKéMON'a\nverilen hasarın yalnızca yarısına neden\lolur.\pBu nedenle, bir BÖCEK/UÇAN POKéMON\nolan BUTTERFREE, normal hasarın\lyalnızca dörtte birini alır.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
  .string "ODDISH, ÇİM/POZON tipi bir\nPOKéMON'dur.\pUÇAN veya PSİKANATİK tipi bir saldırı\nona karşı çok etkilidir.\pBu tür saldırılardan biri normalin iki\nkatı hasar verir.\pTamam, işte başlıyoruz!$"

Pokedude_Text_YeahWeWon::
  .string "İşte bu! Biz kazandık!$"

Pokedude_Text_WeakenMonBeforeCatching::
  .string "POKé DUDE: Bir POKéMON yakalamaya\nçalışırken, hemen POKé TOPLARI\latmayın.\pİlk olarak, HP'sini azaltarak onu\nzayıflatmanız gerekir.$"

Pokedude_Text_BestIfTargetStatused::
  .string "Tamam, bu yeterince iyi olmalı.\pAncak, eğer mümkünse, hedefin bir durum\nsorunu olması en iyisi olacaktır.\pÖrneğin, uyuyor ya da felçli olsaydı\nyakalamak daha kolay olurdu.$"

Pokedude_Text_CantDoubleUpOnStatus::
  .string "Bu, POKéMON'u yakalamayı çok daha\nkolay hale getirecek!\pAh, evet. Bir POKéMON'u felç ederseniz,\nfelcin üstüne uykuya dalmasını\lsağlayamazsınız.\pBaşka bir deyişle, durum sorunlarını\nikiye katlayamazsınız, tamam mı?$"

Pokedude_Text_LetMeThrowBall::
  .string "Tamam! Poke topumu atayım!$"

Pokedude_Text_PickBestKindOfBall::
  .string "Bir POKé TOPU atmadan önce,\nPOKéMON'un durumunu ve türünü göz\lönünde bulundurun ve en iyi çalışacak\lTOP türünü seçin.$"

