Text_MayIHelpYou::
  .string "Merhaba! Size yardımcı olabilir miyim?$"

Text_FillOutQuestionnaire::
  .string "Bir anket var. Doldurmak ister misiniz?$"

Text_QuestionnaireThankYou::
  .string "Anketimizi doldurmaya zaman\nayırdığınız için teşekkür ederiz.\pGörüşleriniz gelecekte referans olarak\nkullanılacaktır.$"

Text_YouKnowThoseWords::
  .string "Ah, merhaba! Bu kelimeleri biliyor\nmusunuz?\pBu, GİZEMLİ HEDİYE hakkında bilgi\nsahibi olmanız gerektiği anlamına\lgeliyor.\pŞu andan itibaren, GİZEMLİ HEDİYELER\nalmalısınız!$"

Text_YouCanAccessMysteryGift::
  .string "Oyununuzu kaydettiğinizde, GİZEMLİ\nHEDİYEYE erişebilirsiniz.$"

Text_ThankYouForAccessingMysteryGift::
  .string "GİZEMLİ HEDİYE Sistemine eriştiğiniz\niçin teşekkür ederiz.$"

