Pokedude_Text_SpeedierBattlerGoesFirst::
  .string "POKé ADAM: Savaşçılardan daha hızlı\n"
  .string "olan ilk saldırıyı yapar.$"

Pokedude_Text_MyRattataFasterThanPidgey::
  .string "Görünüşe göre RATTATA'm PIDGEY'den\n"
  .string "daha hızlıymış.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
  .string "Savaşçılar sırayla saldırır ve\n"
  .string "birbirlerinin HP'sini azaltır.$"

Pokedude_Text_MyRattataWonGetsEXP::
  .string "RATTATA'm düşmanın HP'sini sıfıra\n"
  .string "indirdi, yani kazandı!\p"
  .string "Savaşa katılan POKéMON'lar EXP. Puanı\n"
  .string "kazanır.\p"
  .string "Bir POKéMON yeterince EXP. Puanı\n"
  .string "topladığında, seviye atlar.\p"
  .string "Seviye atlamak POKéMON'unuzu\n"
  .string "eskisinden daha güçlü yapar.$"

Pokedude_Text_UhOhRattataPoisoned::
  .string "POKé ADAM: Uh-oh… RATTATA'm\n"
  .string "zehirlenmiş…\p"
  .string "Eğer bir POKéMON zehirlenirse, sürekli\n"
  .string "olarak HP kaybeder.$"

Pokedude_Text_HealStatusRightAway::
  .string "Bir POKéMON bir durum sorunu\n"
  .string "geliştirirse, onu hemen iyileştirin.$"

Pokedude_Text_UsingItemTakesTurn::
  .string "Yine de bir POKéMON üzerinde bir eşya\n"
  .string "kullanmak bir tur harcar.\p"
  .string "Şimdi sıra rakipte!$"

Pokedude_Text_YayWeManagedToWin::
  .string "Yaşasın! Kazanmayı başardık!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
  .string "POKé ADAM: BALONCUK hareketi SU tipi\n"
  .string "bir saldırıdır.\p"
  .string "Hedeflenen ODDISH, ÇİMEN/ZEHİR\n"
  .string "tipi bir POKéMON'dur.\p"
  .string "SU tipi saldırı ÇİMEN tipi POKéMON\n"
  .string "tarafından emilir…\p"
  .string "Sonuç olarak, hareket çok etkili olmaz\n"
  .string "ve normal hasarın yalnızca yarısını\l"
  .string "verir.$"

Pokedude_Text_GrassEffectiveAgainstWater::
  .string "Uh-oh, bu iyi değil!\p"
  .string "Az önce gördüğün ABSORBE ET\n"
  .string "saldırısı ÇİMEN\l"
  .string "tipi bir harekettir.\p"
  .string "POLIWAG ise SU tipi bir POKéMON.\p"
  .string "Yani, ABSORBE ET süper etkili\n"
  .string "hale gelir ve hasarı\l"
  .string "iki katına çıkarır.$"

Pokedude_Text_LetsTryShiftingMons::
  .string "Bu eşleşmede kazanmak kolay\n"
  .string "olmayacak.\p"
  .string "Hadi POKéMON'u kaydırmayı deneyelim!$"

Pokedude_Text_ShiftingUsesTurn::
  .string "POKéMON'u içeri ve dışarı kaydırmak bir\n"
  .string "tur harcar.\p"
  .string "Şimdi sıra rakipte.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
  .string "BUTTERFREE bir BÖCEK/UÇUŞ tipi\n"
  .string "POKéMON'dur.\p"
  .string "Bu POKéMON'a karşı, ÇİMEN tipi bir\n"
  .string "saldırı…\p"
  .string "…BÖCEK tipi bir POKéMON'a normalin\n"
  .string "sadece yarısı kadar hasar verir…\p"
  .string "…Ayrıca, bir UÇUŞ tip POKéMON'a\n"
  .string "verilen hasarın yalnızca yarısına neden\l"
  .string "olur.\p"
  .string "Bu nedenle, bir BÖCEK/UÇUŞ POKéMON\n"
  .string "olan BUTTERFREE, normal hasarın\l"
  .string "yalnızca dörtte birini alır.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
  .string "ODDISH, ÇİMEN/ZEHİR tipi bir\n"
  .string "POKéMON'dur.\p"
  .string "UÇUŞ veya PSİŞİK tipi bir saldırı\n"
  .string "ona karşı çok etkilidir.\p"
  .string "Bu tür saldırılardan biri normalin iki\n"
  .string "katı hasar verir.\p"
  .string "Tamam, işte başlıyoruz!$"

Pokedude_Text_YeahWeWon::
  .string "İşte bu! Biz kazandık!$"

Pokedude_Text_WeakenMonBeforeCatching::
  .string "POKé ADAM: Bir POKéMON yakalamaya\n"
  .string "çalışırken, hemen POKé TOPU\l"
  .string "atmayın.\p"
  .string "İlk olarak, HP'sini azaltarak onu\n"
  .string "zayıflatmanız gerekir.$"

Pokedude_Text_BestIfTargetStatused::
  .string "Tamam, bu yeterince iyi olmalı.\p"
  .string "Ancak, eğer mümkünse, hedefin bir durum\n"
  .string "sorunu olması en iyisi olacaktır.\p"
  .string "Örneğin, uyuyor ya da felçli olsaydı\n"
  .string "yakalamak daha kolay olurdu.$"

Pokedude_Text_CantDoubleUpOnStatus::
  .string "Bu, POKéMON'u yakalamayı çok daha\n"
  .string "kolay hale getirecek!\p"
  .string "Ah, evet. Bir POKéMON'u felç ederseniz,\n"
  .string "elcin üstüne uykuya dalmasını\l"
  .string "sağlayamazsınız.\p"
  .string "Başka bir deyişle, durum sorunlarını\n"
  .string "ikiye katlayamazsınız, tamam mı?$"

Pokedude_Text_LetMeThrowBall::
  .string "Tamam! POKé TOPU'mu atayım!$"

Pokedude_Text_PickBestKindOfBall::
  .string "Bir POKé TOPU atmadan önce,\n"
  .string "POKéMON'un durumunu ve türünü göz\l"
  .string "önünde bulundurun ve en iyi çalışacak\l"
  .string "TOP türünü seçin.$"

