PokedexRating_Text_HowIsPokedexComingAlong::
  .string "OAK: Seni görmek güzel! POKéDEX'in\nnasıl gidiyor?\pDur, bir bakayım.$"

PokedexRating_Text_SeenXOwnedY::
	.string "POKéDEX'inde toplam ilerlemen\n"
	.string "şu şekilde:\p"
	.string "{STR_VAR_1} POKéMON görmüşsün ve\n"
	.string "{STR_VAR_2} POKéMON'a sahipsin.\p"
	.string "{FONT_NORMAL}PROF. OAK'ın değerlendirmesi:$"

PokedexRating_Text_LessThan10::
  .string "Hâlâ yapacak çok şeyin var.\pGördüğün her çimenliğe gir ve\nPOKéMON ara!$"

PokedexRating_Text_LessThan20::
  .string "Görünüşe göre doğru yolda\nilerliyorsun!\pYardımcılarımdan birine HM FLAŞ\nverdim. Gidip onu bulmaya çalış!$"

PokedexRating_Text_LessThan30::
  .string "POKéDEX'in hala biraz daha\ngelişebilir!\pFarklı POKéMON türleri yakalamaya\nçalış!$"

PokedexRating_Text_LessThan40::
  .string "Güzel, belli ki çok çabalıyorsun!\pYardımcılarımdan birine bir EŞYA\nBULUCU verdim.\lOnu arayıp bulmalısın!$"

PokedexRating_Text_LessThan50::
  .string "POKéDEX'in oldukça iyi gidiyor!\pYardımcılarımdan birine bir\nPARA TILSIMI verdim.\lOnu arayıp bulmalısın!$"

PokedexRating_Text_LessThan60::
  .string "Sonunda 50 türe ulaşmışsın!\pYardımcılarımdan birine EXP\nPAYLAŞ. eşyası verdim.\lOnu arayıp bulmalısın!$"

PokedexRating_Text_LessThan70::
  .string "Hoho!\nBu artık oldukça hacimli bir\lPOKéDEX'e dönüşüyor!$"

PokedexRating_Text_LessThan80::
  .string "Çok iyi!\pBence balığa çıkarak daha fazla\nPOKéMON toplayabilirsin!$"

PokedexRating_Text_LessThan90::
  .string "Harika! Dur tahmin edeyim…\nKoleksiyonculuğu seviyorsun, değil\lmi?$"

PokedexRating_Text_LessThan100::
  .string "Etkilendim!\nBunu yapmak zor olmalı!$"

PokedexRating_Text_LessThan110::
  .string "Sonunda 100 türe ulaştın!\nBu kadar iyi olduğuna\linanamıyorum!$"

PokedexRating_Text_LessThan120::
  .string "POKéMON'un evrimleşmiş formlarına\nbile sahipsin! Süper!$"

PokedexRating_Text_LessThan130::
  .string "Mükemmel! Biraz daha bulmak istiyorsan\narkadaşlarınla takas yapabilirsin!$"

PokedexRating_Text_LessThan140::
  .string "Olağanüstü! Bu işte gerçek bir\nprofesyonel olmuşsun!$"

PokedexRating_Text_LessThan150::
  .string "Söyleyecek bir şeyim kalmadı!\nArtık POKéMON PROFESÖRÜ sensin!$"

PokedexRating_Text_Complete::
  .string "POKéDEX'in tamamen tamamlandı!\nTebrikler!!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "ULUSAL POKéDEX bilgilerin:\p"
	.string "{STR_VAR_1} POKéMON gördün ve\n"
	.string "{STR_VAR_2} POKéMON'a sahipsin.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "ULUSAL POKéDEX'ini doldurmanı\n"
	.string "dört gözle bekliyorum!$"

PokedexRating_Text_YouveCompletedDex::
  .string "Sonunda.\pSonunda POKéDEX'i tamamladın!\pBu muhteşem! Gerçekten, bu harika bir\nbaşarı!$"

PokedexRating_Text_Wroooaaarrr::
  .string "Vroooooooaaaaaaaa!$"

PokedexRating_Text_HaHa::
  .string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
  .string "Teşekkürler, {PLAYER}!\nTüm kalbimle teşekkür ederim!\lHayallerimi gerçeğe dönüştürdün!$"

PokedexRating_Text_LoveSeeingYourPokedex::
  .string "Hoş geldin!\pSöylesene, POKéDEX'in nasıl gidiyor?\pVahaha!\pAslında nasıl olduğunu biliyorum ama\nyine de görmeyi seviyorum!\pBakalım…$"

