Text_MayIHelpYou::
  .string "Merhaba!\nSize yardımcı olabilir miyim?$"

Text_FillOutQuestionnaire::
  .string "Bir anket var.\nDoldurmak ister misiniz?$"

Text_QuestionnaireThankYou::
  .string "Anketimizi doldurmaya zaman\nayırdığınız için teşekkür ederiz.\pGörüşleriniz gelecekte referans olarak\nkullanılacaktır.$"

Text_YouKnowThoseWords::
  .string "Ah, merhaba!\nBu kelimeleri biliyorsunuz demek.\pBu, GİZEMLİ HEDİYE hakkında bilgi\nsahibi olduğunuz anlamına geliyor.\pŞu andan itibaren, GİZEMLİ HEDİYELER\nalabilirsiniz!$"

Text_YouCanAccessMysteryGift::
  .string "Oyununuzu kaydettiğinizde, GİZEMLİ\nHEDİYEYE erişebilirsiniz.$"

Text_ThankYouForAccessingMysteryGift::
  .string "GİZEMLİ HEDİYE Sistemine eriştiğiniz\niçin teşekkür ederiz.$"

