Pokedude_Text_SpeedierBattlerGoesFirst::
  .string "POKé ADAM: Savaşçılardan daha hızlı\n"
  .string "olan ilk saldırıyı yapar.$"

Pokedude_Text_MyRattataFasterThanPidgey::
  .string "Görünüşe göre RATTATA'm PIDGEY'den\n"
  .string "daha hızlıymış.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
  .string "Savaşçılar sırayla saldırır ve\nbirbirlerinin canını azaltır.$"

Pokedude_Text_MyRattataWonGetsEXP::
  .string "RATTATA'm düşmanın canını sıfıra\nindirdi, yani kazandı!\pSavaşa katılan POKéMON'lar EXP. Puanı\nkazanır.\pBir POKéMON yeterince EXP. Puanı\ntopladığında, seviye atlar.\pSeviye atlamak POKéMON'unuzu\neskisinden daha güçlü yapar.$"

Pokedude_Text_UhOhRattataPoisoned::
  .string "POKé DUDE: Eyvah... RATTATA'm\nzehirlenmiş...\pEğer bir POKéMON zehirlenirse, sürekli\nolarak can kaybeder.$"

Pokedude_Text_HealStatusRightAway::
  .string "POKéMON'ların bir durum sorunu\noluşursa, onu hemen iyileştirin.$"

Pokedude_Text_UsingItemTakesTurn::
  .string "POKéMON üzerinde bir eşya kullanmak\nbir tur harcar.\pŞimdi sıra rakipte!$"

Pokedude_Text_YayWeManagedToWin::
  .string "Yaşasın!\nKazanmayı başardık!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
  .string "POKé ADAM: BALONCUK saldırısı SU tipi bir\nsaldırıdır.\pHedeflenen ODDISH, ÇİM/ZEHİR tipi bir\nPOKéMON'dur.\pSU tipi saldırı ÇİM tipi POKéMON\ntarafından emilir...\pSonuç olarak, saldırı çok etkili olmaz\nve normal hasarın yalnızca yarısını\lverir.$"

Pokedude_Text_GrassEffectiveAgainstWater::
  .string "Olamaz, bu hiç iyi değil!\pAz önce gördüğün EMİŞ saldırısı,\nÇİM tipi bir harekettir.\pPOLIWAG ise SU tipi POKéMON'dur.\pYani, EMİŞ, süper etkili hale gelir\nve hasarı iki katına çıkarır.$"

Pokedude_Text_LetsTryShiftingMons::
  .string "Bu eşleşmede kazanmak kolay\nolmayacak.\pHadi POKéMON'u değişmeyi deneyelim!$"

Pokedude_Text_ShiftingUsesTurn::
  .string "Savaştaki POKéMON'u değişmek\nbir tur harcar.\pŞimdi sıra rakipte.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
  .string "BUTTERFREE, BÖCEK/UÇUŞ tipi bir\nPOKéMON'dur.\pBu POKéMON'a karşı, ÇİM tipi bir\nsaldırı...\p...BÖCEK tipi bir POKéMON'a normalin\nsadece yarısı kadar hasar verir...\p...Ayrıca, bir UÇAN tip POKéMON'a\nverilen hasarın yalnızca yarısına neden\lolur.\pBu nedenle, bir BÖCEK/UÇAN POKéMON\nolan BUTTERFREE, normal hasarın\lyalnızca dörtte birini alır.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
  .string "ODDISH, ÇİM/ZEHİR tipi bir\nPOKéMON'dur.\pUÇUŞ veya PSİŞİK tipi bir saldırı\nona karşı çok etkilidir.\pBu tür saldırılardan biri normalin\niki katı hasar verir.\pTamam, işte başlıyoruz!$"

Pokedude_Text_YeahWeWon::
  .string "İşte bu!\nBiz kazandık!$"

Pokedude_Text_WeakenMonBeforeCatching::
  .string "POKé ADAM: Bir POKéMON yakalamaya\nçalışırken, hemen POKé TOPU\latmayın.\pİlk olarak, canını azaltarak\nonu zayıflatmanız gerekir.$"

Pokedude_Text_BestIfTargetStatused::
  .string "Tamam, bu yeterli olmalı.\pEğer mümkünse, rakibe bir durum\netkisi vermeye çalışabilirsinz.\pBu, onu yakalamayı daha da\nkolaylaştırır.\pÖrneğin, uyuyor olsaydı veya felçli\nolsaydı yakalamak daha kolay\lolurdu.$"

Pokedude_Text_CantDoubleUpOnStatus::
  .string "Bu, POKéMON'u yakalamayı çok\nkolay hale getirecek!\pAh, evet. Bir POKéMON'u felç ederseniz,\nfelcin üstüne uykuya dalmasını\lsağlayamazsınız.\pBaşka bir deyişle, durum sorunlarını\nikiye katlayamazsınız, tamam mı?$"

Pokedude_Text_LetMeThrowBall::
  .string "Tamam!\nPOKé topumu atayım!$"

Pokedude_Text_PickBestKindOfBall::
  .string "Bir POKé TOPU atmadan önce,\n"
  .string "POKéMON'un durumunu ve türünü göz\l"
  .string "önünde bulundurun ve en iyi çalışacak\l"
  .string "TOP türünü seçin.$"

