Text_OnlySkilledTrainersAllowedThrough::
  .string "Sadece gerçekten yetenekli\neğitmenlerin geçmesine izin verilir.\pHenüz {STR_VAR_1}'a sahip\ndeğilsiniz!$"

Text_CantLetYouPass::
  .string "Kural kuraldır.\nGeçmenize izin veremem.$"

Text_OhThatsBadgeGoRightAhead::
  .string "Hey! Bu {STR_VAR_1}!\nDevam edin.$"

Text_OnlyPassWithBadgeDontHaveYet::
  .string "Burayı yalnızca {STR_VAR_1}'ne\nsahipseniz geçebilirsiniz.\pHenüz {STR_VAR_1}'a sahip değilsin.\pPOKéMON LİGİ'ne gitmek için ona sahip\nolmalısın.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "{STR_VAR_1}'ne sahipseniz\n"
	.string "buradan geçebilirsiniz.\p"
	.string "Hey! Bu {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Tamam öyleyse.\n"
	.string "Buyurun lütfen.$"
