SafariZone_Text_WouldYouLikeToExit::
  .string "SAFARİ BÖLGESİ'nden hemen çıkmak\nister misiniz?$"

SafariZone_Text_TimesUp::
  .string "PA: Ding-dong!\pZaman doldu!\pPA: SAFARİ OYUNUNUZ sona erdi!$"

SafariZone_Text_OutOfBalls::
  .string "PA: Ding-dong!\pSAFARİ TOPLARINIZ bitmiş!\pPA: SAFARİ OYUNUNUZ sona erdi!$"

SafariZone_Text_WelcomeToSafariZone::
  .string "サファリゾーンへ ようこそ！\pここでは ホウエンでは なかなか みることの できない ポケモンを\pしぜんの すがたの まま めに することが できます\pまた ポケモントレーナーの ようぼうに おこたえ して\pポケモンを つかまえる ことも できます！\pサファリゾーンを たのしんで いってね！$"

SafariZone_Text_WelcomeFirstTime::
  .string "サファリゾーンへ ようこそ！ サファリゾーンは はじめて ですか？$"

SafariZone_Text_ComeInAndEnjoy::
  .string "サファリゾーンを たのしんで いってね！$"

SafariZone_Text_FirstTimeInfo::
  .string "サファリゾーンでは 30この サファリボールを つかって ポケモンを\nつかまえる ことが できます\pサファリボールを つかいきるか 500ぽ あるくと\pゲームは しゅうりょう です\pサファリゾーンを たのしんで いってね！$"

SafariZone_Text_WouldYouLikeToPlay::
  .string "サファリゾーンへ ようこそ！\p500えんで ポケモン つかまえほうだい！ サファリゲームに さんか\nしますか？$"

SafariZone_Text_PlayAnotherTime::
  .string "そうですか こんど ぜひ さんか してください！$"

SafariZone_Text_NotEnoughMoney::
  .string "おかねが たりませんよ！$"

SafariZone_Text_ThatWillBe500Please::
  .string "それでは 500えん いただきます$"

SafariZone_Text_HereAreYourSafariBalls::
  .string "では サファリボールを どうぞ！$"

SafariZone_Text_Received30SafariBalls::
  .string "{PLAYER}は サファリボールを 30こ うけとった！$"

SafariZone_Text_PleaseEnjoyYourself::
  .string "じかんに なりましたら こちらから おしらせ しますので\pぞんぶんに おたのしみ ください！ では いってらっしゃい！$"

SafariZone_Text_ExcuseMeYourPCBoxIsFull::
  .string "Affedersiniz! Bilgisayar kutunuz dolu.$"

SafariZone_Text_YouNeedPokeblockCase::
  .string "あ！ おきゃくさん ポロックケースを おもちで ないですね？\pサファリゾーンは ポロックを つかうと より おたのしみ\nいただけますので\pぜひ ポロックケースを おもちに なって おこし ください！$"

SafariZone_South_Text_StillHaveTimeExit::
  .string "まだ じかんが のこっていますが サファリゾーンを やめますか？$"

SafariZone_South_Text_EnjoyTheRestOfYourAdventure::
  .string "では ひきつづき おたのしみ ください！$"

SafariZone_South_Text_ExitEarlyThankYouForPlaying::
  .string "わかりました\pそれでは のこりの サファリボールを おあずかり します\pおつかれさまでした また ごりよう ください$"

SafariZone_South_Text_GoodLuck::
  .string "それでは いってらっしゃい！ なにか ありましたら わたしに こえを\nかけて くださいね$"

SafariZone_South_Text_Boy::
  .string "しってた？\pあの しかくい はこに ポロックを おくと ポケモンが あつまって\nくるんだよ！$"

SafariZone_South_Text_Man::
  .string "この さきに いきたい けど じてんしゃ もって くるの わすれた‥‥\pおくに めずらしい ポケモンが いそうな きが するのに！$"

SafariZone_Southwest_Text_Woman::
  .string "ポケモンに ポロックを なげても しらんぷり される ときが あるのよ\pポケモンにも すききらいが あるのかしら？$"

SafariZone_Northwest_Text_Man::
  .string "ぜぇ‥‥ ぜぇ‥‥ やっと ここまで きたけど‥‥\pつかれちゃって ポケモン つかまえる げんきも のこって ないよ‥‥$"

SafariZone_North_Text_Fisherman::
  .string "ホウエンに いない みずポケモンを さがしに きたんだけど‥‥\pみずうみは どこにあるのか きみ しってるかい？$"

SafariZone_North_Text_Man::
  .string "ここで めずらしい ポケモンを たくさん つかまえて ともだちと\nこうかん するんだ！$"

SafariZone_South_Text_Youngster::
  .string "ポロックおきばに おいた ポロックが いつのまにか なくなっていた‥‥\pしらない うちに ポケモンが たべちゃったのかな？$"

Route121_SafariZoneEntrance_Text_TrainerTip::
  .string "サファリゾーンの おとくな じょうほう！\pであった ポケモンに ポロックを なげると にげにくく なります！$"

SafariZone_Southwest_Text_RestHouseSign::
  .string "あるき つかれたら ちょっと ひといき！ ‘みんなの きゅうけいじょ'$"

SafariZone_RestHouse_Text_Youngster::
  .string "おれ ポロック もってないけど ポケモン たくさん つかまえたよ\pちかづいて ボールを なげる だけで けっこう つかまえられる\nもんだよ！$"

SafariZone_RestHouse_Text_PsychicM::
  .string "ポロックを つかうと いつもより ちょっぴり にげにくく なるみたい\pだから にげにくい ポケモンに つかっても あんまり いみが ないかもね$"

SafariZone_RestHouse_Text_FatMan::
  .string "ポロックおきばに ポロック おいて ポケモンを つかまえると\pおなじ ような せいかくの ポケモンが あつまる きが するなあ$"

