gText_WouldYouLikeToSaveTheGame::
  .string "Oyunu kaydetmek ister misiniz?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
  .string "Zaten kayıtlı bir dosya var.\nÜzerine yazılsın mı?$"

gText_SavingDontTurnOffThePower::
  .string "KAYDEDİLİYOR…\nOYUNU KAPATMAYIN.$"

gText_PlayerSavedTheGame::
  .string "{PLAYER} oyunu kaydetti.$"

gText_SaveFailed2::
  .string "セーブに しっぱい しました‥$"

gText_DifferentGameFile::
  .string "UYARI!\pÖnceden kaydedilmiş farklı bir oyun\ndosyası var.\pEğer şimdi kaydederseniz, diğer\ndosyanın macerası, eşyalar ve POKéMON\lda dahil olmak üzere, tamamen\lkaybolacaktır.\pŞimdi kaydetmek ve diğer kayıt\ndosyasının üzerine yazmak istediğinizden\lemin misiniz?$"

