PalletTown_Text_HmmIsThatRight::
  .string "Hmm… Bu doğru mu?$"

PalletTown_Text_OhLookLook::
  .string "Hey! Şuna bir bak!$"

PalletTown_Text_ReadItReadIt::
  .string "Oku lütfen!$"

PalletTown_Text_PressStartToOpenMenu::
  .string "EĞİTMEN İPUÇLARI\pMENÜ'yü açmak için START düğmesine\nbasın!$"

PalletTown_Text_SignsAreUsefulArentThey::
  .string "Tabelalar faydalı, değil mi?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
  .string "Hey, dinle!\pŞu EĞİTMEN İPUÇLARI tabelalarından\nbirinde yazanı ezberledim!$"

PalletTown_Text_PressStartToOpenMenuCopy::
  .string "EĞİTMEN İPUÇLARI!\pMENÜ'yü açmak için START'a basın!$"

