CeladonCity_GameCorner_Text_TryPokemonPrinter::
  .string "Bu bir POKéMON YAZICI!\pPOKéMON'unuzun bir çıktısını EĞİTMEN\nKARTINIZIN arkasına koyabilir.\pFiyatı sadece 50 Yen. Denemek ister\nmisiniz?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
  .string "Yeterince paran yok.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
  .string "Lütfen baskı türünü seçin.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
  .string "Fotoğraf için kocaman bir gülümseme,\nlütfen! Üç… İki… Bir…\pFlaş!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
  .string "POKéMON baskınız hazır! EĞİTMEN\nKARTINIZI kontrol edin.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
  .string "Kıkırdama… Bir sürü çıkartma topladım.\nKeşke onları gösterebilseydim.$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
  .string "Ah, mükemmel! Doğru yere geldiniz!\pBak, bak! Gördün mü? Gördünüz mü?\nBunlar benim çıkartmalarım! Bak ne\lkadar çok var!\pEminim biraz istersin. Eminim\nistiyorsundur!\pBana kendin hakkında harika bir şey\nsöylersen sana bir ÇIKARTMA\lvereceğim.\pNe hakkında övüneceksin?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
  .string "Benim için bir şeyle övün. Sana bir\nçıkartma vereceğim.$"

FourIsland_House2_Text_BragAboutWhatToday::
  .string "Ah, merhaba! İşte palavracı\ngeliyor.\pBugün ne hakkında övüneceksin?$"

FourIsland_House2_Text_WowHoFLowest::
  .string "Vay canına, ŞÖHRET SALONU'na\ngirmişsin.\pBu oldukça iyi, evet! Sana bunlardan\nbir tane vereceğim.$"

FourIsland_House2_Text_WowHoFLow::
  .string "Vay canına, ŞÖHRET SALONU'na sık sık\ngiriyorsunuz!\pBu etkileyici, evet! Sana bunlardan bir\ntane vereceğim.$"

FourIsland_House2_Text_WowHoFHigh::
  .string "Vay be! ŞÖHRET SALONU'na bu kadar\nsık mı giriyorsun? Bu gerçekten\linanılmaz, evet!\pPOKéMON LİGİ'nin sahibisin! Sana\nbunlardan bir tane vereceğim.$"

FourIsland_House2_Text_WowHoFHighest::
  .string "Yok artık! Bu kadar çok kez ŞÖHRET\nSALONU'na mı girdin?\pİnanılmazın da ötesindesin, evet! İşte\nbu, sana bunu vermek zorundayım.$"

FourIsland_House2_Text_HoFStickerApplied::
  .string "EĞİTMEN KARTINA ŞÖHRET SALONU\nETİKETİ yapıştırıldı.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
  .string "Hmm…\pBir dahaki sefere daha iyi bir\nhikayeyle gel, tamam mı?$"

FourIsland_House2_Text_LivingLegendHoF::
  .string "Ah, hayır, hayır yapamam.\pSen yaşayan bir efsanesin. Verecek hiç\nETİKET'im kalmadı.$"

FourIsland_House2_Text_WowEggsLowest::
  .string "Vay canına, POKéMON YUMURTASI mı\nvarmış? Bunu bilmiyordum!\pBu oldukça iyi, evet! Sana bunlardan\nbir tane vereceğim.$"

FourIsland_House2_Text_WowEggsLow::
  .string "O kadar çok yumurta mı yumurtladın?\nOnları gerçekten seviyor olmalısın!\pBu etkileyici, evet! Sana bunlardan bir\ntane vereceğim.$"

FourIsland_House2_Text_WowEggsHigh::
  .string "Vay be! Bir sürü yumurta yumurtladın!\pSen bir YUMURTA kuluçka makinesisin!\nSana bunlardan bir tane vereceğim.$"

FourIsland_House2_Text_WowEggsHighest::
  .string "Ne… O kadar çok YUMURTA mı\nyumurtladın?\pYumurta sevginizin arkasında ne var?\nİnanılmaz ötesi, evet!\pSen çok harikasın, sana söylüyorum.\nİşte bu, sana bunu vermek zorundayım.$"

FourIsland_House2_Text_EggStickerApplied::
  .string "YUMURTA ETİKETİ EĞİTMEN KARTINA\nuygulandı.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
  .string "Hmm…\pBir dahaki sefere daha iyi bir\nhikayeyle gel, tamam mı?$"

FourIsland_House2_Text_LivingLegendEggs::
  .string "Ah, hayır, hayır yapamam.\pSen yaşayan bir efsanesin. Verecek hiç\nSITCKERS'ım kalmadı.$"

FourIsland_House2_Text_WowLinkWinsLowest::
  .string "Vay canına, bağlantı savaşında başarılı\nmı oldunuz?\pOldukça güçlüsün, evet! Sana bunlardan\nbir tane vereceğim.$"

FourIsland_House2_Text_WowLinkWinsLow::
  .string "Arkadaşlarını çok dövüşerek yendin,\ndeğil mi?\pEtkileyici derecede güçlüsün, evet!\nSana bunlardan bir tane vereceğim.$"

FourIsland_House2_Text_WowLinkWinsHigh::
  .string "Oha! Arkadaşlarını korkunç sayıda\nyenmişsin.\pBu yüzden arkadaşlarını mı kaybettin?\nSana bunlardan bir tane vereceğim.$"

FourIsland_House2_Text_WowLinkWinsHighest::
  .string "Vay canına! Akıllara durgunluk verecek\nkadar sık kazanıyorsun!\pNe kadar güçlü olduğunu düşünmek beni\nbayıltıyor.\pSen kabusların malzemesisin! İşte bu,\nsana bunu vermek zorundayım.$"

FourIsland_House2_Text_VictoryStickerApplied::
  .string "ZAFER ETİKETİ, EĞİTMEN KARTI'na\nuygulandı.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
  .string "Hmm…\pBir dahaki sefere daha iyi bir\nhikayeyle gel, tamam mı?$"

FourIsland_House2_Text_LivingLegendLinkWins::
  .string "Ah, hayır, hayır yapamam.\pSen yaşayan bir efsanesin. Verecek hiç\nETİKET'im kalmadı.$"

