VSSeeker_Text_BatteryNotChargedNeedXSteps::
  .string "Akü yeterince şarj edilmemiş.\pPili tamamen şarj etmek için gereken\nadım sayısı:\l{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
  .string "Menzil içinde savaşabilecek hiç eğitmen\nyok.\pVS BULUCU\nkapatıldı.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
  .string "Diğer EĞİTMENLER savaşa hazır\ngörünmüyor.\pDaha sonraya kadar bekleyelim.\n{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
  .string "Hey! Seni VIRIDIAN ORMANI'nda\ngörmüştüm!$"

Route3_Text_BenRematchIntro::
  .string "Merhaba! Şortları severim! Rahat ve\ngiymesi kolay!\pSen de şort giymelisin!$"

Route3_Text_JaniceRematchIntro::
  .string "Affedersiniz! Bana bakıp duruyorsun,\ndeğil mi?$"

Route3_Text_GregRematchIntro::
  .string "Siz bir eğitmensiniz, değil mi? Hemen\nbaşlayalım!$"

Route3_Text_SallyRematchIntro::
  .string "Bana attığın o bakış… Çok ilgimi\nçekiyor!$"

Route3_Text_CalvinRematchIntro::
  .string "Hey! Neyin var senin? Hala şort\ngiymiyorsun!$"

Route3_Text_JamesRematchIntro::
  .string "Yetiştirmeye başladığım POKéMON ile\nseninle savaşacağım.$"

Route3_Text_RobinRematchIntro::
  .string "Eek! Beni ittin mi?$"

Route4_Text_CrissyRematchIntro::
  .string "AY DAĞI'nda her zaman mantar\nPOKéMON'u yakalarım.$"

Route6_Text_RickyRematchIntro::
  .string "Oh! Sen bizi gizlice dinleyen meraklı\nçocuksun!$"

Route6_Text_NancyRematchIntro::
  .string "Affedersiniz! Sana bunun özel bir\nkonuşma olduğunu söylemedim mi?\pDinlememelisin, seni kaba insan!$"

Route6_Text_KeigoRematchIntro::
  .string "BÖCEK POKéMON'u olmayan iyi bir şey\nbulmaya çalışıyorum ama…$"

Route6_Text_JeffRematchIntro::
  .string "Ha? Yine benimle gelmek ister misin?$"

Route6_Text_IsabelleRematchIntro::
  .string "Ben mi? Peki, tamam. Bunu bir kez\noynayacağım.$"

Route6_Text_ElijahRematchIntro::
  .string "Hey, uzun zaman oldu! İyileştin mi?$"

Route8_Text_AidanRematchIntro::
  .string "POKéMON'da iyisiniz ama kimya notunuz\nnasıl?$"

Route8_Text_StanRematchIntro::
  .string "Pekala! Başka bir oyun oynayalım!$"

Route8_Text_GlennRematchIntro::
  .string "Savaşta kazanmak için stratejiye\nihtiyacınız var.\pTavsiyemi dinliyor musun?$"

Route8_Text_PaigeRematchIntro::
  .string "Birçok NIDORAN topladım. Onların\nevrimleşmesini istemiyorum ama.$"

Route8_Text_LeslieRematchIntro::
  .string "Okul eğlenceli ama ben hâlâ\nPOKéMON'un da eğlenceli olduğunu\ldüşünüyorum.$"

Route8_Text_AndreaRematchIntro::
  .string "MEOWTH ve PERSIAN çok tatlılar, miyav,\nmiyav, miyav!$"

Route8_Text_MeganRematchIntro::
  .string "Burada böyle durmak aptalca\ngörünebilir ama hâlâ savaşabilirim.$"

Route8_Text_RichRematchIntro::
  .string "Ben başıboş bir oyun adamıyım! Kazanma\nserisindeyim!$"

Route8_Text_JuliaRematchIntro::
  .string "Sevimli, yuvarlak ve kabarık POKéMON\nnedir?\pZaten biliyorsun, değil mi?$"

Route8_Text_RicardoRematchIntro::
  .string "Motorum hala sorun çıkarıyor, dostum.$"

Route8_Text_JarenRematchIntro::
  .string "Tamam, evlat! Bu sefer merhamet\nbekleme!$"

Route8_Text_EliRematchIntro::
  .string "ELI: İkiz gücümüz daha da iyi oldu!$"

Route8_Text_AnneRematchIntro::
  .string "İkiz gücümüz açıldı!$"

Route9_Text_AliciaRematchIntro::
  .string "Yine mi savaşacağız? Bu sefer, sen\nbenimsin!$"

Route9_Text_ChrisRematchIntro::
  .string "O yakışıklı POKéMON'larla birlikte\nolduğunu unutmadım.$"

Route9_Text_DrewRematchIntro::
  .string "LAVENDER'a gitmek için KAYA TÜNELİ\niçinden geçeceğim.\pAma yol boyunca herkes tarafından\ndurduruluyorum.$"

Route9_Text_CaitlinRematchIntro::
  .string "Sakın bugün bana patronluk taslamaya\nkalkma! Kalanlar için oynuyoruz!$"

Route9_Text_JeremyRematchIntro::
  .string "Bwahaha! Harika! Yine sıkıldım, ha!$"

Route9_Text_BriceRematchIntro::
  .string "Hahaha! Her zamanki gibi biraz zor!$"

Route9_Text_BrentRematchIntro::
  .string "POKéMON'umu kozalardan eğitmek için\nher gün erken kalktım!$"

Route9_Text_AlanRematchIntro::
  .string "Hahahaha! Bu sefer ben kazanacağım!$"

Route9_Text_ConnerRematchIntro::
  .string "Git kazan, benim süper\nBÖCEK POKéMON'um!$"

Route10_Text_MarkRematchIntro::
  .string "Vay, yine mi buraya geldin? Belki sen de\nbir POKéMANYAK'sındır? Koleksiyonumu\lgörmek ister misin?$"

Route10_Text_ClarkRematchIntro::
  .string "Ha-hahah-ah-ha! Hapşırmadan\nduramıyorum!$"

Route10_Text_HermanRematchIntro::
  .string "Selam, evlat! Sana POKéMON'umu\ngösterdim mi?$"

Route10_Text_HeidiRematchIntro::
  .string "Yine bir POKéMON SALONU'na gittim.\p…Ama her zamanki gibi kaybettim.$"

Route10_Text_TrentRematchIntro::
  .string "Ah! Bu dağ havası çok lezzetli! O kadar\ngüzel ki, ayrılamıyorum!$"

Route10_Text_CarolRematchIntro::
  .string "Başım dönmeye başladı. Çok uzun\nzamandır yürüyüş yapıyorum.$"

Route11_Text_HugoRematchIntro::
  .string "Kazan, kaybet ya da berabere kal! Şimdi\nrövanş maçımız!$"

Route11_Text_JasperRematchIntro::
  .string "Yarışmak en büyük heyecan. Hala\ndoyamıyorum!$"

Route11_Text_EddieRematchIntro::
  .string "Biliyorsun, değil mi? Hadi gidelim, ama\nhile yapma!$"

Route11_Text_BraxtonRematchIntro::
  .string "Merhaba!\pAma dikkatli ol! Hala bazı kablolar\ndöşüyorum!$"

Route11_Text_DillonRematchIntro::
  .string "Bir süre önce eğitmen oldum. Ama sanırım\nkazanabilirim.$"

Route11_Text_DirkRematchIntro::
  .string "Fwahaha! Ben hiç kaybetmedim!\p…Ve eğer kaybettiysem, hepsini\nunuttum!$"

Route11_Text_DarianRematchIntro::
  .string "Daha önce hiç kazanmamıştım.\pBelki de kaderimde böyle kalmak var…$"

Route11_Text_YasuRematchIntro::
  .string "Sınıfımın en iyisiyim. Her sabah ve\nakşam antrenman yapıyorum!$"

Route11_Text_BernieRematchIntro::
  .string "Canlı kablolara karşı gözünüzü dört\naçın!$"

Route11_Text_DaveRematchIntro::
  .string "POKéMON'umu dikkatlice kaldırdım.\nŞimdiye kadar hazır olmalıydılar. Bu\lsefer onlar da kazanmalı.$"

Route12_Text_NedRematchIntro::
  .string "Evet! Burada bir ısırık var! Bu gerçek\nolabilir!$"

Route12_Text_ChipRematchIntro::
  .string "Sonunda geldin. Balık tutmak bir\nbekleme oyunudur.$"

Route12_Text_JustinRematchIntro::
  .string "Hala bir AY TAŞI bulamadım… Siz\nbuldunuz mu?$"

Route12_Text_LucaRematchIntro::
  .string "Elektrik her zaman benim uzmanlık\nalanım olmuştur.\pYine de denizdeki POKemon hakkında\nhiçbir şey bilmiyorum.$"

Route12_Text_HankRematchIntro::
  .string "BALIKÇI APTAL, POKéMON ÇOCUĞA KARŞI!\nBir raunt daha, dövüş!$"

Route12_Text_ElliotRematchIntro::
  .string "Balık tutmayı seviyorum, beni yanlış\nanlamayın. Ama keşke daha fazla işim\lolsaydı… …Balık tutmaktan vazgeçmek\lzor!$"

Route12_Text_AndrewRematchIntro::
  .string "Yakalamak nedir?\pBeni yenmedikçe asla bilemezsin!$"

Route12_Text_JesRematchIntro::
  .string "JES: Bugün burada kazanacağım ve\nGIA'ma evlenme teklif edeceğim.$"

Route12_Text_GiaRematchIntro::
  .string "Hey, JES… Uzun zamandır bekliyordum.\pEğer bugün kazanırsak, seninle\nevleneceğim!$"

Route13_Text_SebastianRematchIntro::
  .string "Kuşum POKéMON seni hatırlıyor!$"

Route13_Text_SusieRematchIntro::
  .string "Çocukken en iyi EĞİTMEN olmak\nistiyorum!$"

Route13_Text_ValerieRematchIntro::
  .string "Vay canına! Daha havalı rozetleriniz\nvar!$"

Route13_Text_GwenRematchIntro::
  .string "Benim sevimli POKéMON'um seninle\nyeniden tanışmak istiyor.$"

Route13_Text_AlmaRematchIntro::
  .string "Birikimlerimi sıfırladım ve daha fazla\nKARBON aldım.$"

Route13_Text_PerryRematchIntro::
  .string "Bu sefer kaybetmeyeceğim. Rüzgar bana\ndoğru esiyor!$"

Route13_Text_LolaRematchIntro::
  .string "Ah, geri mi döndün?\pElbette, seninle tekrar oynayacağım,\ntatlım.$"

Route13_Text_SheilaRematchIntro::
  .string "Benimle savaştığını unutamaz mısın?$"

Route13_Text_JaredRematchIntro::
  .string "Neye bakıyorsun?$"

Route13_Text_RobertRematchIntro::
  .string "Her zaman POKéMON kuşu ile giderim.\nKendimi onlara adadım.$"

Route14_Text_CarterRematchIntro::
  .string "POKéMON'uma iyi hareketler öğretmek\niçin TM'leri kullandım.$"

Route14_Text_MitchRematchIntro::
  .string "Kuşum POKéMON bu sefer savaşa hazır\nolmalı.$"

Route14_Text_BeckRematchIntro::
  .string "TM'leri POKéMON'lar üstünde\nkullanıyor musun?\lOnları saklamak işe yaramaz.$"

Route14_Text_MarlonRematchIntro::
  .string "Kuşunuz POKéMON'a nasıl UÇULACAĞINI\nöğrettiniz mi?\pOnunla birlikte gökyüzünde\nsüzülebileceksiniz! Bir dene bakalım.$"

Route14_Text_DonaldRematchIntro::
  .string "Kanatlı serap efsanesi…\nDuymuşsunuzdur, değil mi?$"

Route14_Text_BennyRematchIntro::
  .string "Pek ilgimi çekmiyor ama olsun. Hadi\ngidelim!$"

Route14_Text_LukasRematchIntro::
  .string "Hey! Seni hatırlıyorum!\pHadi, hadi. Gidelim, gidelim, gidelim!$"

Route14_Text_IsaacRematchIntro::
  .string "Yine buradasın, ha? Kapa çeneni ve\nsavaş.$"

Route14_Text_GeraldRematchIntro::
  .string "Geniş açık alanlar nedeniyle burada at\nsürüyoruz.$"

Route14_Text_MalikRematchIntro::
  .string "POKéMON savaşı, değil mi? Harika!\nRumble!$"

Route14_Text_KiriRematchIntro::
  .string "JAN, umarım bugün kazanırız.$"

Route14_Text_JanRematchIntro::
  .string "KIRI, işte başlıyoruz! Bu sefer kesin\nkazanalım!$"

Route15_Text_KindraRematchIntro::
  .string "Takaslardan aldığım POKéMON'larla\nsavaşmaya devam edeceğim.$"

Route15_Text_BeckyRematchIntro::
  .string "Nazik görünüyorsun, sanırım seni\nyenebilirim.\pBir kez daha deneyeceğim!$"

Route15_Text_EdwinRematchIntro::
  .string "Islık çaldığımda, kuş POKéMON'lar\netrafımda toplanıyor.\pİnanılmaz tatlılar!$"

Route15_Text_ChesterRematchIntro::
  .string "Hmm? Kuşlarım titriyor! Bekle, sen şu\neğitmen değil misin?$"

Route15_Text_GraceRematchIntro::
  .string "Ah, sen çok tatlısın! Tıpkı sevimli bir\nPOKéMON gibi! Seni şimdi hatırladım!$"

Route15_Text_OliviaRematchIntro::
  .string "Yalnız yaşadığım için korunmak amacıyla\nPOKéMON yetiştiriyorum.\pBu hiç değişmedi.$"

Route15_Text_ErnestRematchIntro::
  .string "Hey, çocuk! Gel hadi! Bunları bir\nezikten aldım!$"

Route15_Text_AlexRematchIntro::
  .string "Bana yenildiğinde tüm paranı ver evlat!$"

Route15_Text_CeliaRematchIntro::
  .string "Ne var ne yok? POKéMON takası tabii\nki.$"

Route15_Text_YazminRematchIntro::
  .string "POKéMON'umla tekrar oynamak ister\nmisin?$"

Route15_Text_MyaRematchIntro::
  .string "Merhaba, sürekli karşılaşıyoruz, değil\nmi?\pKüçük kardeşimi tekrar eğitmeme yardım\neder misin?$"

Route15_Text_RonRematchIntro::
  .string "Kız kardeşim daha da güçlendi.$"

Route16_Text_LaoRematchIntro::
  .string "Ne istiyorsun?$"

Route16_Text_KojiRematchIntro::
  .string "Güzel bisiklet! Çabuk teslim et!$"

Route16_Text_LukeRematchIntro::
  .string "Dışarı çık ve oyna, küçük fare. Sana iyi\ndavranacağım!$"

Route16_Text_HideoRematchIntro::
  .string "Hey, bekle bir saniye! Beni arayıp sonra\nda kaçma!$"

Route16_Text_CamronRematchIntro::
  .string "Kendimi aç ve kötü hissediyorum!\nGerçekten bir kum torbasına ihtiyacım\lvar!$"

Route16_Text_RubenRematchIntro::
  .string "Hey, oradakiler! İyi vakit geçireceğiz!$"

Route16_Text_JedRematchIntro::
  .string "JED: Sınır tanımayan aşkımızı görmek\niçin mi buradasınız?$"

Route16_Text_LeaRematchIntro::
  .string "LEA: Bazen aşkımızın yoğunluğu beni\nkorkutuyor.$"

Route17_Text_RaulRematchIntro::
  .string "Size söyledim, çocuklarla savaşarak\nçabuk zengin olunmaz.$"

Route17_Text_IsaiahRematchIntro::
  .string "Vücudumla gurur duyuyorum, evlat. Gel\nhadi!$"

Route17_Text_VirgilRematchIntro::
  .string "Gezintiye mi çıktın?$"

Route17_Text_BillyRematchIntro::
  .string "Biz BİSİKLETÇİYİZ! Yolları biz\nyönetiriz, dostum!$"

Route17_Text_NikolasRematchIntro::
  .string "VOLTORB bugün sizi ciddi şekilde\nheyecanlandıracak!$"

Route17_Text_ZeekRematchIntro::
  .string "POKéMON'uma seviye atlattım ama\nkesinlikle evrimleşmiyor. Neden?$"

Route17_Text_JamalRematchIntro::
  .string "Gaah! Gerçekten egzersiz yapmalı ve\nbiraz yağlarımı eritmeliyim!$"

Route17_Text_CoreyRematchIntro::
  .string "Asi ol!$"

Route17_Text_JaxonRematchIntro::
  .string "Evet, bu güzel bir bisiklet! Nasıl\ngidiyor?$"

Route17_Text_WilliamRematchIntro::
  .string "Kaybol, çocuk! İşim başımdan aşkın!$"

Route18_Text_WiltonRematchIntro::
  .string "Yeni POKéMON için her çimenlik alanı\nkontrol ediyordum.\pAma bu her zaman kolay olmuyor.$"

Route18_Text_RamiroRematchIntro::
  .string "Koorukukukoo! Kuş sesim iyileşiyor mu?$"

Route18_Text_JacobRematchIntro::
  .string "Seni daha önce uyarmıştım, burası benim\nbölgem!\pBuraya gelmeni istemiyorum.$"

Route19_Text_RichardRematchIntro::
  .string "Yüzmeye gitmek için neredeyse ısındım.$"

Route19_Text_ReeceRematchIntro::
  .string "Bekle! Yavaşla! Ya kalp krizi\ngeçirirsen?$"

Route19_Text_MatthewRematchIntro::
  .string "Yüzmeye bayılırım! Sanırım sen sörf\nyapan tiplerdensin.$"

Route19_Text_DouglasRematchIntro::
  .string "Ufkun ötesinde ne var? Gördünüz mü?$"

Route19_Text_DavidRematchIntro::
  .string "Tekrar POKéMON için dalmayı denedim\nama daha önce olduğu gibi olmadı.$"

Route19_Text_TonyRematchIntro::
  .string "Olan tüm kötü şeyleri unutmak için\ndenize bakıyorum.\p…Sana karşı son kez kaybetmek gibi!$"

Route19_Text_AnyaRematchIntro::
  .string "Her zaman POKéMON'una binebilirsin.\pÇok rahatlatıcı görünüyor. Kazanırsam\nalabilir miyim?$"

Route19_Text_AliceRematchIntro::
  .string "Yüzmek harika! Güneş yanıkları değil!$"

Route19_Text_AxleRematchIntro::
  .string "Bu sular tehlikeli! Buraya geri\ngelmemelisin!$"

Route19_Text_ConnieRematchIntro::
  .string "Burada arkadaşlarımla yüzdüm…\nYoruldum… Gerçekten tekrar savaşmak\lzorunda mıyız?$"

Route19_Text_LiaRematchIntro::
  .string "Kardeşimin daha yeni eğitmen olduğunu\nbiliyorsun, değil mi?\pOnu daha iyi hale getirmek istiyorum, bu\nyüzden yine yardımınıza ihtiyacım var.$"

Route19_Text_LucRematchIntro::
  .string "LUC: Ablam bana POKéMON hakkında her\nşeyi öğretti.\pAcaba daha iyi miyim?$"

Route20_Text_BarryRematchIntro::
  .string "Burada su sığdır. Yüzen birçok insan\nvar.$"

Route20_Text_ShirleyRematchIntro::
  .string "SEAFOAM'da tatil yaptığım için beni\nkıskanıyor musun?$"

Route20_Text_TiffanyRematchIntro::
  .string "Burada dalgaların arasında balıklarla\nbirlikte yüzmeyi seviyorum.$"

Route20_Text_IreneRematchIntro::
  .string "Sen de mi tatildeydin?$"

Route20_Text_DeanRematchIntro::
  .string "Fiziğime bakın!\pHer zamankinden daha da kaslı!$"

Route20_Text_DarrinRematchIntro::
  .string "Neden bir POKéMON'a biniyorsun? Daha\nyüzmeyi öğrenmedin mi?$"

Route20_Text_RogerRematchIntro::
  .string "Kuşum POKéMON'u buraya sürdüm.$"

Route20_Text_NoraRematchIntro::
  .string "Erkek arkadaşım bana büyük inciler\nverdi. Ve daha da büyüdüler!$"

Route20_Text_MissyRematchIntro::
  .string "Buraya CINNABAR ADASI'ndan yüzerek\ngeldim. Dediğim gibi kolay olmadı.$"

Route20_Text_MelissaRematchIntro::
  .string "Batıdaki CINNABAR'da POKéMON için bir\nlaboratuvar var.\pBabam orada çalışıyor.$"

Route21_North_Text_RonaldRematchIntro::
  .string "Balığın ısırıp ısırmadığını mı bilmek\nistiyorsun?$"

Route21_North_Text_WadeRematchIntro::
  .string "Yine büyük bir vurgun yaptım! Bir kez\ndaha denemek ister misin?$"

Route21_North_Text_SpencerRematchIntro::
  .string "Deniz bedenimi ve ruhumu temizliyor!$"

Route21_North_Text_CueBallRematchIntro::
  .string "きょうも およぎに きちまったぜ$"

Route21_South_Text_JackRematchIntro::
  .string "POKéMON'umu denizde yakaladım. Ve\nonları orada eğitiyorum.$"

Route21_South_Text_JeromeRematchIntro::
  .string "Şu anda başka bir triatlon\nyarışmasındayım!$"

Route21_South_Text_RolandRematchIntro::
  .string "Ahh! Güneşi ve rüzgarı hissedin!$"

Route21_South_Text_ClaudeRematchIntro::
  .string "Hey, kes şunu artık. Balıkları hep\nkorkutup kaçırıyorsun!$"

Route21_South_Text_NolanRematchIntro::
  .string "Bir şey bulana kadar bana eşlik et.$"

Route21_North_Text_LilRematchIntro::
  .string "Ha? Yine mi savaş? IAN, bunu tek başına\nyapamaz mısın?$"

Route21_North_Text_IanRematchIntro::
  .string "Kız kardeşim hala pasaklı. Onu forma\nsokmama yardım et!$"

Route25_Text_JoeyRematchIntro::
  .string "Buradayken kaybetmeyeceğim!$"

Route25_Text_DanRematchIntro::
  .string "Babam beni VERMILION ŞEHRİ'ndeki\nS.S. ANNE gemisinde harika bir\lpartiye götürdü.$"

Route25_Text_FlintRematchIntro::
  .string "Ben havalı bir adamım. Bir kız arkadaşım\nvar!\pBu sefer ona ne kadar havalı olduğumu\ngöstereceğim!$"

Route25_Text_KelseyRematchIntro::
  .string "Merhaba! Erkek arkadaşım harika!\nKondisyonum bugün iyi!$"

Route25_Text_ChadRematchIntro::
  .string "İçimde bir his vardı… Seninle tekrar\nsavaşmam gerektiğini biliyordum!$"

Route25_Text_HaleyRematchIntro::
  .string "Arkadaşımın bir sürü sevimli POKéMON'u\nvar. Çok kıskandım!$"

Route25_Text_FranklinRematchIntro::
  .string "MT'de yeni eğitim aldım. Ay, ama depoda\nhala benzin var!$"

Route25_Text_NobRematchIntro::
  .string "Tepede bir POKéMANYAK yaşıyor.\nKoleksiyonunu gördünüz mü?$"

Route25_Text_WayneRematchIntro::
  .string "BILL'i tekrar görmeye mi gidiyorsun?\nÖnce savaşacağız!$"

Route24_Text_ShaneRematchIntro::
  .string "Çimlerin üzerinden başarınızı gördüm!$"

Route24_Text_EthanRematchIntro::
  .string "Tamam! Tamam! Seni ezeceğim!$"

Route24_Text_ReliRematchIntro::
  .string "Hep çok meşgul görünüyorsun…\nYorulmuyor musun?$"

Route24_Text_TimmyRematchIntro::
  .string "KÜLÇE KÖPRÜSÜ'ne gelmeyi gerçekten\nseviyor olmalısınız.$"

Route24_Text_AliRematchIntro::
  .string "Savaştığımız zaman…\pİkinci sırada olmama rağmen en iyisi\nbendim, değil mi?$"

Route24_Text_CaleRematchIntro::
  .string "İnsanlar buna KÜLÇE KÖPRÜSÜ diyor!\pBizi zaten yendiniz, bu yüzden meydan\nokumaya izniniz yok…\p…Ama, bizimle tekrar savaşabilirsiniz.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
  .string "Sırt üstü uzanmış, dalgalarla\nsallanıyorum… Zamanın akıp gittiğini\lfark etmiyorum…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
  .string "Hava muhteşem! Bunu bozmamaya\nçalışacağım.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
  .string "Güneş yanığım acımaya başladı.$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
  .string "Ateş kuşunun dağı büyük bir gölge\noluşturuyor…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
  .string "Bu sefer kazanabileceğime dair güçlü\nbir his var içimde!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
  .string "Bekle! Bekle bir saniye! Büyük bir tane\nyakaladığıma eminim!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
  .string "Eğitimimde bana yine yardım edecek\nmisin?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
  .string "Henüz tek bir eğitim gününü bile\nkaçırmadık!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
  .string "Her sabah kahvaltıdan önce bu adanın\netrafında yüzüyorum… Üç kez!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
  .string "Savaş için uygun giyin! Şu anlamsız\nkıyafetten kurtulun dedim!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
  .string "Bilirsiniz, vahşi doğadayken her şeyin\ntadı harikadır.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
  .string "Yine çok yedim, biraz egzersiz için\nbizimle savaşacak mısın?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
  .string "KIA: Ağabeyim ve ben harika bir\nkombinasyon oluşturduk!\pBu sefer kaybetmeyeceğiz!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
  .string "MIK: KIA ile birlikte hiçbir şeyden\nkorkmuyoruz!\pBu sefer bunu size kanıtlayacağız!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
  .string "Yine savaşacak mıyız?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
  .string "Nereden geldiniz ve nereye\ngidiyorsunuz?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
  .string "Yakında şamandıra yüzüğüm olmadan\nyüzmek istiyorum.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
  .string "Yaşasın! POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
  .string "Ah, hayır, sana daha önce söylemedim\nmi? Lütfen, benden uzak dur!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
  .string "JOY: Daha da güçlendik! Hem de\nçok!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
  .string "Bugün bizi yenemezsiniz!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
  .string "Ah, merhaba!\pPOKéMON'unuzu iyi bir ortamda mı\nyetiştiriyorsunuz?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
  .string "Bu ellerle bugün zaferimi yaratacağım.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
  .string "Tekrarlamak zorunda mıyım? Resim\nyapmaya çalışıyorum. Lütfen gözüme\lgörünme!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
  .string "Hiç ilerleme kaydedemedim… Hala\ndoğru açıyı yakalayamıyorum…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
  .string "Seninle zeka yarıştırmam için bana bir\nfırsat daha mı vereceksin?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
  .string "POKéMON'um için havuz yapmayı\nneredeyse bitirdiler.\pBir ziyaret için uğramalısın.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
  .string "Ben iyi bir koşucuyum. Daha da\nhızlandım!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
  .string "Diyorum ki, dostum! Birlikte\ngeçirdiğimiz zamanın tadını çıkaralım!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
  .string "Ben KUŞ KARDEŞLER'in en büyüğüyüm.\nBeni hatırladın mı?\pDoğru, kuşları gagaları için seven\nbenim!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
  .string "Ben KUŞ KARDEŞLER'in ortanca\nçocuğuyum.\pKanatları seven benim. Hadi tekrar\nsavaşalım!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
  .string "Ben KUŞ KARDEŞLER'in en küçüğüyüm.\pKuşları tüyleri için severim. Seni bir\ndaha göreceğimi sanmıyordum!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
  .string "Hala hiç şansım yok. Bir savaş hız\ndeğişikliği olurdu!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
  .string "Gasp… Gasp…\pALTINCI ADA'nın limanından buraya\nyine tek seferde yüzdüm.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
  .string "Ben yüzerken hep yanıma geliyorsun.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
  .string "AVA: Bugün yine ikiye iki denizci savaşı\nyapalım!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
  .string "GEB: Ablam ve ben eskisinden çok daha\ngüçlüyüz!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
  .string "…Ha?\pEvimi hayal ediyorum ama IŞINLANMA\nbeni hep buraya getiriyor!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
  .string "Ah, merhaba. Yine hoş bir meltem esiyor.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
  .string "Hehehe, yine gizlice çalışıyorum.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
  .string "Ne yani, benim gibi yüzücüleri\ngörmekten bıktınız mı?\pAww, nefret etme! Benimle tekrar savaş.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
  .string "Erkek arkadaşım yine meşgul.$"

SixIsland_WaterPath_Text_EarlRematchIntro::
  .string "Hadi, söyle bana, buralarda dağlar\nnerede?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
  .string "Merhaba, POKéMON! Tekrar oynama\nzamanı!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
  .string "Merhaba, POKéMON! Tekrar savaşma\nzamanı!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
  .string "Bu dünyada hâlâ çözülememiş pek çok\nsır var gibi görünüyor.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
  .string "Merhaba, daha önce tanışmamış mıydık?\nSeni geri gelmeye zorlayan neydi?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
  .string "Bu adada gizemli taşlar olduğu\nsöylenir.\pSon görüşmemizden bu yana bir şey\nkeşfettiniz mi?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
  .string "Seninle bir rövanş, çok yüksekte!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
  .string "Buralardaki araziye oldukça aşinayım.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
  .string "Yaklaşımını hissettim.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
  .string "Bu adada bir yerlerde, tuhaf\nPOKéMON'lar uyuyor.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
  .string "Kyahaha!\pGeri gelmen hiçbir şeyi\ndeğiştirmeyecek. Seni zahmetsizce\luzaklaştıracağım!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
  .string "Merhaba! Sen benim hayran kulübümün\nbir üyesisin, değil mi?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
  .string "Bu ada çok dağınık… Devriye gezmek\nçok sıkıcı…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
  .string "POKéMON'u kötüye kullanan insanları\naffetmiyorum!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
  .string "EVE: JON ile takım kurup tekrar birlikte\nsavaşacağım.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
  .string "JON: EVE ile birlikteyken sanki hiç\nkaybetmeyecekmişiz gibi hissediyorum,\lasla.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
  .string "Bir savaş daha yapalım. Kondisyonum en\nüst seviyede!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
  .string "En güçlü POKéMON'a sahip olmanızın bir\nönemi yok…\pOnları nasıl doğru kullanacağınızı\nbilmiyorsanız hiçbir şey ifade etmez!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
  .string "Çevreyi korumak için çalışıyorum.\nKarşılığında doğa da beni koruyor!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
  .string "Ne zaman karşılaşsak, o şık\nayakkabıları giyiyorsun.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
  .string "Daha da sertleşmiş olmalısın. Seninle\ndövüşmeme izin ver, lütfen!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
  .string "Bu kadar güçlü olabilmem için bana\nmümkün olan en iyi eğitim verildi.\pBu sefer kaybetmeyeceğim. Kesinlikle\nkaybetmeyeceğim!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
  .string "LEX: Sevgili NYA, birlikte kesin\nkazanacağız!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
  .string "Akıl hocam LEX'i aşağı çekmeyeceğim!\nBiz kazanacağız!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
  .string "Bu taş oda hakkında bir şey keşfettiniz\nmi?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
  .string "Mistik bir POKéMON'un burada uyuduğu\nsöylenir.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
  .string "Öğretmenim bana biraz daha nasıl resim\nyapılacağını gösteriyor.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
  .string "Bugün dersimize ek olarak odayı tekrar\ngörmeye geldik.$"

