Text_FirstShouldRestoreMonsHealth::
  .string "İlk olarak, POKéMON'unuzu tam\nsağlığına kavuşturalım.$"

Text_MonsHealedShouldBuyPotions::
  .string "POKéMON'unuz mükemmel bir şekilde\niyileştirildi.\pEğer POKéMON'unuzun enerjisi, yani\ncanı düştüyse, lütfen bizi görmeye\lgelin.\pEğer uzun yol kat etmeyi\nplanlıyorsanız, POKéMON MART'tan\lİKSİR satın almalısınız.\pYine bekleriz!$"

Text_MonsHealed::
  .string "POKéMON'unuz mükemmel bir şekilde\niyileştirildi.\pYine bekleriz!$"

Text_HadQuiteAnExperienceTakeRest::
  .string "ANNE: {PLAYER}!\nEvine hoş geldin.\pOldukça iyi bir deneyim yaşamışsın gibi\ngörünüyor.\pBelki de biraz dinlenmelisin.$"

Text_MomExplainHPGetPotions::
  .string "ANNE: Ah, güzel!\nSen ve POKéMON'un harika görünüyorsunuz.\pAz önce PROF. OAK'tan haber aldım.\pPOKéMON'un enerjisinin CAN ile\nölçüldüğünü söyledi.\pPOKéMON'unun canı azaldığında canını\nherhangi bir POKéMON MERKEZİ'nde\lyenileyebilirmişsin.\pEğer uzaklara seyahat edeceksen,\nakıllı bir eğitmen olup POKé MART'tan\lİKSİR stoklamayı unutma.\pBeni gururlandır, tatlım!\nKendine iyi bak!$"

Text_WhitedOutLostMoney::
  .string "{PLAYER}'ın kullanılabilir POKéMON'u\nkalmadı!\p{PLAYER} panikledi ve kaçarken ¥{STR_VAR_1}\ndüşürdü...\p... ... ... ...\p{PLAYER} kaçtı!$"

Text_WhitedOut::
  .string "{PLAYER}'ın kullanılabilir POKéMON'u\nkalmadı!\p{PLAYER} kaçtı!$"

