SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "Bu adada, bağlantılara bağlı\n"
    .string "farklı olaylar yaşanır.\p"
    .string "Bu bağlantılar nelerdir?\p"
    .string "Bu senin kendin keşfedeceğin\n"
    .string "bir şey.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "Buraya SEAGALLOP feribotu\n"
    .string "ile mi geldin?\p"
    .string "O yüksek-hızlı gemilerden en az 10\n"
    .string "tane var.\p"
    .string "Ama nereye giderler hiç\n"
    .string "bilmiyorum.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "Eğer kendine güveniyorsan, EĞİTMEN\n"
    .string "KULESİ'ne bir göz at.$"


