SevenIsland_SevaultCanyon_Text_CyndyIntro::
.string "Kondisyonum mükemmel durumda!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
.string "Hey!\n"
.string "Bir şeyler yolunda gitmiyor…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
.string "Şu anki durumumla, sanırım\n"
.string "EĞİTMEN KULESİ'ne katılmamak\l"
.string "en iyisi…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
.string "En güçlü POKéMON'a sahip olmak\n"
.string "önemli değil…\p"
.string "Onları doğru kullanmayı\n"
.string "bilmiyorsan, hiçbir anlamı yok!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
.string "Gerçekten ustasın.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
.string "Bazen, en güçlü POKéMON'lara\n"
.string "sahip EĞİTMENLER görürsünüz\l"
.string "ama onları nasıl kullanacaklarını\l"
.string "bilmezler.\p"
.string "POKéMON eğitmeden önce,\n"
.string "EĞİTMENLER'in kendilerinin\l"
.string "büyümesi gerekir.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
.string "Doğayı korumak için çalışıyorum.\n"
.string "Karşılığında, doğa da beni koruyor!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
.string "Vay! Çok güçlüsün!\n"
.string "Beni de korur musun?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
.string "Uzaydan bakıldığında, gezegenimiz\n"
.string "sadece bir damla su.\p"
.string "Ama biz o damla suyu herkes için\n"
.string "korumak istiyoruz.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
.string "O ayakkabılar gerçekten çok şık.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
.string "Görünüşüne rağmen, çok güçlüsün.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
.string "Annemin sana bu şık\n"
.string "KOŞU AYAKKABILARINI aldığını\l"
.string "mı söyledin?\p"
.string "Seni çok seviyor olmalı.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
.string "Çok güçlü görünüyorsun.\n"
.string "Lütfen benimle savaş!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
.string "Bunu biliyordum!\n"
.string "Düşündüğüm kadar güçlüymüşsün!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
.string "Savaş stilin bana çok faydalı\n"
.string "bilgiler verdi.\p"
.string "Çok teşekkürler!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
.string "En güçlü olmak için en iyi\n"
.string "eğitimi aldım.\p"
.string "Kimseye kaybetmek istemiyorum!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
.string "Teşekkürler. Sana kaybederek özgür\n"
.string "hissediyorum.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
.string "Nedense, en ufak şeylere bile\n"
.string "çok öfkeleniyorum.\p"
.string "Derin nefes alarak sakinleşeceğim.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
.string "LEX: Sevgilim NYA, birlikte\n"
.string "kazanabiliriz!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
.string "LEX: Sanırım biraz dikkatsiz\n"
.string "davranmışım…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
.string "LEX: NYA için iyi bir deneyim\n"
.string "olduğunu düşünüyorum.\p"
.string "Teşekkürler.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
.string "LEX: İkimize aynı anda meydan\n"
.string "okumanızı isteyebilir miyim?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
.string "NYA: Akıl hocam LEX'i \n"
.string "utandırmamak için\l"
.string "elimden geleni yapacağım!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
.string "NYA: Ah, hayır…\n"
.string "Üzgünüm, ben…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
.string "NYA: Sanırım LEX'in yanında\n"
.string "daha fazla eğitim ve rehberliğe\l"
.string "ihtiyacım var…\p"
.string "…LEX, lütfen, yanında kalıp\n"
.string "öğrenmeye devam edebilir miyim?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
.string "NYA: Özür dilerim, ama ikişerli\n"
.string "stilde savaşabilir miyiz?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
.string "SEVAULT KANYONU\n"
.string "TANOBY HARABELERİ ÖNDE$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
.string "Tabii ki tek başına antrenman\n"
.string "yapmak kötü bir şey değil.\p"
.string "Ama bir ortakla zirveye ulaşmak\n"
.string "de kötü bir şey değil.\p"
.string "Hatta BRUNO bile…\l"
.string "BRAWLY adında biriyle antrenman\l"
.string "yapmıştı.$"
