OneIsland_Text_BillLetsGoSeeCelio::
    .string "BILL: İşte buradayız!\n"
    .string "Burası BİRİNCİ ADA.\p"
    .string "Çevrede birkaç ada var\n"
    .string "ve bu onlardan biri.\p"
    .string "Arkadaşım CELIO beni almaya\n"
    .string "buraya tekne gönderdi.\p"
    .string "ADA'nın PC ağından\n"
    .string "tek başına sorumlu.\p"
    .string "…Neden şimdi bunu söylüyorum?\n"
    .string "Hadi CELIO'ya gidelim!$"

Text_WhereDoYouWantToSail::
    .string "Ahoy, oradaki!\n"
    .string "Hangi limana yelken açmak istersin?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "İşte buradayız, ıssız bir adada.\p"
    .string "CELIO gibi düzgün bir gence\n"
    .string "sahip olduğumuz için şanslıyız.\p"
    .string "Torunum CELIO'nun arkadaşından\n"
    .string "çok heyecanlanmıştı.\p"
    .string "Bir POKéMANYAK hakkında\n"
    .string "bir şeyler miydi?\p"
    .string "Ne anlama geldiğinden emin\n"
    .string "değilim, ama CELIO adamdır!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "Torunum yeni bir atılımdan\n"
    .string "heyecanlanmıştı.\p"
    .string "KANTO'daki insanlarla artık PC\n"
    .string "bağlantımız olduğunu söyledi.\p"
    .string "Ne anlama geldiğinden emin\n"
    .string "değilim, ama CELIO adamdır!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "Torunum yeni bir atılımdan\n"
    .string "heyecanlanmıştı.\p"
    .string "HOENN'deki insanlarla sonunda PC\n"
    .string "bağlantımız olduğunu söyledi.\p"
    .string "Ne anlama geldiğinden emin\n"
    .string "değilim, ama CELIO adamdır.\p"
    .string "Torunum için mükemmel bir koca\n"
    .string "olurdu!$"

OneIsland_Text_IslandSign::
    .string "BİRİNCİ ADA\n"
    .string "Arkadaşlar Knot Adası'nda toplanır$"

OneIsland_Text_PokemonNetCenterSign::
    .string "POKéMON dünyasını genişletiyoruz!\n"
    .string "POKéMON NET MERKEZİ$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "Merhaba, geziyor musun?\n"
    .string "Buradaki sıcak iklim harika değil mi?$"
