LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Hayaletlere inanır mısın?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Cidden mi?\n"
    .string "Öyleyse inananlar var…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, sanmam.\p"
    .string "Ama o omzundaki beyaz el…\n"
    .string "Sanırım hayal gücümün ürünü.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "Bu şehir, POKéMON'ların mezarı\n"
    .string "olarak bilinir.\p"
    .string "Anma törenleri POKéMON KULESİ'nde\n"
    .string "yapılır.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Hayaletler POKéMON KULESİ'nde\n"
    .string "belirdi.\p"
    .string "ROKET TAKIMI tarafından öldürülen\n"
    .string "POKéMON'ların ruhları olabilirler.$"

LavenderTown_Text_TownSign::
    .string "LAVENDER KASABASI\n"
    .string "Asil Mor Kasaba$"

LavenderTown_Text_SilphScopeNotice::
    .string "Yeni SILPH GÖZLÜĞÜ!\n"
    .string "Görünmez Olanı Görünür Kıl!\p"
    .string "SILPH ŞTİ.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER GÖNÜLLÜLERİ\n"
    .string "POKéMON EVİ$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON KULESİ\n"
    .string "POKéMON Ruhlarının Huzurevi$"
