PokemonMansion_Text_PressSecretSwitchJP::
    .string "Gizli bir anahtar var!\p"
    .string "Basıp görmek ister misin?$"

PokemonMansion_Text_LetsTryIt::
    .string "Deneyelim! ‥Tık$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "Basmaktan vazgeçti$"

PokemonMansion_1F_Text_SimonIntro::
    .string "Bu yer, çok büyük!$"

PokemonMansion_1F_Text_SimonDefeat::
    .string "Ay!$"

PokemonMansion_1F_Text_SimonPostBattle::
    .string "Ortağım nereye gitti merak ediyorum.$"

PokemonMansion_1F_Text_BraydonIntro::
    .string "Akıl hocam bir zamanlar burada\n"
    .string "yaşamıştı.$"

PokemonMansion_1F_Text_BraydonDefeat::
    .string "Vaov!\n"
    .string "Ezici!$"

PokemonMansion_1F_Text_BraydonPostBattle::
    .string "Demek sıkıştın?\n"
    .string "Oradan atlayabilirsin!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .string "Günlük: 6 Şubat\n"
    .string "MEW doğurdu.\p"
    .string "Yenidoğan'a MEWTWO adını verdik.$"

