LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "ROKET TAKIMI para için her şeyi\nyapar!\p"
    .string "Onlar için hiçbir iş pis,\n"
    .string "hiçbir eylem iğrenç ve hiçbir\l"
    .string "suç ahlaksız değildir!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "CUBONE'un annesini, ROKET\n"
    .string "TAKIMI'ndan kaçmaya çalışırken\l"
    .string "gördüm.\p"
    .string "Ne yazık ki kaçarken öldürüldü…$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "CUBONE türünün kafatası\n"
    .string "taktığını biliyor musun?\p"
    .string "İnsanlar bunun için çok para öder.$"
