Route17_Text_RaulIntro::
    .string "Burada çocuklarla\n"
    .string "savaşarak hızlı para kazanamazsın.$"

Route17_Text_RaulDefeat::
    .string "Yandım!$"

Route17_Text_RaulPostBattle::
    .string "BİSİKLET YOLU'nda iyi şeyler\n"
    .string "bulabilirsin.\p"
    .string "Onları toplayıp satarak\n"
    .string "iyi para kazanabilirsin.$"

Route17_Text_IsaiahIntro::
    .string "Vücudumla gurur duyuyorum, çocuk.\n"
    .string "Haydi!$"

Route17_Text_IsaiahDefeat::
    .string "Hoo!$"

Route17_Text_IsaiahPostBattle::
    .string "Seni karın üstü buradan\n"
    .string "dışarı atabilirim!$"

Route17_Text_VirgilIntro::
    .string "FUCHSIA'ya mı gidiyorsun?$"

Route17_Text_VirgilDefeat::
    .string "Çakıldım!$"

Route17_Text_VirgilPostBattle::
    .string "Bayır aşağı yarışmaya bayılıyorum!$"

Route17_Text_BillyIntro::
    .string "Biz MOTORCULAR'ız!\n"
    .string "Yolların efendisiyiz, adamım!$"

Route17_Text_BillyDefeat::
    .string "Duman oldum!$"

Route17_Text_BillyPostBattle::
    .string "Macera mı arıyorsun?$"

Route17_Text_NikolasIntro::
    .string "VOLTORB'un gücüne kapıl!$"

Route17_Text_NikolasDefeat::
    .string "Toprağa düştüm!$"

Route17_Text_NikolasPostBattle::
    .string "VOLTORB'umu terk edilmiş\n"
    .string "ENERJİ SANTRALİ'nden aldım.$"

Route17_Text_ZeekIntro::
    .string "POKéMON'umu geliştirdim, ama evrim\n"
    .string "geçirmiyor. Neden?$"

Route17_Text_ZeekDefeat::
    .string "Sen de kim oluyorsun!$"

Route17_Text_ZeekPostBattle::
    .string "Belki de bazı POKéMON'ların\n"
    .string "evrimleşmesi için\l"
    .string "ELEMENT TAŞLARI gerekiyor.$"

Route17_Text_JamalIntro::
    .string "Biraz egzersiz yapmam gerekiyor!$"

Route17_Text_JamalDefeat::
    .string "İyiydi!\n"
    .string "İyi bir antrenmandı!$"

Route17_Text_JamalPostBattle::
    .string "Kesin kilo verdim!$"

Route17_Text_CoreyIntro::
    .string "Asi ol!$"

Route17_Text_CoreyDefeat::
    .string "Aaaah!$"

Route17_Text_CoreyPostBattle::
    .string "İnançların için savaşmaya hazır ol!$"

Route17_Text_JaxonIntro::
    .string "Güzel BİSİKLET!\n"
    .string "Nasıl gidiyor?$"

Route17_Text_JaxonDefeat::
    .string "Vay canına!$"

Route17_Text_JaxonPostBattle::
    .string "Eğim yönlendirmeyi zorlaştırıyor.$"

Route17_Text_WilliamIntro::
    .string "Defol buradan, çocuk!\n"
    .string "Yoruldum!$"

Route17_Text_WilliamDefeat::
    .string "Tatmin oldun mu?$"

Route17_Text_WilliamPostBattle::
    .string "Birkaç saat uyumam lazım!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "Bir duyuru.\p"
    .string "Atılmış eşyalara dikkat et.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "EĞİTMEN İPUCU\p"
    .string "Tüm POKéMON'lar eşsizdir.\p"
    .string "Aynı tür ve seviyedeki POKéMON'lar\n"
    .string "bile farklı hızlarda büyür.$"

Route17_Text_PressBToStayInPlace::
    .string "EĞİTMEN İPUCU\p"
    .string "Yokuş aşağı sabit durmak için\n"
    .string "B tuşuna bas.$"

Route17_Text_RouteSign::
    .string "ROTA 17\n"
    .string "CELADON ŞEHRİ - FUCHSIA ŞEHRİ$"

Route17_Text_DontThrowGameThrowBalls::
    .string "Bir duyuru!\p"
    .string "Havlu atma, POKé\n"
    .string "TOPLARINI at!$"

Route17_Text_CyclingRoadSign::
    .string "BİSİKLET YOLU\n"
    .string "Eğim burada bitiyor!$"
