Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Merhaba, ben GÜNDÜZ BAKIM\n"
    .string "servisini işletiyorum.\p"
	.string "Bir POKéMON'una bakmamı ister misin?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Tekrar gelin.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Hangi POKéMON'una bakayım?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Tamam.\n"
	.string "İstediğin zaman gel.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Tamam, {STR_VAR_1}'ına\n"
    .string "bir süreliğine bakacağım.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Bir süre sonra gel bana.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Zaten geri mi döndün?\p"
	.string "{STR_VAR_1} daha fazla\n"
    .string "zaman geçirmek istiyor$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "{STR_VAR_2} kadar bir ücret ödeyerek\n"
	.string "bu POKéMON'unu geri alabilirsin.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Teşekkürler!\n"
	.string "İşte POKéMON'un.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} {STR_VAR_1}'unu GÜNDÜZ\n"
	.string "BAKIM ADAMINDAN geri aldı.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Oh? Yanında sadece tek bir\n"
	.string "POKéMON'un var.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "Eğer bu POKéMON'u bana bırakırsan,\n"
	.string "neyle savaşacaksın?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "{STR_VAR_1} çok gelişti.\p"
	.string "Evet, oldukça fazla\n"
    .string "büyüdüğünü söyleyebilirim.\p"
	.string "Bakalım…\n"
	.string "Seviye olarak,\l"
    .string "{STR_VAR_2} seviye büyümüş.\p"
	.string "Harika değil miyim?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Eğer için yerin yoksa bu\n"
	.string "POKéMON'unu geri alamazsın.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Yeterli paran yok.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "Sana bakmamı ister misin?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "Üzgünüm, gizli hareketlere sahip\n"
    .string "POKéMON'ları kabul edemem.$"
