SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
.string "Kyahaha!\n"
.string "Kolayca savuracağım seni!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
.string "Tch!\n"
.string "Çok güçlüsünüz!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
.string "Ne o?\n"
.string "Göründüğüm gibi değilmiyim.\p"
.string "Stratejimin bir parçası bu, hehe!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
.string "Merhaba!\n"
.string "Hayranlarımdan mısın?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
.string "Öyleyse bir hayran değilsin…\p"
.string "Durumu değiştirebilirim.\n"
.string "Sana şarkı söyleyeyim!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
.string "Lalalah…\n"
.string "POKéMON'larımı salarım,\l"
.string "Kızlar çığlık atar, bayılırlar!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
.string "Bu ada çok dağınık…\n"
.string "Devriye gezmek kolay değil.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
.string "Evet…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
.string "Senin gibi şehirli EĞİTMENLER…\n"
.string "Çok güçlüsünüz.\p"
.string "KULE'ye gideceksiniz, değil mi?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
.string "POKéMON'ları istismar edenleri\n"
.string "cezalandırırım!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
.string "Sorunlu bir EĞİTMEN\n"
.string "gibi görünmüyorsun.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
.string "POKéMON'larınıza\n"
.string "şefkatle yaklaşırsanız,\l"
.string "onlar da anlayacak.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
.string "EVE: JON'la takım olup\n"
.string "beraber savaşacağız.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
.string "EVE: JON'la kaybettik.\n"
.string "Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
.string "EVE: JON'la daha çok\n"
.string "çalışmamız gerekiyor.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
.string "EVE: JON'la takım olup\n"
.string "sizinle savaşmak istiyorum.\p"
.string "Lütfen iki POKéMON'la geri gelin, olur mu?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
.string "JON: EVE'le birlikteyken\n"
.string "asla yenilmeyeceğimizi hissediyorum.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
.string "JON: EVE'le birlikteyken\n"
.string "yenilmiş gibi hissetmiyorum!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
.string "JON: EVE'le birlikteyken,\n"
.string "kazansam da kaybetsem de mutlu\l"
.string "oluyorum.\p"
.string "Büyülü bir şey bu!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
.string "JON: EVE'yle birlikte,\n"
.string "sizinle savaşmak isterim.\p"
.string "Bu yüzden ikişer POKéMON'la\n"
.string "savaşalım, olur mu?$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
.string "SEVAULT KANYON GİRİŞİ\p"
.string "EĞİTMENLER'den kanyondaki\n"
.string "bitkilere zarar vermemeleri\l"
.string "rica olunur.$"
