Route12_Text_MonSprawledOutInSlumber::
    .string "Bir POKéMON derin ve rahat bir\n"
    .string "uykuda uyukluyor.$"

Text_SnorlaxWokeUp::
    .string "SNORLAX uyandı!\p"
    .string "Sinirli bir şekilde saldırdı!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX sakinleşti.\n"
    .string "Büyük bir esnemeyle…\l"
    .string "Dağlara geri döndü.$"

Text_WantToUsePokeFlute::
    .string "POKé FLÜT kullanmak ister misin?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} POKé FLÜT'ü çaldı.$"

Route12_Text_NedIntro::
    .string "Evet!\n"
    .string "İşte oltaya takıldı!$"

Route12_Text_NedDefeat::
    .string "Tch!\n"
    .string "Sadece küçük bir balık…$"

Route12_Text_NedPostBattle::
    .string "Dur!\n"
    .string "İğnem takıldı!$"

Route12_Text_ChipIntro::
    .string "Sabırlı ol.\n"
    .string "Balık tutmak bekleme oyunudur.$"

Route12_Text_ChipDefeat::
    .string "O kaçtı!$"

Route12_Text_ChipPostBattle::
    .string "Daha iyi bir OLTA olsaydı,\n"
    .string "daha iyi POKéMON yakalayabilirdim…$"

Route12_Text_JustinIntro::
    .string "Bir AY TAŞI arıyorum.\n"
    .string "Sen buldun mu?$"

Route12_Text_JustinDefeat::
    .string "Auvv!$"

Route12_Text_JustinPostBattle::
    .string "POKéMON'umu bir AY TAŞI ile\n"
    .string "geliştirebilirdim.\p"
    .string "O zaman kazanırdım, bahse girerim.$"

Route12_Text_LucaIntro::
    .string "Uzmanlığım elektrik.\p"
    .string "Ama SU POKéMON'ları hakkında\n"
    .string "hiçbir şey bilmiyorum.$"

Route12_Text_LucaDefeat::
    .string "Fişim çekildi!$"

Route12_Text_LucaPostBattle::
    .string "Su elektriği ilettiği için\n"
    .string "SU POKéMON'larına şok yapmalısın.$"

Route12_Text_HankIntro::
    .string "BALIKÇI APTAL POKéMON\n"
    .string "ÇOCUĞU ile karşı karşıya!$"

Route12_Text_HankDefeat::
    .string "Çok fazla temas!$"

Route12_Text_HankPostBattle::
    .string "Sanırım sevdiğin şeyde\n"
    .string "iyi oluyorsun.\p"
    .string "POKéMON'da beni yendin,\n"
    .string "ama balık tutmada beni geçemezsin.$"

Route12_Text_ElliotIntro::
    .string "Balık tutmayı seviyorum,\n"
    .string "yanlış anlaşılmasın.\p"
    .string "Ama daha fazla işim olsa\n"
    .string "daha iyi olurdu.$"

Route12_Text_ElliotDefeat::
    .string "Kolay değil…$"

Route12_Text_ElliotPostBattle::
    .string "Sorun değil.\n"
    .string "Kaybetmek artık canımı sıkmıyor.$"

Route12_Text_AndrewIntro::
    .string "Yakalamak ne?\p"
    .string "Asla ne yakalayacağını bilemezsin!$"

Route12_Text_AndrewDefeat::
    .string "Kaybetti!$"

Route12_Text_AndrewPostBattle::
    .string "Ne, MAGIKARP mı?\p"
    .string "Onları sürekli yakalıyorum.\n"
    .string "Ama, çok güçsüzler.$"

Route12_Text_RouteSign::
    .string "ROTA 12\n"
    .string "LAVENDER'ın kuzeyi$"

Route12_Text_SportfishingArea::
    .string "BALIK TUTMA ALANI$"

Route12_Text_JesIntro::
    .string "JES: Kazanırsam, GIA'ya evlenme\n"
    .string "teklifi edeceğim.$"

Route12_Text_JesDefeat::
    .string "JES: Ah, lütfen, neden kazanmamıza\n"
    .string "izin vermedin?$"

Route12_Text_JesPostBattle::
    .string "JES: Ah, GIA, beni affet,\n"
    .string "sevgilim!$"

Route12_Text_JesNotEnoughMons::
    .string "JES: GIA ve ben, sonsuza\n"
    .string "dek birlikte olacağız.\p"
    .string "İki POKéMON'un olmadığı sürece\n"
    .string "seninle savaşamayız.$"

Route12_Text_GiaIntro::
    .string "GIA: Hey, JES…\p"
    .string "Eğer kazanırsak,\n"
    .string "seninle evleneceğim!$"

Route12_Text_GiaDefeat::
    .string "GIA: Ah, ama neden?$"

Route12_Text_GiaPostBattle::
    .string "GIA: JES, aptal!\n"
    .string "Bunu mahvettin!$"

Route12_Text_GiaNotEnoughMons::
    .string "GIA: JES olmadan savaşamam.\p"
    .string "Bir tane daha POKéMON'un yok mu?$"
