SaffronCity_Gym_Text_SabrinaIntro::
    .string "Gelişini önceden gördüm.\p"
    .string "Çocukluğumdan beri psişik\n"
    .string "güçlere sahibim.\p"
    .string "Bir kaşığı dikkatsizce\n"
    .string "fırlattığımda büküldüğünü\l"
    .string "görmemle başladı.\p"
    .string "Dövüşmeyi sevmiyorum,\n"
    .string "ama istersen güçlerimi göstermeye\l"
    .string "hazırım!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "Bu yenilgi beni şok etti!\n"
    .string "Ama yenilgi, yenilgidir.\p"
    .string "Kabul ediyorum, kazanmak\n"
    .string "için yeterince çalışmadım.\p"
    .string "Zaferinle BATAKLIK ROZETİ'ni\n"
    .string "hak ettin.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Psişik güç, sadece birkaç kişinin\n"
    .string "sahip olduğu bir şey değildir.\p"
    .string "Herkes psişik güce sahiptir.\n"
    .string "İnsanlar sadece bunun farkında\l"
    .string "değiller.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "BATAKLIK ROZETİ, SV. 70'e kadar\n"
    .string "olan POKéMON'ların size itaat\l"
    .string "etmesini sağlar.\p"
    .string "Daha güçlü POKéMON'lar vahşi hale\n"
    .string "gelebilir ve savaş sırasında\l"
    .string "emirlerinizi dinlemeyebilir.\p"
    .string "Bu sorunu önlemek için\n"
    .string "POKéMON'unuzu çok fazla\l"
    .string "yükseltmeyin.\p"
    .string "Dur, lütfen bu TM'yi de al.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER}, SABRINA'dan TM04 aldı.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04, SAKİNLEŞ içerir.\p"
    .string "POKéMON'un konsantre olmasını\n"
    .string "sağlar ve hem ÖZ. SLD hem de\l"
    .string "ÖZ. SVN'yı arttırır.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Çantanız diğer öğelerle dolu.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA, benden çok daha genç,\n"
    .string "ama saygımı kazandı.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Yeterli değil!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "Eşitler arasındaki bir savaşta,\n"
    .string "daha güçlü iradeye sahip olan\l"
    .string "kazanır.\p"
    .string "SABRINA'yı yenmek istiyorsan,\n"
    .string "odaklan ve zafer için kendini\l"
    .string "motive et.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Görünmeyen gücümüzden mi\n"
    .string "korkuyorsunuz?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "Bunu asla tahmin etmedim!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSİŞİK POKéMON'ların sadece\n"
    .string "hayaletlerden ve böceklerden\l"
    .string "korktuğunu unutma!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON, EĞİTMEN'lerine benzer.\p"
    .string "POKéMON'unuzun güçlü olması\n"
    .string "gerek, öyle değil mi?$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "Bunu biliyordum!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "Öğrenecek çok şeyim var…\p"
    .string "PSİŞİK'i ustalıkla öğrenmeli\n"
    .string "ve POKéMON'larıma öğretmeliyim…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "Anlıyorsun, değil mi?\p"
    .string "POKéMON dünyasında, sadece\n"
    .string "güç yetmez.$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "Buna inanamıyorum!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA, yan taraftaki\n"
    .string "KARATE USTASI'nı yendi.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "Senin ve benim POKéMON'larımız\n"
    .string "savaşacak!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "Yenildim!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "Bunun olacağını biliyordum.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA genç, ama aynı zamanda\n"
    .string "çok yetenekli bir LİDER.\p"
    .string "Onu kolay kolay yenemezsin!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Auv!\n"
    .string "Bayıldım!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "Eskiden SAFFRON'da iki tane\n"
    .string "POKéMON SALONU vardı.\p"
    .string "Ancak yan taraftaki DÖVÜŞ DOJOSU,\n"
    .string "SALON statüsünü kaybetti.\p"
    .string "Tek bir SALON olmaya karar\n"
    .string "verdiğimizde, onları yendik.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON SALONU, psişik eğitimi\n"
    .string "ile ünlüdür.\p"
    .string "SABRINA'yı görmek istiyorsun,\n"
    .string "değil mi? Anlayabiliyorum!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Auv!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "Evet, doğru! Zihninizi okuyabilmem\n"
    .string "için telepati kullandım!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon adayı!\p"
    .string "SABRINA'nın POKéMON'ları güç\n"
    .string "yerine psişik güç kullanır.\p"
    .string "DÖVÜŞ POKéMON'ları özellikle\n"
    .string "PSİŞİK POKéMON'lara karşı zayıftır.\p"
    .string "Bir yumruk bile atamadan\n"
    .string "yok olurlar!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psişik güç mü?$\n"
    .string "Eğer psişik güçlere sahip olsaydım\n"
    .string "slot makinelerinde bir servet\l"
    .string "kazanırdım!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON SALONU\n"
    .string "LİDER: SABRINA\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON SALONU\n"
    .string "LİDER: SABRINA\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}, {PLAYER}$"
