PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Bir ihtiyar dolandırıcı beni tuhaf\n"
    .string "bir balık POKéMON'u ile kandırdı!\p"
    .string "Çok güçsüz ve buna rağmen karşılığında\l¥500 ödedim!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "POKéMON'larını özenle yetiştirirsen\n"
    .string "harikalar yaratabilirsin.\p"
    .string "Onları bırakmaz ve geliştirirsen\n"
    .string "en zayıfları bile seni şaşırtabilir.$"
