PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Bir ihtiyar dolandırıcı beni\n"
    .string "tuhaf bir balık POKéMON'a kandırdı!\p"
    .string "Çok güçsüz ve buna ¥500 ödedim!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "POKéMON'larınızı özenle\n"
    .string "yetiştirirseniz iyi şeyler\l"
    .string "olabilir.\p"
    .string "Eğer onları bırakmazsanız zayıf\n"
    .string "olanlar bile sizi şaşırtır.$"
