PokemonTower_6F_Text_AngelicaIntro::
    .string "Bana…kan…\n"
    .string "ver…$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Ahh!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Zayıf ve kansız hissediyorum…$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Ahh…\n"
    .string "Aaaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Bir şey düştü!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "Saçım düşmedi!\n"
    .string "Kötü bir ruhtu!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "Burada ne oluyor?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Defolun…\n"
    .string "İstilacılar…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "Hayalet aslında CUBONE'un annesinin\n"
    .string "huzursuz ruhuydu!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "Annenin ruhu sakinleşti.\p"
    .string "Artık ahirete gitti…$"
