VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Suç işlerken POKéMON\n"
    .string "kullanan kötü insanlar var.\p"
    .string "Örneğin, ROKET TAKIMI nadir\n"
    .string "POKéMON ticareti yapıyor.\p"
    .string "Ayrıca popüler veya faydalı\n"
    .string "olmadıklarını düşündükleri\l"
    .string "POKéMON'ları terk ediyorlar.\p"
    .string "İşte bu ROKET TAKIMI'nın ne kadar\n"
    .string "korkunç insanlar olduğunu gösterir.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "POKéMONların iyi ya da kötü\n"
    .string "olabileceğini düşünüyorum. Her şey\l"
    .string "EĞİTMENİNE bağlı.$"
