Text_ExplosionTeach::
    .string "Düşünebiliyor musun?\n"
    .string "Bu yanardağ patlasa ne olurdu?\p"
    .string "Patlama bizim sonumuz olurdu.\n"
    .string "Ne kadar korkunç, değil mi?\p"
    .if ENG_MOVES == 1
    .string "Korkmuşken, EXPLOSION öğretmemi\n"
    .else
    .string "Korkmuşken, PATLAMA öğretmemi\n"
    .endif
    .string "ister misin?$"

Text_ExplosionDeclined::
    .string "Evet, haklısın.\n"
    .string "Çok korkutucu.$"

Text_ExplosionWhichMon::
    .string "Çok cesursun!\p"
    .if ENG_MOVES == 1
    .string "EXPLOSION'ı hangi POKéMON'a\n"
    .else
    .string "PATLAMA'yı hangi POKéMON'a\n"
    .endif
    .string "öğretmeliyim?$"

Text_ExplosionTaught::
    .string "Bu yanardağın üzerinde\n"
    .if ENG_MOVES == 1
    .string "EXPLOSION kullanmak…\p"
    .else
    .string "PATLAMA kullanmak…\p"
    .endif
    .string "Ne kadar korkutucu ve heyecan verici!$"

@ Aşağıdaki 4 satır, yukarıdaki metinlerin kullanılmayan JP versiyonlarıdır
Text_ExplosionTeachJP::
    .string "Bu yanardağ patlasa\n"
    .string "Ne olurdu, hepimiz ölürdük\l"
    .string "Ne kadar korkunç\l"
    .string "Öğrenmek ister misin?$"

Text_ExplosionDeclinedJP::
    .string "Evet, çok korkutucu\n"
    .string "Titriyorum!$"

Text_ExplosionWhichMonJP::
    .string "Çok cesursun!\n"
    .string "Hangi POKéMON'u seçmeliyim?$"

Text_ExplosionTaughtJP::
    .string "Yanardağ patladığında\n"
    .string "Çok heyecan verici!$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "Burada deneyelim.\n"
    .string "Burada kazmaya çalışacağız.\p"
    .string "YÖNETİCİ'lerin bahsettiği hazine\n"
    .string "burada olmalı.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "Ne…?\n"
    .string "Beni engelliyorsun. Defol.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "Oh, sonunda deldik.\n"
    .string "Hazine avına çıkalım!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "Bulduğumuz her hazineyi DEPO'ya\n"
    .string "taşımalıyız, anlaştık mı?\p"
    .string "…Ah, şifreler neydi?\n"
    .string "ROKET DEPOSU'ndaki şifreler.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "Ne, şifreyi unuttun mu?\n"
    .string "Aslında iki tane var.\p"
    .string "İlk şifre\n"
    .string "“GOLDEEN kütük istiyor”\p"
    .string "İkinci şifre ise…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "Hey!\n"
    .string "Bu hınzır bizi dinliyor!$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "Bizi gizlice dinliyordun,\n"
    .string "değil mi?$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "Hey, ne oluyor?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "Nasıl kazandın sen?$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "Hazinemize ortak mı olmak\n"
    .string "istiyorsun?\p"
    .string "Buna izin veremem!$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "Dur!\n"
    .string "Ama nasıl?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "Duymuş olduklarını unut!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "Bu bir yenilgi…\n"
    .string "Yeniden gruplanmamız gerekecek.\p"
    .string "Sen!\n"
    .string "Sakın içeri girmeyi bile düşünme!\p"
    .string "Kendi iyiliğin için,\n"
    .string "bunu aklından bile geçirme!$"

MtEmber_Exterior_Text_LoganIntro::
    .string "Aktif yanardağlar, patlamaya\n"
    .string "başlamış veya başlamak üzere olan\l"
    .string "yanardağlardır.$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "Ah… Bu çok sıcak!\n"
    .string "Kan ter içinde kaldım!$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "Dünyada 1.500'den fazla aktif\n"
    .string "yanardağ olduğu söyleniyor.\p"
    .string "Onları düşündükçe içim ısınıyor!$"

MtEmber_Exterior_Text_BethIntro::
    .string "Yanardağların içinde mağaraların\n"
    .string "nasıl oluştuğunu biliyor musun?$"

MtEmber_Exterior_Text_BethDefeat::
    .string "Atchah!\n"
    .string "Şaşırtıcı derecede iyisin!$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "Yüzeydeki lav sertleştiğinde\n"
    .string "ve içindeki magma aktığında,\l"
    .string "mağaralar oluşur.$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "Kırık kalbimi onarmak için\n"
    .string "antrenman yapıyorum…\p"
    .string "En azından fiziksel olarak beni\n"
    .string "güçlendiriyor! Haydi!$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "Galiba abarttım…$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "Savaşma şeklin, beni terk eden\n"
    .string "adama benziyor…$"
