SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "Ah, denizciler ve savaşlar!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "Doğru!\n"
    .string "İyi savaştın, kanka!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "Hahaha!\n"
    .string "Denizci olmak ister misin, kanka?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "Hadi bakalım!\n"
    .string "Denizci gururum söz konusu!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "Senin savaşçı ruhun beni yendi!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "VERMILION ŞEHRİ'ndeki BALIK\n"
    .string "GURU'sunu gördün mü?$"

