SixIsland_Text_IslandSign::
    .string "ALTINCI ADA\n"
    .string "Bilgelik Adası, Şans Adası$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .string "Bu yolda ilerlemeye devam et ve\n"
    .string "SU YOLU'na ulaşacaksın.\p"
    .string "Orada kal ve HARABE VADİ'ye\n"
    .string "ulaşacaksın.$"

SixIsland_Text_SkyAtNightIsFantastic::
    .string "Şehirden bu kadar uzakta olunca,\n"
    .string "gece gökyüzü muhteşem olur.$"
