Text_RockSlideTeach::
    .string "Kayalık bir dağdasın,\n"
    .string "kayalıklar tehlike yaratabilir.\p"
    .string "Düşünebiliyor musun?\n"
    .string "Kayalar üzerinize yuvarlanıyor?\p"
    .string "Waaaaaaaaaaah, çok korkutucu!\n"
    .string "Tam bir dehşet!\p"
    .string "Pek korkmuş gibi görünmüyorsun.\n"
    .ifdef ENG_NAMES
    .string "ROCK SLIDE'ı denemek ister misin?$"
    .else
    .string "KAYA DÜŞÜŞÜ'nü denemek ister misin?$"
    .endif

Text_RockSlideDeclined::
    .string "Öyleyse sonunda korkuyorsun.$"

Text_RockSlideWhichMon::
    .ifdef ENG_NAMES
    .string "Hangi POKéMON'a ROCK SLIDE\n"
    .else
    .string "Hangi POKéMON'a KAYA DÜŞÜŞÜ\n"
    .endif
    .string "öğretmeliyim?$"

Text_RockSlideTaught::
    .string "Bu tünelde kullanmak biraz\n"
    .string "korkutucu olabilir…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "İpucu: Kayalar suyun akışını\n"
    .string "değiştirebilir.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "TEHLİKE\n"
    .string "Hızlı akım!$"
