Text_RockSlideTeach::
    .string "Kayalık bir dağdasın,\n"
    .string "kayalıklar tehlike yaratabilir.\p"
    .string "Düşünebiliyor musun?\n"
    .string "Kayalar üzerinize yuvarlanıyor?\p"
    .string "Waaaaaaaaaaah, çok korkutucu!\n"
    .string "Tam bir dehşet!\p"
    .string "Korkmuş gibi görünmüyorsun.\n"
    .string "KAYA DÜŞÜŞÜ'nü denemek ister misin?$"

Text_RockSlideDeclined::
    .string "Öyleyse sonunda korkuyorsun.$"

Text_RockSlideWhichMon::
    .string "Hangi POKéMON'a KAYA DÜŞÜŞÜ\n"
    .string "öğretmeliyim?$"

Text_RockSlideTaught::
    .string "Bu tünelde kullanmak biraz\n"
    .string "korkutucu olabilir…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "İpucu: Kayalar suyun akışını\n"
    .string "değiştirebilir.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "TEHLİKE\n"
    .string "Hızlı akım!$"
