CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Ben mi?\n"
    .string "Ben programcıyım!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "Grafik tasarımcısıyım!\n"
    .string "Seni ben çizdim!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "Ben hikayeyi yazdım!\n"
    .string "ERIKA'ya bayılacaksın!\p"
    .string "MISTY'yi de çok seviyorum!\n"
    .string "Ve SABRINA, onu da seviyorum!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Öyle mi?\p"
    .string "Ben oyun tasarımcısıyım!\p"
    .string "POKéDEX'i tamamlamak zor,\n"
    .string "ama pes etme!\p"
    .string "Bittiğinde gel bana göster!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Vay canına! Harika!\n"
    .string "POKéDEX'ini tamamladın!\l"
    .string "Tebrikler!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "Bu oyun programı! Dokunursan\n"
    .string "oyunda hata olabilir!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "Birileri çalışmak yerine\n"
    .string "oyun oynuyor!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "Bu senaryo!\n"
    .string "Sonuna bakmamalısın!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "GAME FREAK\nGeliştirme Odası$"
