CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .string "POKéMON'un durum arttırıcıları\n"
    .string "sadece burada satın alınabilir.\p"
    .string "CAN ARTTIR, bir POKéMON'un\n"
    .string "MAKS CAN'ını arttırır.\p"
    .string "KALSİYUM, bir POKéMON'un\n"
    .string "ÖZ. SLD'sını arttırır.\p"
    .string "ÇİNKO, bir POKéMON'un\n"
    .string "ÖZ. SVN'sını yükseltir.\p"
    .string "KARBON, taban HIZ statülerini\n"
    .string "geliştirir.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .string "Ben POKéMON durum\n"
    .string "artırıcılar için buradayım.\p"
    .string "PROTEİN, bir POKéMON'un taban\n"
    .string "SALDIRI gücünü arttırır.\p"
    .string "DEMİR, bir POKéMON'un taban\n"
    .string "SAVUNMA statüsünü arttırır.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .string "5. Kat: ECZANE$"
