SilphCo_7F_Text_HaveMonForSavingUs::
    .string "Oh! Merhaba! Sen bir ROKET\n"
    .string "üyesi değilsin!\p"
    .string "Bizi kurtarmaya mı geldin?\n"
    .string "Oh, teşekkürler!\p"
    .string "Bizi kurtardığın için bu POKéMON'u\n"
    .string "sana vermek istiyorum.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER}, SILPH çalışanından\n"
    .string "bir LAPRAS elde etti!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Bu bir LAPRAS.\n"
    .string "Çok zeki bir POKéMON.\p"
    .string "Onu laboratuvarımızda tutuyorduk\n"
    .string "ama sen daha iyi bakabilirsin.\p"
    .string "LAPRAS'a karşı iyi bir EĞİTMEN\n"
    .string "olacağını düşünüyorum!\p"
    .string "Çok iyi yüzüyor.\n"
    .string "Sana suda yolculuk yapmada\l"
    .string "yardımcı olacak!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "ROKET TAKIMI'nın PATRON'u\n"
    .string "toplantı odasına gitti!\p"
    .string "BAŞKAN'ımız iyi mi?\n"
    .string "Endişeliyim.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "Sonunda kurtuldum, teşekkürler!$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "ROKET TAKIMI USTA TOP'un\n"
    .string "peşindeydi.\p"
    .string "USTA TOP tüm POKéMON'ları yakalar.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "ROKET TAKIMI yüzünden USTA TOP\n"
    .string "projesini iptal ettik.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "ROKET TAKIMI'nın SILPH'i veya\n"
    .string "POKéMON'larımızı kontrol\l"
    .string "etmesi kötü olurdu.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Vay!\p"
    .string "ROKET TAKIMI'nı tek başına\n"
    .string "mı kaçırdın?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "Sen!\n"
    .string "Burası gerçekten tehlikeli!\p"
    .string "Beni kurtarmaya mı geldin?\n"
    .string "Yapamazsın!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Çok teşekkürler!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Eyvah!\n"
    .string "Bir fare kokusu alıyorum!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Işıklar kapandı!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "Sadece dolaşarak patronumu\n"
    .string "bulamazsın!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Hehehe!\p"
    .string "Benim bir SILPH çalışanı\n"
    .string "olduğumu mu düşündün?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "Bitti!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Yaşına rağmen yetenekli bir eğitmensin!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "ROKET KARDEŞLER'den biriyim!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aaa!\n"
    .string "Kardeşler, yenildim!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Önemli değil.\n"
    .string "Kardeşlerim intikamımı alacak!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "Çocuk bir casus musun?\n"
    .string "Sen olmalısın!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Tamam!\n"
    .string "Yenildim!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Patronum sinirlenmeden git evine!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: Neden bu kadar uzun\n"
    .string "sürdü, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: Hahaha! Seni burada\n"
    .string "bekliyordum!\p"
    .string "ROKET TAKIMI'nın seni\n"
    .string "yavaşlattığını düşündüm!\p"
    .string "Umurumda değil!\p"
    .string "SAFFRON'da seni görmüştüm, bu yüzden\n"
    .string "gelip geliştiğini görmek istedim!$"

SilphCo_7F_Text_RivalDefeat::
    .string "Oh, adamım!\p"
    .string "Demek ki ROKET PATRONU'na\n"
    .string "meydan okumaya hazırsın!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“Hey sen!\p"
    .string "Bu yeteneklerle\n"
    .string "henüz yolun başında sayılırsın\l"
    .string "diyebilirim.$"

SilphCo_7F_Text_RivalPostBattle::
    .string "Evet, {PLAYER}!\n"
    .string "Ben daha da ileri gidiyorum!\p"
    .string "POKéDEX'imi kontrol ederken\n"
    .string "güçlü olanları ve evrimlerini\l"
    .string "görmeye başlıyorum!\p"
    .string "Ben bir dahiyim, değil mi?\p"
    .string "POKéMON LİGİ'ne gidip ELİT\n"
    .string "DÖRTLÜ'yü yeneceğim.\p"
    .string "Dünyanın en güçlü eğitmeni olacağım!\p"
    .string "{PLAYER}, sana bol şans!\n"
    .string "Endişelenme!\l"
    .string "Görüşürüz!$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİSİ\n"
    .string "7. Kat$"

