Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "Nöbet görevindeyim.\n"
    .string "Ama susadım!\p"
    .string "Dur, yol kapalı.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, o ÇAY…\n"
    .string "Çok lezzetli görünüyor…$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? Bu içeceği içebilir miyim?\n"
    .string "Teşekkürler!\l"
    .string "… …\l"
    .string "Yudum, yudum…\l"
    .string "… …\l"
    .string "Yutkun…\l"
    .string "Eğer SAFFRON\l"
    .string "ŞEHRİ'ne gitmek istiyorsan…\l"
    .string "… …\l"
    .string "Geçebilirsin.\p"
    .string "Bu ÇAY'ı diğer nöbetçilerle\n"
    .string "paylaşacağım!$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "Merhaba, nasıl gidiyor?$"
