SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "Hera, Hera, Heracross!\n"
    .string "Parlak ve büyük, böcek patronu!\l"
    .string "Seviyorum, ihtiyacım var, HERACROSS!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "Eeeeek!\n"
    .string "Bu bir HERACROSS!\p"
    .string "Lütfen, lütfen, ölçebilir miyim\n"
    .string "ne kadar büyük olduğunu?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "Eeeek, {STR_VAR_2} inç!\n"
    .string "Buna benzer bir şey görmedim!\l"
    .string "Bir ödül hak ettin!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "Çok daha büyük bir\n"
    .string "HERACROSS görmek istiyorum.\p"
    .string "Ah, onlara bayılıyorum, büyük\n"
    .string "HERACROSS!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "Huh? Bu {STR_VAR_2} inç…\n"
    .string "Ah, yine aynı.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "Ah, sadece {STR_VAR_2} inç.\n"
    .string "Önceki HERACROSS daha büyük.\p"
    .string "En büyüğü {STR_VAR_3} inçti,\n"
    .string "bana getirdiğin en büyük HERACROSS.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "Ah, hayır! Bu olmaz!\p"
    .string "HERACROSS daha maço görünüyor\n"
    .string "ve havalı, güzel bir boynuzu var!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "Çantan dolmuş.\n"
    .string "Ödülüm sığmayacak.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "Gördüğüm en büyük HERACROSS\n"
    .string "Şimdiye kadar ölçtüğüm:\p"
    .string "{STR_VAR_3} inç!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "Bu bir çeşit boş grafik.\p"
    .string "Kayıtları yazmak için alanlar var.$"
