ViridianCity_Gym_Text_GiovanniIntro::
    .string "Hahahaha!\n"
    .string "Sığınağıma hoş geldin!\p"
    .string "ROKET TAKIMI'nın eski şanını\n"
    .string "geri getirecektim.\p"
    .string "Ama yine de beni buldun.\n"
    .string "Öyle olsun.\l"
    .string "Bu sefer, geri durmayacağım!\p"
    .string "Bir kez daha en büyük EĞİTMEN\n"
    .string "GIOVANNI'ye karşı savaşacaksın!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "Ha!\n"
    .string "Gerçekten haşin bir savaş\l"
    .string "oldu. Kazandın!\p"
    .string "Kanıt olarak, sana DÜNYA ROZETİ'ni\n"
    .string "veriyorum!\p"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "Bu şekilde kaybettiğim için,\n"
    .string "takipçilerimin yüzüne bakamam.\l"
    .string "Güvenlerini boşa çıkardım.\p"
    .string "Bugünden itibaren, ROKET TAKIMI\n"
    .string "sonsuza dek bitti!\p"
    .string "Kendimi tekrar antrenman\n"
    .string "yapmaya adadım.\p"
    .string "Bir gün tekrar görüşelim!\n"
    .string "Hoşça kal!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "DÜNYA ROZETİ, tüm POKéMON'ların\n"
    .string "körü körüne itaat etmesini sağlar.\p"
    .string "Bu, bir POKéMON EĞİTMENİ\n"
    .string "olarak ustalığının kanıtıdır.\p"
    .string "Bununla, POKéMON LİGİ'ne\n"
    .string "katılabilirsin.\p"
    .string "Ayrıca, bu TM'yi al.\p"
    .string "Onu POKéMON LİGİ mücadelen için\n"
    .string "bir hediye olarak düşün.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER}, GIOVANNI'den TM26\n"
    .string "aldı.$"

ViridianCity_Gym_Text_ExplainTM26::
    .if ENG_MOVES == 1
    .string "TM26, EARTHQUAKE'i içerir.\p"
    .else
    .string "TM26, DEPREM'i içerir.\p"
    .endif
    .string "Bu, güçlü bir saldırıdır ve\n"
    .string "büyük bir sarsıntıya neden olur.\p"
    .string "Bu, çok uzun zaman önce buradaki\n"
    .string "SALONU çalıştırdığımda yapıldı…$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "Bunu almak için yerin yok!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "Heh!\p"
    .string "Şimdi yorulmuş olmalısın\n"
    .string "diye düşünüyorum!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "Yakıt bitti!$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "SALON LİDER'imizle başa çıkmak\n"
    .string "için güce ihtiyacın olacak.$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "Rrrrooaa!\n"
    .string "Kendimi öfkeye kaptırıyorum!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "Vaaahh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "Hala yeterli değilim!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "POKéMON'larla birlikte\n"
    .string "müthiş müzik yapıyoruz!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "Mükemmel bir uyum içindesiniz!$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "SALON LİDER'imizin kimliğini\n"
    .string "biliyor musun?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "Karate, dövüş sanatlarının\n"
    .string "en üst seviyesidir!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "Keşke POKéMON'um karateyi\n"
    .string "benim kadar iyi bilseydi…$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "Gerçekten yetenekli olanlar stil\n"
    .string "ile kazanır.$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "Kontrolümü kaybettim!$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "LİDER, bu şekilde kaybettiğim\n"
    .string "için beni azarlayacak…$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "Ben KARATE KRALI'yım!\n"
    .string "Kaderin benimle!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "POKéMON LİGİ mi?\n"
    .string "Sen? Çok kendini beğenme!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "POKéMON'un, kırbaç sesimi\n"
    .string "duyduğunda korkacak!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "Auv!$\n"
    .string "Kırbaç darbesi!$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "Dur!\n"
    .string "Sadece dikkatsizdim!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "VİRİDİAN SALONU uzun süredir\n"
    .string "kapalıydı.\p"
    .string "Ama şimdi, LİDER'imiz geri\n"
    .string "döndü!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "Yenildim mi?$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "SALON LİDER'imizi yenmeden\n"
    .string "POKéMON LİGİ'ne katılamazsın!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon adayı!\p"
    .string "VIRIDIAN LİDER'inin kimliğini\n"
    .string "ben bile bilmiyorum.\p"
    .string "Ama bir şey kesin.\n"
    .string "Bu, tüm SALON LİDER'lerinden\l"
    .string "en zorlu olanı olacak.\p"
    .string "Ayrıca, VIRIDIAN eğitmenlerinin\n"
    .string "YER türündeki POKéMON'ları\l"
    .string "sevdiğini duydum.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "Aklımı başımdan alıyorsun!\n"
    .string "VİRİDİAN'ın SALON LİDERİ\l"
    .string "GIOVANNI miydi?$"

ViridianCity_Gym_Text_GymStatue::
    .string "VİRİDİAN POKéMON SALONU\n"
    .string "LİDER: ?\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRIDIAN POKéMON SALONU\n"
    .string "LİDER: GIOVANNI\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}, {PLAYER}$"
