RocketHideout_B1F_Text_Grunt1Intro::
    .string "Sen kimsin?\n"
    .string "Buraya nasıl girdin?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Auv!\n"
    .string "Yenildim!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Vay canına… ROKET TAKIMI'nı\n"
    .string "küçümsüyorsun, değil mi?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "ROKET TAKIMI'nın operasyonuna\n"
    .string "çomak soktun?! Ne cesaret!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "Bum!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "Bundan kurtulamayacaksın,\n"
    .string "yaramaz çocuk!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "Kaçak var!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "Yapamıyorum!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "SILPH GÖZLÜK? Hıh!\n"
    .string "Nerede olduğunu bilmiyorum.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "Neden buraya geldin?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "Bu olmamalı!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "Tamam, konuşacağım…\n"
    .string "PATRONU görmek için asansöre bin.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "Kayıp mı oldun, küçük fare?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Neden…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "Uh-oh, o gürültü bir\n"
    .string "şekilde kapıyı açtı!$"

