RocketHideout_B4F_Text_GiovanniIntro::
    .string "Hey! Buraya geldiğinize şaşmamak\n"
    .string "elde değil.\p"
    .string "ROKET TAKIMI dünyadaki tüm\n"
    .string "POKéMON'ları yakalar.\p"
    .string "Suç imparatorluğumuzu ayakta\n"
    .string "tutmak için önemli araçlardır.\p"
    .string "Ben liderleriyim, GIOVANNI!\p"
    .string "Cesaretin için acı dolu\n"
    .string "bir son göreceksin!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "NE!\n"
    .string "Bu mümkün değil!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "POKéMON'larını çok iyi\n"
    .string "yetiştirdiğini görüyorum.\p"
    .string "Senin gibi bir çocuk asla benim\n"
    .string "ulaşmak istediklerimi anlayamaz.\p"
    .string "Bu seferlik yolunu açacağım!\p"
    .string "Tekrar karşılaşacağımızı umuyorum…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "Seni tanıyorum!\p"
    .string "AY DAĞI'ndaki planlarımızı\n"
    .string "bozmuştun!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Yenildim yine!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "ROKET TAKIMI'na karşı\n"
    .string "bir şeyin mi var?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "Kötülüğümüzün güzelliğini\n"
    .string "nasıl görmezden gelebilirsin?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "PATRON!\n"
    .string "Seni hayal kırıklığına\l"
    .string "uğrattığım için üzgünüm!$"

RocketHideout_B4F_Text_Grunt1Intro::
    .string "Asansör çalışmıyor mu?\n"
    .string "ANAHTAR kimin elinde?$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "Hayır!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
    .string "Oh, hayır!\n"
    .string "ANAHTAR'ı düşürdüm!$"

