SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "Nasıl gireceğimi kestiremiyorum.\n"
    .string "İçeri girmek için ne yapmam gerek?$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "Sana bir şey söyleyeyim mi, burayı\n"
    .string "ben keşfettim.\p"
    .string "Bana öyle imrenerek bakma, olur mu?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "Kapı kıpırdamıyor bile.\n"
    .string "Daha dikkatli bir şekilde\l"
    .string "kontrol etmeli miyim?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER}, kapıya dokunmadı.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "Yakından bakınca, kapıda birçok\n"
    .string "nokta var…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "Kapı açık.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "Görünüşe göre, bu dünyada hala\n"
    .string "çözülmeyi bekleyen birçok sır var.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "Hmm…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "Sana da önerim, dünyanın sırlarını\n"
    .string "ve gizemlerini her gün düşünmen.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "Merak ediyorum, seni buraya\n"
    .string "getiren şey neydi?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "Çok uzun zamandır savaşmamıştım,\n"
    .string "içgüdülerim körelmiş.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "SEVII ADALARI'nda birçok\n"
    .string "enkaz var.\p"
    .string "Çoğunluğu çok eski.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "Bu adada gizemli taşlar\n"
    .string "olduğu söyleniyor.\p"
    .string "Sanırım bu enkazla bir ilgisi var.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "Oh, ilginç.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "Oradaki enkazlar…\p"
    .string "İçeri nasıl gireceğimi bulamadım.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "Seninle, bu yükseklikte savaşmak!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "Ah, sana karşı bu kadar\n"
    .string "kolay yenilmek!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "Tırmanmanın keyfini çıkar!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "Bu civarda olan bitenlere oldukça\n"
    .string "vakıfım.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "Bana bu kadar baskı yapmana\n"
    .string "gerek yok.\l"
    .string "Sana seve seve söylerim.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "Enkazın kapısı…\n"
    .string "Dışında garip desenler var.\l"
    .string "Ama anlamını bilmiyorum.$"
