SafariZone_North_Text_RestHouse::
    .string "DİNLENME EVİ$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "GİZLİ EV hala ileride.$"

SafariZone_North_Text_Area2::
    .string "ALAN 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "POKéMON'lar uzun otlarda saklanır.\p"
    .string "Onları dışarı çıkarmak için otlu\n"
    .string "alanlarda zikzaklar çizin.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "GİZLİ EV'i bulun ve ücretsiz\n"
    .string "HM kazanın.$"
