VictoryRoad_2F_Text_DawsonIntro::
    .string "Buradan geçebilirsen,\n"
    .string "ELİT DÖRTLÜ'ye gidebilirsin.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "Hayır!\n"
    .string "İnanılmaz!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "POKéMON bilgisi konusunda\n"
    .string "beni yenebilirsin!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "Burası ZAFER YOLU.\n"
    .string "EĞİTMEN'lerin son sınavı!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "Hapşuu!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "Sıkışırsan, bazı kayaları\n"
    .string "ittirebilirsin.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "Ah, demek ELİT DÖRTLÜ'ye meydan\n"
    .string "okumak istiyorsun?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "Beni yendin!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} da buradan geçti.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "Haydi!\n"
    .string "Seni yeneceğim!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "Dayak yedim!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "ZAFER YOLU'nda olmaya\n"
    .string "hak kazandın…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "ZAFER YOLU çok mu zor?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "Çok iyi!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "Birçok EĞİTMEN burada\n"
    .string "mücadeleyi bırakıp eve döner.$"

