SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "SAFARI BÖLGESİ devasa, değil mi?\p"
    .string "FUCHSIA SALON LİDERİ,\n"
    .string "KOGA, sık sık devriye geziyor.\p"
    .string "Sayesinde, burada oynarken\n"
    .string "güvende olduğumuzu biliyoruz.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "POKéMON'a TAŞ atmak onları\n"
    .string "kaçırtabilir, ama yakalamak da\l"
    .string "daha kolay olur.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "YEM kullanmak, POKéMON'un\n"
    .string "dikkatini çeker ve burada\l"
    .string "kalmasını sağlar.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "Çok gezdim ama istediğim\n"
    .string "POKéMON'a rastlayamadım.$"
