SSAnne_Deck_Text_ShipDepartingSoon::
    .string "Parti bitti.\n"
    .string "Gemi yakında ayrılacak.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "Of!\n"
    .string "Güverteleri temizlemek zor iş!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "Urf… Hasta gibiyim…\p"
    .string "Deniz tutması yaşadım, bu yüzden\n"
    .string "biraz hava almaya çıktım.$"

SSAnne_Deck_Text_EdmondIntro::
    .string "Hey, kanka!\p"
    .string "Biraz dans edelim!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "Sen inanılmazsın!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "Bu büyük dünyada kaç çeşit\n"
    .string "POKéMON olduğunu düşünüyorsun?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "Ahoy!\n"
    .string "Deniz tutması mı yaşıyorsun?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "Dikkatsiz davrandım!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "Babam dünyada 100 çeşit POKéMON\n"
    .string "olduğunu söyledi. Bence daha fazla.$"

