FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Mağaradaki POKéMON'lara\n"
    .string "kirli ellerini sürme!\p"
    .string "Söylediğimi yapmazsan,\n"
    .string "hesabını sorarım!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Ah, susun hanımefendi, ve\n"
    .string "bizi yalnız bırakın.\p"
    .string "Gözlüklerinizin buhar\n"
    .string "toplamasına izin vermeyin!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Burada ne yapıyorsun?\p"
    .string "Hayır, daha sonra selamlaşırız.\n"
    .string "Şu anda, yardımına ihtiyacım var.\p"
    .string "Lütfen bu kaçak avcıları dışarı\n"
    .string "atmadan başka bir şey yapmalarına\l"
    .string "izin verme.\p"
    .string "Buradaki POKéMON'ları yakalayıp\n"
    .string "sonra da satıyorlar!\p"
    .string "Hazır mısın?\n"
    .string "Şuradakini indir lütfen!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "W-ne?!\p"
    .string "Kim bizim yakaladığımız\n"
    .string "POKéMON'larla istediğimizi\l"
    .string "yapamayacağımızı söylüyor?\p"
    .string "Bizimle mi tartışıyorsun?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Bunu planlamamıştık!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hım.\n"
    .string "Aşağılanasıca zayıf.\p"
    .string "Sen!\n"
    .string "Söyle bana!\p"
    .string "Yakalanan POKéMON'ları nereye\n"
    .string "götürdün?\p"
    .string "Suratını ilk ve son defa\n"
    .string "dağıtacağım!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "A-asla!\n"
    .string "Sana bunu söylemem!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Eğer itiraf etmeyeceksen,\n"
    .string "seni donduracağız.\p"
    .string "LAPRAS arkadaşlarına yaptıklarınız\n"
    .string "için çok öfkeli.\p"
    .string "Haydi, LAPRAS!\n"
    .string "BUZ IŞINI…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Vavaah! Tamam!\n"
    .string "Konuşacağım!\p"
    .string "POKéMON'lar BEŞİNCİ ADA'da\n"
    .string "ROKET DEPOSU'nda.\p"
    .string "İşte! Söyledim!\n"
    .string "Şimdi gidiyoruz!\p"
    .string "…Ama ROKET DEPOSU'na asla\n"
    .string "girebileceğinizi sanmıyorum!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, teşekkür ederim.\n"
    .string "Ama bu korkunç…\p"
    .string "Bu adalarda doğdum ve büyüdüm.\p"
    .string "Bu korkunç suçluların burada\n"
    .string "serbestçe gezdiğinden haberim\l"
    .string "yoktu…$"
