FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "LORELEI: Mağaradaki POKéMON'lara\n"
    .string "kirli ellerini sürme!\p"
    .string "Söylediğimi yapmazsan,\n"
    .string "hesabını sorarım!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "Ah, susun, hanımefendi, ve\n"
    .string "bizi yalnız bırakın.\p"
    .string "Gözlüklerinizin buhar\n"
    .string "toplamasına izin vermeyin!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "LORELEI: {PLAYER}?!\n"
    .string "Burada ne yapıyorsun?\p"
    .string "Hayır, daha sonra yakalayabiliriz.\n"
    .string "Şu anda, yardımına ihtiyacım var.\p"
    .string "Lütfen bu kaçak avcıları dışarı\n"
    .string "atmadan önce başka bir şey\l"
    .string "yapmalarına izin verme.\p"
    .string "Buradaki POKéMON'ları yakalayıp\n"
    .string "sonra da satıyorlar!\p"
    .string "Hazır mısın?\n"
    .string "Lütfen o birini al!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "W-ne?!\p"
    .string "Kim bizim yakaladığımız\n"
    .string "POKéMON'larla istediğimizi\l"
    .string "yapamayacağımızı söylüyor?\p"
    .string "Bizimle mi tartışıyorsun?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "Bunu planlamamıştık!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "LORELEI: Hıphızır.\n"
    .string "O kadar iğrenç bir şekilde\n"
    .string "zayıf.\p"
    .string "Sen!\n"
    .string "Bana söyle!\p"
    .string "Yakalanan POKéMON'ları nereye\n"
    .string "götürdün?\p"
    .string "Halkamı bir kez ve herkes için\n"
    .string "parçalıyorum!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "Yok artık!\n"
    .string "Sana bunu söylemeyeceğim!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "LORELEI: Eğer itiraf etmeyeceksen,\n"
    .string "derin dondurucuya koyacağız.\p"
    .string "LAPRAS, arkadaşlarına yaptığınız\n"
    .string "şey için öfkelidir.\p"
    .string "Haydi, LAPRAS!\n"
    .string "ICE BEAM…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "Vay canına! Tamam!\n"
    .string "Konuşacağım!\p"
    .string "POKéMON'lar BEŞİNCİ ADA'da\n"
    .string "ROKET DEPOSU'nda.\p"
    .string "İşte bu! Bunu söyledim!\n"
    .string "Şimdi gidiyoruz!\p"
    .string "…Ama asla ROKET DEPOSU'na\n"
    .string "giremeyeceğinizi düşünüyorum!\p"
    .string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, teşekkür ederim.\n"
    .string "Ama bu korkunç…\p"
    .string "Bu adalarda doğdum ve büyüdüm.\p"
    .string "Bu korkunç suçluların burada\n"
    .string "serbest bırakıldığından haberim\l"
    .string "yoktu…$"
