CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "O acınası ROKET TAKIMI!\p"
    .string "Bak neler yapmışlar evime!\p"
    .string "Bir POKéMON'a çukur KAZMAYI\n"
    .string "öğreten TM çaldılar!\p"
    .string "Bir MANKEY veya SANDSHREW'de\n"
    .string "kullanacaktım…$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "Kaybolduğunu kabullendim.\p"
    .string "DIGLETT'e bir TM olmadan KAZ\n"
    .string "öğretmeye karar verdim.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "ROKET TAKIMI bir kötülük için\n"
    .string "çukur kazmaya çalışıyor!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "ROKET TAKIMI bir çıkış yolu\n"
    .string "bıraktı!$"

