LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "O korkunç ROKET TAKIMI!\n"
    .string "Merhameti asla hak etmiyorlar!\p"
    .string "Zavallı CUBONE'un annesi…\p"
    .string "ROKET TAKIMI'ndan kaçmaya\n"
    .string "çalışırken öldürüldü.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "POKéMON KULESİ'nin hayaleti\n"
    .string "gitti!\p"
    .string "Birisi mutlaka huzursuz ruhunu\n"
    .string "teskin etmiş olmalı!$"
