SaffronCity_House_Text_DontLookAtMyLetter::
    .string "Teşekkürler yazdığın için.\n"
    .string "Umarım yakında görüşürüz!\p"
    .string "Hey!\n"
    .string "Mektubuma bakma!$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .string "TAKLİTÇİ çok tatlı!\n"
    .string "Onun için bir POKé BEBEK alıyorum.$"

SaffronCity_House_Text_ExplainPPUp::
    .string "Bir PP ARTIRICI hediye aldım.\p"
    .string "Bir POKéMON'un hamlesinin PP'sini\n"
    .string "arttırmak için kullanılır.\p"
    .string "Sadece az PP'si olan güçlü bir\n"
    .string "hamle için kullanmalıyım.$"
