SSAnne_2F_Room2_Text_BrooksIntro::
    .string "Gençlerle yarışmak beni genç tutuyor.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "İyi maç!\n"
    .string "Ah, gençliğime döndüm sanki!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "On beş yıl önce kazanırdım!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "Bak neler yakaladım!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "Bitti, daha yok!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "Parti bitti mi?\p"
    .string "Gemi partisi sona ermiş olmalı.$"

