FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "LORELEI: Aklımı kurcalayan bir şey var.\n"
    .string "Doğduğum adaya bir şey olursa…\p"
    .string "POKéMON LİGİ'nde olsam haberim olmaz.\p"
    .string "Acaba bu beni sorumsuz mu yapar?\p"
    .string "Bu beni evime karşı sorumsuz mu yapar?$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "LORELEI: Yani, buradaki tüm\n"
    .string "sorunları çözdün mü?\p"
    .string "Harika.\p"
    .string "Bu, burada sürekli kalmam için bir\n"
    .string "sebep olmadığı anlamına geliyor.\p"
    .string "Teşekkürler…\p"
    .string "Kısa bir süre içinde POKéMON\n"
    .string "LİGİ'ne döneceğim.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "Gelecekte ne olacağını\n"
    .string "bilmiyorum, ama…\p"
    .string "Şimdilik yapabileceğimi yapacağım.\n"
    .string "Yalnızca bunu yapabilirim.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "Her yer POKéMON peluş oyuncaklarla\n"
    .string "dolu!$"
