Route4_Text_TrippedOverGeodude::
    .string "Ayy! Taştan bir POKéMON'a\n"
    .string "takıldım, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "Mantar POKéMON'lar için\n"
    .string "AY DAĞI'na geldim.$"

Route4_Text_CrissyDefeat::
    .string "Onca emeğime yazık oldu!$"

Route4_Text_CrissyPostBattle::
    .string "Burada artık mantar\n"
    .string "kalmadı sanırım.\p"
    .string "Bence hepsini topladım.$"

Route4_Text_MtMoonEntrance::
    .string "AY DAĞI\n"
    .string "Mağara Girişi$"

Route4_Text_RouteSign::
    .string "ROUTE 4\n"
    .string "AY DAĞI - CERULEAN ŞEHRİ$"

Text_MegaPunchTeach::
    .string "Gürültülü bir yumruk!\p"
    .string "Yıkıcı güçle dolu!\p"
    .string "Zor durumda kaldığında,\n"
    .ifdef ENG_NAMES
    .string "MEGA PUNCH en iyi saldırı!\l"
    .else
    .string "MEGA YUMRUK en iyi saldırı!\l"
    .endif
    .string "Katılıyor musun?\p"
    .string "Hadi!\n"
    .string "Şimdi POKéMON'una öğretelim!$"

Text_MegaPunchDeclined::
    .ifdef ENG_NAMES
    .string "MEGA PUNCH'ın değerini\n"
    .else
    .string "MEGA YUMRUK'ün değerini\n"
    .endif
    .string "anladığında geri dönersin.$"

Text_MegaPunchWhichMon::
    .string "Tamam!\n"
    .string "Hangi POKéMON öğrenecek?$"

Text_MegaPunchTaught::
    .string "Şimdi yumruk yoldaşı\n"
    .string "olduk!\p"
    .string "Şu yanlış eğitilen salak seni\n"
    .string "görmeden gitmelisin,\l"
    .string "kafayı tekme atmakla bozmuş.$"

Text_MegaKickTeach::
    .string "Vahşi bir tekme!\p"
    .string "Yıkıcı güçle dolu!\p"
    .ifdef ENG_NAMES
    .string "Esas mesele şu ki, MEGA KICK\n"
    .else
    .string "Esas mesele şu ki, MEGA TEKME\n"
    .endif
    .string "en iyi saldırı!\l"
    .string "Katılıyor musun?\p"
    .string "Tamam!\n"
    .string "POKéMON'una öğreteceğim!$"

Text_MegaKickDeclined::
    .ifdef ENG_NAMES
    .string "MEGA KICK'in değerini\n"
    .else
    .string "MEGA TEKME'nin değerini\n"
    .endif
    .string "anladığında geri döneceksin.$"

Text_MegaKickWhichMon::
    .string "Harika!\n"
    .string "Hangi POKéMON öğrenecek?$"

Text_MegaKickTaught::
    .string "Şimdi tekme ruh ikiziyiz!\p"
    .string "Görülmeden gitmelisin,\n"
    .string "Şu yanlış eğitilen salak seni\l"
    .string "görmeden gitmelisin,\l"
    .string "kafayı tekme atmakla bozmuş.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Vay canına, bu KAYA ROZETİ!\n"
    .string "BROCK'tan aldın, değil mi?\p"
    .string "BROCK çok havalı. Sadece güçlü\n"
    .string "değil, sevilen ve saygı duyulan\l"
    .string "biri. Onun gibi bir SALON\l"
    .string "LİDERİ olmak istiyorum.$"
