VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Kirliliğe dikkat ediyoruz.\p"
    .string "GRIMER'ın toksik çamurda\n"
    .string "çoğaldığını duyduk.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Liman'da demirlemiş S.S. ANNE'yi\n"
    .string "gördün mü?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "Öyleyse, S.S. ANNE ayrıldı mı?\p"
    .string "Bir yıl sonra bu zamanlarda\n"
    .string "tekrar VERMILION'da olacak.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "Bu arsa üzerinde bir bina\n"
    .string "inşa ediyorum. Hepsi benim.\p"
    .string "POKéMON'um toprağı eziyor\n"
    .string "temel oluşturmak için.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guooh! Goh goh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "Bir MACHOP toprağı düzleştiriyor.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S. ANNE, lüks bir kruvazördür.\p"
    .string "Yılda bir kez VERMILION'a uğrar.$"

VermilionCity_Text_CitySign::
    .string "VERMILION ŞEHRİ\n"
    .string "Muhteşem Günbatımının Limanı$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "DİKKAT!\p"
    .string "ROTA 12, uyuyan bir POKéMON\n"
    .string "tarafından engellenmiş olabilir.\p"
    .string "KAYA TÜNELİ üzerinden\n"
    .string "LAVENDER KASABASI'na gidin.\p"
    .string "VERMILION POLİSİ$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN KULÜBÜ\n"
    .string "Tüm POKéMON hayranlarını bekleriz!$"

VermilionCity_Text_GymSign::
    .string "VERMILION POKéMON SALONU\n"
    .string "LİDER: TEĞMEN SURGE\l"
    .string "Yıldırım Amerikalı!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION LİMANI$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "S.S. ANNE'e Hoş Geldiniz!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "S.S. ANNE'e Hoş Geldiniz!\p"
    .string "Biletin var mı?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} S.S. Biletini gösterdi!\p"
    .string "{FONT_MALE}Harika!\n"
    .string "S.S. ANNE'e Hoş Geldiniz!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER} gerekli\n"
    .string "S.S. Biletine sahip değil.\p"
    .string "{FONT_MALE}Üzgünüm!\p"
    .string "Gemiye binmek için bilete ihtiyacınız var.$"

VermilionCity_Text_TheShipSetSail::
    .string "Gemi yelken açtı.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "Ah, ÜÇLÜ-BİLET'e sahipsin.\p"
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Tamam, her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 7 hemen\n"
    .string "ayrılacak.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "Ah, PRİZMA BİLETine sahipsin.\p"
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Oh! O bir MİSTİK BİLET!\n"
    .string "Bu gerçekten nadir.\p"
    .string "Sizi her zaman NAVEL KAYASINA\n"
    .string "götürmekten mutluluk duyarız.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Oh! O bir AURORA BİLETİ!\n"
    .string "Bu gerçekten nadir.\p"
    .string "Sizi her zaman DOĞUM ADASI'na\n"
    .string "götürmekten mutluluk duyarız.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Tamam, özel bir feribota binmek\n"
    .string "için her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 10 hemen\n"
    .string "ayrılacak.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Tamam, özel bir feribota binmek\n"
    .string "için her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 12 hemen\n"
    .string "ayrılacak.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Oh, merhaba, {PLAYER}!\n"
    .string "Nasılsın?\p"
    .string "BEN PROF. OAK'ın YARDIMCISIYIM.\p"
    .string "Diğer YARDIMCI'yı gördün mü?\p"
    .string "PROF. OAK'den sana bir paketi\n"
    .string "vardı, {PLAYER}.\p"
    .string "O, ROTA 2 civarında seni arayacak\n"
    .string "dedi, {PLAYER}.\p"
    .string "Eğer ROTA 2 bölgesindeyseniz,\n"
    .string "lütfen onu arayın.$"
