VermilionCity_Text_GrimerMultipliesInSludge::
    .string "Kirliliğe dikkat ediyoruz.\p"
    .string "GRIMER'ın toksik çamurda\n"
    .string "çoğaldığını duyduk.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "Liman'da demirlemiş S.S. ANNE\n"
    .string "gemisini gördün mü?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "Hey, S.S. ANNE ayrıldı mı?\p"
    .string "Bir yıl sonra bu zamanlarda\n"
    .string "tekrar VERMILION'da olacak.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "Bu arsa üzerinde bir bina inşa\n"
    .string "ediyorum. Burası benim.\p"
    .string "POKéMON'um temel oluşturmak için\n"
    .string "toprağı eziyor.$"

VermilionCity_Text_Machop::
    .string "MACHOP: Guooh! Goh goh!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "Bir MACHOP toprağı düzleştiriyor.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "S.S. ANNE, lüks bir kruvazördür.\p"
    .string "Yılda bir kez VERMILION'a uğrar.$"

VermilionCity_Text_CitySign::
    .string "VERMILION ŞEHRİ\n"
    .string "Muhteşem Günbatımının Limanı$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "DİKKAT!\p"
    .string "ROTA 12, uyuyan bir POKéMON\n"
    .string "tarafından engellenmiş olabilir.\p"
    .string "KAYA TÜNELİ üzerinden LAVENDER\n"
    .string "KASABASI'na gidebilirsiniz.\p"
    .string "VERMILION POLİSİ$"

VermilionCity_Text_PokemonFanClubSign::
    .string "POKéMON FAN KULÜBÜ\n"
    .string "Tüm POKéMON hayranlarını bekleriz!$"

VermilionCity_Text_GymSign::
    .string "VERMILION POKéMON SALONU\n"
    .string "LİDER: TEĞMEN SURGE\l"
    .string "Yıldırım Amerikalı!$"

VermilionCity_Text_VermilionHarbor::
    .string "VERMILION LİMANI$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "S.S. ANNE'e hoş geldiniz!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "S.S. ANNE'e hoş geldiniz!\p"
    .string "Biletiniz var mı?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} S.S. biletini gösterdi!\p"
    .string "{FONT_MALE}Harika!\n"
    .string "S.S. ANNE'e hoş geldiniz!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "{FONT_NORMAL}{PLAYER}, gerekli S.S. biletine\n"
    .string "sahip değil.\p"
    .string "{FONT_MALE}Üzgünüm!\p"
    .string "Gemiye binmek için bilete\nihtiyacınız var.$"

VermilionCity_Text_TheShipSetSail::
    .string "Gemi yelken açtı.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "ÜÇLÜ-BİLET'e sahipsiniz.\p"
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_Seagallop7Departing::
    .string "Tamam, her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 7 feribotu\n"
    .string "birazdan kalkıyor.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "PRİZMA BİLETine sahipsiniz.\p"
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "Hey! Bu bir MİSTİK BİLET!\n"
    .string "Bu gerçekten nadir.\p"
    .string "Sizi her zaman GÖBEKLİ KAYA'ya\n"
    .string "götürmekten mutluluk duyarız.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "Hey! Bu bir AURORA BİLETİ!\n"
    .string "Bu gerçekten nadir.\p"
    .string "Sizi her zaman DOĞUM ADASI'na\n"
    .string "götürmekten mutluluk duyarız.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "SEAGALLOP feribotuna binmek ister\n"
    .string "misiniz?$"

VermilionCity_Text_Seagallop10Departing::
    .string "Tamam, özel bir feribota binmek\n"
    .string "için her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 10 feribotu\n"
    .string "birazdan kalkıyor.$"

VermilionCity_Text_Seagallop12Departing::
    .string "Tamam, özel bir feribota binmek\n"
    .string "için her şey yolunda.\p"
    .string "SEAGALLOP YÜKSEK-HIZ 12 feribotu\n"
    .string "hemen kalkıyor.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "Merhaba, {PLAYER}!\n"
    .string "Nasılsın?\p"
    .string "Ben PROF. OAK'ın YARDIMCISIYIM.\p"
    .string "Diğer YARDIMCI'yı gördün mü?\p"
    .string "PROF. OAK'dan senin için bir\n"
    .string "paketi vardı, {PLAYER}.\p"
    .string "Dedi ki ROTA 2 civarında seni\n"
    .string "arayacakmış, {PLAYER}.\p"
    .string "Eğer ROTA 2 civarındaysan,\n"
    .string "lütfen onu bul.$"
