@ Tüm Eğitmen Kulesi metni (Lobi ve Çatı) burada iç içe geçmiştir

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
.string "Merhaba!\p"
.string "Hoş geldin EĞİTMEN KULESİ'ne, burada\n"
.string "eğitmenler her yerden toplanıyor!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
.string "Dünyanın dört bir yanından gelen\n"
.string "eğitmenler burada savaşmak için\p"
.string "bekliyorlar. Bir bakalım…\p"
.string "Şu anda, eğitmenler sadece\n"
.string "{STR_VAR_1}. kata kadar var.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
.string "Sekizinci kata kadar eğitmenler\n"
.string "sizi bekliyor.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
.string "Bekleyen eğitmenleri yenmeye ne\n"
.string "dersin?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
.string "Tamam, saati başlatacağım,\n"
.string "bunun için hazır ol.\p"
.string "Hazır ol…\p"
.string "Durumuna bak…\p"
.string "Hadi!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
.string "Lütfen tekrar gelin!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
.string "Bu kötü olmuş.\p"
.string "Savaşırken inanılmaz bir çaba\n"
.string "gösterdiğini düşünüyorum.\p"
.string "Lütfen geri dön ve tekrar dene!$"

TrainerTower_Lobby_Text_GiveItYourBest::
.string "En iyisini yapmanı dilerim.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
.string "Eğitmenler yer değiştirdiğinde,\n"
.string "hareket biraz kaotik olabilir.\p"
.string "Kaosu önlemek için resepsiyon\n"
.string "kontuarı buraya taşıdık.\p"
.string "Uygulamakta olduğumuz için özür\n"
.string "dileriz.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
.string "Merhaba…\p"
.string "Bu KULE'nin sahibiyim…\p"
.string "Bakın, gökyüzü bu çatıdan nasıl\n"
.string "yükseliyor…\p"
.string "Rüzgarın okşamaları burada…\p"
.string "Her şey o kadar mükemmel…\p"
.string "Savaşın da mükemmeldi…$"

TrainerTower_Roof_Text_ThisIsForYou::
.string "Bu senin için…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
.string "Oh!\n"
.string "Muhteşem!\p"
.string "Buraya bu kadar hızlı gelmeniz\n"
.string "gerçekten harika.\p"
.string "Gerçek şu ki, bunu rekor bir\n"
.string "zamanda başardınız…\p"
.string "Rekorunuzu resepsiyon\n"
.string "kontuarına yazdıracağım.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
.string "Buraya gelmeniz biraz zaman\n"
.string "aldı, değil mi?$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
.string "Senden daha iyi bir zaman\n"
.string "görmek istiyorum…\p"
.string "Sana güveniyorum.\p"
.string "O zamana kadar, hoşça kal…$"

TrainerTower_Text_XMinYZSec::
.string "{STR_VAR_1} dk. {STR_VAR_2}.{STR_VAR_3} sn.$"

TrainerTower_Lobby_Text_HereAreTheResults::
.string "Sonuçlar burada!$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
.string "Bu bir iki-iki savaşıdır.\p"
.string "En az iki POKéMON'unuz yoksa\n"
.string "savaşamazsınız.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
.string "Eğitmen Kulesi'nde, ZAMAN SALDIRISI\n"
.string "adında bir etkinlik var.\p"
.string "Resepsiyon kontuarından çatıdaki\l"
.string "SAHİBİ'ne ne kadar hızlı\n"
.string "çıktığınızı zamanlayacağız.\p"
.string "En iyi zamanlar Zaman Tablosu'na\n"
.string "kaydolacak.\p"
.string "Arkadaşlarınızla rekabete girerek\n"
.string "en hızlı kim olduğunu görün.\p"
.string "Burada eğitmenleri yendiğinizde\n"
.string "herhangi bir EXP Puanı veya para\n"
.string "kazanmayacaksınız.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
.string "Katılımınız için teşekkürler!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
.string "Burada ne kadar iyi olduğumu\n"
.string "görmek için varım.\p"
.string "Acaba beni neler bekliyor?\p"
.string "Gerçekten heyecan verici!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
.string "Of, of…\n"
.string "Of…\p"
.string "Savaşmayı bir kenara bırakın! Bu\n"
.string "merdivenler… Onlardan daha zor\n"
.string "bir savaş yok!$"
