@ Tüm Eğitmen Kulesi metni (Lobi ve Çatı) burada iç içe geçmiştir

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "Merhaba!\p"
    .string "EĞİTMEN KULESİ'ne hoş geldiniz.\n"
    .string "Her yerden eğitmenler burada\ltoplanır!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "Dünyanın dört bir yanından gelen\n"
    .string "eğitmenler burada savaşmak için\p"
    .string "bekliyorlar. Bir bakalım…\p"
    .string "Şu anda, eğitmenler sadece\n"
    .string "{STR_VAR_1}. kata kadar var.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "Sekizinci kata kadar eğitmenler\n"
    .string "sizi bekliyor.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "Bekleyen eğitmenleri yenmeye ne\n"
    .string "dersiniz?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "Tamam, saati başlatacağım,\n"
    .string "hazırlanın lütfen.\p"
    .string "Hazırlan…\p"
    .string "Başla!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "Lütfen tekrar gelin!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "Bu kötü oldu.\p"
    .string "Savaşırken inanılmaz bir çaba\n"
    .string "gösterdiğinizi düşünüyorum.\p"
    .string "Lütfen tekrar deneyin!$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "En iyisini yapmanı dilerim.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "Eğitmenler yer değiştirdiğinde,\n"
    .string "hareket biraz kaotik oluyor.\p"
    .string "Kaosu önlemek için resepsiyon\n"
    .string "tezgahını buraya taşıdık.\p"
    .string "Uygulamakta olduğumuz için özür\n"
    .string "dileriz.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "Merhaba…\p"
    .string "Bu KULE'nin sahibiyim…\p"
    .string "Bak, gökyüzü bu çatıdan nasıl\n"
    .string "yükseliyor…\p"
    .string "Rüzgarın dokunuşu hissediliyor…\p"
    .string "Her şey o kadar mükemmel ki…\p"
    .string "Savaşınız da mükemmeldi…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "Bu sizin için.$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "Vay!\n"
    .string "Muhteşem!\p"
    .string "Buraya bu kadar hızlı gelmeniz\n"
    .string "gerçekten harika.\p"
    .string "Gerçek şu ki, bunu rekor bir\n"
    .string "zamanda başardınız…\p"
    .string "Rekorunuzu resepsiyon\n"
    .string "tezgahına yazdıracağım.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "Buraya gelmeniz biraz zaman\n"
    .string "aldı, değil mi?$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "Sizden daha iyi bir zamanlama\n"
    .string "görmek istiyorum…\p"
    .string "Size güveniyorum.\p"
    .string "O zamana kadar, hoşça kalın…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1} dk. {STR_VAR_2}.{STR_VAR_3} sn.$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "Sonuçlar burada!$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "Bu bir ikiye-iki savaşıdır.\p"
    .string "En az iki POKéMON'unuz yoksa\n"
    .string "savaşamazsınız.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "Eğitmen Kulesi'nde, ZAMAN SAVAŞI\n"
    .string "adında bir etkinlik var.\p"
    .string "Resepsiyon kontuarından çatıdaki\l"
    .string "SAHİBİ'ne ne kadar hızlı\n"
    .string "çıktığınızı zamanlayacağız.\p"
    .string "En iyi zamanlar Zaman Tablosu'na\n"
    .string "kaydolacak.\p"
    .string "Arkadaşlarınızla rekabete girerek\n"
    .string "en hızlı kim olduğunu görün.\p"
    .string "Burada eğitmenleri yendiğinizde\n"
    .string "herhangi bir EXP Puanı veya para\l"
    .string "kazanmayacaksınız.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "Katılımınız için teşekkürler!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "Burada ne kadar iyi olduğumu\n"
    .string "görmek için varım.\p"
    .string "Acaba beni neler bekliyor?\p"
    .string "Gerçekten heyecan verici!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "Of, of…\n"
    .string "Of…\p"
    .string "Savaşmayı bir kenara bırak!\n"
    .string "Şu merdivenler… Onlardan daha\l"
    .string "zor bir savaş yok!$"
