PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "POKéMON'lar geliştikçe yeni\n"
    .string "saldırılar öğrenir.\p"
    .string "Ama bazı saldırılar sadece insanlar\n"
    .string "tarafından öğretilebilir.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Bir POKéMON yakalamak, POKéMON'da\n"
    .string "UYKU, ZEHİR, YANIK veya FELÇ gibi\l"
    .string "sorunları varsa daha kolaydır…\p"
    .string "Hepsi yakalamayı kolaylaştırır.\n"
    .string "Ama POKéMON'u yakalamak yine de\lhiçbir zaman kesin değildir!$"
