PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "POKéMON'lar geliştikçe\n"
    .string "yeni saldırılar öğrenir\p"
    .string "Ama bazı saldırılar sadece\n"
    .string "insanlar tarafından öğretilebilir.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "Bir POKéMON yakalamak eğer\n"
    .string "UYKU, ZEHİR, YANIK veya FELÇ\l"
    .string "durumu varsa daha kolay…\p"
    .string "Hepsi etkili. Ama POKéMON'u\n"
    .string "yakalamak yine de kesin değil!$"
