PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Pokémon Ligine hoş geldin.\p"
    .string "ELİT DÖRTLÜ'nden LORELEI'yim.\p"
    .string "BUZ POKéMON'ları konusunda\n"
    .string "beni kimse geçemez.\p"
    .string "Dondurucu saldırılar çok güçlü.\p"
    .string "Pokémon'ların donduğunda\n"
    .string "acımasızca saldırırım.\p"
    .string "Hahaha!\n"
    .string "Hazır mısın?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "POKéMON LİGİne tekrar hoş geldin.\p"
    .string "Ben, ELİT DÖRTLÜ'nden LORELEI,\n"
    .string "geri döndüm!\p"
    .string "Bildiğin gibi,\n"
    .string "BUZ POKéMON'ları konusunda\n"
    .string "beni kimse geçemez.\p"
    .string "Dondurucu saldırılar çok güçlü.\p"
    .string "POKéMON'ların donduğunda\n"
    .string "acımasızca saldırırım.\p"
    .string "Hahaha!\n"
    .string "Hazır mısın?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Bu böyle olmamalıydı!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Senden beklediğimden iyisin.\n"
    .string "Yoluna devam et.\p"
    .string "POKéMON LİGİ'nin gücünü\n"
    .string "tatmış oldun.$"
