PokemonLeague_LoreleisRoom_Text_Intro::
    .string "POKéMON LİGİ'ne hoş geldin.\p"
    .string "Ben ELİT DÖRTLÜ'nden LORELEI.\p"
    .string "BUZ POKéMON'ları konusunda\n"
    .string "beni kimse geçemez.\p"
    .string "Dondurucu saldırılar çok güçlüdür.\p"
    .string "POKéMON'ların donduğunda\n"
    .string "acımasızca saldırırım.\p"
    .string "Hahaha!\n"
    .string "Hazır mısın?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "POKéMON LİGİ'ne tekrar hoş geldin.\p"
    .string "Ben, ELİT DÖRTLÜ'nden LORELEI,\n"
    .string "geri döndüm!\p"
    .string "Bildiğin gibi,\n"
    .string "BUZ POKéMON'ları konusunda\l"
    .string "beni kimse geçemez.\p"
    .string "Dondurucu saldırılar çok güçlüdür.\p"
    .string "POKéMON'ların donduğunda\n"
    .string "acımasızca saldırırım.\p"
    .string "Hahaha!\n"
    .string "Hazır mısın?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "…Bu böyle olmamalıydı!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Sen beklediğimden iyisin.\n"
    .string "Yoluna devam et.\p"
    .string "POKéMON LİGİ'nin gücünü\n"
    .string "tatmış oldun.$"
