CeladonCity_Gym_Text_ErikaIntro::
    .string "Merhaba…\n"
    .string "Hava güzel, değil mi?\l"
    .string "Çok hoş…\p"
    .string "…Ah, canım…\n"
    .string "Sanırım dalmışım. Hoş geldin.\p"
    .string "Adım ERIKA.\n"
    .string "CELADON SALONU'nun lideriyim.\p"
    .string "Çiçek düzenleme sanatı\n"
    .string "öğrencisiyim.\p"
    .string "POKéMON'larım sadece\n"
    .string "ÇİMEN tipindedir.\p"
    .string "…Ah, özür dilerim, bana meydan\n"
    .string "okumak istediğinizi bilmiyordum.\p"
    .string "Pekala, ama kaybetmeyeceğim.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Ah!\n"
    .string "Yenildiğimi kabul ediyorum.\l"
    .string "Çok güçlüsün.\p"
    .string "Size GÖKKUŞAĞI ROZETİ'ni\n"
    .string "vermek zorundayım.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "POKéMON kataloğu mu yapıyorsun?\n"
    .string "İtiraf etmeliyim ki etkilendim.\p"
    .string "Eğer çekici olmasalardı\n"
    .string "POKéMON'ları asla toplamazdım.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "GÖKKUŞAĞI ROZETİ, POKéMON'ların\n"
    .string "50. seviyeye kadar\l"
    .string "itaat etmesini sağlayacak.\p"
    .string "Ayrıca POKéMON'ların savaş dışında\n"
    .string "GÜÇ kullanmasına izin verir.\p"
    .string "Lütfen yanında bunu da al.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER}, ERIKA'dan TM19\n"
    .string "aldı.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 GİGA EMİŞ içerir.\p"
    .string "Vurduğu hasarın yarısı, POKéMON'u\n"
    .string "iyileştirmek için emilir.\p"
    .string "Sence de harika bir hamle\n"
    .string "değil mi?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "Bunun için yer açmalısın.$"

CeladonCity_Gym_Text_KayIntro::
    .string "Bu SALON hakkında bilgi vermeliyim.\p"
    .string "Buraya sadece gerçek bayanlar\n"
    .string "girebilir!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Çok sert oynuyorsun!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "Eeeeh!\n"
    .string "Umarım ERIKA seni ezip geçer!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Oh, hoş geldin.\n"
    .string "Sıkılmaya başlamıştım.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Makyajım!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "ÇİMEN tipi POKéMON'lar\n"
    .string "SU tipine karşı güçlüdür.\p"
    .string "Ayrıca KAYA ve YER tipi\n"
    .string "POKéMON'lara karşı da\l"
    .string "bir avantajları var.$"

CeladonCity_Gym_Text_TinaIntro::
    .string "…Daha önce burayı\n"
    .string "gözetlemiyor muydun?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "Gerçekten göz açıcı!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Oh, demek ERIKA'ya bakıyordun…\n"
    .string "Bana bakmıyordun…$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "Bak, bak!\n"
    .string "POKéMON'larımı gör.\p"
    .string "ÇİMEN tipini seviyorum. Onların\n"
    .string "kolay gelişmesini seviyorum.$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "Hayır!$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "Bu SALON'da sadece ÇİMEN tipi\n"
    .string "POKéMON'lar kullanıyoruz.\p"
    .string "Neden? Çünkü çiçek düzenlemeleri\n"
    .string "için de onları kullanıyoruz!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Oh, selam!\p"
    .string "Burada BÖCEK veya ATEŞ tipi\n"
    .string "POKéMON'ları sevmeyiz!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Olamaz!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Liderimiz ERIKA sessiz olabilir,\n"
    .string "ama buralarda ünlüdür.$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Tanıştığımıza memnun oldum.\n"
    .string "Hobim POKéMON eğitmek.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "Muhteşem!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Yakında bir randevum var.\n"
    .string "Kibar olmayı öğrenmeliyim,\l"
    .string "özellikle savaşmam gerekiyorsa.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "CELADON SALONU'na hoş geldiniz!\p"
    .string "Buradaki güzel bayanları\n"
    .string "küçümsemeyin.$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "Oh!\n"
    .string "Yenildim!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "En iyi POKéMON'umu getirmemiştim.\n"
    .string "Bir sonraki sefere hazır ol!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKéMON SALONU\n"
    .string "LİDER: ERIKA\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKéMON SALONU\n"
    .string "LİDER: ERIKA\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}, {PLAYER}$"
