CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "Susadım!\n"
    .string "Bir şeyler içmek istiyorum!\p"
    .string "{FONT_NORMAL}Ona içecek vermek ister misin?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "Hangi içeceği vermek istersin?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "Hahay!\p"
    .string "TAZE SU!\p"
    .string "Teşekkürler!\n"
    .string "Bunun karşılığında sana\l"
    .string "bu hediyeyi verebilirim!$"

Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} küçük kızdan bir\n"
    .string "{STR_VAR_2} aldı.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .if ENG_MOVES == 1
    .string "TM16 LIGHT SCREEN içerir.\p"
    .else
    .string "TM16 IŞIK DUVARI içerir.\p"
    .endif
    .string "Bu hareket,\n"
    .string "rakibinin özel saldırılarının\l"
    .string "gücünü azaltır.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "Hahay!\p"
    .string "GAZOZ!\p"
    .string "Teşekkürler!\n"
    .string "Bunun karşılığında sana\l"
    .string "bu hediyeyi verebilirim!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .if ENG_MOVES == 1
    .string "TM20 SAFEGUARD içerir.\p"
    .else
    .string "TM20 MİSTİKKORUMA içerir.\p"
    .endif
    .string "Bu hareket, POKéMON'ların durum\n"
    .string "sorunlarının önüne geçer.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "Hahay!\p"
    .string "LİMONATA!\p"
    .string "Teşekkürler!\n"
    .string "Bunun karşılığında sana\l"
    .string "bu hediyeyi verebilirim!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .if ENG_MOVES == 1
    .string "TM33 REFLECT içerir.\p"
    .else
    .string "TM33 YANSIT içerir.\p"
    .endif
    .string "Bu hareket, rakibinin fiziksel\n"
    .string "saldırılarının gücünü azaltır.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "Bunun için yerin yok!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "Teşekkürler, gerek yok!\n"
    .string "Aslında pek susamadım!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "Kardeşim bir EĞİTMEN,\n"
    .string "inan ya da inanma!\p"
    .string "Ama çok çocuksu ve\n"
    .string "beni delirtiyor!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "Susadım!\n"
    .string "Bir şeyler içmek istiyorum!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "ÇATI KATI:\n"
    .string "İÇECEK OTOMATLARI$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "Bir içecek otomatı!\n"
    .string "Acaba ne içecekler var?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "Yeterli param yok!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "Bir kutu {STR_VAR_1} çıktı!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "Daha fazla eşya koyacak yer yok!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "Susamadım!$"
