SSAnne_1F_Room2_Text_TylerIntro::
    .string "POKéMON'ları seviyorum!\n"
    .string "Peki ya sen?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "Vay canına! \n"
    .string "Harikasın!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Dinle, dinle!\n"
    .string "Arkadaş olalım, olur mu?\p"
    .string "Böylece POKéMON takas edebiliriz\n"
    .string "ve eğlenceli şeyler yapabiliriz.$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "Bu POKéMON'ları dünyanın\n"
    .string "dört bir yanından topladım!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "Aman Tanrım!\n"
    .string "Bunları almak için dünyayı dolaştım!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "Zavallı POKéMON'larımı acıttın!\p"
    .string "Onları bir POKéMON Merkezi'nde\n"
    .string "iyileştirmeni istiyorum.$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "Çocuklarım ve ben,\n"
    .string "dünyayı geziyoruz.$"

