FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "Ben BALIK GURU'sunun ağabeyiyim.\p"
    .string "Balık avlamayı çok seviyorum!\p"
    .string "Onsuz yapamam. Sana soruyorum,\n"
    .string "balık tutmayı sever misin?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "Harika! Tarzını beğendim.\n"
    .string "Sanırım arkadaş olabiliriz.\p"
    .string "Al bunu ve balık tut, genç dostum!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER}, BALIK GURU'sunun\n"
    .string "ağabeyinden bir İYİ OLTA aldı.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "Balık tutmak bir yaşam tarzıdır!\n"
    .string "Güzel bir şiire benzer.\p"
    .string "ESKİ OLTA sadece MAGIKARP\n"
    .string "yakalayabilir, öyle değil mi?\p"
    .string "Ama bir İYİ OLTA ile çok daha\n"
    .string "iyi POKéMON'lar yakalayabilirsin.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "Ah…\n"
    .string "Bu çok üzücü…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "Merhaba {PLAYER}!\n"
    .string "Balık tutuyor musun?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "Aman Tanrım!\n"
    .string "Sana bir hediyem vardı, ama\n"
    .string "yerin yok!$"
