IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon olacak gibisin!\p"
    .string "POKéMON LİGİ'nde ELİT DÖRTLÜ'yü\n"
    .string "ard arda yenmelisin.\p"
    .string "Yenilirsen, baştan başlaman gerek!\p"
    .string "Hazırsan!\n"
    .string "Hadi göster kendini!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "Buradan itibaren ELİT DÖRTLÜ'yü\n"
    .string "tek tek yenmelisin.\p"
    .string "Eğer kazanırsan, bir sonraki\n"
    .string "EĞİTMEN'in kapısı açılacak.\p"
    .string "Bol şans!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "Üzgünüm, buraya boşuna gelmişsin.\p"
    .string "ELİT DÖRTLÜ'den LORELEI şu an yok.\p"
    .string "Bu yüzden POKéMON LİGİ geçici\n"
    .string "olarak kapalı.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "AGATHA'nın HAYALET türü\n"
    .string "POKéMON'ları gerçekten çok\l"
    .string "güçlü ve korkutucu.\p"
    .string "Ben de DÖVÜŞ türlerimi\n"
    .string "maksimum seviyeye çıkardım.\p"
    .string "AGATHA'ya karşı oldukça emindim,\n"
    .string "ama beni yendi.\p"
    .string "O yaşlı kadın aynı zamanda çok da\n"
    .string "sinirli.\p"
    .string "O korkutucu kadını sinirlendirmek\n"
    .string "hiç de zor değil.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "Belki de ELİT DÖRTLÜ üyesi olmak\n"
    .string "kanlarında var.\p"
    .string "Duyduğuma göre, LANCE'in uzaklarda\n"
    .string "bir SALON LİDERİ kuzeni varmış.$"
