Text_MetronomeTeach::
.string "Tik-tak-tik!\n"
.string "Harika bir hareket öğreteceğim.\p"
.string "Bir POKéMON'a öğret ve eğlenceyi\n"
.string "izle!\p"
.string "Hareketin adı METRONOM\n"
.string "İlginizi çekti mi?$"

Text_MetronomeDeclined::
.string "Sana çok eğlence getirecek!$"

Text_MetronomeWhichMon::
.string "Tamam!\n"
.string "Hangi POKéMON'a öğretmeliyim?$"

Text_MetronomeTaught::
.string "Tik-tak-tik!\n"
.string "Bu bir METRONOM sesidir.\p"
.string "POKéMON'unun beynini, bilmediği\n"
.string "hareketleri kullanmaya yönlendirir.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
.string "Merhaba!\p"
.string "Ben önemli bir doktorum.\n"
.string "Evet, çok önemliyim.\p"
.string "Burada, nadir POKéMON fosilleri\n"
.string "üzerinde çalışıyorum.\p"
.string "Sen!\n"
.string "Bana verecek bir fosilin var mı?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
.string "Hayır mı?\n"
.string "Ne yazık!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
.string "Biraz zaman alacak!\p"
.string "Biraz dolaşmak istersin, değil mi?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
.string "Geç kaldın.\n"
.string "Neredeydin?\p"
.string "Fosilin hayata döndü!\n"
.string "{STR_VAR_1} olduğunu düşünüyorum!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
.string "{PLAYER} doktor tarafından verilen\n"
.string "{STR_VAR_1}'ı aldı.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
.string "POKéMON'lar için yer yok!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
.string "Oh!\n"
.string "Bu bir {STR_VAR_2}!\p"
.string "Bu, {STR_VAR_1} adlı, artık\n"
.string "soyu tükenmiş bir POKéMON fosili!\p"
.string "Diriltme Makinem, o POKéMON'u\n"
.string "yeniden hayata döndürecek!$"

@ TODO: Aşağıdaki metin döküm hatasını çöz?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
.string "İşte!\n"
.string "Çabuk onu bana ver!\p"
.string "{FONT_NORMAL}{PLAYER}, garip doktora\n"
.string "{STR_VAR_2}'yi verdi.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
.string "Bu biraz zaman alacak!\n"
.string "Biraz yürüyüşe çıkabilirsin!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
.string "Aiyah!\n"
.string "Tekrar gel!$"
