Route21_North_Text_RonaldIntro::
	.string "Balıkların ısırdığını mu merak\n"
	.string "ediyorsun?$"

Route21_North_Text_RonaldDefeat::
	.string "Vay canına!$"

Route21_North_Text_RonaldPostBattle::
	.string "İyi bir şey yakalayamıyorum.\n"
	.string "İyi bir POKéMON yok!$"

Route21_North_Text_WadeIntro::
	.string "Büyük bir avım var!\n"
	.string "Katılmak ister misin?$"

Route21_North_Text_WadeDefeat::
	.string "Hehe, MAGIKARP pek para etmiyor\n"
	.string "biliyorsun, değil mi?$"

Route21_North_Text_WadePostBattle::
	.string "Sadece MAGIKARP yakalıyorum\n"
    .string "gibi görünüyor!$"

Route21_North_Text_SpencerIntro::
	.string "Deniz bedenimi ve ruhumu temizliyor!$"

Route21_North_Text_SpencerDefeat::
	.string "Aya!$"

Route21_North_Text_SpencerPostBattle::
	.string "Deniz harika, ama ben dağları da\n"
	.string "seviyorum.$"

@ Aşağıda, Gen 1'de Route 21'deki Cue Ball'un savaş metni yer alıyor.
@ Bu eğitmen Gen 3'te kullanılmadığından, metni kullanılmıyor/çevrilmiyor
@ İlginç bir şekilde, bu eğitmen için bir tekrar giriş metni eklemişler
@ RB'den İngilizce çeviriler listelenmiştir

@ "Yüzmemde bir sorun mu var?$"
Route21_North_Text_CueBallIntro::
	.string "Bazen ben de\n"
	.string "yüzmeye gelirim!$"

@ "Ucuz vuruş!$"
Route21_North_Text_CueBallDefeat::
	.string "Vay canına!$"

@ "Ne gibi görünüyorum? Bir lastik cankurtaran mı? Defol!$"
Route21_North_Text_CueBallPostBattle::
	.string "Kolay yüzüyormuşum gibi\n"
	.string "mi görünüyorum? Defol!$"
