Route15_Text_KindraIntro::
    .string "Yeni POKéMON'larım var.\n"
    .string "Onları seninle deneyebilir miyim?$"

Route15_Text_KindraDefeat::
    .string "Yeterince iyi değil!$"

Route15_Text_KindraPostBattle::
    .string "Takasla aldığın POKéMON'un\n"
    .string "takma adını değiştiremezsin.\p"
    .string "Sadece orijinal EĞİTMEN\n"
    .string "takma adı değiştirebilir.$"

Route15_Text_BeckyIntro::
    .string "Nazik görünüyorsun, bu yüzden seni\n"
    .string "yenebileceğimi düşünüyorum.\p"
    .string "Hadi deneyelim!$"

Route15_Text_BeckyDefeat::
    .string "Hayır, yanlış!$"

Route15_Text_BeckyPostBattle::
    .string "MOTORCULAR'dan korkuyorum.\n"
    .string "Çok çirkin ve kaba görünüyorlar!$"

Route15_Text_EdwinIntro::
    .string "Islık çaldığımda kuş POKéMON'ları\n"
    .string "çağırabiliyorum.$"

Route15_Text_EdwinDefeat::
    .string "Auv!\n"
    .string "Bu trajik!$"

Route15_Text_EdwinPostBattle::
    .string "Belki de savaşlar için uygun değilim.\n"
    .string "Sanırım doğru türde değilim.$"

Route15_Text_ChesterIntro::
    .string "Hmm? Kuşlarım titriyor!\n"
    .string "İyisin, değil mi?$"

Route15_Text_ChesterDefeat::
    .string "Tam da düşündüğüm gibi!$"

Route15_Text_ChesterPostBattle::
    .string "Bu çok açık, bunu bilmelisin,\n"
    .string "ama…\p"
    .string "DEPREM ve YARIK gibi\n"
    .string "hamlelerin kuş\l"
    .string "POKéMON'larına etkisi yok.$"

Route15_Text_GraceIntro::
    .string "Oh, sen küçük ve sevimlisin!\n"
    .string "Tıpkı şirin bir POKéMON gibi!$"

Route15_Text_GraceDefeat::
    .string "Ama çok sevimli görünüyordun!$"

Route15_Text_GracePostBattle::
    .string "Seni affediyorum.\n"
    .string "Bunu alabilirim.\l"
    .string "Artık büyük bir kızım.$"

Route15_Text_OliviaIntro::
    .string "Yalnız yaşadığım için koruma\n"
    .string "amaçlı POKéMON yetiştiriyorum.$"

Route15_Text_OliviaDefeat::
    .string "POKéMON benim için kazanmak ya da\n"
    .string "kaybetmekle ilgili değil.$"

Route15_Text_OliviaPostBattle::
    .string "Eve geldiğimde POKéMON'larımın\n"
    .string "beni karşılamasını seviyorum.\p"
    .string "Bu çok rahatlatıcı.$"

Route15_Text_ErnestIntro::
    .string "Hey, çocuk! Hadi!\n"
    .string "Bunları bir ezikten aldım!$"

Route15_Text_ErnestDefeat::
    .string "Neden olmasın?$"

Route15_Text_ErnestPostBattle::
    .string "Hayat çok kısa.\n"
    .string "Haydut olarak yaşamak havalı.\l"
    .string "ROKET TAKIMI ÇOK YAŞA!$"

Route15_Text_AlexIntro::
    .string "Kaybedince tüm paranı ver,\n"
    .string "çocuk!$"

Route15_Text_AlexDefeat::
    .string "Bu doğru olamaz!$"

Route15_Text_AlexPostBattle::
    .string "Parayla ilgili şaka yapıyordum.\n"
    .string "Beni ciddiye alma.$"

Route15_Text_CeliaIntro::
    .string "Havalı ve güncel olan nedir?\n"
    .string "POKéMON takas etmek!$"

Route15_Text_CeliaDefeat::
    .string "Takas dedim!$"

Route15_Text_CeliaPostBattle::
    .string "Arkadaşlarımla sürekli POKéMON\n"
    .string "takas ediyorum.$"

Route15_Text_YazminIntro::
    .string "POKéMON'larım ile oynamak\n"
    .string "ister misin?$"

Route15_Text_YazminDefeat::
    .string "Çok sabırsızdım!$"

Route15_Text_YazminPostBattle::
    .string "Daha zayıf insanlarla antrenman\n"
    .string "yapacağım.$"

Route15_Text_RouteSign::
    .string "ROTA 15\n"
    .string "Batı'da FUCHSIA ŞEHRİ$"

Route15_Text_MyaIntro::
    .string "MYA: Sen mükemmelsin.\n"
    .string "Küçük kardeşimi eğitmeme\l"
    .string "yardım eder misin?$"

Route15_Text_MyaDefeat::
    .string "MYA: RON, odaklanmalısın!\n"
    .string "Ne yaptığınıza konsantre olun!$"

Route15_Text_MyaPostBattle::
    .string "MYA: Tamam, artıracağız.\n"
    .string "Eğitim menümüze ekleme yapacağım!$"

Route15_Text_MyaNotEnoughMons::
    .string "MYA: Bize meydan okumak ister\n"
    .string "misin?\p"
    .string "Ancak iki POKéMON'a ihtiyacın var.$"

Route15_Text_RonIntro::
    .string "RON: Kız kardeşim kaybettiğimizde\n"
    .string "korkunç olur.$"

Route15_Text_RonDefeat::
    .string "RON: Oh, hayır, hayır…\n"
    .string "Kız kardeşim, üzgünüm!$"

Route15_Text_RonPostBattle::
    .string "RON: Oh, berbat…\n"
    .string "Keşke iyi bir kız kardeşim\l"
    .string "olsaydı…$"

Route15_Text_RonNotEnoughMons::
    .string "RON: Kız kardeşimle ve benimle\n"
    .string "savaşmak mı istedin?\p"
    .string "O zaman iki POKéMON'a\n"
    .string "ihtiyacın var.$"

