CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "Hoş geldin!\p"
    .string "Bir sonraki kapıda JETON'larını\n"
    .string "harika ödüllerle değiştirebilirsin.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "ROKET OYUN KÖŞESİ'a Hoş Geldin!\p"
    .string "JETON'a ihtiyacın var mı?\n"
    .string "Satın almak ister misin?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "Hayır mı?\n"
    .string "Lütfen bir gün gel ve oyna!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "Ah, üzgünüm.\n"
    .string "JETON KASAN yok.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "Vay!\n"
    .string "JETON KASAN dolmuş.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "JETON alacak paran yok.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "Teşekkürler.\n"
    .string "İşte JETON'ların!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "Kimseye söyleme.\p"
    .string "Burayı ROKET TAKIMI'nın yönettiği\n"
    .string "söyleniyor.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "Bu makinelerin farklı oranlara\n"
    .string "sahip olduğunu düşünüyorum.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "Çocuk, oynamak ister misin?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} adamdan 10 JETON aldı$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "JETON'larıma ihtiyacın yok!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "Kazançlar gelip gidiyor.\n"
    .string "Hiçbir şey kesin değil.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "Bu slot oyunları…\n"
    .string "Kazan veya kaybet, sadece şans işi.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "Hey!\p"
    .string "Yapacak daha iyi işlerin var,\n"
    .string "şampiyon adayı!\p"
    .string "CELADON SALON lideri ERIKA.\p"
    .string "O bir ÇİMEN-tipi POKéMON ustasıdır\n"
    .string "ve doğayla iç içedir.\p"
    .string "Çiçeklerle içli dışlı olmasından\n"
    .string "dolayı yumuşak görünebilir…\p"
    .string "Ama onu hafife almamalısın!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "Onlar JETON'lar karşılığında\n"
    .string "nadir POKéMON'lar sunuyorlar.\p"
    .string "Ama bir türlü kazanamıyorum!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "Oyunlar korkutucu!\n"
    .string "Bağımlı olmak çok kolay!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "N'aber?\n"
    .string "Biraz JETON ister misin?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} iyi adamdan 20 JETON aldı$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "Çok fazla JETON'un var!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "Olamaz! İstediğim POKéMON için\n"
    .string "daha fazla JETON lazım!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "Hey, ne yapıyorsun?\n"
    .string "Dikkatimi dağıtma!\p"
    .string "Al sana biraz JETON, şimdi defol!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} adamdan 20 JETON aldı\n"
    .string "$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "Zaten yeterince JETON'un var!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "Püf noktası, makaraları\n"
    .string "yakından izlemektir.$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "Bu posteri koruyorum!\n"
    .string "Defol, yoksa!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "Hay aksi!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "ROKET TAKIMI KARARGÂHI\n"
    .string "keşfedilebilir!\p"
    .string "PATRON'a haber vermeliyim!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "Hey!\p"
    .string "Posterin arkasındaki bir düğme!?\n"
    .string "Hadi basayım!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "Bir JETON KASASI gerekiyor…$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "Ups!\n"
    .string "JETON KASAM yok!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "Bir slot makinesi!\n"
    .string "Oynamak ister misin?$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "ARIZALI\n"
    .string "Bu bozuk.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "ÖĞLE TATİLİNDE\n"
    .string "Bu rezerve edilmiş.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "Birilerinin anahtarları!\n"
    .string "Geri dönecekler.$"
