SixIsland_WaterPath_Text_RoseIntro::
    .string "Nereye gideceğimi serin bir esintiye\n"
    .string "bıraktım ve buraya geldim.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Hıhı… O kararlı halin çok tatlı.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Oradaki ormana gitmek istiyorum,\n"
    .string "ama…\p"
    .string "Orada çok BÖCEK POKéMON'u var.\n"
    .string "Biraz korkutucu.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Kimsenin görmeyeceği şekilde\n"
    .string "gizli gizli pratik yapıyorum.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "Kaybettiğimi kimse görmedi,\n"
    .string "öyle değil mi?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Bir performans sanatçısı olarak,\n"
    .string "çabalarımın görülmesini istemem.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "Ne, YÜZÜCÜLERDEN bıktım mı\n"
    .string "demek istiyorsun?\p"
    .string "Aww, yapma böyle!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "Oh, hayır, hayır, hayır.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "YÜZÜCÜ olduğum için üzerimdeki kötü\n"
    .string "imajı silemedim…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Erkek arkadaşım çok meşgul, bu\n"
    .string "yüzden yüzmeye tek başıma geliyorum.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "Biliyordum böyle olacağını!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Erkek arkadaşımla\n"
    .string "vakit geçiremediğimde,\l"
    .string "bana verdiği POKéMON'larla vakit\l"
    .string "geçiriyorum.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Söyle, bu civarda dağlar nerede?\p"
    .string "Biraz da oraları\n"
    .string "keşfetmek istiyorum.$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "Savaşırken yolumu kaybettim!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "Bu civarda dağ yok mu?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MIU: Merhaba, POKéMON!\n"
    .string "Oyun zamanı!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MIU: Oh, hayır!\n"
    .string "Anne!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MIU: Kaybetmek içimi hüzünlendiriyor.\n"
    .string "Ama yine de eğlenceliydi!$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MIU: MIA ve ben İKİZLERİZ.\n"
    .string "Birlikte savaşmak istiyoruz.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MIA: Merhaba, POKéMON!\n"
    .string "Savaşmaya hazır mısın?$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MIA: Çok kötüsün!\n"
    .string "Kazandığın için utanmalısın!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MIA: Ohh…\n"
    .string "Üzgünüm POKéMON'larım…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MIA: Sadece bir POKéMON'un mu var?\p"
    .string "Yalnız hissetmiyor musun?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Aranıyor!\n"
    .string "Nihai Boynuz!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "SU YOLU\n"
    .string "HARABE VADİ'ye gider$"
