CinnabarIsland_Text_DoorIsLocked::
    .string "Kapı kilitli…$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "CINNABAR SALONU'ndaki BLAINE\n"
    .string "oldukça tuhaf bir adam.\p"
    .string "LAB inşa edilmeden çok önce\n"
    .string "adada yaşıyordu.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "Bilim insanları, yanmış binada\n"
    .string "deneyler yapıyorlar.\p"
    .string "Bilirsin, oraya POKéMON KONAĞI\n"
    .string "diyorlar.$"

CinnabarIsland_Text_IslandSign::
    .string "CINNABAR ADASI\n"
    .string "Alevli Şehrin Yanık Arzuları$"

CinnabarIsland_Text_PokemonLab::
    .string "POKéMON LABORATUVARI$"

CinnabarIsland_Text_GymSign::
    .string "CINNABAR ADASI POKéMON SALONU\n"
    .string "LİDER: BLAINE\l"
    .string "Sıcakkanlı Quiz Ustası!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "Hey?\n"
    .string "Hey, sen {PLAYER} değil misin!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "Bak, benim BILL.\n"
    .string "Uzun zamandır görüşemedik!\p"
    .string "Umarım hala PC sistemimi\n"
    .string "kullanıyorsundur.\p"
    .string "Dinle, burada karşılaştığımıza\n"
    .string "göre, benimle biraz vakit geçirmek\l"
    .string "ister misin?\p"
    .string "Güneyde BİRİNCİ ADA adında küçük\n"
    .string "bir ada var.\p"
    .string "Bir arkadaşım beni davet etti,\n"
    .string "oraya gidiyorum.$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "Tamam o zaman.\n"
    .string "Hadi gidelim!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "Ne, çok mu meşgulsün?\p"
    .string "Tamam, anladım.\n"
    .string "Zaten tekne henüz gelmedi.\p"
    .string "Oradaki POKéMON MERKEZİ'nde\n"
    .string "bekleyeceğim.\p"
    .string "Buradaki işin bittiğinde beni\n"
    .string "görmeye gel.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "Sanırım arkadaşımın teknesi de\n"
    .string "gelmiş.\p"
    .string "Tekneyi özellikle beni almak için\n"
    .string "CINNABAR'a gönderdi.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "Hey, uzun bir yolculuktu, değil\n"
    .string "mi?\p"
    .string "Arkadaşım CELIO seninle vakit\n"
    .string "geçirmeyi sevdi.\p"
    .string "Tekrar gidersen memnun olur.\p"
    .string "Eğer ÜÇLÜ-BİLET'e sahipsen, her\n"
    .string "zaman VERMILION LİMANI'ndan\l"
    .string "feribota binebilirsin.\p"
    .string "Şimdilik teşekkürler, görüşürüz!$"
