OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "Hm!\n"
    .string "Haaaaaaaah!\p"
    .string "Ah! Cennet gibi!\n"
    .string "Su içimi ısıtıyor!\p"
    .string "Sen de atla içeri.\p"
    .string "Ortaya git, rahatla ve\n"
    .string "sıcak ol!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "Banyodan sonraki en sevdiğim\n"
    .string "kısmı bu.\p"
    .string "Bir kase çorba ile içimi de\n"
    .string "ısıtmayı seviyorum!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "Su mükemmel sıcaklıkta.\n"
    .string "Muhteşem hissettiriyor…\p"
    .string "{PLAYER} ve POKéMON'lar tamamen\n"
    .string "yenilendi!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "Sıcak bir kaynak havuzunda\n"
    .string "yüzen terapi gibi.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "Yüzüme bak.\n"
    .string "Cildimin ne kadar pürüzsüz\l"
    .string "olduğuna bak.\p"
    .string "Sıcak kaynak suyu cildimi\n"
    .string "genç tutuyor.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "Dürüst bir antrenman gününden\n"
    .string "sonra, sıcak kaynak havuzunda\l"
    .string "rahatlamak gibisi yok.\p"
    .string "BRUNO, benim üstadım,\n"
    .string "ara sıra SPA'ya uğrar.\p"
    .string "Hem kendi hem de POKéMON'u\n"
    .string "için yaralanmaları tedavi\l"
    .string "etmeye gelir.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "Sıcak kaynaklar volkanlarla\n"
    .string "el ele gider.\p"
    .string "Buradaki KÖZ SPA'yı ben\n"
    .string "yıllar önce yaptım.\p"
    .string "Bu devasa kayayı elle\n"
    .string "oyarak havuz yaptım.\p"
    .string "Burayı yaparken bunu\n"
    .string "kullanıyordum. Artık verebilirim.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "O, kayaları tuzlu kraker gibi\n"
    .string "parçalayan bir şey.$"
