SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "ROKET TAKIMI binaya baskın yaptı!\n"
    .string "Binayı ele geçirdiler!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "Eh, işe geri dönmeliyim.$"

SilphCo_6F_Text_HelpMePlease::
    .string "Aman Tanrım, aman Tanrım.\n"
    .string "Lütfen bana yardım edin!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "Nişanlandık.\n"
    .string "Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "Yanımdaki adam…\n"
    .string "O kadar korkak ki!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "O çok çaresiz, ona bakacak\n"
    .string "biri gerekiyordu.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "ROKET TAKIMI, POKéMON'larla\n"
    .string "dünyayı fethetmeye çalışıyor.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "ROKET TAKIMI kaçtı, ve bunun\n"
    .string "sebebi sensin!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "Onlar kesinlikle POKéMON\n"
    .string "ürünlerimiz için SILPH'i hedef aldı.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "Büyüyünce SILPH için\n"
    .string "çalışmaya gel.$"

SilphCo_6F_Text_Grunt1Intro::
    .string "Ben ROKET KARDEŞLER'den\n"
    .string "biriyim!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "Alevler söndü!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "Sorun değil!\n"
    .string "Kardeşlerim intikamımı alacak!$"

SilphCo_6F_Text_TaylorIntro::
    .string "O berbat BAŞKAN!\p"
    .string "Beni TIKSI ŞUBESİ'ne gönderdiği\n"
    .string "için bunu hak etti!\p"
    .string "O yüzden ROKET TAKIMI peşimize\n"
    .string "düştü, bundan eminim!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "Vuruldum!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "TIKSI ŞUBESİ mi?\n"
    .string "Orası Rusya'nın çorak bir yerinde!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "ROKET TAKIMI'nı satacak kadar\n"
    .string "kötü müsün?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "Sen ihanet ettin!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "Eğer adaletten yana olursanız,\n"
    .string "biz kötü adamlara ihanet etmiş\l"
    .string "olursunuz!$"

SilphCo_6F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİSİ\n"
    .string "6. Kat$"

