ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "UUUUAAAAAĞĞĞĞHHH…\n"
    .string "KIAAAHH!\p"
    .string "…İşe yaramıyor! Bu kaşığı\n"
    .string "zihnimle bükemiyorum.\p"
    .string "Belki de gerçekten psişik\n"
    .string "güçlerim yoktur.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "SAFFRON SALONU'ndaki kızı biliyor\n"
    .string "musun?\p"
    .string "PSİŞİK-tip POKéMON kullanıyor,\n"
    .string "değil mi?\p"
    .string "Ona gerçekten hayranım.\p"
    .string "Duydum ki çok havalı ve\n"
    .string "güzel bir lidermiş.$"


