@ Bu dosyanın metni garip bir şekilde bölündü ve FourIsland_PokemonCenter_1F/text.inc dosyasında. Ayrıca bu dosyada kullanılmayan bir JP sürümü de var.

JPText_BodySlamTeach::
    .string "Hadi bakalım, salla kendini!\n"
    .string "Hangimiz daha çabuk yorulacak?\l"
    .string "Bir ezilme yarışması yapıyoruz!\p"
    .string "Eğer sen ekibe katılırsan\n"
    .string "Ezilir gibisin…\l"
    .string "Yerine, Pokemon'una\l"
    .string "Ezilme hareketini öğretmemi ister misin?$"

JPText_BodySlamDeclined::
    .string "Tekrar gel, salla kendini!$"

JPText_BodySlamWhichMon::
    .string "Hangi Pokemon'a\n"
    .string "öğretmek istersin?$"

JPText_BodySlamTaught::
    .string "Salla salla!$"

FourIsland_House1_Text_YoureAwfullyHeavy::
    .string "Hop! Şimdi!\n"
    .string "Çok ağırsın!$"
