FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon:
    .string "Tek bir POKéMON ile\n"
    .string "iyi EĞİTMEN olamazsın.\p"
    .string "Fakat birçok POKéMON'u\n"
    .string "eşit şekilde eğitmek de\l"
    .string "kolay değil.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian:
    .string "VIRIDIAN ŞEHRİ'nin batısında\n"
    .string "dar bir patika var.\p"
    .string "Bu yol POKéMON LİGİ merkezine\n"
    .string "gider. Merkez tüm EĞİTMENLERİ\l"
    .string "yönetir.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex:
    .string "Eğer bir POKéDEX üzerinde\n"
    .string "çalışıyorsan, SAFARİ BÖLGESİ'ne\l"
    .string "gitmelisin.\p"
    .string "Tüm nadir POKéMON türleri\n"
    .string "orada bulunur.$"
