Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
.string "Nöbetteyim.\n"
.string "Ama çok susadım!\p"
.string "Dur, yol kapalı.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
.string "Oh, o ÇAY…\n"
.string "Çok lezzetli görünüyor…$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
.string "Ne? Bu içeceği içebilir miyim?\n"
.string "Teşekkürler!\l"
.string "… …\l"
.string "Yudum, yudum…\l"
.string "… …\l"
.string "Yutkun…\l"
.string "Eğer SAFFRON ŞEHRİ'ne\l"
.string "gitmek istiyorsan…\l"
.string "… …\l"
.string "Geçebilirsin.\p"
.string "Bu ÇAY'ı diğer nöbetçilerle\n"
.string "paylaşacağım!$"

Route6_NorthEntrance_Text_HiHowsItGoing::
.string "Merhaba, nasıl gidiyor?$"
