CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "O BILL!\p"
    .string "Duydum ki nadir POKéMON'lar\n"
    .string "için her şeyi yapar.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "BILL'i duydun mu?\p"
    .string "Herkes ona POKéMANYAK diyor!\p"
    .string "Fakat bence insanlar sadece\n"
    .string "BILL'ş kıskanıyorlar.\p"
    .string "Kim POKéMON'larından bahsetmek\n"
    .string "istemez ki?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL'in çok sayıda POKéMON'u var!\n"
    .string "Nadir olanları da topluyor!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Neden yukarı çıkmıyorsun ve\n"
    .string "arkadaşlarınla POKéMON takası\l"
    .string "yapmıyorsun?\p"
    .string "Takas yaparak çok daha fazla\n"
    .string "çeşitliliğe sahip olabilirsin.\p"
    .string "Takas edilen POKéMON'lar da\n"
    .string "hızla gelişir.$"
