SaffronCity_Text_WhatDoYouWantGetLost::
    .string "Ne istiyorsun?\n"
    .string "Kaybol!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "PATRON bu şehri ROKET TAKIMI\n"
    .string "adına ele geçireceğini söyledi!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "Asi olma!\n"
    .string "Yoksa sana zarar verebilirim!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "SAFFRON, ROKET TAKIMI'na ait!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "Bir suçlu olarak yaşamım beni\n"
    .string "çok canlı hissettiriyor!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "Auv!\n"
    .string "Yürüdüğün yere dikkat et!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "SILPH kontrolümüz altında, artık\n"
    .string "tüm dünyadaki POKéMON'ları\l"
    .string "kullanabiliriz!\p"
    .string "Pis zengin olacağız, evet!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "ROKET TAKIMI'nı tek başına mı yendin?\n"
    .string "Bu inanılmaz!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "Evet! ROKET TAKIMI gitti!\n"
    .string "Tekrar dışarı çıkmak güvenli!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "ROKET TAKIMI gelince\n"
    .string "insanlar buradan kaçtılar.\p"
    .string "Artık SAFFRON'a geri dönmeliler.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "SILPH'i haberlerde okuyunca\n"
    .string "PIDGEOT'umla buraya uçtum.\p"
    .string "Çoktan bitti mi?\n"
    .string "Aksiyonu kaçırdım…$"

SaffronCity_Text_Pidgeot::
    .string "PIDGEOT: Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "ROKET PATRONU'nu SILPH binasından\n"
    .string "kaçarken gördüm.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Bir güvenlik görevlisiyim.\p"
    .string "Şüpheli çocukları içeri almam!$"

SaffronCity_Text_HesTakingASnooze::
    .string "…\n"
    .string "Horlama…\p"
    .string "Hah! Uykuya dalıyor!$"

SaffronCity_Text_CitySign::
    .string "SAFFRON ŞEHRİ\n"
    .string "Parlayan, Altın Ticaret Ülkesi$"

SaffronCity_Text_FightingDojo::
    .string "DÖVÜŞ DOJOSU$"

SaffronCity_Text_GymSign::
    .string "SAFFRON ŞEHRİ POKéMON SALONU\n"
    .string "LİDER: SABRİNA\l"
    .string "PSİŞİK POKéMON Ustası!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "TAM İYİLEŞTR yanma, felç, zehir\n"
    .string "donma, uyku gibi tüm,\l"
    .string "durumları çözer.\p"
    .string "Diğer eşyalardan biraz daha pahalı,\n"
    .string "ama daha pratik.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "Yeni SÜPER TOP, yakalarken\n"
    .string "geliştirilmiş oranlar sunar.\p"
    .string "Onunla zor POKéMON'ları\n"
    .string "yakalamaya çalış.$"

SaffronCity_Text_SilphCoSign::
    .string "SILPH ŞTİ. OFİS BİNASI$"

SaffronCity_Text_MrPsychicsHouse::
    .string "BAY PSİŞİK'İN EVİ$"

SaffronCity_Text_SilphsLatestProduct::
    .string "SILPH'in en yeni ürünü!\n"
    .string "Yakında çıkacak…$"

SaffronCity_Text_TrainerFanClubSign::
    .string "POKéMON EĞİTMENİ FAN KULÜBÜ\p"
    .string "Birçok EĞİTMEN bu levhaya\n"
    .string "isimlerini yazdılar.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "Bu FAN KULÜBÜ…\n"
    .string "Burada kimsenin bir fikri yok!\p"
    .string "Nasıl LANCE'in muhteşemliğini\n"
    .string "tanıyamadılar?\p"
    .string "O adalet için duruyor!\n"
    .string "Soğukkanlı ve tutkuludur!\l"
    .string "O en büyük, LANCE!$"
