TwoIsland_Text_IslandSign::
    .string "İKİNCİ ADA\n"
    .string "İki Kat Eğlence$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Gel ve Kap!\n"
    .string "Eğlenceli OYUN KÖŞESİ$"

TwoIsland_Text_DangerFastCurrent::
    .string "TEHLİKE! HIZLI AKINTI!\n"
    .string "Balık tutmak ve sörf yapmak\lyasaktır!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Hey!\n"
    .string "Merhaba, dükkanıma hoş geldin!\p"
    .string "Yeni açıldık.\p"
    .string "Ürünlerimiz sınırlı, ama umarım\n"
    .string "ihtiyaçlarınızı karşılayabiliriz.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "LOSTELLE'i kurtardığın için sana\n"
    .string "ne kadar minnettar olduğumu\l"
    .string "anlatamam.\p"
    .string "Sayende, ADA halkı KANTO\n"
    .string "halkına bakış açısını değiştirdi.\p"
    .string "Ben de KANTO'danım.\p"
    .string "ADA halkı, bana ürün\n"
    .string "çeşitlendirmesinde yardım etti.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Merhaba! Burada elimden\n"
    .string "geleni yapıyorum.\p"
    .string "Umarım sen de öyle yaparsın,\n"
    .string "{PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Merhaba, {PLAYER}!\n"
    .string "Hoş geldin!\p"
    .string "Uzak diyarlardan eşyalar getirmeye\n"
    .string "başladım.\p"
    .string "Nadir eşyalara da sahibim.\n"
    .string "Lütfen göz at!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "Oradaki adam, CELADON ŞEHRİ'nden\n"
    .string "taşınmış.\p"
    .string "Kardeşinin dükkanı var.\p"
    .string "Acaba kendini neye attığını\n"
    .string "biliyor muydu?$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "Dükkan sahibinin kardeşi OYUN\n"
    .string "KÖŞESİ'nde çalışıyor.\p"
    .string "Daha fazla ürün alabilmek için\n"
    .string "para biriktiriyorlar.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Dinle, dinle.\n"
    .string "Biliyor musun?\p"
    .string "Ünlü bir EĞİTMEN bir süre önce\n"
    .string "ADAYA gelmişti.\p"
    .string "O, ELİT DÖRTLÜ'den.\n"
    .string "Adı BRUNO.\p"
    .string "Öfkelilik Çubuklarının tükendiğini\n"
    .string "öğrenince üzgün ayrıldı.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "Bilge bir EĞİTMEN, nadir eşyaları\n"
    .string "buradan alır!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "Burnun ucunda bir kulübede yaşayan\n"
    .string "yaşlı bir kadın var.\p"
    .string "POKéMON'lara göz kırpar.\n"
    .string "Korkutucu.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Zıp! Zıp!\n"
    .string "Zıplama oyununu denedin mi?\p"
    .string "Katılabilecek POKéMON…\n"
    .string "Zıp! Zıp!\p"
    .string "Bazıları zıp zıp zıplar!\p"
    .string "Bazıları da zııııııp!\p"
    .string "Biliyor muydun?\n"
    .string "Zıp Zıp!$"
