TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner:
    .string "OYUN KÖŞESİ'ne\n"
    .string "gittin mi?\p"
    .string "Tek başına gitmek iyi değil.\n"
    .string "Bir arkadaşını da götürmelisin.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape:
    .string "İKİNCİ ADA'da çok az insan\n"
    .string "yaşıyor.\p"
    .string "Tepenin ucunda yaşayan yaşlı bir\n"
    .string "kadından bahsediyorlar.\p"
    .string "Orada ne zamandır yaşadığını\n"
    .string "kimse bilmiyor.$"
