FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "SELPHY: Ah evet?\n"
    .string "Tanışıyor muyuz sanki?\p"
    .string "Ah, ama önemli değil.\p"
    .string "Çok sıkıldım.\n"
    .string "Lütfen, dileğimi gerçekleştirin.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Bir POKéMON görmek istiyorum.\n"
    .string "Tatlı bir {STR_VAR_1}.\p"
    .string "Hemen görmek istiyorum.\n"
    .string "Lütfen dileğimi gerçekleştirin.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "SELPHY: Ah, sıkıldım.\n"
    .string "Sizi beklemekten yoruldum.\p"
    .string "Bu seferlik affediyorum,\n"
    .string "ama bir daha böyle olmasın.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "SELPHY: Ah, merhaba.\p"
    .string "Ah, lütfen. O, benim için\n"
    .string "yakaladığın {STR_VAR_1} olmalı.\p"
    .string "Kıkır kıkır…\n"
    .string "Sana benziyor.\p"
    .string "Çok naziksin.\p"
    .string "… …  … …  … …\n"
    .string "Bir sorun mu var?\p"
    .string "Gidebilirsin.\p"
    .string "… …  … …  … …\n"
    .string "Ah, peki. Şimdi anlıyorum.\p"
    .string "SEBASTIAN!\n"
    .string "Hemen yanıma gelmelisin!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "Kahya: Emredersiniz, hanımefendi.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "SELPHY: Bu kişiye bir teşekkür\n"
    .string "hediyesi verilmesini sağlayın.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "Kahya: Emriniz olur,\n"
    .string "hanımefendi.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "Kahya: Lütfen, hanımefendi\n"
    .string "SELPHY'yi memnun ettiğiniz için\l"
    .string "teşekkür ediyorum. Lütfen bunu\l"
    .string "kabul edin.$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "Kahya: Çantanız maalesef\n"
    .string "dolmuş gibi görünüyor.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Ah…\n"
    .string "Ne yazık.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "SELPHY: Şansınız bol olsun.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "Kahya: Hanımefendi SELPHY'nin\n"
    .string "gülümsemesi güneş kadar parlak.\p"
    .string "Lütfen, hanımefendi SELPHY'ye\n"
    .string "mutluluk verin.$"
