Route16_Text_LaoIntro::
    .string "Ne istiyorsun?$"

Route16_Text_LaoDefeat::
    .string "Gülme, sakın gülme!$"

Route16_Text_LaoPostBattle::
    .string "Burada takılmayı seviyoruz.\n"
    .string "Sana ne?$"

Route16_Text_KojiIntro::
    .string "Süper bir BİSİKLET!\n"
    .string "Bana ver!$"

Route16_Text_KojiDefeat::
    .string "Nokta!$"

Route16_Text_KojiPostBattle::
    .string "Bırak, senin bisikletine\n"
    .string "ihtiyacım yok!$"

Route16_Text_LukeIntro::
    .string "Gel küçük fare, oynayalım!$"

Route16_Text_LukeDefeat::
    .string "Sen küçük bir sıçansın!$"

Route16_Text_LukePostBattle::
    .string "Kaybetmeyi hiç sevmem!\n"
    .string "Defol gözümün önünden!$"

Route16_Text_HideoIntro::
    .string "Hey, çarptın bana!$"

Route16_Text_HideoDefeat::
    .string "Ka bum!$"

Route16_Text_HideoPostBattle::
    .string "Burada takılmayı seviyoruz,\n"
    .string "senin hoşuna gitsin ya da gitmesin.\p"
    .string "FUCHSIA'dan sahil boyunca\n"
    .string "VERMILION'a gidebilirsin.$"

Route16_Text_CamronIntro::
    .string "Açım ve sinirliyim!\n"
    .string "Bir yumruk torbasına ihtiyacım var!$"

Route16_Text_CamronDefeat::
    .string "Kötü, çok kötü!$"

Route16_Text_CamronPostBattle::
    .string "Eğer POKéMON'a sahip olacaksam,\n"
    .string "vahşi olmaları daha iyi.\p"
    .string "Düşmanlarımı perişan etmek için\n"
    .string "onları kullanırdım.$"

Route16_Text_RubenIntro::
    .string "Hey, merhaba!\n"
    .string "Eğlenelim!$"

Route16_Text_RubenDefeat::
    .string "Sinirimi bozma!$"

Route16_Text_RubenPostBattle::
    .string "Kötü kokulu POKéMON'larımla\n"
    .string "insanları taciz etmekten\l"
    .string "hoşlanıyorum.\p"
    .string "İnsanları korkutmak için harikalar.\n"
    .string "Ve evet, ısırırlar da.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "Bir POKéMON derin ve rahat\n"
    .string "bir uykuda uzanıyor.$"

Route16_Text_CyclingRoadSign::
    .string "Eğimli yokuşu keyifle kullanın!\n"
    .string "BİSİKLET YOLU$"

Route16_Text_RouteSign::
    .string "ROTA 16\n"
    .string "CELADON ŞEHRİ - FUCHSIA ŞEHRİ$"

Route16_Text_JedIntro::
    .string "JED: Aşkımız sınır tanımıyor.\n"
    .string "Aşıkız ve bunu gösteriyoruz!$"

Route16_Text_JedDefeat::
    .string "JED: Ah, hayır! Aşkım\n"
    .string "beni bir kaybeden olarak gördü!$"

Route16_Text_JedPostBattle::
    .string "JED: Dinle LEA.\n"
    .string "Lütfen benden biraz uzaklaş.$"

Route16_Text_JedNotEnoughMons::
    .string "JED: Sadece bir POKéMON'un mu var?\n"
    .string "Kalbin hiç mi sevgi içermiyor?$"

Route16_Text_LeaIntro::
    .string "LEA: Bazen, aşkımızın yoğunluğu\n"
    .string "beni korkutuyor.$"

Route16_Text_LeaDefeat::
    .string "LEA: Ahh! Ama JED bile yenilse\n"
    .string "soğukkanlılığını koruyor!$"

Route16_Text_LeaPostBattle::
    .string "LEA: Ehehe, üzgünüm.\n"
    .string "JED çok cool.$"

Route16_Text_LeaNotEnoughMons::
    .string "LEA: Ah, sadece bir POKéMON'un\n"
    .string "mu var?\p"
    .string "Sana ya da POKéMON'una yalnızlık\n"
    .string "hissettirmiyor mu?$"
