Route6_Text_RickyIntro::
    .string "Kim orada?\n"
    .string "Dinlemeyi kes!$"

Route6_Text_RickyDefeat::
    .string "Kazanamıyorum bir türlü!$"

Route6_Text_RickyPostBattle::
    .string "Fısıltı…\n"
    .string "Fısıltı…$"

Route6_Text_NancyIntro::
    .string "Özür dilerim!\n"
    .string "Bu özel bir konuşmaydı!$"

Route6_Text_NancyDefeat::
    .string "İıı!\n"
    .string "Kaybetmeyi hiç sevmiyorum.$"

Route6_Text_NancyPostBattle::
    .string "Fısıltı…\n"
    .string "Fısıltı…$"

Route6_Text_KeigoIntro::
    .string "Burada pek böcek yok.$"

Route6_Text_KeigoDefeat::
    .string "Hayır!\n"
    .string "Şaka mı yapıyorsun?$"

Route6_Text_KeigoPostBattle::
    .string "Böcekleri seviyorum, bu yüzden\n"
    .string "VIRIDIAN ORMANI'na geri dönüyorum.$"

Route6_Text_JeffIntro::
    .string "Hı?\n"
    .string "Benimle mi konuşmak istiyorsun?$"

Route6_Text_JeffDefeat::
    .string "İğrenç…\n"
    .string "Sizin meydan okumanızı yenemedim…$"

Route6_Text_JeffPostBattle::
    .string "Daha fazla POKéMON getirmeliyim\n"
    .string "Böylece daha güvende hissederim.$"

Route6_Text_IsabelleIntro::
    .string "Ben mi?\n"
    .string "Tamam, oynayalım!$"

Route6_Text_IsabelleDefeat::
    .string "Şeyler yolunda gitmedi…$"

Route6_Text_IsabellePostBattle::
    .string "Güçlenmek istiyorum.\n"
    .string "Sizin sırrınız ne?$"

Route6_Text_ElijahIntro::
    .string "Seni hiç görmemiştim.\n"
    .string "İyi misin?$"

Route6_Text_ElijahDefeat::
    .string "Çok iyisin!$"

Route6_Text_ElijahPostBattle::
    .string "POKéMON'larım zayıf mı?\n"
    .string "Yoksa ben mi kötüyüm?\l"
    .string "Sence hangisi?$"

Route6_Text_UndergroundPathSign::
    .string "ALT GEÇİŞ YOLU\n"
    .string "CERULEAN ŞEHRİ - VERMILION ŞEHRİ$"
