CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Sadece yetenekli EĞİTMENLER\n"
    .string "POKéMON ROZETİ toplayabilir.\p"
    .string "En az bir rozetin var gibi\n"
    .string "görünüyor.\p"
    .string "Bu ROZETLER inanılmaz sırlar taşır,\n"
    .string "biliyor muydun?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "O zaman…\p"
    .string "Sekiz ROZETTEN hangisini\n"
    .string "açıklamamı istersin?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Her zaman gelip beni\n"
    .string "ziyaret edebilirsin.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "Tüm POKéMON'larının SALDIRI\n"
    .string "değerleri biraz artar.\p"
    .string "Ayrıca FLAŞ hareketini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "SV. 30'a kadar POKéMON'lar sana\n"
    .string "itaat edecek.\p"
    .string "Buna takas yoluyla elde ettiğin\n"
    .string "yabancı POKéMON'lar da dahil.\p"
    .string "Ancak, daha yüksek seviyedeki\n"
    .string "POKéMON'lar\l"
    .string "savaş sırasında yaramaz olacak.\p"
    .string "Ayrıca KES hareketini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "Tüm POKéMON'larının HIZ değerleri\n"
    .string "biraz artar.\p"
    .string "Ayrıca UÇ hareketini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "Lv. 50'ye kadar POKéMON'lar sana\n"
    .string "itaat edecek.\p"
    .string "Bu, takas yoluyla elde ettiğin\n"
    .string "yabancı POKéMON'ları da içerir.\p"
    .string "Ancak, daha yüksek seviyedeki\n"
    .string "POKéMON'lar\l"
    .string "savaş sırasında yaramaz olacak.\p"
    .string "Ayrıca GÜÇ hareketini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "Tüm POKéMON'larının SAVUNMA\n"
    .string "statüleri biraz artar.\p"
    .string "Ayrıca SÖRF hareketini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "Lv. 70'e kadar POKéMON'lar sana\n"
    .string "itaat edecek.\p"
    .string "Bu, takas yoluyla elde ettiğin\n"
    .string "yabancı POKéMON'ları da içerir.\p"
    .string "Ancak, daha yüksek seviyedeki\n"
    .string "POKéMON'lar\l"
    .string "savaş sırasında yaramaz olacak.\p"
    .string "Ayrıca KAYA DARBESİ hareketini\n"
    .string "savaş dışı kullanmanı sağlar.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "Tüm POKéMON'larının ÖZEL SALDIRI\n"
    .string "ve ÖZEL SAVUNMA statüleri artar.\p"
    .string "Ayrıca ŞELALE hamlesini savaş dışı\n"
    .string "kullanmanı sağlar.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "Tüm POKéMON'lar sana itaat edecek!$"
