ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Köşedeki bilgisayarı\n"
    .string "kullanmaktan çekinmeyin!\p"
    .string "Resepsiyonist söyledi.\n"
    .string "Çok nazik bir hanımefendi!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Önümüzdeki her şehirde bir\n"
    .string "POKéMON MERKEZİ var.\p"
    .string "Para almazlar, bu yüzden\n"
    .string "POKéMON iyileştirmekten çekinmeyin.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "POKéMON MERKEZLERİ yorgun,\n"
    .string "yaralı veya baygın POKéMON'larınızı\l"
    .string "iyileştirir.\p"
    .string "Tüm POKéMON'ları tamamen\n"
    .string "sağlıklı hale getirirler.$"
