Route3_Text_TunnelFromCeruleanTiring::
    .string "Of ne demek… Dinlenmem gerek…\n"
    .string "Of…\p"
    .string "CERULEAN'dan gelen tünel çok\n"
    .string "yorucu!$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "Seni\l"
    .string "VIRIDIAN ORMANI'nda görmüştüm!$"

Route3_Text_ColtonDefeat::
    .string "Yenildim yine!$"

Route3_Text_ColtonPostBattle::
    .string "Ormanlarda bulamayacağın başka\n"
    .string "türde POKéMON'lar var.$"

Route3_Text_BenIntro::
    .string "Merhaba!\n"
    .string "Şort giymeyi severim!\p"
    .string "Çok rahat ve giymesi çok\n"
    .string "kolay!$"

Route3_Text_BenDefeat::
    .string "İnanamıyorum!$"

Route3_Text_BenPostBattle::
    .string "POKéMON'larınızı depolamak için\n"
    .string "bir POKéMON MERKEZİ'nin PC'sini\p"
    .string "kullanıyor musunuz? Her bir\n"
    .string "KUTU 30 POKéMON tutabilir.$"

Route3_Text_JaniceIntro::
    .string "Affedersin!\n"
    .string "Bana baktın, değil mi?$"

Route3_Text_JaniceDefeat::
    .string "Çok kötüsün!$"

Route3_Text_JanicePostBattle::
    .string "Bakmak istemiyorsan,\n"
    .string "savaşmamalısın!$"

Route3_Text_GregIntro::
    .string "Sen bir EĞİTMEN misin?\n"
    .string "Hemen başlayalım!$"

Route3_Text_GregDefeat::
    .string "Yeni POKéMON'larım olsaydı,\n"
    .string "kazanabilirdim!$"

Route3_Text_GregPostBattle::
    .string "Eğer bir POKéMON KUTUSU dolarsa,\n"
    .string "başka bir KUTUYA geçin.$"

Route3_Text_SallyIntro::
    .string "Bana baktığın o bakış…\n"
    .string "Çok merak uyandırıcı!$"

Route3_Text_SallyDefeat::
    .string "İyi davran!$"

Route3_Text_SallyPostBattle::
    .string "Eğer EĞİTMENLER seni görmezse,\n"
    .string "savaşlardan kaçınabilirsin.$"

Route3_Text_CalvinIntro::
    .string "Hey! Şort giymiyorsun!\n"
    .string "Neyin var?$"

Route3_Text_CalvinDefeat::
    .string "Yenildim!\n"
    .string "Yenildim! Yenildim!$"

Route3_Text_CalvinPostBattle::
    .string "Her zaman şort giyerim,\n"
    .string "kışın bile.\l"
    .string "Bu benim prensibim.$"

Route3_Text_JamesIntro::
    .string "Yeni yakaladığım POKéMON'larla\n"
    .string "sana karşı savaşacağım.$"

Route3_Text_JamesDefeat::
    .string "Bitti!\n"
    .string "Bitti bitti!$"

Route3_Text_JamesPostBattle::
    .string "Eğitilmiş POKéMON'lar, vahşi\n"
    .string "olanlardan daha güçlüdür.$"

Route3_Text_RobinIntro::
    .string "Ay!\n"
    .string "Bana dokundun mu?$"

Route3_Text_RobinDefeat::
    .string "Bu kadar mı?$"

Route3_Text_RobinPostBattle::
    .string "ROTA 4, AY DAĞI'nın eteklerinde.$"

Route3_Text_RouteSign::
    .string "ROTA 3\n"
    .string "AY DAĞI İLERİDE$"
