SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "POKéMON'ların kendi\n"
    .string "kişilikleri var, insanlar gibi.\p"
    .string "PIKACHU'um ACELECİ bir karaktere\n"
    .string "sahip, bu yüzden hızlı bir\l"
    .string "POKéMON oldu.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "Tamam, harabeleri keşfetmek için\n"
    .string "hazırlıklar tamam.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "YEDİNCİ ADA'da balık tutmam gerek.\p"
    .string "Bu, SEVII ADALARI'ndaki balıkçılık\n"
    .string "turumu tamamlayacak.\p"
    .string "Ancak önce biraz POKé TOPU\n"
    .string "stoklamam gerekiyor.$"
