Text_DoubleEdgeTeach::
    .string "Kendinle gurur duymalısın.\p"
    .string "ZAFER YOLU'nu savaşarak\n"
    .string "cesurca geçtin.\p"
    .string "Bu başarını takdir ederek,\n"
    .string "RİSKLİ VURUŞ öğretmek isterim.\p"
    .string "Bu tekniği öğretmemi ister misin?$"

Text_DoubleEdgeDeclined::
    .string "Tekniği sana her zaman\n"
    .string "öğretmeye hazırım.$"

Text_DoubleEdgeWhichMon::
    .string "Hangi POKéMON'a RİSKLİ VURUŞ\n"
    .string "öğretmemi istersin?$"

Text_DoubleEdgeTaught::
    .string "POKéMON LİGİ için bu motivasyonunu\n"
    .string "koruyarak devam et.\p"
    .string "Onlara meydan oku ve onları devir!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "Bir dahi çocuk hakkında\n"
    .string "dedikodular duydum.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "Dedikodular doğruymuş!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "Öyleyse, ROKET TAKIMI'ndan\n"
    .string "GIOVANNI'yi yenen sen misin?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "EĞİTMENLER daha güçlü rakipler arar.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "Oh!\n"
    .string "Çok güçlüsün!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "Zorlu savaşlar seni\n"
    .string "daha da güçlendirir.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "Sana ne kadar iyi olduğumu\n"
    .string "gösterceğim!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "Çok sinirlendim!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "Bana ne kadar iyi olduğumu\n"
    .string "gösterdin…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "Sadece seçilmiş olanlar\n"
    .string "buradan geçebilir!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "Buna inanamıyorum!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "Buradaki tüm EĞİTMENLER,\n"
    .string "POKéMON LİGİ'ne gidiyor\p"
    .string "Sakın rehavete kapılma.$"

VictoryRoad_3F_Text_RayIntro::
    .string "RAY: Biz, büyük başarılara\n"
    .string "imza atacağız!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "RAY: Saçmalık!\n"
    .string "Bunu kabul edemem!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "RAY: Bizi yendin.\n"
    .string "Büyüklük hala çok uzakta…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "RAY: Birlikte zirveye ulaşmak için\n"
    .string "çalışıyoruz.\p"
    .string "Bizimle savaşmak için iki\n"
    .string "POKéMON'a ihtiyacın var.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TYRA: Birlikte şampiyon olmak için\n"
    .string "çalışıyoruz.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TYRA: Ah, ama…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TYRA: Bana güç ve gücün sonsuz\n"
    .string "şekilde var olabileceğini gösterdin.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TYRA: Sadece bir POKéMON ile\n"
    .string "bizimle savaşamazsın.$"

