FiveIsland_Text_IslandSign::
    .string "BEŞ ADA\n"
    .string "Zamanın Geçtiği Ada: Chrono Adası$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Oh, bu berbattı. ÇAYIR'da\n"
    .string "oynamak istiyordum.\p"
    .string "Ama garip bir bina yaptılar\n"
    .string "orada, artık oynayamıyorum.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Son zamanlarda bu taraflar daha da\n"
    .string "yoğunlaştı.\p"
    .string "Son zamanlarda iyi balık da\n"
    .string "yakalayamadım.$"
