FiveIsland_Text_IslandSign::
    .string "BEŞİNCİ ADA\n"
    .string "Zamanın Geçtiği Ada: Chrono Adası$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Oh, bu berbat. ÇAYIR'da\n"
    .string "oynamak istiyordum.\p"
    .string "Ama oraya garip bir bina\n"
    .string "yaptılar, artık oynayamıyorum.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Son zamanlarda bu taraflar daha da\n"
    .string "yoğunlaştı.\p"
    .string "Son zamanlarda iyi balık da\n"
    .string "yakalayamadım.$"
