ViridianForest_Text_FriendsItchingToBattle::
    .string "Bazı arkadaşlarla BÖCEK\n"
    .string "POKéMON yakalamaya geldik!\p"
    .string "Hepsi POKéMON savaşlarına\n"
    .string "girmek için can atıyorlar!$"

ViridianForest_Text_RickIntro::
    .string "Hey! POKéMON'un var!\n"
    .string "Hadi!\l"
    .string "Savaşalım!$"

ViridianForest_Text_RickDefeat::
    .string "Hayır!\nCATERPIE dayanamaz!$"

ViridianForest_Text_RickPostBattle::
    .string "Sst! Böcekleri kaçıracaksın.\n"
    .string "Bir dahaki sefere, olur mu?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "Bir POKéMON EĞİTMENİ isen,\l"
    .string "dans edemezsin!$"

ViridianForest_Text_DougDefeat::
    .string "Hı?\n"
    .string "POKéMON'um kalmadı!$"

ViridianForest_Text_DougPostBattle::
    .string "Bu çok kötü! Daha güçlüleri\n"
    .string "yakalamam lazım!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, dur!\n"
    .string "Neden bu kadar acele ediyorsun?$"

ViridianForest_Text_SammyDefeat::
    .string "Pes ediyorum!\n"
    .string "Gerçekten iyisin!$"

ViridianForest_Text_SammyPostBattle::
    .string "Bazen, yerde şeyler bulabilirsin.\p"
    .string "Düştüğüm şeyleri arıyorum.\n"
    .string "Yardımcı olur musun?$"

ViridianForest_Text_AnthonyIntro::
    .string "Küçük olabilirim, ama bana acıma!\n"
    .string "Bunu sevmiyorum!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Ah, yazık.\n"
    .string "Hiçbir şey yolunda gitmedi.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Harçlığımın bir kısmını kaybettim…$"

ViridianForest_Text_CharlieIntro::
    .string "POKéMON'ların evrimleşebildiğini\n"
    .string "biliyor muydun?$"

ViridianForest_Text_CharlieDefeat::
    .string "Oh!\n"
    .string "Kaybettim!$"

ViridianForest_Text_CharliePostBattle::
    .string "BÖCEK POKéMON'lar hızlı evrimleşir.\n"
    .string "Onlarla çok eğleniyorum!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "POKéMON yakalamak için POKé\n"
    .string "TOPU atıyordum ve elimde kalmadı.\p"
    .string "Bu yüzden yeterince POKé\n"
    .string "TOPUN olduğundan emin ol.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "EĞİTMEN İPUCU\p"
    .string "Eğer POKéMON'ların zayıfsa ve\n"
    .string "savaşmalardan kaçınmak istiyorsan,\l"
    .string "otlu alanlardan uzak dur!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Zehirlenmeye karşı PANZEHİR\n"
    .string "kullanın! POKéMON MARKET'lerden\l"
    .string "alabilirsiniz!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "EĞİTMEN İPUCU\p"
    .string "PROF. OAK ile iletişime geçmek\n"
    .string "için bir PC kullanın\l"
    .string "ve POKéDEX'inizi\l"
    .string "değerlendirmesini isteyin!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "EĞİTMEN İPUCU\p"
    .string "Başkasına ait bir POKéMON'u\n"
    .string "yakalayamazsınız.\p"
    .string "Yalnızca yabani POKéMON'ları\n"
    .string "yakalamak için POKé TOPU atın!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "EĞİTMEN İPUCU\p"
    .string "Yakalamadan önce POKéMON'ları\n"
    .string "zayıflatın!\p"
    .string "Sağlıklıysalar kaçabilirler!$"

ViridianForest_Text_LeavingViridianForest::
    .string "VIRIDIAN ORMANINDAN AYRILIYOR\n"
    .string "PEWTER ŞEHRİ İLERİDE$"
