ViridianForest_Text_FriendsItchingToBattle::
    .string "Birkaç arkadaşımla BÖCEK\n"
    .string "POKéMON'u yakalamaya geldik!\p"
    .string "Hepsi POKéMON savaşlarına\n"
    .string "girmek için can atıyorlar!$"

ViridianForest_Text_RickIntro::
    .string "Hey! POKéMON'un var!\n"
    .string "Hadi! Savaşalım!$"

ViridianForest_Text_RickDefeat::
    .string "Olamaz!\nCATERPIE dayanamadı!$"

ViridianForest_Text_RickPostBattle::
    .string "Şşt! Böcekleri kaçıracaksın.\n"
    .string "Bir dahaki sefere, olur mu?$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "Bir POKéMON EĞİTMENİ isen,\l"
    .string "kaçamazsın!$"

ViridianForest_Text_DougDefeat::
    .string "Hı?\n"
    .string "POKéMON'um kalmadı!$"

ViridianForest_Text_DougPostBattle::
    .string "Bu çok kötü! Daha güçlüleri\n"
    .string "yakalamam lazım!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, dur!\n"
    .string "Neden bu kadar acele ediyorsun?$"

ViridianForest_Text_SammyDefeat::
    .string "Pes ediyorum!\n"
    .string "Gerçekten iyisin!$"

ViridianForest_Text_SammyPostBattle::
    .string "Bazen, yerde bir şeyler bulabilirsin.\p"
    .string "Düşürdüğüm şeyleri arıyorum.\n"
    .string "Yardımcı olur musun?$"

ViridianForest_Text_AnthonyIntro::
    .string "Küçük olabilirim, ama bana acıma!\n"
    .string "Bunu sevmiyorum!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Ah, yazık.\n"
    .string "Hiçbir şey yolunda gitmedi.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Harçlığımın bir kısmını kaybettim…$"

ViridianForest_Text_CharlieIntro::
    .string "POKéMON'ların evrimleşebildiğini\n"
    .string "biliyor muydun?$"

ViridianForest_Text_CharlieDefeat::
    .string "Ah!\n"
    .string "Kaybettim!$"

ViridianForest_Text_CharliePostBattle::
    .string "BÖCEK POKéMON'ları hızlı evrimleşir.\n"
    .string "Onlarla çok eğleniyorum!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "POKéMON yakalamak için POKé\n"
    .string "TOPU atıyordum ama elimde kalmadı.\p"
    .string "Bu yüzden yeterince POKéTOPUN\n"
    .string "olduğundan emin ol.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "Eğer POKéMON'larınız zayıfsa ve\n"
    .string "savaşlardan kaçınmak istiyorsanız\l"
    .string "otlu alanlardan uzak durun!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "Zehirlenmeye karşı PANZEHİR\n"
    .string "kullanın! POKéMON MARKET'lerinden\l"
    .string "alabilirsiniz!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "PROF. OAK ile iletişime geçmek\n"
    .string "için PC kullanıp POKéDEX'inizin\l"
    .string "değerlendirmesini isteyin!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "Başkasına ait bir POKéMON'u\n"
    .string "yakalayamazsınız.\p"
    .string "Yalnızca vahşi POKéMON'ları\n"
    .string "yakalayabilirsiniz!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "Yakalamadan önce POKéMON'ları\n"
    .string "zayıflatın!\p"
    .string "Sağlıklıysalar kaçabilirler!$"

ViridianForest_Text_LeavingViridianForest::
    .string "VIRIDIAN ORMANI SONU\n"
    .string "PEWTER ŞEHRİ İLERİDE$"
