SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "Şimdilerde pek de iyi görünmüyorum\n"
    .string "ama gençken…\p"
    .string "Her yere uçardım, bulduğum\n"
    .string "her EĞİTMEN'e meydan okurdum.\p"
    .string "Şimdi tek eğlencem, geçmişi\n"
    .string "yâd edip savaşları izlemek.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "Kutunun etrafında hafif bir rüzgâr\n"
    .string "esiyor.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "Ah!\n"
    .string "Hoş geldin, dostum!\p"
    .string "Bir şey söyleyeyim mi? Bodrumda\n"
    .string "gizli bir oda var.\p"
    .string "{STR_VAR_1} adında bir EĞİTMEN\n"
    .string "şu an orada bekliyor.\p"
    .string "Söyle bana, {STR_VAR_1}'e meydan\n"
    .string "okumak için mi geldin?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "Oh…\n"
    .string "Savaşmayacaksın…\p"
    .string "Anlıyorum, anlıyorum.\n"
    .string "… …\p"
    .string "Eğer fikrini değiştirirsen, lütfen\n"
    .string "geri gel.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "Ah!\n"
    .string "Benim için savaşacak mısın?\p"
    .string "O zaman kutuyu kenara çekmem\n"
    .string "boşuna değilmiş.\p"
    .string "… …\p"
    .string "Fakat bir sorun var. Bu gizli oda\n"
    .string "çok sağlam değil.\p"
    .string "Savaşın 3 POKéMON ile\n"
    .string "sınırlı olmasını ister misin?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "Tamam! Savaşmadan önce oyunu\n"
    .string "kaydetmek ister misin?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "Tamam.\n"
    .string "Hiçbir şeyi sakınmadan savaş!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "Maç berabere bitti.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "Berabere mi bitti?\p"
    .string "Fakat şunu söylemeliyim ki, muhteşem\n"
    .string "bir gösteriydi.\p"
    .string "Gerçekten derinlik hissi veren harika\n"
    .string "bir savaş olduğunu söyleyebilirim!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "Bravo!\p"
    .string "Gerçekten bravo!\n"
    .string "Ne müthiş bir savaş!\p"
    .string "O kadar müthişti ki, gözlerimi\n"
    .string "yaşartıyor!\p"
    .string "Uzmanca kullanılan tekniklerin\n"
    .string "çarpışması!\p"
    .string "Gücün güç ile çarpışması!\p"
    .string "Evet!\n"
    .string "Muhteşem bir gösteriydi!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "Yazık!\n"
    .string "Üzüntünü hissedebiliyorum.\p"
    .string "Fakat bu üzüntü seni daha iyi\n"
    .string "yapacak.\p"
    .string "Onu kullan, ondan ders al ve\n"
    .string "büyüklük ararken motivasyonun\l"
    .string "olsun.\p"
    .string "Bu üzüntüyü unutma ve\n"
    .string "çalışmalarını artır!$"
