FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "Akşam yemeği için\n"
    .string "bir şey almana gerek yok!\p"
    .string "Eşim balık tutmaya giderken\n"
    .string "böyle demişti.\p"
    .string "Sözünü tutup tutmayacağından\n"
    .string "emin değilim.$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "Akşam yemeği için bir şey\n"
    .string "almana gerek yokmuş!\p"
    .string "Eşim bugün balık tutmaya\n"
    .string "giderken böyle demiş.\p"
    .string "Sözünü tutup tutmayacağından\n"
    .string "emin değilim.$"
