MtMoon_B2F_Text_MiguelIntro::
    .string "Dur, bekle!\p"
    .string "Bu fosilleri ben buldum!\n"
    .string "İkisi de benim!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Tamam!\n"
    .string "Seninle paylaşacağım!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "Her birimiz bir fosil alalım!\n"
    .string "Açgözlü olmayalım!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "Pekala.\n"
    .string "O zaman bu fosil benim!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "Uzaklarda, CINNABAR ADA'sında\n"
    .string "bir POKéMON LAB'ı var.\p"
    .string "Fosilleri canlandırma üzerine\n"
    .string "araştırma yapıyorlar.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "Biz, ROKET TAKIMI, fosilleri\n"
    .string "bulacağız!\p"
    .string "Fosillerden POKéMON'ları\n"
    .string "diriltirsek çok zengin oluruz!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Auv!\n"
    .string "Şimdi sinirlendim!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "Beni sinirlendirdin!\p"
    .string "ROKET TAKIMI seni\n"
    .string "kara listeye alacak!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "Biz, ROKET TAKIMI,\n"
    .string "POKéMON çetesiyiz!\l"
    .string "Gücümüzle korku salarız!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "Batırdım!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Lanet olsun!\n"
    .string "Arkadaşlarım buna sessiz kalmaz!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "Burada büyük bir iş çeviriyoruz!\n"
    .string "Defol buradan, çocuk!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "Evet, iyiymişsin…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "Eğer bir fosil bulursan, bana\n"
    .string "ver ve kaybol!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Küçük çocuklar büyüklerle\n"
    .string "uğraşmamalı!\p"
    .string "Bu iş sana zarar verebilir!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "Çok sinirlendim!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "İnsanlar gelmeden çok önce\n"
    .string "POKéMON'lar burada yaşardı.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "DOME FOSİLİ'ni ister misin?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "HELİX FOSİLİ'ni ister misin?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "HELİX FOSİLİ elde ettin!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "DOME FOSİLİ elde ettin!$"



