FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "Ayy!\p"
    .string "Düşündüm ki burası antik bir enkaz\n"
    .string "Ama hayaletlerle dolu!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "Ayy! Merhamet!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "Buradan çıkmaya çalışıyorum ama\n"
    .string "Aynı yere geri dönüyorum hep.\p"
    .string "Belki de taşların sayısı\n"
    .string "Bir ipucu veriyor…$"
