TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Şimdi, LOSTELLE bugün nereye\n"
    .string "kayboldu?\p"
    .string "O her gün bana tam bu zamanda\n"
    .string "öğle yemeği getirirdi…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Sen, oradaki!\n"
    .string "LOSTELLE'in arkadaşı mısın?\p"
    .string "Buralarda LOSTELLE'i gördün mü?\n"
    .string "Nerede olduğunu bilmiyorum.\l"
    .string "Çoktan burada olmalıydı.\p"
    .string "LOSTELLE şirin bir kız - bana\n"
    .string "benziyor - ya birileri…\p"
    .string "Ya LOSTELLE'in başına bir şey\n"
    .string "geldiyse?!\p"
    .string "Lütfen, onu bulmama yardım edin!\n"
    .string "Lütfen onu ÜÇÜNCÜ ADA'da arayın!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Hah? Bu OYUN KÖŞESİ de ne?\n"
    .string "Daha ne kadar üzücü olabilir?\p"
    .string "O çömezler…\p"
    .string "Adada bekleyeceklerini söylediler,\n"
    .string "o zaman neredeler?\p"
    .string "Hey, sen! Burada başka ÜÇÜNCÜ\n"
    .string "ADA var mı?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Yatağından çıkmadan önce uyanmaya\n"
    .string "çalış, serseri.\p"
    .string "Burası İKİNCİ ADA!\p"
    .string "Çık hemen! Kirli motosikletini\n"
    .string "mekanımdan uzak tut!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Ha…\n"
    .string "Oh, oh, anladım.\p"
    .string "Tch…\n"
    .string "Bu adalar kafa karıştırıcı…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Şuna bakar mısın?\n"
    .string "O serseri parkeleri çizdi.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hey, ama dinle! Yalvarıyorum sana,\n"
    .string "ÜÇÜNCÜ ADA'ya gitmelisin.\p"
    .string "Eğer LOSTELLE'e bir şey olursa…\p"
    .string "Evim ÜÇÜNCÜ ADA'daki kırmızı\n"
    .string "çatılı bina.\p"
    .string "Belki geç de olsa buraya gelir,\n"
    .string "o yüzden buradan ayrılamam.\p"
    .string "Bu yüzden bana bu iyiliği\n"
    .string "yapmanı istiyorum.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Üzgünüm.\n"
    .string "Bugün hiçbir oyunu oynamıyoruz.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Oyunları yakında senin için\n"
    .string "başlatacağız!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Öyleyse LOSTELLE'i kurtardın mı?\n"
    .string "Nasıl teşekkür edebilirim?\p"
    .string "LOSTELLE, tatlım, beni affet!\p"
    .string "Baban, korktuğunu ve zor\n"
    .string "durumda olduğunu bilmiyordu!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Baba, sorun yok.\n"
    .string "{PLAYER} ile arkadaş oldum!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Oh, bu ne?\n"
    .string "Bunu benim için mi diyorsun?\p"
    .string "Neden nadir kayalar ve taşlar\n"
    .string "sevdiğimi nasıl bildin?\p"
    .string "Bir adamı mutlu etmeyi biliyorsun.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} LOSTELLE'in babasına\n"
    .string "METEORİT'i verdi.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Oh, anladım, bu BILL'den!\n"
    .string "Benim adıma ona teşekkür et!\p"
    .string "Biliyorsun, harikaydın.\n"
    .string "Bunun senin olmasını istiyorum.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} LOSTELLE'in babasından\n"
    .string "bir AY TAŞI aldı.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "Çantanız başka bir şey almıyor…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Tamam, OYUN KÖŞESİ'ni hemen\n"
    .string "çalıştıracağım.\p"
    .string "Bir arkadaşla gelmelisin.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Dinle, dinle!\p"
    .string "Lütfen bana tekrar havalı olmanı\n"
    .string "göster!$"
