TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "LOSTELLE bugün nereye kayboldu?\p"
    .string "O her gün bana tam bu zamanda\n"
    .string "öğle yemeği getirirdi…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Sen, oradaki!\n"
    .string "LOSTELLE'in arkadaşı mısın?\p"
    .string "Buralarda LOSTELLE'i gördün mü?\n"
    .string "Nerede olduğunu bilmiyorum.\l"
    .string "Çoktan burada olmalıydı.\p"
    .string "LOSTELLE pek tatlıdır - tıpkı\n"
    .string "benim gibi - ya birileri…\p"
    .string "Ya LOSTELLE'in başına bir şey\n"
    .string "geldiyse?!\p"
    .string "Lütfen, onu bulmama yardım et!\n"
    .string "Lütfen ÜÇÜNCÜ ADA'ya git ve ara!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Hah? Bu OYUN KÖŞESİ nedir?\n"
    .string "Bu daha ne kadar kötü olabilir?\p"
    .string "O palyaçolar…\p"
    .string "Adada bekleyeceklerini söylediler,\n"
    .string "o zaman nerede olabilirler ki?\l"
    .string "Neredeler?\p"
    .string "Hey, sen! Yoksa buradan başka bir\n"
    .string "ÜÇÜNCÜ ADA daha mı var?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Konuşmadan önce gözlerini aç ve\n"
    .string "uyan, sersem.\p"
    .string "Burası İKİNCİ ADA'dır!\p"
    .string "Kaybol buradan! Kirli\n"
    .string "motosikletini mekanımdan çıkar!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Ha…\n"
    .string "Ah, Ah, anladım.\p"
    .string "Cık…\n"
    .string "Bu adalar kafa karıştırıcı…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Şuna bak?\n"
    .string "O serseri zeminimi çizdi.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hey, ama dinle! Yalvarıyorum sana,\n"
    .string "ÜÇÜNCÜ ADA'ya gitmelisin.\p"
    .string "Ya LOSTELLE'e bir şey olursa!?\p"
    .string "Evim ÜÇÜNCÜ ADA'daki kırmızı\n"
    .string "çatılı bina.\p"
    .string "O her an buraya gelebilir,\n"
    .string "bu yüzden hiçbir yere gidemem.\p"
    .string "Bana büyük bir iyilik yapman\n"
    .string "gerekiyor.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Üzgünüm.\n"
    .string "Bugün hiçbir oyunu oynamıyoruz.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Oyunları yakında senin için\n"
    .string "başlatacağız!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Hey, LOSTELLE'i kurtardın mı sen?\n"
    .string "Nasıl teşekkür edebilirim?\p"
    .string "LOSTELLE, tatlım, beni affet!\p"
    .string "Baban, korktuğunu ve zor\n"
    .string "durumda olduğunu bilmiyordu!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Baba, sorun yok.\n"
    .string "{PLAYER} ile arkadaş oldum!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Ha, bu ne?\n"
    .string "Bunu benim için mi diyorsun?\p"
    .string "Nadir kayalar ve taşlar sevdiğimi\n"
    .string "nereden bildin?\p"
    .string "Bir adamı mutlu etmeyi biliyorsun.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER}, LOSTELLE'in babasına\n"
    .string "METEORİT'i verdi.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Anladım, bu BILL'den demek ki!\n"
    .string "Benim adıma ona teşekkür et!\p"
    .string "Biliyorsun, harikaydın.\n"
    .string "Bunun senin olmasını istiyorum.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} LOSTELLE'in babasından\n"
    .string "bir AY TAŞI aldı.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "Çantan dolu…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Tamam, OYUN KÖŞESİ'ni hemen\n"
    .string "çalıştıracağım.\p"
    .string "Bir ara arkadaşlarınla gelip\n"
    .string "oynamalısın.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Dinle, dinle!\p"
    .string "Lütfen bana tekrar havalı pozunu\n"
    .string "göster!$"
