TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "Şimdi LOSTELLE nerede?\n"
    .string "bugün?\p"
    .string "O her gün bana öğle yemeği getirir\n"
    .string "gün tam şu anda…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "Hm? Sen, orada!\n"
    .string "LOSTELLE'in arkadaşı mısın?\p"
    .string "LOSTELLE'i etrafta gördün mü?\n"
    .string "Nerede olduğunu bilmiyorum.\l"
    .string "Çoktan burada olmalıydı.\p"
    .string "LOSTELLE bir tatlıdır - benim\n"
    .string "görünüşümü aldı - öyleyse biri…\p"
    .string "Bir şeyler LOSTELLE'e mi oldu?\n"
    .string "Lütfen, onu bulmama yardım edin!\n"
    .string "Lütfen ÜÇ ADAYA gidin ve arayın!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "Hah? Bu OYUN KÖŞESİ nedir?\n"
    .string "Bu daha ne kadar üzgün olabilir?\p"
    .string "O palyaçolar…\p"
    .string "Adada bekleyeceklerini söylediler,\n"
    .string "o zaman nerede olduklarını\l"
    .string "nasıl biliyor?\p"
    .string "Hey, sen! Burada başka ÜÇÜNCÜ\n"
    .string "ADA var mı?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "Yatağından çıkmadan önce uyanmaya çalış,\n"
    .string "punk.\p"
    .string "Bu İKİNCİ ADA'dır!\p"
    .string "Harekete geç! Kirli motosikletini\n"
    .string "yerimden çıkar!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Huh…\n"
    .string "Oh, oh, anladım.\p"
    .string "Tch…\n"
    .string "Bu adalar kafa karıştırıcı…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "Buna bakın?\n"
    .string "O punk zeminimi çizdi.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Hey, ama dinle! Yalvarıyorum sana,\n"
    .string "üç adaya gitmelisin.\p"
    .string "Eğer LOSTELLE'e bir şey olursa\n"
    .string "Yerim, kırmızı çatılı ev,\n"
    .string "ÜÇÜNCÜ ADA'da.\p"
    .string "O sadece burada geç gelebilir,\n"
    .string "o yüzden hiçbir yere gidemem.\p"
    .string "Bu yüzden sana büyük bir\n"
    .string "iyilik yapman gerekiyor.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Üzgünüm.\n"
    .string "Bugün hiçbir oyunu oynamıyoruz.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Oyunları yakında senin için\n"
    .string "başlatacağız!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "Öyleyse LOSTELLE'i kurtardın mı?\n"
    .string "Nasıl teşekkür edebilirim?\p"
    .string "LOSTELLE, tatlım, beni affet!\p"
    .string "Baban, korktuğunu ve zor\n"
    .string "durumda olduğunu bilmiyordu!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "LOSTELLE: Baba, sorun yok.\n"
    .string "{PLAYER} ile arkadaş oldum!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "Oh, bu ne?\n"
    .string "Bunu benim için mi diyorsun?\p"
    .string "Neden nadir kayalar ve taşlar\n"
    .string "sevdiğimi nasıl bildin?\p"
    .string "Bir adamı mutlu etmeyi biliyorsun.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} METEORİT'i verdi\n"
    .string "LOSTELLE'in babasına.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "Oh, anladım, bu BILL'den!\n"
    .string "Onun için ona teşekkür etmelisin!\p"
    .string "Biliyorsun, harikaydın.\n"
    .string "Bunu senin olmasını istiyorum.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} bir AY TAŞI aldı\n"
    .string "LOSTELLE'in babasından.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "Çantanız başka bir şey almıyor…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Tamam, OYUN KÖŞESİ'ni hemen\n"
    .string "çalıştıracağım.\p"
    .string "Bir arkadaşla gelmelisin.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "Dinle, dinle!\p"
    .string "Lütfen bana tekrar havalı olmanı\n"
    .string "göster!$"
