Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "POKéMON LİGİ'ne mi gidiyorsun?\n"
	.string "Unut gitsin!\p"
	.string "Herhalde hiç rozetin yok,\n"
	.string "değil mi?\p"
	.string "Rozetsiz seni içeri\n"
	.string "almayacaklar.\p"
	.string "Bu arada, POKéMON'ların\n"
	.string "güçlendi mi?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww!\n"
	.string "Şanslıydın!$"

Route22_Text_EarlyRivalPostBattle::
	.string "POKéMON LİGİ'nde birçok\n"
	.string "güçlü EĞİTMEN olduğunu duydum\p"
	.string "Onları nasıl alt\n"
	.string "edeceğimi düşünmeliyim.\p"
	.string "Sen de oyalanmayı kes ve\n"
	.string "harekete geç!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!$"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}: Neden 2 Pokemonum var\n"
	.string "diye mi soruyorsun?\p"
	.string "Sen de daha fazla yakalamalısın!$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: Ne? {PLAYER}!\n"
	.string "Burada seni görmek sürpriz oldu!\p"
	.string "POKéMON LİGİ'ne mi gidiyorsun?\p"
	.string "Rozetleri de topladın mı?\n"
	.string "Bu havalı!\p"
	.string "O zaman {PLAYER}, POKéMON\n"
	.string "LİGİ'ne hazırlık olarak seni\l"
	.string "bir güzel pataklayacağım!\p"
	.string "Hadi gel!$"

Route22_Text_LateRivalDefeat::
	.string "Ne!?\p"
	.string "Sadece dikkatsizdim, {PLAYER}!$"

Route22_Text_LateRivalPostBattle::
	.string "Biraz ısındım.\n"
	.string "Artık POKéMON LİGİ için hazırım!\p"
	.string "{PLAYER}, daha çok pratik\n"
	.string "yapman lazım.\p"
	.string "Ama hey, bunu zaten biliyorsun!\n"
	.string "Ben kaçtım. Sonra görüşürüz!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!$"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}: Hahaha! {PLAYER}!\n"
	.string "Bu kadar mı?\p"
	.string "Bana kıyasla daha çok\n"
	.string "çalışman lazım {PLAYER}!\p"
	.string "Daha çok antrenman yap!\n"
	.string "Kaybeden!$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LİGİ\n"
	.string "Ana Giriş$"
