OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "Dalgaların salladığı bir\n"
    .string "salıncakta uzanmak…\p"
    .string "Tarifsiz bir duygu.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "Kaybettim…\n"
    .string "Kötü hissettiriyor.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "Buradaki deniz keyifle\n"
    .string "yüzülebilecek kadar sıcak.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Okyanus akıntısı, iyi şeyleri bu\n"
    .string "plaja sürükler.\p"
    .string "Bu yüzden sık sık sahilde yürüyüşe\n"
    .string "çıkarım.$"
