SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "BAŞKAN: Oh, sevgili çocuk!\n"
    .string "SILPH'i kurtardığın için\l"
    .string "teşekkürler.\p"
    .string "Tehlikeli anımızda bizi kurtardığını\n"
    .string "asla unutmayacağım.\p"
    .string "Bir şekilde teşekkür etmeliyim.\p"
    .string "Zengin olduğum için sana her şeyi\n"
    .string "verebilirim.\p"
    .string "İşte, belki bu işini görür.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "BAŞKAN: Oh, sevgili kız!\n"
    .string "SILPH'i kurtardığın için\l"
    .string "teşekkürler.\p"
    .string "Tehlikeli anımızda bizi kurtardığını\n"
    .string "asla unutmayacağım.\p"
    .string "Bir şekilde teşekkür etmeliyim.\p"
    .string "Zengin olduğum için sana her şeyi\n"
    .string "verebilirim.\p"
    .string "İşte, belki bu işini görür.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} BAŞKAN'dan USTA TOP\n"
    .string "elde etti!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "BAŞKAN: Bunu hiçbir yerde\n"
    .string "bulamazsın.\p"
    .string "Bu, gizli prototip USTA\n"
    .string "TOP'umuz.\p"
    .string "Her POKéMON'u kesin yakalar!\p"
    .string "Ancak, kullanırken dikkatli ol.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "Bunun için yerin yok.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "KATİP: Bizi kurtardığın için\n"
    .string "teşekkürler.\p"
    .string "Biz, BAŞKAN'dan işçisine kadar,\n"
    .string "sana borçluyuz.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "Tekrar karşılaştık!\p"
    .string "BAŞKAN ile çok önemli bir iş\n"
    .string "konuşuyorduk.\p"
    .string "Yetişkin işlerine burnunu sokma…\p"
    .string "Yoksa acı çekersin!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "Aaaah!!\n"
    .string "Yenildim yine!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Lanet olsun!\n"
    .string "SILPH için planlarımızı mahvettin!\p"
    .string "Ama, ROKET TAKIMI asla yıkılmaz!\p"
    .string "{PLAYER}! Tüm POKéMON'ların\n"
    .string "ROKET TAKIMI için var olduğunu\l"
    .string "unutma!\p"
    .string "Şimdi gidiyorum, ama geri döneceğim!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Dur orada!\n"
    .string "Hareket etme!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Yapma…\n"
    .string "Lütfen!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "Demek, PATRONU görmek istiyorsun?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Dur! PATRON ile randevun var mı?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Aaaah!\n"
    .string "Yıkıldım!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Dikkatli ol…\n"
    .string "PATRON güçlü POKéMON'ları sever!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "Monitörde POKéMON'lar var!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİS\n"
    .string "11. Kat$"

