PokemonMansion_Text_PressSecretSwitch::
    .string "Gizli bir düğme!\p"
    .string "Basıyor musun?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Kim istemez ki?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Henüz değil!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "Dışarı çıkamıyorum!\n"
    .string "Bu eski yer büyük bir bulmaca.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, hayır!\n"
    .string "Çantamdaki ganimetlerim!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "Buradaki düğmeler birbiri ardına\n"
    .string "kapıları açıp kapatır.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Günlük: 5 Temmuz\n"
    .string "Guyana, Güney Amerika\p"
    .string "Yeni bir POKéMON, ormanın\n"
    .string "derinliklerinde keşfedildi.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Günlük: 10 Temmuz\n"
    .string "Yeni keşfedilen POKéMON'a\l"
    .string "MEW adını verdik.$"

