CinnabarIsland_Gym_Text_BlaineIntro::
.string "Hah! \n"
.string "Ben CINNABAR SALONU'nun\n"
.string "kızgın lideri BLAINE'im\p"
.string "Ateşli POKéMON'larım müthiş\n"
.string "sıcaklıkla hazır ve sert!\p"
.string "Tüm meydan okuyanları yakarlar!\p"
.string "Hah!\n"
.string "İyisi mi sen bir YANIK İLACI al!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
.string "Kül oldum, kül!\n"
.string "Hiçbir şey kalmadı!\n"
.string "VOLKAN ROZETİ'ni hak ettin.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
.string "FIRE BLAST en güçlü ateş\n"
.string "tekniğidir.\p"
.string "Bunu SU POKéMON'larına harcama.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
.string "Hah!\p"
.string "VOLKAN ROZETİ, POKéMON'larının\n"
.string "ÖZEL istatistiklerini artırır.\p"
.string "İşte, bunu da sana veriyorum!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
.string "{PLAYER} BLAINE'den TM38\n"
.string "aldı.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
.string "TM38 ATEŞPATLAMA içerir.\n"
.string "Bunu ATEŞ tipi POKéMON'lara öğret.\n"
.string "VULPIX veya CHARMELEON için ideal.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
.string "Bunun için yer aç, çocuk!$"

CinnabarIsland_Gym_Text_ErikIntro::
.string "POKéMON'un ateş nefesinin ne kadar\n"
.string "sıcak olabileceğini biliyor musun?$"

CinnabarIsland_Gym_Text_ErikDefeat::
.string "Yow!\n"
.string "Çok sıcak, çok!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
.string "Ateş, daha doğrusu alev…\p"
.string "…Hava içindeki oksijen…\p"
.string "Bla bla bla bla…$"

CinnabarIsland_Gym_Text_QuinnIntro::
.string "Önceden bir hırsızdım, ama artık\n"
.string "bir EĞİTMEN oldum.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
.string "Teslim oluyorum!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
.string "Başkalarının POKéMON'larını\n"
.string "çalmaktan kendimi alı koyamıyorum.$"

CinnabarIsland_Gym_Text_AveryIntro::
.string "POKéMON'lara iyice çalıştım.\n"
.string "Kazanamazsın!$"

CinnabarIsland_Gym_Text_AveryDefeat::
.string "Waah!\n"
.string "Çalışmalarım yetersiz kaldı!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
.string "Teorilerim senin için çok\n"
.string "karmaşık.$"

CinnabarIsland_Gym_Text_RamonIntro::
.string "Ben ATEŞ türlerini severim.\n"
.string "İşte bu kadar.$"

CinnabarIsland_Gym_Text_RamonDefeat::
.string "Çok sıcak!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
.string "Keşke bir hırsız POKéMON'um\n"
.string "olsaydı. Onu kullanırdım!$"

CinnabarIsland_Gym_Text_DerekIntro::
.string "BLAINE'in neden bir\n"
.string "EĞİTMEN olduğunu biliyorum.$"

CinnabarIsland_Gym_Text_DerekDefeat::
.string "Auv!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
.string "Liderimiz BLAINE bir gün\n"
.string "dağlarda kaybolmuştu.\p"
.string "Gece olduğunda ateşli bir\n"
.string "kuş POKéMON'u göründü.\p"
.string "Onun ışığı BLAINE'e yol gösterdi.$"

CinnabarIsland_Gym_Text_DustyIntro::
.string "Birçok SALON'a gittim, ama burası\n"
.string "tarzıma en uygun olanı.$"

CinnabarIsland_Gym_Text_DustyDefeat::
.string "Yowza!\n"
.string "Çok sıcak!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
.string "PONYTA, NINETALES…\n"
.string "Bunlar popüler ATEŞ POKéMON'ları.$"

CinnabarIsland_Gym_Text_ZacIntro::
.string "Ateşin H2O'ya karşı zayıftır$"

CinnabarIsland_Gym_Text_ZacDefeat::
.string "Oh!\n"
.string "Söndüm!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
.string "Elbette ki su ateşi söndürür.\n"
.string "Ama ateş buzları eritir, bu yüzden\l"
.string "ATEŞ türü BUZ türlerini yener.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
.string "Yo!\n"
.string "Şampiyon adayı!\p"
.string "BLAINE ateşli bir ATEŞ POKéMON'u\n"
.string "uzmanıdır.\p"
.string "Onu suyla söndür!\n"
.string "Ve YANIK İLACI almayı unutma.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
.string "{PLAYER}!\n"
.string "O ateş topunu yendin!$"

CinnabarIsland_Gym_Text_GymStatue::
.string "CİNNABAR POKéMON SALONU\n"
.string "LİDER: BLAINE\n"
.string "KAZANAN ANTRENÖRLER:\n"
.string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
.string "CİNNABAR POKéMON SALONU\n"
.string "LİDER: BLAINE\n"
.string "KAZANAN ANTRENÖRLER:\n"
.string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
.string "POKéMON Bilgi Yarışması!\p"
.string "Doğru cevapla bir sonraki odaya\n"
.string "geçebilirsin.\p"
.string "Yanlış cevap verirsen bir\n"
.string "EĞİTMEN ile savaşmak zorunda\l"
.string "kalacaksın.\p"
.string "POKéMON'larını SALON LİDERİ\n"
.string "saklamak istiyorsan…\p"
.string "Soruları doğru cevapla!\n"
.string "Başlıyoruz!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
.string "CATERPIE METAPOD'a evrimleşir.$"

CinnabarIsland_Gym_Text_QuizQuestion2::
.string "Dokuz adet resmi POKéMON\n"
.string "LİGİ ROZETİ vardır.$"

CinnabarIsland_Gym_Text_QuizQuestion3::
.string "POLIWAG üç kez evrimleşir.$"

CinnabarIsland_Gym_Text_QuizQuestion4::
.string "ELEKTRİK hareketleri YER\n"
.string "türlerine etkilidir.$"

CinnabarIsland_Gym_Text_QuizQuestion5::
.string "Aynı tür ve seviyedeki\n"
.string "POKéMON'lar aynı değildir.$"

CinnabarIsland_Gym_Text_QuizQuestion6::
.string "TM28 MEZARTAŞ içerir.$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
.string "Doğru cevap!\n"
.string "Geçebilirsin!$"

CinnabarIsland_Gym_Text_SorryBadCall::
.string "Üzgünüm!\nYanlış cevap!$"
