PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "Ne!?\p"
    .string "ROKET TAKIMI AY DAĞI'nda mı?\n"
    .string "Hı?\p"
    .string "Telefonla konuşuyorum!\n"
    .string "Defol buradan!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "“Esner”\p"
    .string "JIGGLYPUFF şarkı söylediğinde\n"
    .string "POKéMON'ların uykusu geliyor…\p"
    .string "…Benim de…\n"
    .string "“Horrr”…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "Gerçekten bir PIKACHU istiyorum\n"
    .string "bu yüzden CLEFAIRY'imi\l"
    .string "onunla takas edebilirim.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .string "Oradaki çocukla POKéMON takası\n"
    .string "yapıyorum.\p"
    .string "İki PIKACHU'm vardı, bu yüzden\n"
    .string "birini takas etmenin iyi olacağını\l"
    .string "düşündüm.$"
