SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "Kanka, kaybedersen\n"
    .string "denize yürüyeceksin!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "Vah!\n"
    .string "Bir çocuğa yenildim!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "Denize çıktığımızda bazen\n"
    .string "denizanası POKéMON'lar görürüz.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "Merhaba yabancı!\p"
    .string "Denizden mi geldin, dağlardan mı?\p"
    .string "Dur, biraz sohbet edelim.\n"
    .string "Tüm POKéMON'larım denizden.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "Olamaz!\n"
    .string "Bunu kaçırdım!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "Yardımcım olacaktın!$"


