Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Merhaba! Ben bir POKéMON'um…\n"
    .string "…Hayır değilim!\p"
    .string "Bana BILL de!\n"
    .string "Ben gerçek bir POKéMANYAK'ım!\p"
    .string "Hey!\n"
    .string "O şüpheci bakışın ne?\p"
    .string "Sana yalan söylemiyorum, dostum.\p"
    .string "Bir deneyde başarısız oldum ve\n"
    .string "bir POKéMON'la birleşmiş oldum!\p"
    .string "O zaman, ne dersin?\n"
    .string "Bana burada yardım et!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Merhaba! Ben bir POKéMON'um…\n"
    .string "…Hayır değilim!\p"
    .string "Bana BILL de!\n"
    .string "Ben gerçek bir POKéMANYAK'ım!\p"
    .string "Hey!\n"
    .string "O şüpheci bakış ne?\p"
    .string "Sana yalan söylemiyorum,\n"
    .string "hanımefendi.\p"
    .string "Bir deneyde başarısız oldum ve\n"
    .string "bir POKéMON'la birleşmiş oldum!\p"
    .string "O zaman, ne dersin?\n"
    .string "Bana burada yardım et!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Ben IŞINLAYICI'ya girene\n"
    .string "kadar bekle.\p"
    .string "Oraya girdiğimde, PC'ye git ve\n"
    .string "Hücre Ayrıştırma Sistemini\l"
    .string "çalıştır.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Hayır!?\n"
    .string "Şimdi bu kadar soğuk yapma!\p"
    .string "Gel, bir adama yardım etmelisin\n"
    .string "başım büyük, büyük bir belada!\p"
    .string "Ne dersin, şef?\n"
    .string "Lütfen?\l"
    .string "Tamam?\l"
    .string "Tamam!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Hayır!?\n"
    .string "Şimdi bu kadar soğuk yapma!\p"
    .string "Gel, bir adama yardım etmelisin\n"
    .string "başım büyük, büyük bir belada!\p"
    .string "Ne dersin, güzellik?\n"
    .string "Lütfen?\l"
    .string "Tamam?\l"
    .string "Tamam!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Teşekkürler, dostum!\l"
    .string "Sana bir borcum var!\p"
    .string "Öyleyse, POKéMON koleksiyonumu\n"
    .string "görmeye mi geldin?\p"
    .string "Hayır mı?\n"
    .string "Bu kötü.\p"
    .string "Sana teşekkür borçluyum…\n"
    .string "Oh, burada, belki bu işi görür.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Teşekkürler, hanımefendi!\l"
    .string "Sana bir borcum var!\p"
    .string "Öyleyse, POKéMON koleksiyonumu\n"
    .string "görmeye mi geldin?\p"
    .string "Hayır mı?\n"
    .string "Bu kötü.\p"
    .string "Sana teşekkür borçluyum…\n"
    .string "Oh, burada, belki bu işi görür.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER}, BILL'den bir\n"
    .string "S.S. BİLETİ aldı.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Çok fazla eşyan var!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "O tatil gemisi S.S. ANNE\n"
    .string "VERMILION ŞEHRİ'nde.\p"
    .string "Gemide birçok EĞİTMEN olduğunu\n"
    .string "duydum.\p"
    .string "Partilerine davet edildim, ama\n"
    .string "ben şık partileri sevmiyorum.\p"
    .string "Neden sen gitmiyorsun?\n"
    .string "Git ve eğlen.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Bazı nadir POKéMON'larımı\n"
    .string "görmek ister misin?\p"
    .string "Hadi, PC'ye bak.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "IŞINLAYICI PC monitöründe\n"
    .string "görüntüleniyor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER}, IŞINLAYICI'nın\n"
    .string "Hücre Ayrıştırıcısını başlattı.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILL'in favori POKéMON listesi!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Hangi POKéMON'u görmek istersin?$"
