Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "POKéMON'umun külleri, POKéMON\n"
    .string "KULESİ'nde saklanıyor.\p"
    .string "Bu TM'i alabilirsin.\n"
    .string "Artık buna ihtiyacım yok…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "POKéMON'umun külleri, POKéMON\n"
    .string "KULESİ'nde saklanıyor.\p"
    .string "Bu TM'i alabilirsin.\n"
    .string "Artık buna ihtiyacım yok…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} küçük kızdan TM27\n"
    .string "aldı.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .if ENG_MOVES == 1
    .string "TM27 RETURN isimli bir hamle.\p"
    .else
    .string "TM27 KARŞILIK isimli bir hamle.\p"
    .endif
    .string "Eğer POKéMON'unu iyi\n"
    .string "beslersen, sevgisini savaşlarda\l"
    .string "en iyi performansı ile\l"
    .string "gösterecektir.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "Bunun için yerin yok.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "Teleskopun gösterdiğine bakalım\n"
    .string "…\p"
    .string "Bir adam balık tutuyor!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "Teleskopun gösterdiğine bakalım\n"
    .string "…\p"
    .string "POKéMON KULESİ!$"
