CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "CINNABAR SALONU'na geldim,\n"
    .string "ama kapı sıkıca kapalı.\p"
    .string "Bir yerlerde\n"
    .string "bir anahtarı olmalı.\p"
    .string "Acaba o yanmış\n"
    .string "müstakil evde mi?\p"
    .string "SALON LİDERİ'nin arkadaşı\n"
    .string "orada yaşıyormuş diyorlar.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "Çok arkadaşın var mı?\p"
    .string "Tabii ki, normal arkadaşlarla\n"
    .string "bağlantı kurmak eğlenceli.\p"
    .string "Ama ara sıra UNION ROOM'a\n"
    .string "uğramayı düşünür müsün?\p"
    .string "Bilemezsin, belki de yeni\n"
    .string "arkadaşlar edinebilirsin.\p"
    .string "UNION ROOM'a bakmak\n"
    .string "zamanına değer.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "POKéMON'ların evrimi\n"
    .string "iptal edildikten sonra da\l"
    .string "hamle öğrenebilir.\p"
    .string "Yeni hareketler öğrenilene kadar\n"
    .string "evrim bekleyebilir.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "BILL: Hey, beni beklettin!\n"
    .string "ONE ISLAND'a yelken açmaya\l"
    .string "hazır mısın?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "Oh, daha bitirmedin mi?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "Eh, bu kadar.\n"
    .string "Hadi gidelim!$"
