RocketHideout_B2F_Text_GruntIntro::
    .string "PATRON dedi ki, SILPH GÖZLÜK ile\n"
    .string "hayaletleri görebiliyormuşsunuz.$"

RocketHideout_B2F_Text_GruntDefeat::
    .string "Teslim oluyorum!$"

RocketHideout_B2F_Text_GruntPostBattle::
    .string "ROKET TAKIMI karargahı yerin dört\n"
    .string "kat altındadır.\p"
    .string "PATRON'a kolayca ulaşabileceğinizi\n"
    .string "mi sanıyorsunuz?$"

