PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "Burada ne işin var?\l"
    .string "POKéMON'un mu öldü?\p"
    .string "Hey! Hala hayatta!\p"
    .string "En azından bayıltabilirim!\n"
    .string "Haydi başlayalım!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "Ne?\n"
    .string "Pis herif!\p"
    .string "Sana karşı yumuşak davrandım,\n"
    .string "biliyor musun?$"

PokemonTower_2F_Text_RivalVictory::
    .string "Ah, vah!\n"
    .string "Gerçekten öldüler!\l"
    .string "Çok zayıflardı!\l"
    .string "Lütfen daha iyi bak, onlar buna değer.$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "POKéDEX ilerlemen nasıl gidiyor?\n"
    .string "Ben bir CUBONE yakaladım!\p"
    .string "Daha büyük bir MAROWAK bulamıyorum.\n"
    .string "Nerede olabilirler?\p"
    .string "Sanırım hiçbiri kalmadı!\p"
    .string "Neyse, ben gitmeliyim.\n"
    .string "Yapacak çok şeyim var,\l"
    .string "senin gibi değilim.\p"
    .string "Sonra görüşürüz!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Biz bile kayıp ruhları\n"
    .string "tanımlayamadık.\p"
    .string "Bir SILPH GÖZLÜK onların\n"
    .string "gerçek yüzünü ortaya çıkarabilir.$"
