SSAnne_1F_Corridor_Text_LeStrongSilentType::
    .string "Merhaba!\n"
    .string "Bu geminin garsonuyum!\p"
    .string "Size hizmet etmekten\n"
    .string "memnuniyet duyarım!\p"
    .string "… … …\n"
    .string "Ah! Sessiz ve güçlü tip!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
    .string "Yolcular bu uzun yolculuktan\n"
    .string "dolayı huzursuz.\p"
    .string "Sıkılan yolcular sana\n"
    .string "meydan okuyabilirler!$"

