Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
.string "Nöbetteyim.\n"
.string "Ama çok susadım!\p"
.string "Dur, yol kapalı.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
.string "Oh, o ÇAY…\n"
.string "Çok lezzetli görünüyor…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
.string "Huh? Bu içeceği içebilir miyim?\n"
.string "Teşekkürler!\l"
.string "… …\l"
.string "Yudum, yudum…\l"
.string "… …\l"
.string "Yutkun…\l"
.string "Eğer SAFFRON şehrine\l"
.string "gitmek istiyorsan\l"
.string "geçebilirsin.\p"
.string "Bu ÇAY'ı diğer nöbetçilerle\n"
.string "paylaşacağım!\l"
.string "Teşekkürler.$"

Route5_SouthEntrance_Text_HiHowsItGoing::
.string "Merhaba, nasıl gidiyor?$"
