CeruleanCity_Gym_Text_MistyIntro::
    .string "Merhaba, burada yenisin!\p"
    .string "Sadece POKéMON hakkında bir\l"
    .string "politikası olan EĞİTMENLER\n"
    .string "profesyonel olabilir.\p"
    .string "POKéMON'u yakalayıp eğitirken\n"
    .string "yaklaşımın nedir?\p"
    .string "Benim politikam, SU tipi\n"
    .string "POKéMON'larla tüm gücüyle\l"
    .string "saldırmaktır!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 SU VURUŞU öğretir.\p"
    .string "Onu su POKéMON'u üstünde kullan!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "CASCADEBADGE, tüm POKéMON'ların\n"
    .string "SV. 30'a kadar itaat etmesini\n"
    .string "sağlar.\p"
    .string "Buna takas yoluyla elde ettiğin\n"
    .string "yabancı POKéMON'lar da dahil.\p"
    .string "Daha da fazlası var. Artık KES\n"
    .string "hamlesini herhangi bir zamanda\l"
    .string "hatta savaş dışı kullanabilirsin.\p"
    .string "Küçük ağaçları keserek yeni\n"
    .string "yollar açabilirsin.\p"
    .string "Ayrıca favori TM'imi de alabilirsin.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER}, MISTY'den TM03\n"
    .string "aldı.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "Bunun için yer açmalısın!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Vay canına!\n"
    .string "Çok iyisin!\p"
    .string "Tamam!\p"
    .string "Çok iyi performans gösterdin, o\n"
    .string "yüzden CASCADEBADGE'i sana\n"
    .string "veriyorum.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "Ne? Sen mi?\n"
    .string "Sana karşı yeterince iyiyim!\p"
    .string "MISTY'yi rahatsız etmeye gerek\n"
    .string "yok.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "Beni yendin!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Diğer EĞİTMENLERE karşı\n"
    .string "savaşarak gerçekten ne kadar\l"
    .string "iyi olduğunu görmelisin.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Çabuk!\p"
    .string "İlk ben varım!\n"
    .string "Hadi başlayalım!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "Bu olmamalıydı!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY, kendini sürekli olarak\n"
    .string "geliştiren bir EĞİTMEN.\p"
    .string "Sana yenilmeyecek!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon adayı!\p"
    .string "Bir tavsiyede bulunayım!\p"
    .string "LİDER MISTY, SU tipi\n"
    .string "POKéMON'ları kullanan bir\l"
    .string "profesyoneldir.\p"
    .string "Tüm suyunu ÇİMEN tipi\n"
    .string "POKéMON'larla emebilirsin.\p"
    .string "Ya da ELEKTRİK tipi POKéMON\n"
    .string "kullanıp onları çarpabilirsin!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "MISTY'yi yendin!\n"
    .string "Bak, sana ne demiştim?\p"
    .string "Sen ve ben, çocuk, oldukça iyi\n"
    .string "bir takım oluruz!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON SALONU\n"
    .string "LİDER: MISTY\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON SALONU\n"
    .string "LİDER: MISTY\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}, {PLAYER}$"
