FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Eee…\n"
    .string "Evet, ben HAMLE SİLİCİ.\p"
    .string "POKéMON'ların hamlelerini\n"
    .string "unutmasını sağlayabilirim.\p"
    .string "Bunu yapmak ister misin?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Hangi POKéMON hamlesini\n"
    .string "unutmalı?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Hangi hamle unutulmalı?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} sadece bir hamle\n"
    .string "biliyor gibi görünüyor…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'in {STR_VAR_2}\n"
    .string "hamlesi unutulsun mu?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "Mükemmel!\p"
    .string "{STR_VAR_1}, {STR_VAR_2}'i\n"
    .string "tamamen unuttu.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Başka bir hamle unutmak\n"
    .string "istersen tekrar gel.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "Ne?\n"
    .string "Hiçbir YUMURTANIN hamle bilmesi\n"
    .string "gerekmiyor.$"
