Text_DreamEaterTeach::
    .string "Ah, uykulu hissediyorum!\n"
    .string "Güneşte sızmış gibi hissediyorum.\p"
    .string "DROWZEE'nin rüyamı yediği\n"
    .string "garip bir rüya gördüm.\p"
    .string "Ve…\n"
    .string "Rüya yemeyi öğrendim… Brr,\l"
    .string "çok ürkütücü!\p"
    .string "Lütfen bir POKéMON'una öğreteyim ki\n"
    .string "bunu unutabileyim!$"

Text_DreamEaterDeclined::
    .string "ZZZ. Horr…$"

Text_DreamEaterWhichMon::
    .string "Hangi POKéMON RÜYA YİYEN\n"
    .string "öğrenmek ister?$"

Text_DreamEaterTaught::
    .string "ZZZ…\n"
    .string "Artık… daha fazla…yiyemem…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "CLEFAIRY'nin aydan geldiği söyleniyor.\n"
    .string "Bu, dolaşan bir rivayet.\p"
    .string "AY DAĞI'dan AY TAŞLARI düştükten\n"
    .string "sonra göründüler.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "Burada pek çok ciddi\n"
    .string "POKéMON EĞİTMENLERİ yok.\p"
    .string "Hepsi BÖCEK AVCILARI vesaire\p"
    .string "Biliyorsun, sadece hobiciler.\p"
    .string "Ama PEWTER SALONU'nun BROCK'u hiç\n"
    .string "değilse onlardan farklı.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "MÜZE'ye baktınız mı?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "AY DAĞI'dan çıkan o fosiller\n"
    .string "harika değil miydi?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Gerçekten mi?\n"
    .string "Kesinlikle gitmelisin!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "İşte bu, MÜZE.\p"
    .string "İçeri girmek için ücret ödemen\n"
    .string "gerekiyor, ama buna değer.\l"
    .string "Görüşürüz!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Ne yaptığımı biliyor musun?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "Doğru!\n"
    .string "Bu çok zorlu bir iş!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "Bahçeme vahşi POKéMON\n"
    .string "girmesin diye SPREY sıkıyorum!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "Sen bir EĞİTMEN'sin, değil mi?\p"
    .string "BROCK yeni rakipler arıyor\n"
    .string "Beni takip et!$"

PewterCity_Text_GoTakeOnBrock::
    .string "Eğer kendine güveniyorsan,\n"
    .string "BROCK'a meydan oku!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "EĞİTMEN İPUCU\n"
    .string "Tüm POKéMON'lar, ne kadar kısa süre\l"
    .string "savaşırlarsa savaşsın hepsi\l"
    .string "EXP. Puanı kazanırlar.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "DİKKAT!\p"
    .string "Hırsızlar AY DAĞI'dan POKéMON\n"
    .string "fosilleri çalıyorlar. Eğer bilginiz\l"
    .string "varsa lütfen PEWTER POLİSİ'ni arayın.$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER BİLİM MÜZESİ$"

PewterCity_Text_GymSign::
    .string "PEWTER ŞEHRİ POKéMON GYM\n"
    .string "LİDER: BROCK\l"
    .string "Kaya gibi sağlam bir EĞİTMEN!$"

PewterCity_Text_CitySign::
    .string "PEWTER ŞEHRİ\n"
    .string "Bir Taş Gri Şehri$"

@ Aşağıdaki 3 JP metni kullanılmıyor. Muhtemelen oyuncuya Berry Pouch vermesi için kesilen bir NPC
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "Hey! O\n"
    .string "Spor Salon rozeti…\l"
    .string "Vay canına, Taş'ı yendin mi? \p"
    .string "Çok etkilendim\n"
    .string "Hazineyi sana vereceğim!$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "İçinde meyveler var\p"
    .string "Yararlı meyveler de\n"
    .string "içinde, bu yüzden\l"
    .string "Onları dikkatli kullanın, lütfen!$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "Bir POKéMON'a meyve verin\p"
    .string "Savaşırken\n"
    .string "onları kullanacaklar\l"
    .string "kendi kendine.\p"
    .string "Yaraları iyileştirmekten veya\n"
    .string "zehirlenmeyi ortadan kaldırmaktan\l"
    .string "daha kolay ve kullanışlı, değil mi?$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "Seni yakaladığıma memnun oldum.\n"
    .string "PROF. OAK'ın YARDIMCISIYIM.\p"
    .string "Bunu teslim etmem istendi,\n"
    .string "bunu sana veriyorum.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} YARDIMCI'dan.\n"
    .string "KOŞU AYAKKABISI aldı.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER}, KOŞU AYAKKABI'larını.\n"
    .string "giydi.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Koşmak için B düğmesine basın.\n"
    .string "Ama sadece koşabileceğin yerlerde!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Eh, ben laboratuvara geri dönmeliyim.\n"
    .string "Hoşça kal!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "Bir mektup ekli…\p"
    .string "Sevgili {PLAYER},\p"
    .string "Benim küçük şampiyon adayım\n"
    .string "için bir çift KOŞU AYAKKABISI\p"
    .string "Unutma, her zaman sana destek olacağım!\n"
    .string "Asla pes etme!\p"
    .string "İmza: Annen$"
