PokemonTower_3F_Text_HopeIntro::
    .string "Ugh… Ahh…\n"
    .string "Ah… Ggh…$"

PokemonTower_3F_Text_HopeDefeat::
    .string "Hey!\n"
    .string "Kurtuldum!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Hayaletler SILPH GÖZLÜK\n"
    .string "ile tespit edilebilir.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke…\n"
    .string "Ahh!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "Ne?\n"
    .string "Ne yapıyorum ben?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "Özür dilerim!\n"
    .string "Beni ele geçirmişlerdi!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Defol!\n"
    .string "Kötü ruh!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "Oh!\n"
    .string "Ruh gitti!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "Yukarıdakiler de…\n"
    .string "Büyünün etkisindeydi.$"
