Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough:
    .string "Merhaba! Beni hatırlıyor musun?\n"
    .string "PROF. OAK'ın asistanlarından\l"
    .string "biriyim.\p"
    .string "POKéDEX'iniz {STR_VAR_1} türde\n"
    .string "veri içeriyorsa,\l"
    .string "size bir ödül vermem gerekiyor.\p"
    .string "PROF. OAK, size vermek için\n"
    .string "bana {STR_VAR_2} bıraktı.\p"
    .string "Öyleyse, {PLAYER}, sana bir soru\n"
    .string "sormak istiyorum.\p"
    .string "En az {STR_VAR_1} çeşit POKéMON\n"
    .string "verisi topladın mı?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo:
    .string "Harika! {STR_VAR_3} çeşit POKéMON\n"
    .string "yakaladın veya sahip oldun!\p"
    .string "Tebrikler!\n"
    .string "İşte bu senin için!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide:
    .string "{PLAYER}, asistandan {STR_VAR_2}\n"
    .string "aldı.$"

Route15_WestEntrance_2F_Text_ExplainExpShare:
    .string "EXP. PAYLAŞ, bir POKéMON\n"
    .string "tarafından tutulan bir eşyadır.\p"
    .string "POKéMON, savaşmadan da\n"
    .string "EXP. Puanının bir kısmını alacak.\l"
    .string "Böylece, savaşmadan da deneyim\l"
    .string "kazanabilecek.$"

Route15_WestEntrance_2F_Text_LargeShiningBird:
    .string "Teleskoba bir bakalım…\p"
    .string "Büyük, parlayan bir kuş\n"
    .string "denize doğru uçuyor!$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon:
    .string "Teleskoba bir bakalım…\p"
    .string "Ufukta küçük bir ada\n"
    .string "var gibi görünüyor!$"
