SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "Yorgun görünüyorsun.\n"
    .string "Kısa bir şekerleme yapmalısın.$"

SilphCo_9F_Text_DontGiveUp::
    .string "Pes etme!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "Çok teşekkürler.$"

SilphCo_9F_Text_Grunt1Intro::
    .string "POKéMON'ların sana bayılıyor,\n"
    .string "çocuk!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "Aaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Eğer ben de senin yaşındayken bir\n"
    .string "EĞİTMEN olsaydım…$"

SilphCo_9F_Text_EdIntro::
    .string "POKéMON'ların zayıf noktaları var!\n"
    .string "Onları bulurum!$"

SilphCo_9F_Text_EdDefeat::
    .string "Beni yendin!$"

SilphCo_9F_Text_EdPostBattle::
    .string "Zayıf noktaları hedeflemek\nişe yarar.\p"
    .string "Tür avantajlarını düşün.$"

SilphCo_9F_Text_Grunt2Intro::
    .string "Ben ROKET TAKIMI'nın dört\n"
    .string "KARDEŞ'inden biriyim!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "Varg!\n"
    .string "Kardeşler, yenildim!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "Kardeşlerim intikamımı alacak!$"

SilphCo_9F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİSİ\n"
    .string "9. Kat$"

