Route25_Text_JoeyIntro::
    .string "Yerel EĞİTMEN'ler buraya\n"
    .string "pratik yapmak için gelirler.$"

Route25_Text_JoeyDefeat::
    .string "İyiydin.$"

Route25_Text_JoeyPostBattle::
    .string "Tüm POKéMON'ların zayıf\n"
    .string "yanları vardır. Hatta en\p"
    .string "güçlülerin bile. Bu yüzden\n"
    .string "farklı türlerdeki POKéMON'ları\p"
    .string "eğitmek en iyisidir.$"

Route25_Text_DanIntro::
    .string "Babam beni S.S. ANNE'deki\n"
    .string "harika bir partiye götürdü.\p"
    .string "VERMILION ŞEHRİ'ndeydi.$"

Route25_Text_DanDefeat::
    .string "Kızgın değilim!$"

Route25_Text_DanPostBattle::
    .string "S.S. ANNE'deyken, tüm dünyadan\n"
    .string "EĞİTMEN'ler gördüm.$"

Route25_Text_FlintIntro::
    .string "Ben çok havalıyım.\n"
    .string "Bir kız arkadaşım var!$"

Route25_Text_FlintDefeat::
    .string "Ayy, yazık…$"

Route25_Text_FlintPostBattle::
    .string "Oh, olsun.\n"
    .string "Kız arkadaşım beni teselli\p"
    .string "edecek.$"

Route25_Text_KelseyIntro::
    .string "Merhaba!\n"
    .string "Erkek arkadaşım çok havalı!$"

Route25_Text_KelseyDefeat::
    .string "Kondisyonum iyi değil…$"

Route25_Text_KelseyPostBattle::
    .string "Keşke erkek arkadaşım senin\n"
    .string "kadar iyi olsa.$"

Route25_Text_ChadIntro::
    .string "Bu hisse kapılmıştım…\p"
    .string "Seni yenmem gerektiğini\n"
    .string "biliyordum!$"

Route25_Text_ChadDefeat::
    .string "Kaybetmeyi biliyordum!$"

Route25_Text_ChadPostBattle::
    .string "Eğer POKéMON'un şaşırırsa,\n"
    .string "onu değiştir. Bu iyi bir\l"
    .string "taktik.$"

Route25_Text_HaleyIntro::
    .string "Arkadaşımın çok tatlı POKéMON'ları\n"
    .string "var. Çok kıskanıyorum!$"

Route25_Text_HaleyDefeat::
    .string "Artık o kadar kıskanç değilim!$"

Route25_Text_HaleyPostBattle::
    .string "Sen AY DAĞI'ndan mı geldin?\n"
    .string "Bir CLEFAIRY verebilir misin?$"

Route25_Text_FranklinIntro::
    .string "AY DAĞI'ndan yeni indim,\n"
    .string "ama hala enerjim var!$"

Route25_Text_FranklinDefeat::
    .string "Çok çalıştın!$"

Route25_Text_FranklinPostBattle::
    .string "Zevzek!\n"
    .string "Bir ZUBAT o mağarada beni ısırdı.$"

Route25_Text_NobIntro::
    .string "Bir POKéMANYAK'ın koleksiyonunu\n"
    .string "görmeye gidiyorum.$"

Route25_Text_NobDefeat::
    .string "Beni yendin, hem de çok güzel!\n"
    .string "Helal olsun sana!$"

Route25_Text_NobPostBattle::
    .string "POKéMANYAK gerçekten adına\n"
    .string "yaraşır biriymiş. Koleksiyonu\p"
    .string "pek çok nadir POKéMON türünü\n"
    .string "içeriyor.$"

Route25_Text_WayneIntro::
    .string "BILL'i görmeye gidiyor musun?\n"
    .string "Önce seninle savaşacağım!$"

Route25_Text_WayneDefeat::
    .string "Sen harikasın!$"

Route25_Text_WaynePostBattle::
    .string "Aşağıdaki patika CERULEAN\n"
    .string "ŞEHRİ'ne giden bir kısa yol.$"

Route25_Text_SeaCottageSign::
    .string "DENİZ KÖŞKÜ\n"
    .string "BILL burada yaşıyor!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "Bu tepe, ünlü bir buluşma\n"
    .string "noktasıdır.\p"
    .string "SALON LİDERİ MISTY, bu yer için\n"
    .string "büyük umutlar besliyor.$"

Route25_Text_AreYouHereAlone::
    .string "Merhaba, yalnız mı geldin?\p"
    .string "Eğer CERULEAN tepesindeysen…\n"
    .string "Partnerinle gelmelisin.$"
