ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "KANTO MOTORCULARIYIZ!\n"
    .string "VIN! VIIIINN! VINNN!\p"
    .string "Motorum güçsüz, bu yüzden\n"
    .string "egzoz sesini ben çıkarıyorum!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hey, sen!\n"
    .string "Biraz para ver bana!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Ayy!\p"
    .string "Sen kimsin?!\n"
    .string "Polisi arayacağım!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "O MOTOSİKLETLİLER…\n"
    .string "Gittiler mi?\p"
    .string "Oh, şükürler olsun!\n"
    .string "Gerçekten beni korkuttular!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "O MOTOSİKLETLİLER kaçtı ve\n"
    .string "LOSTELLE şuan güvende.\p"
    .string "Her şey yoluna girdi!$"
