ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "KANTO MOTOSİKLETLİLERİYİZ!\n"
    .string "Vrooom! Vavaaavroom! Vrooom!\p"
    .string "Motorum güçsüz, o yüzden\n"
    .string "egzoz sesini ben çıkarmalıyım!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "Hey, hanımefendi!\n"
    .string "Harcamak için biraz para ver bana!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "Ayy!\p"
    .string "Sen kimsin?!\n"
    .string "Polisi arayacağım!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "O MOTOSİKLETLİLER…\n"
    .string "Gittiler mi?\p"
    .string "Oh, şükürler olsun!\n"
    .string "Gerçekten beni korkuttular!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "O MOTOSİKLETLİLER kaçtı ve\n"
    .string "LOSTELLE güvende bulundu.\p"
    .string "Her şey yoluna girdi!$"
