PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
.string "{RIVAL}: Sen miydin {PLAYER}?\n"
.string "Dedem burada değil.$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
.string "{RIVAL}: Dede!\n"
.string "Beklemekten sıkıldım!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
.string "{RIVAL}: Hey! Dede! Bu adil değil!\n"
.string "Ya ben?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
.string "{RIVAL}: Hah, senin gibi açgözlü\n"
.string "olmam gerekmiyor. Ben olgunum!\p"
.string "Önce sen seç, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
.string "{RIVAL}: O zaman ben de bunu\n"
.string "alıyorum!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
.string "{RIVAL} PROF. OAK'tan {STR_VAR_1}\n"
.string "aldı!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
.string "{RIVAL}: Benim POKéMON'um\n"
.string "seninkinden daha güçlü görünüyor.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
.string "{RIVAL}: Dur, {PLAYER}!\n"
.string "POKéMON'larımızı bir test edelim!\p"
.string "Haydi, seni yenmeye hazırım!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
.string "NE?\n"
.string "İnanılmaz!\l"
.string "Yanlış POKéMON'u seçmişim!$"

@ Ayrıca Route 22'deki erken savaş için de kullanılır
Text_RivalVictory::
.string "{RIVAL}: Evet!\n"
.string "Harika değil miyim?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
.string "{RIVAL}: Tamam! POKéMON'umu daha\n"
.string "da güçlendirmek için savaşacağım!\p"
.string "{PLAYER}! Dede!\n"
.string "Sonra görüşürüz!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
.string "{RIVAL}: Dede!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
.string "{RIVAL}: Neredeyse unutuyordum!\n"
.string "Beni neden çağırdın?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
.string "{RIVAL}: Tamam, Dede!\n"
.string "Her şeyi bana bırak!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
.string "{PLAYER}, söylemek zorundayım, ama bu\n"
.string "görevde bize lazım değilsin.\p"
.string "Aklıma bir fikir geldi! Kardeşimden\n"
.string "bir HARİTA ödünç alacağım.\p"
.string "Bir de sana da ödünç vermemesi\n"
.string "için uyaracağım, {PLAYER}!\l"
.string "Hahaha!\p"
.string "Şimdi bizim eve gelmekle sakın\n"
.string "uğraşma!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
.string "OAK: {RIVAL}?\n"
.string "Bir düşünelim…\p"
.string "Ah, doğru.\nSana gelmeni ben söyledim!\p"
.string "Şimdi, {PLAYER}.\p"
.string "Burada üç POKéMON var.\p"
.string "Haha!\p"
.string "POKéMON'lar bu POKé TOPLARININ\n"
.string "içinde duruyor.\p"
.string "Gençken, ciddi bir POKéMON\n"
.string "EĞİTMENİ idim.\p"
.string "Ama şimdi, yaşlandım ve\n"
.string "sadece bu üçü kaldı.\p"
.string "Birini alabilirsin.\n"
.string "Hadi seç!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
.string "OAK: Sabırlı ol, {RIVAL}.\n"
.string "Sen de bir tane alacaksın!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
.string "OAK: Şimdi, {PLAYER}.\p"
.string "Bu üç POKé TOPUNUN içinde\n"
.string "POKéMON'lar var.\p"
.string "Kendin için hangisini seçeceksin?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
.string "OAK: Hey!\n"
.string "POKéMON'unu seçmeden gitme!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
.string "Ah! CHARMANDER'ı seçiyorsun.\n"
.string "Onu sabırla eğitmelisin.\p"
.string "Öyleyse, {PLAYER}, ATEŞ POKéMON'u\n"
.string "CHARMANDER'ı mı seçiyorsun?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
.string "Hm! SQUIRTLE'ı seçiyorsun.\n"
.string "Onu eğitmeye değer.\p"
.string "Öyleyse, {PLAYER}, SU POKéMON'u\n"
.string "SQUIRTLE'ı mı seçiyorsun?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
.string "Anladım! BULBASAUR'ı seçiyorsun.\n"
.string "Onu eğitmesi kolaydır.\p"
.string "Öyleyse, {PLAYER}, ÇİMEN POKéMON'u\n"
.string "BULBASAUR'ı mı seçiyorsun?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
.string "Bu POKéMON çok enerjiktir!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
.string "{PLAYER} PROF. OAK'tan {STR_VAR_1}\n"
.string "aldı!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
.string "OAK: Bir YABANİ POKéMON çıkarsa,\n"
.string "POKéMON'unla savaşabilir.\p"
.string "Onunla birlikte, bir sonraki şehre\n"
.string "ulaşabilmelisin.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
.string "OAK: {PLAYER}, genç POKéMON'unu\n"
.string "savaşarak eğit.\p"
.string "Gelişmesi için savaşmalı.$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
.string "OAK: Oh, {PLAYER}!\n"
.string "Eski POKéMON'um nasıl?\p"
.string "Sanırım sana daha çok bağlandı.\p"
.string "Sen bir POKéMON EĞİTMENİ olarak\n"
.string "yetenekli olmalısın.\p"
.string "Ne o?\n"
.string "Bana bir şey mi getirdin?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
.string "{PLAYER} OAK'IN PAKETİNİ teslim etti.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
.string "Ah! \n"
.string "Bu özel sipariş ettiğim POKé TOPU!\p"
.string "Teşekkürler!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
.string "OAK: Oh, doğru!\n"
.string "Siz ikiniz için bir ricam var.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
.string "Masanın üstünde gördüğün makine,\n"
.string "bir POKéDEX. Bu makine, gördüğün\l"
.string "POKéMON'lar hakkında otomatik\l"
.string "olarak veri kaydeder.\p"
.string "Yüksek teknoloji bir ansiklopedidir!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: {PLAYER} ve {RIVAL}.\n"
    .string "Bunları yanınıza alın.$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER}, PROF. OAK'tan POKéDEX aldı.$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: Sadece onları görerek\n"
    .string "POKéMON'lar hakkında ayrıntılı\l"
    .string "veri elde edemezsin.\p"
    .string "Tam veriyi elde etmek için onları\n"
    .string "yakalamalısın.\p"
    .string "İşte sana vahşi POKéMON'ları\n"
    .string "yakalamak için birkaç araç.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} beş POKé TOPU aldı.$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Bir vahşi POKéMON göründüğünde,\n"
    .string "savaş başlar.\p"
    .string "Bir POKé TOPU at ve onu\n"
    .string "yakalamayı dene!\p"
    .string "Ancak bu her zaman işe yaramaz.\p"
    .string "Sağlıklı bir POKéMON kaçabilir.\n"
    .string "Şanslı olmalısın!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Dünyadaki tüm POKéMON'ların\n"
    .string "tam bir rehberini yapmak…\p"
    .string "Bu benim hayalimdi!\p"
    .string "Ama çok yaşlandım.\n"
    .string "Artık hiçbir işi bitiremiyorum.\p"
    .string "Bu yüzden, birinin bu hayalimi\n"
    .string "benim yerime gerçekleştirmesini\l"
    .string "istiyorum.\p"
    .string "Hadi, harekete geçin.\p"
    .string "Bu POKéMON tarihinde büyük bir\n"
    .string "girişim olacak!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "Dünyadaki POKéMON'lar seni bekliyor,\n"
    .string "{PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "Ah, {PLAYER}!\n"
    .string "POKéDEX'in nasıl gidiyor?\p"
    .string "{RIVAL} bazı POKéMON'ları\n"
    .string "zaten yakaladı ve veri ekledi.\p"
    .string "Peki, {PLAYER}, senin POKéDEX'ine\n"
    .string "bir bakalım.\p"
    .string "…Ne oldu?\n"
    .string "Hiç yeni veri eklememişsin.\p"
    .string "Sana bunları veriyorum, biraz daha\n"
    .string "çaba göster.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Beni bir ara görmeye gel.\p"
    .string "Sonuçta, POKéDEX'inin nasıl\n"
    .string "ilerlediğini bilmek istiyorum.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "Ansiklopedi gibi, ama sayfalar boş.$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "Bunlar POKé TOPLARI.\n"
    .string "İçlerinde POKéMON var!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "Bu, PROF. OAK'ın son POKéMON'u.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "MENÜ'yü açmak için START'a basın!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "KAYDET seçeneği MENÜ'dedir.\n"
    .string "Düzenli olarak kullanın.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Tüm POKéMON türlerinin diğerlerine\n"
    .string "karşı güçlü ve zayıf noktaları vardır.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "Burada bir e-posta mesajı var.\p"
    .string "…\p"
    .string "Sonunda!\n"
    .string "POKéMON LİGİ'nin en iyi\l"
    .string "EĞİTMENLERİ tüm gelenleri\l"
    .string "kabul etmeye hazır!\p"
    .string "En iyi POKéMON'larını getir ve\n"
    .string "bir EĞİTMEN olarak ne derece\l"
    .string "güçlü olduğunu gör!\p"
    .string "POKéMON LİGİ HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, lütfen bizi ziyaret\n"
    .string "edin! …$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Ben PROF. OAK'ın YARDIMCISI olarak\n"
    .string "POKéMON araştırmaları yapıyorum.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Merhaba, {PLAYER}. POKéMON'larınla\n"
    .string "iyi arkadaş olduğuna eminim.\p"
    .string "Bu arada, DAISY'i tanıyor\n"
    .string "muydun?\p"
    .string "Eğer DAISY'ye POKéMON'unu\n"
    .string "gösterirsen, onun ne kadar\n"
    .string "seni sevdiğini söyleyebilir.\p"
    .string "Bazen, senin için bir POKéMON'u\n"
    .string "bakım yapar.\p"
    .string "Bu bir sır, lütfen kimseye söyleme.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "PROF. OAK yakında kendi radyo\n"
    .string "programına sahip olacak.\p"
    .string "Programın adı PROF. OAK'ın\n"
    .string "POKéMON SEMİNERİ olacak.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "PROF. OAK pek öyle gibi\n"
    .string "görünmeyebilir, ama o POKéMON\l"
    .string "konusunda otoritedir.\p"
    .string "Birçok POKéMON EĞİTMENİ ona\n"
    .string "büyük saygı duyar.$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "Ah, şimdi bu mükemmel!\p"
    .string "{PLAYER}, senden başka bir önemli\n"
    .string "iyilik isteğim var.\p"
    .string "Dikkatlice dinlemen gerekiyor.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Son zamanlarda, birçok nadir POKéMON\n"
    .string "türü gözlemlendi.\p"
    .string "KANTO'da hiç görülmemiş POKéMON'lar\n"
    .string "hakkında konuşuyorum.\p"
    .string "Kendim gidip görmek isterdim, ama\n"
    .string "çok yaşlıyım.\p"
    .string "Ben yapamadığım için, {PLAYER},\n"
    .string "benim yerime gitmeni istiyorum.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: Hey, bunu duydum!\p"
    .string "Dede, neden her zaman {PLAYER}'ı\n"
    .string "benden daha fazla tercih ediyorsun?\p"
    .string "Daha fazla POKéMON topladım,\n"
    .string "hem de daha hızlı.\p"
    .string "Her şeyi bana bırakmalısın.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: Biliyorum, biliyorum.\n"
    .string "Tabi ki yardımınıza\l"
    .string "ihtiyacım var.\p"
    .string "Şimdi, her iki POKéDEX'e de\l"
    .string "bakmalıyım.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK her iki POKéDEX'i\n"
    .string "aldı.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…ve işlem tamam!\p"
    .string "Artık bu cihazlar daha fazla\n"
    .string "POKéMON kaydedebilir.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "{PLAYER}'ın POKéDEX'i güncellendi!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Şimdi, {PLAYER} ve {RIVAL}!\p"
    .string "Artık, gerçekten POKéDEX'inizi\n"
    .string "doldurmak için çok çalışmalısınız.\p"
    .string "Onları gelmiş geçmiş en iyi ve\n"
    .string "en eksiksiz hale getirmenizi istiyorum!\p"
    .string "Gerçekten, bu POKéMON tarihindeki\n"
    .string "çok büyük bir girişim!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Dede, sakin ol.\n"
    .string "Bu kadar heyecanlanma.\p"
    .string "POKéDEX'i tamamlayacağım,\n"
    .string "sen merak etme.\p"
    .string "Sanırım önce BİRİNCİ ADA'ya\n"
    .string "bakınacağım…\p"
    .string "Her neyse, ben kaçtım!$"


