FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "Bu adada güçlü bir\n"
    .string "EĞİTMEN büyüdü. \p"
    .string "Siz bile onu tanırsınız.\n"
    .string "ELİT DÖRTLÜ'nün LORELEI'si!\p"
    .string "LORELEI daha küçükken,\n"
    .string "Ben ona POKéMON'ları öğrettim.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "SEVII ADALARI genelde\n"
    .string "sıcak bir bölgededir.\p"
    .string "Fakat bir istisna var, dikkat!\p"
    .string "ICEFALL MAĞARASI, içindeki\n"
    .string "POKéMON'lar yüzünden çok soğuk.$"
