Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER} çantan\n"
    .string "dolu gibi görünüyor$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "POKéMON'lar için iyi isimler\n"
    .string "bulmak zor değil mi?\p"
    .string "Özellikle bir sürü yakaladıysan.\p"
    .string "LAVENDER KASABASI'nda, POKéMON\n"
    .string "takma adları değerlendiren\l"
    .string "bir adam var.\p"
    .string "Ayrıca POKéMON'unu yeniden\nadlandırmana\l"
    .string "yardımcı olabilir.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "LAVENDER KASABASI'na ulaşmayı\n"
    .string "hedefliyorsan,\l"
    .string "KAYA TÜNELİ'nden geç. Oradan\l"
    .string "CERULEAN ŞEHRİ'ne ulaşabilirsin.$"
