Route9_Text_AliciaIntro::
    .string "Yanında POKéMON var!\n"
    .string "Sen benim olacaksın!$"

Route9_Text_AliciaDefeat::
    .string "Beni aldattın…$"

Route9_Text_AliciaPostBattle::
    .string "Önümüzdeki tünel zifiri\n"
    .string "karanlık.\p"
    .string "İçeri girmek için FLAŞ\n"
    .string "gerekiyor.$"

Route9_Text_ChrisIntro::
    .string "Oraya yürüyen kim?\n"
    .string "İyi görünen POKéMON'ları var!$"

Route9_Text_ChrisDefeat::
    .string "Işıklar kapandı!$"

Route9_Text_ChrisPostBattle::
    .string "Yürümeye devam et!$"

Route9_Text_DrewIntro::
    .string "KAYA TÜNELİ'ne gidiyorum\n"
    .string "LAVENDER'a geçmek için…$"

Route9_Text_DrewDefeat::
    .string "Yeterli değilmişim…$"

Route9_Text_DrewPostBattle::
    .string "Sen de KAYA TÜNELİ'ne mi gidiyorsun?$"

Route9_Text_CaitlinIntro::
    .string "Bana akıl öğretme!$"

Route9_Text_CaitlinDefeat::
    .string "Hayır!\n"
    .string "Çok güçlüsün.$"

Route9_Text_CaitlinPostBattle::
    .string "Çok yeteneklisin.\n"
    .string "Bol şanslar!$"

Route9_Text_JeremyIntro::
    .string "Hahahaha!\n"
    .string "Harika! Canım sıkılıyordu, eh!$"

Route9_Text_JeremyDefeat::
    .string "Devam et, eh!\n"
    .string "Dur, POKéMON'larım bitti!$"

Route9_Text_JeremyPostBattle::
    .string "Bana karşı durdun, eh?\n"
    .string "Cesaretlisin!$"

Route9_Text_BriceIntro::
    .string "Hahaha!\n"
    .string "Sen bir sert çocuksun!$"

Route9_Text_BriceDefeat::
    .string "Ne o?$"

Route9_Text_BricePostBattle::
    .string "Hahaha!\n"
    .string "Çocuklar güçlü olmalı!$"

Route9_Text_BrentIntro::
    .string "Her gün erken kalkıp POKéMON'ları\n"
    .string "geliştirmek için uğraştım!$"

Route9_Text_BrentDefeat::
    .string "NE?\n"
    .string "Zaman kaybı!$"

Route9_Text_BrentPostBattle::
    .string "Güçlenmek için sadece böcek\n"
    .string "toplamak yetmez…$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Haydi gel!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "Adil bir şekilde yendin!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Biz neşeli adamlarız, hep güleriz!$"

Route9_Text_ConnerIntro::
    .string "Hadi, süper BÖCEK POKéMON'um!$"

Route9_Text_ConnerDefeat::
    .string "Böceklerim…$"

Route9_Text_ConnerPostBattle::
    .string "Eğer BÖCEK POKéMON'ları\n"
    .string "sevmiyorsan, beni\l"
    .string "sinirlendiriyorsun!$"

Route9_Text_RouteSign::
    .string "ROTA 9\n"
    .string "CERULEAN ŞEHRİ - KAYA TÜNELİ$"
