Route24_Text_JustEarnedFabulousPrize::
    .string "Tebrikler! Beş eğitmeni yendin!\n"
    .string "Muhteşem bir ödül kazandın!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER} gizemli EĞİTMEN'den\n"
    .string "bir KÜLÇE kazandı!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "Yer kalmamış!$"

Route24_Text_JoinTeamRocket::
    .string "Ayrıca, ROKET TAKIMI'na katılmak\n"
    .string "ister misin?\p"
    .string "Biz profesyonel POKéMON\n"
    .string "suçlularından oluşan bir grubuz!\p"
    .string "Katılmak ister misin?\p"
    .string "Emin misin?\p"
    .string "Gel, bize katıl!\p"
    .string "Katılmanı söylüyorum!\p"
    .string "…Tamam, ikna etmem gerek!\p"
    .string "Reddedemeyeceğin bir\n"
    .string "teklif sunacağım!$"

Route24_Text_RocketDefeat::
    .string "Ayy!\n"
    .string "İyiymişsin!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "Yeteneklerinle, ROKET TAKIMI'nda\n"
    .string "üst düzey bir lidere dönüşürsün.\p"
    .string "Fırsatı düşün! Bu şansı kaçırma!$"

Route24_Text_ShaneIntro::
    .string "Başarılarını çimlerden izledim!$"

Route24_Text_ShaneDefeat::
    .string "Böyle olacağını biliyordum!$"

Route24_Text_ShanePostBattle::
    .string "Köprüdeki insanlar beni korkuttu.$"

Route24_Text_EthanIntro::
    .string "Tamam! Ben 5 numarayım!\n"
    .string "Seni ezeceğim!$"

Route24_Text_EthanDefeat::
    .string "Vay canına!\n"
    .string "Çok fazla!$"

Route24_Text_EthanPostBattle::
    .string "Elimden geleni yaptım,\n"
    .string "pişman değilim!$"

Route24_Text_ReliIntro::
    .string "Ben 4 numarayım!\n"
    .string "Yoruluyor musun?$"

Route24_Text_ReliDefeat::
    .string "Ben de kaybettim!$"

Route24_Text_ReliPostBattle::
    .string "Elimden geleni yaptım,\n"
    .string "pişman değilim!$"

Route24_Text_TimmyIntro::
    .string "3 numara burada!\n"
    .string "Kolay olmayacak!$"

Route24_Text_TimmyDefeat::
    .string "Auv!\n"
    .string "Beni ezip geçtin!$"

Route24_Text_TimmyPostBattle::
    .string "Elimden geleni yaptım,\n"
    .string "pişman değilim!$"

Route24_Text_AliIntro::
    .string "Ben ikincisiyim!\n"
    .string "Şimdi işler ciddileşiyor!$"

Route24_Text_AliDefeat::
    .string "Nasıl kaybettim?$"

Route24_Text_AliPostBattle::
    .string "Elimden geleni yaptım,\n"
    .string "pişman değilim!$"

Route24_Text_CaleIntro::
    .string "İnsanlar buna KÜLÇE\n"
    .string "KÖPRÜSÜ diyor!\p"
    .string "Beş EĞİTMEN'i yen ve muhteşem\n"
    .string "bir ödül kazan!\p"
    .string "Bunu yapabilecek misin?$"

Route24_Text_CaleDefeat::
    .string "Vay be!\n"
    .string "İyi iş!$"

Route24_Text_CalePostBattle::
    .string "Elimden geleni yaptım,\n"
    .string "pişman değilim!$"
