ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "Doğru mu?\p"
    .string "CELADON MAĞAZASI bu dükkandan\n"
    .string "daha büyük mü?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "Bazen burada ilaç alırım.\p"
    .string "Ama birçok kişi MEYVE ORMANI'ndan\n"
    .string "aldıkları MEYVE ile POKéMON\l"
    .string "iyileştirir. Sonuçta, MEYVE\l"
    .string "ücretsiz ve hiç tükenmez.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "O MOTOSİKLETLİLER bu POKéMON\n"
    .string "MARKET'i mahvetmek üzereydiler.\p"
    .string "Gitmeye karar verdikleri için\n"
    .string "çok memnunum.$"
