ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "Denizden gelen tuzlu koku…\n"
    .string "Kalbimi gıdıklıyor.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…Hımm, hımm…\n"
    .string "Burada kötü bir koku var…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "Acaba bu koku ter kokan\n"
    .string "POKéMON'undan mı geliyor…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "Aceleyle nereye gidiyorsun?\n"
    .string "Acele etme!$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "Harika POKéMON'lar yetiştirmişsin.\n"
    .string "Tebrikler!$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Bu yolda devam ederseniz, sonunda\n"
    .string "MEYVE ORMANI'na ulaşacaksınız.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Annemin söylediğine göre, yüzmek\n"
    .string "için simidime ihtiyacım var.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "Aaağh!\n"
    .string "Ağlıyorum!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "Bu sene yüzmeyi kesin öğreneceğim!\n"
    .string "Sabırsızlanıyorum!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "Hadi, hadi!\n"
    .string "POKéMON zamanı!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "Şimdi ne olacak?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "Acaba kazandım mı, yoksa\n"
    .string "kaybettim mi?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "Aman Tanrım, buraya gelmeyin!\n"
    .string "Lütfen benden uzak durun!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Tamam, kazandınız!\n"
    .string "Şimdi lütfen gidin!$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "Bir POKéMON mayomu ısırdı.\n"
    .string "Artık sudan çıkamam!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "JOY: Sana favori POKéMON'umuzu\n"
    .string "göstereceğiz!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "JOY: Ahh…\n"
    .string "MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "JOY: Eğlenceliydi, değil mi?\n"
    .string "Tekrar savaşmak isterim!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "JOY: MEG ile savaşmak istiyorum,\n"
    .string "ama bir POKéMON yetmez.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MEG: Favori POKéMON'umuzu\n"
    .string "sana göstereceğiz.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MEG: Ahh…\n"
    .string "JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MEG: JOY, eğlenceliydi, değil mi?\n"
    .string "Tekrar savaşalım!$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MEG: JOY ile birlikte savaşmak\n"
    .string "istiyorum, ama bir tane yetmez.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "MEYVE ORMANI İLERİDE$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BAĞ KÖPRÜSÜ\n"
    .string "Lütfen geçerken sessiz olun.\p"
    .string "MEYVE ORMANI İLERİDE$"
