FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "Bu ellerle, zaferimi yaratacağım!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "Bu utanç verici…\n"
    .string "Yüzüm kızardı…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "Eyvah, boyalarım her yere saçıldı!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Affedersiniz!\n"
    .string "Resim yapıyorum, lütfen\l"
    .string "görüş alanımdan çıkın!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "Bu yenilgi…\n"
    .string "Beyaza bürünmüş gibiyim…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GİLLİAN?\n"
    .string "Lütfen başını biraz eğ…\l"
    .string "İşte bu! Bu ifadesi istiyorum!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Hmm…\n"
    .string "Açı tam değil…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Ah…\n"
    .string "Hislerim üzgün…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "Gök ve deniz…\n"
    .string "Çok değişkenler.\p"
    .string "Değişen ifadeleri yakalamak\n"
    .string "zor.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "Arkadaşımın tatil köyüne geldim,\n"
    .string "bilmeniz gerekirse.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "Aman tanrım, çok güçlüsünüz.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "Deniz melteminde keyifle\n"
    .string "savaşmak hoşuma gidiyor.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "POKéMON'lar için özel bir yüzme\n"
    .string "havuzu yaptırmayı düşünüyorum.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "Aman tanrım!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "Havuz güzel olurdu, ama bir sauna\n"
    .string "da harika olabilir.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "Koşmayı iyi biliyorum.\n"
    .string "Çok hızlıyım!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "Eyvah!\n"
    .string "Acele ettim!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "Rüzgarla koşmak uçuyormuşum\n"
    .string "gibi hissettiriyor!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "Şunu söylemeliyim ki, bu yerin\n"
    .string "deniz yaşamı bana iyi geliyor.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "Bu şok edici!\n"
    .string "Şaka yapıyorsunuz, değil mi?$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "Bunun için bu kadar ciddi olmak…\n"
    .string "Saçmalık.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "SELPHY: Teşekkürler.\p"
    .string "Şimdi gidebilirsin.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "SELPHY'NİN EVİ$"
