CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "SPREY sadece böcekleri uzak\n"
    .string "tutmaz, zayıf POKéMON'lara da\p"
    .string "etkili. POKéMON LİSTESİ'nin\n"
    .string "soluna en güçlü POKéMON'u koy.\p"
    .string "İlk POKéMON'un güçlü ise,\n"
    .string "SPREY'in etkisi artar.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "NADİR ŞEKER'den haberin var mı?\n"
    .string "Mağazalarda satılmıyorlar.\p"
    .string "Sanırım POKéMON'ları aniden\n"
    .string "hızlıca geliştiriyor.$"
