Route11_Text_HugoIntro::
    .string "Kazan ya da kaybet!$"

Route11_Text_HugoDefeat::
    .string "Eyvah!\n"
    .string "İstediğim gibi gitmedi!$"

Route11_Text_HugoPostBattle::
    .string "POKéMON yaşam demek!\n"
    .string "Ve yaşamak oyun oynamak demek!$"

Route11_Text_JasperIntro::
    .string "Rekabet!\n"
    .string "Asla yeterince alamam!$"

Route11_Text_JasperDefeat::
    .string "Şansım vardı!$"

Route11_Text_JasperPostBattle::
    .string "POKéMON dünyasında\n"
    .string "korkak olamazsın!$"

Route11_Text_EddieIntro::
    .string "Hadi başlayalım, ama hile yok!$"

Route11_Text_EddieDefeat::
    .string "Ne?\n"
    .string "Bu doğru değil!$"

Route11_Text_EddiePostBattle::
    .string "Elimden geleni yaptım.\n"
    .string "Pişman değilim.$"

Route11_Text_BraxtonIntro::
    .string "Dikkat!\n"
    .string "Kablolar döşüyorum!$"

Route11_Text_BraxtonDefeat::
    .string "O elektrik gibiydi!$"

Route11_Text_BraxtonPostBattle::
    .string "Enerji tasarrufu yapın!$"

Route11_Text_DillonIntro::
    .string "Ben bir EĞİTMEN oldum.\n"
    .string "Ama kazanabileceğimi düşünüyorum.$"

Route11_Text_DillonDefeat::
    .string "POKéMON'um kazanamadı…\n"
    .string "Yeterince güçlü değiller mi?$"

Route11_Text_DillonPostBattle::
    .string "Şimdi ne olacak?\n"
    .string "Beni yalnız bırak!$"

Route11_Text_DirkIntro::
    .string "Fwahaha!\n"
    .string "Hiç kaybetmedim!$"

Route11_Text_DirkDefeat::
    .string "İlk defa kaybettim!$"

Route11_Text_DirkPostBattle::
    .string "Sadece şanslıydın, hepsi bu.$"

Route11_Text_DarianIntro::
    .string "Hiç kazanamadım…$"

Route11_Text_DarianDefeat::
    .string "Bunu bekliyordum…$"

Route11_Text_DarianPostBattle::
    .string "Her zamanki gibi şanssızdım.$"

Route11_Text_YasuIntro::
    .string "Sınıfımın en iyisiyim.\n"
    .string "Her sabah antrenman yapıyorum.$"

Route11_Text_YasuDefeat::
    .string "Müsibet!\n"
    .string "POKéMON'larımın daha güçlü\l"
    .string "olması gerekiyor!$"

Route11_Text_YasuPostBattle::
    .string "Dağlardan inen şişman\n"
    .string "bir POKéMON var.\p"
    .string "Eğer onu yakalayabilirsen\n"
    .string "eminim güçlü olacaktır.$"

Route11_Text_BernieIntro::
    .string "Elektrik tellerine dikkat et!$"

Route11_Text_BernieDefeat::
    .string "Vay!\n"
    .string "Çok çarpıcı!$"

Route11_Text_BerniePostBattle::
    .string "Eh, işe geri dönmeliyim.$"

Route11_Text_DaveIntro::
    .string "POKéMON'larıma iyi baktım.\n"
    .string "Şimdi hazır olmaları gerekiyor!$"

Route11_Text_DaveDefeat::
    .string "Elveda!\n"
    .string "Hoşça kal, teşekkürler!$"

Route11_Text_DavePostBattle::
    .string "Tch…\n"
    .string "Daha güçlülerini bulmam gerek!$"

Route11_Text_DiglettsCave::
    .string "DIGLETT'İN MAĞARASI$"
