CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "Hehehe! Slot makineleri\n"
    .string "büyük paralar kazandırıyor!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "ŞEF!\n"
    .string "Bugün 2000 tane daha\n"
    .string "POKéMON'u slot makinesi\l"
    .string "ödülü olarak gönderdik!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "OYUN KÖŞESİ'ndeki postere sakın\n"
    .string "dokunma!\lOrada gizli bir düğme\n"
    .string "falan yok!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.$", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
