SixIsland_OutcastIsland_Text_RocketIntro::
    .string "Burada hiç nadir POKéMON yok!\n"
    .string "Hiçbiri yok! Canımı sıkıyor.\l"
    .string "Bunu senden bileceğim!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "…Hıh?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "Dinle, nadir bir POKéMON\n"
    .string "gördün mü?$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "Hiç şansım yok. Savaşta\n"
    .string "tempoyu değiştirecek kadar!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "Hayır, hiç şansım yok…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "Ancak bir şey yakalamadan eve\n"
    .string "dönemem.$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "Hıçkırık… Hıçkırık…\p"
    .string "ALTINCI ADADAN buraya bir kerede\n"
    .string "yüzerek geldim.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "Hıçkırık…\n"
    .string "Hıçkırık…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "Yüzmenin yarısındayım…\n"
    .string "Yoruldum…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "Yüzerek POKéMON göndermek\n"
    .string "kolay değil, biliyor musun?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "Yüzmede sana kaybetmedim.\n"
    .string "Bu beni etkilemez.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "Buradan yukarıdaki adaya mı\n"
    .string "gidiyorsun?\p"
    .string "Orada ilginç bir şey görmedim.$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "AVA: İki kişilik bir deniz\n"
    .string "savaşına ne dersin?$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "AVA: Vay canına, çok iyiymişsin!\n"
    .string "Tek başına da harikasın!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "AVA: Biliyor musun, havuzdan\n"
    .string "çok daha fazla keyif alıyorum.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "AVA: Bize meydan mı okuyorsun?\p"
    .string "Savaşmak için en az iki POKéMON'a\n"
    .string "ihtiyacın var.$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "GEB: Ablacım, yardım et!\n"
    .string "Lütfen benimle savaş!$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "GEB: Vay canına, Ablacım, bu kişi\n"
    .string "gerçekten iyi!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "GEB: Ablama sarılıyorum çünkü\n"
    .string "dibe basamıyorum.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "GEB: Lütfen benimle ve ablamla\n"
    .string "savaş!$"
