Route14_Text_CarterIntro::
    .string "TM'leri kullanman gerektiğini\n"
    .string "biliyor musun?\p"
    .string "Böylece POKéMON'larına\n"
    .string "iyi hareketler öğretebilirsin.$"

Route14_Text_CarterDefeat::
    .string "Henüz yeterli değilsin.$"

Route14_Text_CarterPostBattle::
    .string "HM'lere sahipsin, değil mi?\p"
    .string "POKéMON'ların kolay kolay\n"
    .string "bu hareketleri unutmazlar.$"

Route14_Text_MitchIntro::
    .string "Kuş POKéMON'larım savaşmaya hazır.$"

Route14_Text_MitchDefeat::
    .string "Henüz hazır değiller!$"

Route14_Text_MitchPostBattle::
    .string "Kuş POKéMON'larımın daha iyi hareketler\n"
    .string "öğrenmesi gerekiyor.$"

Route14_Text_BeckIntro::
    .string "CELADON MAĞAZASI'nda\n"
    .string "satılan TM'lere bakmalısın.\p"
    .string "TM'ler pek nadir sayılmaz, ama\l"
    .string "HM'lere sahip çok az kişi vardır.$"

Route14_Text_BeckDefeat::
    .string "Ayy, berbat!$"

Route14_Text_BeckPostBattle::
    .string "Aynı türden bir hareket öğretmeyi dene.\n"
    .string "Bu, hareketin gücünü artırırmış.$"

Route14_Text_MarlonIntro::
    .string "Uçan POKéMON'una UÇ hareketini\n"
    .string "öğretmeyi denedin mi?\l"
    .string "Böylece onunla\l"
    .string "gökyüzünde süzülebilirsin!$"

Route14_Text_MarlonDefeat::
    .string "Alev alev yandın!$"

Route14_Text_MarlonPostBattle::
    .string "Uçan POKéMON'larımdan başkasını\n"
    .string "eğitmek istemiyorum. Onlar benim\l"
    .string "tek gerçek aşkım.$"

Route14_Text_DonaldIntro::
    .string "Kanatlı mucizelerin efsanesini\n"
    .string "duydun mu?$"

Route14_Text_DonaldDefeat::
    .string "Neden?\n"
    .string "Neden kaybettim?$"

Route14_Text_DonaldPostBattle::
    .string "Kanatlı mucizeler, efsanevi uçan\n"
    .string "POKéMON'lardır.\p"
    .string "Üç tane var: ARTICUNO,\n"
    .string "ZAPDOS ve MOLTRES.$"

Route14_Text_BennyIntro::
    .string "Pek ilgimi çekmiyor, ama olsun.\n"
    .string "Haydi başlayalım!$"

Route14_Text_BennyDefeat::
    .string "Biliyordum!$"

Route14_Text_BennyPostBattle::
    .string "Bu uçsuz bucaksız gökyüzünde\n"
    .string "kazanmak veya kaybetmek önemsiz.$"

Route14_Text_LukasIntro::
    .string "Hadi, hadi.\n"
    .string "Haydi, haydi, haydi!$"

Route14_Text_LukasDefeat::
    .string "Aarrg!\n"
    .string "Kaybettim! Defol!$"

Route14_Text_LukasPostBattle::
    .string "Ne, ne, ne?\n"
    .string "Hala ne istiyorsun?$"

Route14_Text_IsaacIntro::
    .string "Zaman öldürmem gerekiyor.\n"
    .string "Sus ve savaş.$"

Route14_Text_IsaacDefeat::
    .string "Ne?\n"
    .string "Sen mi?$"

Route14_Text_IsaacPostBattle::
    .string "POKéMON eğitmek çok sıkıcı dostum.$"

Route14_Text_GeraldIntro::
    .string "Burada dolaşıyoruz çünkü geniş\n"
    .string "alanlar var.$"

Route14_Text_GeraldDefeat::
    .string "Çakıldım!$"

Route14_Text_GeraldPostBattle::
    .string "POKéMON'unu güçlü yapman güzel.\n"
    .string "Güç her şeydir!\n"
    .string "Bunu biliyorsun!$"

Route14_Text_MalikIntro::
    .string "POKéMON savaşı mı?\n"
    .string "Süper! Hadi başlayalım!$"

Route14_Text_MalikDefeat::
    .string "Savrulup gittim!$"

Route14_Text_MalikPostBattle::
    .string "Seninle tek başımıza savaşsak,\n"
    .string "ben kazanırdım, biliyorsun!$"

Route14_Text_RouteSign::
    .string "ROTA 14\n"
    .string "Batı FUCHSIA ŞEHRİ'ne gider$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, beraber çok\n"
    .string "çalışalım, tamam mı?$"

Route14_Text_KiriDefeat::
    .string "KIRI: Hıçkı…\n"
    .string "Kaybettik, değil mi?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Kaybettiysem, benim\n"
    .string "yüzümden mi?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: İki POKéMON'un varsa\n"
    .string "savaşabiliriz.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, hazır mısın?\n"
    .string "Çok çalışmalıyız!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeeh!\n"
    .string "Haksızlık!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, ağlama!\n"
    .string "Bir dahakine daha çok çalışacağız.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: Savaşmak istiyorsun ama\n"
    .string "yeterli POKéMON'un yok.$"
