ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Of! Notlarımı ezberlemeye çalışıyorum\n"
    .string "ama zor.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Tamam!\p"
    .string "Lütfen tahtadaki yazıları dikkatlice\n"
    .string "okuyun!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Defterimize bir göz atalım.\p"
    .string "İlk sayfa…\p"
    .string "POKé TOPLARI POKéMON yakalamak\n"
    .string "için kullanılır.\p"
    .string "Partinize en fazla altı POKéMON\n"
    .string "alabilirsiniz.\p"
    .string "POKéMON yetiştirip savaşanlara\n"
    .string "EĞİTMEN denir.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "İkinci sayfa…\p"
    .string "Sağlıklı bir POKéMON yakalamak zor\n"
    .string "olabilir, önce zayıflatın.\p"
    .string "Zehirle, yak, ya da başka bir\n"
    .string "durum sorunu yarat.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Üçüncü sayfa…\p"
    .string "POKéMON EĞİTMEN'leri savaşmak için\n"
    .string "birbirlerini ararlar.\p"
    .string "EĞİTMENLER için zaferin tadı\n"
    .string "gerçekten tatlıdır.\p"
    .string "Her yerdeki POKéMON SALONLARI'nda\n"
    .string "sürekli savaşlar yapılır.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Dördüncü sayfa…\p"
    .string "Tüm POKéMON EĞİTMEN'lerinin\n"
    .string "hedefi basittir.\p"
    .string "İlk sekiz POKéMON SALONU\n"
    .string "LİDERLERİNİ yenmelisiniz.\p"
    .string "Böylece… POKéMON LİGİ'nin ELİT\n"
    .string "DÖRTLÜSÜ ile savaşmaya hak\n"
    .string "kazanırsınız!$"

ViridianCity_School_Text_TurnThePage::
    .string "Sayfayı çevirelim mi?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "KIZ: Hey!\n"
    .string "Notlarıma bakma!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "Tahta, savaş sırasındaki POKéMON\n"
    .string "DURUM sorunlarını listeler.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Hangi konuyu okumak istersin?$"

ViridianCity_School_Text_ExplainSleep::
    .string "UYKU halindeki bir POKéMON\n"
    .string "saldıramaz.\p"
    .string "POKéMON, savaşlardan sonra da\n"
    .string "uykuda kalır.\p"
    .string "UYANDIRICI kullanarak\n"
    .string "uyandırabilirsin.$"

ViridianCity_School_Text_ExplainBurn::
    .string "YANIK, SALDIRI gücünü azaltır ve\n"
    .string "CAN kaybına yol açar.\p"
    .string "YANIK savaştan sonra da kalır.\n"
    .string "YANIK İLACI kullanarak tedavi\n"
    .string "edebilirsin.$"

ViridianCity_School_Text_ExplainPoison::
    .string "Zehirlenince, bir POKéMON'un\n"
    .string "sağlığı sürekli düşer.\p"
    .string "Zehir, savaşlardan sonra da kalır.\n"
    .string "Bir PANZEHİR kullanarak zehiri\n"
    .string "tedavi et!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "Donmuş bir POKéMON hareket\n"
    .string "edemez hale gelir.\p"
    .string "Savaş bittikten sonra da donuk\n"
    .string "kalır.\p"
    .string "BUZ ÇÖZÜCÜ kullanarak POKéMON'unu\n"
    .string "çözebilirsin.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Felç, HIZ'ı azaltır ve POKéMON'un\n"
    .string "hareket etmesini engelleyebilir.\p"
    .string "Felç savaştan sonra da kalır.\p"
    .string "ANTİ FELÇ kullanarak tedavi\n"
    .string "uygulayın.$"
