SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "Bu gemi, dünya çapındaki\n"
    .string "EĞİTMENLER için bir lüks gemidir!\p"
    .string "Her limanda, EĞİTMEN'lerle\n"
    .string "partiler düzenliyoruz.$"

SSAnne_2F_Corridor_Text_RivalIntro::
    .string "{RIVAL}: Merhaba!\n"
    .string "{PLAYER}!\p"
    .string "Seni burada görmeyi düşünmezdim!\n"
    .string "{PLAYER}, gerçekten davetli miydin?\p"
    .string "Peki, POKéDEX'in nasıl gidiyor?\p"
    .string "Ben çoktan 40 çeşit yakaladım,\n"
    .string "dostum.\p"
    .string "Farklı çeşitler her yerde.\p"
    .string "Çimenlik alanlarda dolaş ve\n"
    .string "onları bulmak için dikkatlice bak.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
    .string "Höf!\p"
    .string "En azından POKéMON'unu\n"
    .string "eğitiyorsun!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "Bu gemi yolculuğu sana iyi gelmedi!\p"
    .string "Daha fazla vücudunu\n"
    .string "antrenman etmelisin!$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
    .string "{RIVAL}: Gemide bir KESME\n"
    .string "ustasının olduğunu duydum.\p"
    .string "Ama o sadece deniz tutması\n"
    .string "olan yaşlı bir adamdı!\p"
    .string "KES gerçekten faydalıdır.\n"
    .string "Evet, işine yarayacak.\p"
    .string "Sen de gidip onu görmelisin.\n"
    .string "Ben kaçtım!$"

