Route10_Text_MarkIntro::
    .string "Vay, buraya kadar mı geldin?\n"
    .string "Belki sen de bir POKéMANYAK'sın?\l"
    .string "Koleksiyonumu görmek ister misin?$"

Route10_Text_MarkDefeat::
    .string "Hımpf.\n"
    .string "Kızgın değilim!$"

Route10_Text_MarkPostBattle::
    .string "Evde daha nadir POKéMON'um var!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-ha!\n"
    .string "Gülmüyorum!\l"
    .string "Ah-hapşuu! Haha-ha-çık!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-çık!\n"
    .string "Hapşuu!\l"
    .string "Horlama! Hıçkırık!$"

Route10_Text_HermanIntro::
    .string "Merhaba, çocuk!\n"
    .string "POKéMON'umu görmek ister misin?$"

Route10_Text_HermanDefeat::
    .string "Aman Tanrım!\n"
    .string "POKéMON'um!$"

Route10_Text_HermanPostBattle::
    .string "Seni sevmiyorum.\n"
    .string "Kendimden daha iyi kimseyi sevmiyorum!$"

Route10_Text_HeidiIntro::
    .string "Birkaç kez POKéMON SALONUNA\n"
    .string "gittim.\p"
    .string "…Ama hep kaybediyorum.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "Tüm eğitimime rağmen!$"

Route10_Text_HeidiPostBattle::
    .string "Bazı POKéMANYAK'ların\n"
    .string "etrafta dolaştığını fark ettim.\p"
    .string "Hayal edebiliyor musun?\n"
    .string "Buralarda dolaştıklarını?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "Bu dağ havası harika!$"

Route10_Text_TrentDefeat::
    .string "Bu kafamı dağıttı!$"

Route10_Text_TrentPostBattle::
    .string "Dağ havası şişkinlik yaptı!$"

Route10_Text_CarolIntro::
    .string "Biraz baygın hissediyorum.\n"
    .string "Uzun zamandır yürüyüş yapmıyorum.$"

Route10_Text_CarolDefeat::
    .string "Çok yorgunum.\n"
    .string "Hazır değildim.$"

Route10_Text_CarolPostBattle::
    .string "Dağlardaki POKéMON'lar\n"
    .string "çok iri…\p"
    .string "Pembe, çiçek desenli\n"
    .string "bir POKéMON isterdim!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "KAYA TÜNELİ\n"
    .string "LAVENDER KASABASI'na dönüş$"

Route10_Text_RockTunnel::
    .string "KAYA TÜNELİ$"

Route10_Text_PowerPlant::
    .string "ENERJİ SANTRALİ$"
