LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "Ben bu şehre yeni taşındım.\p"
    .string "BAY FUJİ'nin de aslında buranın\n"
    .string "yerlisi olmadığı söyleniyor.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Bu tuhaf, BAY FUJİ burada değil.\n"
    .string "Nereye gitti?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "BAY FUJİ, CUBONE'un annesi için\n"
    .string "yalnız başına dua ediyor.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .string "Bu gerçekten BAY FUJİ'nin evi.\p"
    .string "O çok iyi biri.\p"
    .string "Terk edilmiş ve öksüz POKéMON'lara\n"
    .string "bakar.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .string "Çok sıcak!\n"
    .string "POKéMON'ları kucaklamak çok güzel.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "BAY FUJİ: {PLAYER}…\p"
    .string "POKéDEX arayışın, güçlü bir adanma\n"
    .string "gerektiriyor.\p"
    .string "POKéMON'ları derin bir sevgi\n"
    .string "olmadan araman başarısız olabilir.\p"
    .string "Bunun yardımcı olup olmayacağından\n"
    .string "emin değilim, ama sana vermek\l"
    .string "isterim.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER}, BAY FUJİ'den bir\n"
    .string "POKE FLÜT aldı.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "POKé FLUTE'u duyduğunda, uyuyan\n"
    .string "POKéMON'lar uyanacak.\p"
    .string "Uyuyan engeller olan POKéMON'lara\n"
    .string "karşı kullanmayı dene.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "Bunun için yer açmalısın!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "BAY FUJİ: POKé FLÜT'üm sana\n"
    .string "yardım etti mi?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "POKéMON FAN DERGİSİ\n"
    .string "Aylık Büyük Ödül Çekilişi!\p"
    .string "Başvuru formu…\p"
    .string "Boş! Kesilmiş. Biri zaten\n"
    .string "almış olmalı.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "Raf, POKéMON dergileriyle dolu.\p"
    .string "POKéMON YÜZÜ…\p"
    .string "POKéMON FAN…$"
