RockTunnel_1F_Text_LennyIntro::
    .string "Bu tünel çok uzun, çocuk!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "Vay!\n"
    .string "Sen kazandın!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "ONIX'e dikkat et.\n"
    .string "Onlar nadiren görünürler.\p"
    .string "Yüksek seviyeliler\n"
    .string "seni sıkıştırabilir!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Hmm.\n"
    .string "Sanırım burada kaybolmuşum…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "Kendine gel!\n"
    .string "Ne yapıyorum?\l"
    .string "Çıkış nerede?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "ROTA 12'deki uyuyan POKéMON\n"
    .string "beni bu yola soktu.$"

RockTunnel_1F_Text_LucasIntro::
    .string "Senin gibi yabancılar bana saygı\n"
    .string "göstermeli!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "Pes ediyorum!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "Dağcılık yeteneğin var!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "POKéMON savaşı!\n"
    .string "Hazır mısın, başla!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "Oyun bitti!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "Eh, giderken bir ZUBAT alacağım!$"

RockTunnel_1F_Text_LeahIntro::
    .string "Ay!\p"
    .string "Karanlıkta komik şeyler yapma!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "Karanlıktı…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "Bu tünelde bir MACHOP gördüm.$"

RockTunnel_1F_Text_DanaIntro::
    .string "Yabani POKéMON aramak için\n"
    .string "uzaklara geldim.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "POKéMON'um kalmadı!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "Tatlı ve zararsız görünüyordun.\n"
    .string "Ne kadar yanlış düşündüğümü anladım!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "POKéMON'un var!\n"
    .string "Başlayalım!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "Zorlusun!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "Of!\n"
    .string "Ter içinde kaldım.$"

RockTunnel_1F_Text_RouteSign::
    .string "KAYA TÜNELİ\n"
    .string "CERULEAN ŞEHRİ - LAVENDER KASABASI$"
