CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "Merhaba!\p"
    .string "Üzgünüm, şu an kısa bir moladayız.\n"
    .string "Hemen döneriz.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "POKéMON'larım zayıf, bu yüzden\n"
    .string "sık sık ECZANEYE gitmem gerekiyor.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "Şşt! OYUN KÖŞESİ'nin altında gizli\n"
    .string "bir bodrum katı olduğunu duydum.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Çıt çıt…\p"
    .string "O masadaki adam, slot makinelerinde\n"
    .string "her şeyini kaybetti.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "Devam et! Gül! \n"
    .string "Tamamen battım!\p"
    .string "Artık slot oynamayacağım!\n"
    .string "Artık düzgün yaşayacağım!\p"
    .string "Al!\n"
    .string "Artık buna ihtiyacım yok!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} adamdan JETON KASASI\n"
    .string "aldı.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "Buna yer açın!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Her zaman kazanacağımı\n"
    .string "düşünmüştüm…$"
