TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Merhaba, ben POKéMON Hamle\n"
    .string "Manyağıyım.\p"
    .string "Her POKéMON'un büyürken öğrendiği\n"
    .string "her hamleyi biliyorum.\p"
    .string "Ayrıca bir mantar delisiyim.\p"
    .string "Bana iki KÜÇÜK MANTAR ya da,\n"
    .string "bir BÜYÜK MANTAR getir.\p"
    .string "Bunu yaparsan, POKéMON'una\n"
    .string "bir hamle öğretirim.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Hmm…\n"
    .string "Mantar kokusu alıyorum!\p"
    .string "Bir POKéMON'una hareket\n"
    .string "öğretmemi ister misin?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hangi POKéMON'u eğiteyim?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hangi hamleyi öğretmemi istersin?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Üzgünüm…\p"
    .string "Görünüşe göre bu POKéMON'a\n"
    .string "öğretebileceğim bir hamle yok.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "Bir-iki mantara ihtiyacım\n"
    .string "var sadece.\l"
    .string "Bana ne vermek istersin?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER}, karşılığında iki\n"
    .string "KÜÇÜK MANTAR verdi.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER}, karşılığında bir\n"
    .string "BÜYÜK MANTAR verdi.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Eğer POKéMON'unun hareket\n"
    .string "öğrenmesi gerekiyorsa, birkaç\l"
    .string "mantara ihtiyacım var.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hmm? Bir yumurtaya hamle\n"
    .string "öğretemem.$"
