TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "Merhaba, POKéMON Hamle Manyağıyım.\p"
    .string "Her POKéMON'un büyürken öğrendiği\n"
    .string "her hareketi biliyorum.\p"
    .string "Ayrıca bir mantar delisiyim.\p"
    .string "Bana iki KÜÇÜK MANTAR getir,\n"
    .string "ya da bir BÜYÜK MANTAR.\p"
    .string "Bunu yaparsanız, bir POKéMON'a\n"
    .string "bir hamle öğretirim.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "Hmm…\n"
    .string "Mantar kokusu alıyorum!\p"
    .string "Bir POKéMON'unuza hareket\n"
    .string "öğretmemi ister misiniz?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "Hangi POKéMON'a eğitim verilecek?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "Hangi hareketi öğretmemi istersin?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "Üzgünüm…\p"
    .string "Görüntüye göre bu POKéMON'a\n"
    .string "öğretebileceğim bir hareketim yok.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "O zaman bir veya iki\n"
    .string "mantara ihtiyacım var.\l"
    .string "Bana ne vermek istersin?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} karşılığında iki\n"
    .string "KÜÇÜK MANTAR verdi.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} karşılığında bir\n"
    .string "BÜYÜK MANTAR verdi.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "Eğer POKéMON'unuzun hareket\n"
    .string "öğrenmesi gerekiyorsa, bir veya\l"
    .string "iki mantara ihtiyacım var.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "Hmm? Bir yumurtaya öğretecek\n"
    .string "hiçbir hareketim yok.$"
