SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} bir SAFİR buldu!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "Fufu… Fufufufu…\n"
    .string "Tahminim doğru çıktı.\p"
    .string "Seni takip etmem yerindeymiş!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "Burada bir SAFİR olduğunu\n"
    .string "biliyordum, bu yüzden o benim!\p"
    .string "ROKET TAKIMI'na satıp iyi para\n"
    .string "kazanacağım.\p"
    .string "…Bana öyle bakma!\p"
    .string "Eğer geri istiyorsan, sattıktan\n"
    .string "sonra geri alabilirsin.\p"
    .string "ROKET DEPOSU'nun\n"
    .string "parolasını bile söyleyeceğim.\p"
    .string "Bildiğim parola:\n"
    .string "“Evet, hayır, CHANSEY.”\p"
    .string "Bitti.\n"
    .string "Lütfen bana kızma!$"
