FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Ben KUŞ KARDEŞLER'in en büyüğüyüm.\p"
    .string "Kuşların en iyi yanı…\n"
    .string "Sanırım gagası olmalı.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "O kadar keskin!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Buradan DÖRDÜNCÜ ADA'ya uçabilirsin.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Ben KUŞ KARDEŞLER'in ortancasıyım.\p"
    .string "Kuşların en iyi yanı…\n"
    .string "Kanatları gibi.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "Çırpın, çırpın!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Orada çok kasvetli bir adam vardı.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Ben KUŞ KARDEŞLER'in en küçüğüyüm.\p"
    .string "Kuşların en iyi yanı…\n"
    .string "Tüyleri gibi.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Tüyler çok rahatlatıcı…\n"
    .string "Uyku getiriyor…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "KUŞ POKéMON'ların neşeyle oynaması\n"
    .string "beni mutlu ediyor.$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Sürt, sürt…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Merhaba…\p"
    .string "POKéMON'ların çok sağlıklı\n"
    .string "görünüyor…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "ONIX'imi gömdüğüm yer burası…\n"
    .string "Adı TECTONIX'ti…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "Bir kayada\p"
    .string "“Burada TECTONIX yatıyor”\n"
    .string "yazılı.\p"
    .string "Mezarın önüne bir LİMONATA\n"
    .string "bırakılmış.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "Başka bir LİMONATA bırakmak\n"
    .string "ister misin?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER}, mezarın önüne bir adet\n"
    .string "LİMONATA bıraktı.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "Te-teşekkürler…\p"
    .string "O, TECTONIX'in favori içeceğiydi…\p"
    .string "Yabancı biri olarak, bu iyiliğin…\n"
    .string "Beni biraz mutlu etti.\p"
    .string "Lütfen bunu teşekkür olarak kabul\n"
    .string "et.$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Lütfen POKéMON'larına da iyi davran.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Eğer yerin yoksa, bir sonraki\n"
    .string "sefere kadar ben saklayabilirim$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Oh, sen o zamandaki…\p"
    .string "Hala sana vermek istediğim şeyi\n"
    .string "sakladım.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Ühü, ühü…\p"
    .string "… … …\n"
    .string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Kayalar ve taşlar bir mezar gibi\n"
    .string "yığılmış.\p"
    .string "Kayada “Burada TECTONIX yatıyor”\n"
    .string "yazılı.$"
