Text_UltimateMoveThatMon::
    .string "Bu türün en iyi hareketini\n"
    .string "geliştirdim…\p"
    .string "Ama hiç kimse bundan\n"
    .string "faydalanmayacak mı?\p"
    .string "…Hm? Hmmm!\p"
    .string "S-sen…\n"
    .string "O {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Hayır…\n"
    .string "Yanılmışım.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Oh! İşte bu!\n"
    .string "Bu POKéMON!\p"
    .string "Bu {STR_VAR_1} en iyi hareketimi\n"
    .string "öğrenmeye değer!\p"
    .string "Buna izin verir misin?\p"
    .string "{STR_VAR_1}'ine {STR_VAR_2}\n"
    .string "öğreteyim mi?$"

Text_YouRejectIt::
    .string "Gaah! Reddediyor musun?\n"
    .string "Hayır, vazgeçmeyeceğim!$"

Text_LetMeConferUltimateMove::
    .string "Buna izin veriyorsun?\p"
    .string "O zaman, {STR_VAR_2} hareketini\n"
    .string "{STR_VAR_1}'ine aktarayım.\p"
    .string "Ggggrah-awooo!$"

Text_TaughtMove::
    .string "Hıçkırık…\p"
    .string "Yaşarken bu hareketi\n"
    .string "öğretmeyi düşünmezdim…$"

Text_MakeBestUseOfMove::
    .string "Senden bu hareketi en iyi şekilde\n"
    .string "kullanmanı ve güçlenmeni rica\n"
    .string "ediyorum!$"

Text_PassedOnEverythingIKnow::
    .string "Hıçkırık…\p"
    .string "Artık hiçbir pişmanlığım yok.\n"
    .string "Bildiğim her şeyi aktardım.\p"
    .string "Artık yaşayabilirim, çünkü\n"
    .string "görevimi tamamladım.$"

Text_FeelRejuvenated::
    .string "Bilgimi sana aktardıktan sonra,\n"
    .string "büyük bir rahatlama hissettim.\p"
    .string "Aslında, kendimi yeniden\n"
    .string "gençleşmiş gibi hissediyorum!$"
