Text_UltimateMoveThatMon::
    .string "Bu türün en iyi hamlesini\n"
    .string "geliştirdim…\p"
    .string "Ama hiç kimse bundan\n"
    .string "faydalanmayacak mı?\p"
    .string "…Hm? Hmmm!\p"
    .string "S-sen…\n"
    .string "O {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…Hayır…\n"
    .string "Yanılmışım.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "Hey! İşte bu!\n"
    .string "Bu o POKéMON!\p"
    .string "Bu {STR_VAR_1} en iyi hamlemi\n"
    .string "öğrenmeye değer!\p"
    .string "Buna izin verir misin?\p"
    .string "{STR_VAR_1}'ine {STR_VAR_2}\n"
    .string "öğreteyim mi?$"

Text_YouRejectIt::
    .string "Gaah! Reddediyorsun demek.\n"
    .string "Hayır, vazgeçmeyeceğim!$"

Text_LetMeConferUltimateMove::
    .string "Buna izin veriyorsun demek.\p"
    .string "O zaman, {STR_VAR_2} hamlesini\n"
    .string "{STR_VAR_1}'ine öğreteyim.\p"
    .string "Ggggrah-avuuuu!$"

Text_TaughtMove::
    .string "Hıh…\p"
    .string "Bu hamleyi ölmeden öğretmek\n"
    .string "hiç aklıma gelmezdi…$"

Text_MakeBestUseOfMove::
    .string "Senden bu hamleyi en iyi şekilde\n"
    .string "kullanmanı ve güçlenmeni rica\l"
    .string "ediyorum!$"

Text_PassedOnEverythingIKnow::
    .string "Hıh…\p"
    .string "Artık hiçbir pişmanlığım yok.\n"
    .string "Bildiğim her şeyi aktardım.\p"
    .string "Artık rahat edebilirim çünkü\n"
    .string "görevimi tamamladım.$"

Text_FeelRejuvenated::
    .string "Bilgimi sana aktardıktan sonra\n"
    .string "büyük bir rahatlama hissettim.\p"
    .string "Aslında, kendimi yeniden\n"
    .string "gençleşmiş gibi hissediyorum!$"
