Route1_Text_WorkAtPokeMartTakeSample::
    .string "Merhaba!\n"
    .string "Bir POKéMON MARKETİ'nde\lçalışıyorum.\p"
    .string "Bu, her türlü eşyayı satan\n"
    .string "pratik bir mağaza zinciri.\p"
    .string "Lütfen, VIRIDIAN ŞEHRİ'ndeki\n"
    .string "mağazamıza uğrayın.\p"
    .string "İşte sizin için bir eşantiyon!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Lütfen, POKéMON yakalamak için\n"
    .string "POKé TOPU'na ihtiyacınız olursa\lbize uğrayın.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER}, İKSİR'i ÇANTA'daki\n"
    .string "EŞYA bölümüne koydu.$"

Route1_Text_CanJumpFromLedges::
    .string "Yol boyunca o çıkıntıları\ngörüyor musun?\p"
    .string "Biraz korkutucu,\nama onlardan atlayabilirsin.\p"
    .string "Bu şekilde PALLET KASABASI'na daha\n"
    .string "hızlı geri dönebilirsin.$"

Route1_Text_RouteSign::
    .string "ROTA 1\n"
    .string "PALLET KASABASI - VIRIDIAN ŞEHRİ$"
