PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Gel, çocuk!\n"
    .string "Bu alanı arındırdım.\l"
    .string "Burada dinlenebilirsin.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Ver…bana…\n"
    .string "her…şeyini…$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Ah!$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "Beni kontrol ediyordu.$"

PokemonTower_5F_Text_RuthIntro::
    .string "Sen…bize…\n"
    .string "katılacaksın…$"

PokemonTower_5F_Text_RuthDefeat::
    .string "Ne kabusmuş!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "Benim ruhum ele geçirilmişti.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Zombiler!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Ne?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "Aklima kavuştum.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Ugh…\n"
    .string "Uff…$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Oh!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Dağlarda onca eğitimime rağmen,\n"
    .string "kötü ruhlara yenik düştüm…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Arındırılmış ve korunmuş\n"
    .string "alana girdiniz.\p"
    .string "{PLAYER}'in POKéMON'ları\n"
    .string "tamamen iyileşti.$"
