Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad:
    .string "Yaya geçişine kapalı!\n"
    .string "BİSİKLET YOLU!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse:
    .string "BİSİKLET YOLU deniz kenarındaki\n"
    .string "bir iniş rotasıdır. Keyfini çıkar!$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp:
    .string "Affedersiniz!\n"
    .string "Lütfen bekleyin!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort:
    .string "İçeri nasıl girdin?\n"
    .string "İyi iş!$"
