Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "Ben BALIKÇI GURU'nun küçük\n"
    .string "kardeşiyim.\p"
    .string "Balık tutmaya bayılıyorum!\n"
    .string "Söyle, sen de sever misin?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "Harika! Tarzını beğendim.\n"
    .string "Sanırım arkadaş olabiliriz.\p"
    .string "Bunu al ve balık tut, genç dostum!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER}, BALIKÇI GURU'nun\n"
    .string "kardeşinden bir SÜPER OLTA aldı.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "Balık tutmak bir yaşam tarzı!\n"
    .string "Güzel bir şiire benziyor.\p"
    .string "Denizlerden ırmaklara, çık ve\n"
    .string "büyük balığı yakala, dostum.\p"
    .string "Şimdi, bir isteğim var.\p"
    .string "Eğer büyük bir MAGIKARP\n"
    .string "yakalarsan, görmek isterim.\p"
    .string "Balık tutmayı sevdiğim kadar\n"
    .string "devasa MAGIKARP'ları görmeyi de\l"
    .string "o kadar çok seviyorum.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "Ah…\n"
    .string "Bu çok hayal kırıklığına uğratıcı…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "Merhaba {PLAYER}!\n"
    .string "Balık tutmaya gittin mi?\p"
    .string "Herhangi bir suda SÜPER OLTA ile\n"
    .string "balık tutmayı dene.\p"
    .string "Farklı yerlerde farklı POKéMON'lar\n"
    .string "bulacaksın.\p"
    .string "Ah, ve devasa MAGIKARP'ları\n"
    .string "getirmeyi unutma.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "Oh? {PLAYER}?\n"
    .string "O bir MAGIKARP mı!\p"
    .string "Bana hemen göster, lütfen!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …Vay!\n"
    .string "{STR_VAR_2} inç!\p"
    .string "Balık tutmanın şiirsel yönlerini\n"
    .string "anlaman çok iyi!\p"
    .string "Bunu almalısın.\n"
    .string "Israr ediyorum!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "Daha büyük rekorlarını görmeyi\n"
    .string "dört gözle bekleyeceğim!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "Hı?\n"
    .string "{STR_VAR_2} inç?\p"
    .string "Bu, daha önce gördüğümle aynı boy.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "Hmm…\n"
    .string "Bu {STR_VAR_2} inç uzunluğunda.\p"
    .string "Daha önce getirdiğin {STR_VAR_3}\n"
    .string "inçlik balığa yetişemiyor.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "Hı… Bu pek MAGIKARP'a benzemiyor.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "Ah, hayır!\p"
    .string "Sana bir hediyem vardı, ama yerin\n"
    .string "yok.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "Gördüğüm en devasa MAGIKARP\n"
    .string "…\p"
    .string "{STR_VAR_3} inç!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "Bu, bir çeşit boş tablo.\p"
    .string "Rekor yazmak için alanları var.$"
