CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "Bilmediğim hiçbir şey yok,\n"
    .string "siyah tahtaya yazdığım gibi.\p"
    .string "GAME BOY ADVANCE'daki\n"
    .string "POKéMON dünyasını biliyorum!\p"
    .string "Arkadaşlarınla buluş ve POKéMON\n"
    .string "takasının tadını çıkar!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} bir EEVEE aldı!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "POKéMON'larla dolu burası!\n"
    .string "Lütfen başka bir kutu seç.$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "POKéMON Dersi\p"
    .string "Kablosuz Adaptör ile Oynama$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Hangi başlığı okumak istersin?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "POKéMON KABLOSUZ KULÜBÜ,\n"
    .string "herhangi bir POKéMON MERKEZİ'nin\l"
    .string "üst katındadır.\p"
    .string "Kablosuz Adaptör'ünüzü kullanarak\n"
    .string "arkadaşlarınızla bağlantı kurun.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "Sadece bir arkadaşla bağlantı\n"
    .string "kurmak için, DİREKT KÖŞESİ'ne\l"
    .string "gitmelisin.\p"
    .string "Bu, POKéMON KABLOSUZ KULÜBÜ'ndeki\n"
    .string "sağ taraftaki bankodur.\p"
    .string "Arkadaşınızla birlikte TAKAS\n"
    .string "KÖŞESİ'ne veya KOLEZYUM'a gidin.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "Herhangi biriyle bağlantı kurmak\n"
    .string "ve iletişim kurmak için, BİRLİK\l"
    .string "ODASI'na gidin.\p"
    .string "Bu, POKéMON KABLOSUZ KULÜBÜ'ndeki\n"
    .string "sol taraftaki bankodur.\p"
    .string "BİRLİK ODASI'na gidin ve diğer\n"
    .string "EĞİTMENLER ile tanışın.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "Bu, TM'ler hakkında bir broşür.\p"
    .string "… …\p"
    .string "Toplamda elli tane TM var.\p"
    .string "Ayrıca, tekrar tekrar\n"
    .string "kullanılabilen yedi tane\l"
    .string "HM de var.\p"
    .string "SILPH ŞTİ.$"
