CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon:
    .string "PORYGON'u almayı çok istiyorum!\n"
    .string "Ama slotlarda kazanmak çok zor.$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday:
    .string "Harika bir gündü, çok para kazandım!\n"
    .string "Keşke her gün böyle olsa…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired:
    .string "Bir JETON KASASI'na\n"
    .string "ihtiyacınız var…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes:
    .string "JETON'ları hediyelere çeviriyoruz.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize:
    .string "Hangi hediyeyi istersiniz?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo:
    .string "İşte hediyeniz.$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize:
    .string "Öyleyse, {STR_VAR_1} almak mı\n"
    .string "istiyorsunuz?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM:
    .string "Tamam, istediğiniz şey\n"
    .string "{STR_VAR_2} TM'si mi?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins:
    .string "Üzgünüm, daha fazla\n"
    .string "JETON gerekiyor.\l"
    .string "Bu hediyeyi alamazsınız.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom:
    .string "Maalesef, envanteriniz dolu.$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen:
    .string "Pekala, iyi günler.$"
