SixIsland_PatternBush_Text_BethanyIntro::
    .string "Merak ettim, sen POKéMON'unu\n"
    .string "nasıl eğitiyorsun?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "Sen POKéMON'unu çok sevgiyle\n"
    .string "eğitiyorsun!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "Senin annenin seni sevgiyle\n"
    .string "büyüttüğü gibi, sen de POKéMON'unu\l"
    .string "aynı şekilde eğitmelisin.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "Buradaki POKéMON'ların doğal\n"
    .string "ekolojisini korumaya çalışıyorum.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "Sen çok gençsin, ama çok güçlüsün!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "POKéMON yakalamaman gerektiğini\n"
    .string "söylemiyorum.\p"
    .string "Sadece insanların POKéMON'larını\n"
    .string "sorumlu bir şekilde eğitmelerini\l"
    .string "istiyorum.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "Sadece burada yaşayan bir BÖCEK\n"
    .string "POKéMON'u yakaladım!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "Haha…\n"
    .string "POKéMON'um harika, değil mi?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "Bir kız var, çimlerin yakınında.\n"
    .string "HERACROSS'ların boyunu\l"
    .string "ölçüyor.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "Bilmelisin, BÖCEK POKéMON'ları\n"
    .string "kullanmadan yapamıyorum.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "Sorun yok, kaybetmek de POKéMON\n"
    .string "oynamanın eğlenceli bir parçası.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "Bu arada, “çekici” garip bir\n"
    .string "kelime, değil mi?\p"
    .string "Mesela, alet gibi mi,\n"
    .string "yoksa araba gibi mi?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "Evet, evet, evet!\n"
    .string "Tüm bu BÖCEK POKéMON'larına bak!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "Kutlama yaparken yenildim!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "Bir dahaki sefere küçük kardeşimi\n"
    .string "getireceğim.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "Bakın, bakın! Çimlerde komik\n"
    .string "desenler var.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "Süper, harika!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "Çimlerdeki komik desenler…\p"
    .string "Dedemin çoraplarındaki desenlere\n"
    .string "benziyorlar.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "Sanırım beni sıradan biri\n"
    .string "sandın, değil mi?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "Zayıf olduğumu düşündün, değil\n"
    .string "mi?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "Ayıp be, şehirli arkadaşlar çok\n"
    .string "kokoş geliyorsunuz böyle şapka\l"
    .string "takarak…\p"
    .string "Bana onu versene?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "Derin bir nefes al.\n"
    .string "Hava harika, değil mi?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "İstersen, sana doğru nefes alma\n"
    .string "tekniklerini öğretirim.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "Önce nefesini ver.\n"
    .string "İçindeki her şeyi boşalt.\p"
    .string "Nefes veremeyecek duruma\n"
    .string "gelince, temiz havayı içine çek!\p"
    .string "Harika hissettiriyor, değil mi?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "BÖCEK POKéMON'larını seviyorum.\n"
    .string "Bu yüzden sürekli buradayım.\p"
    .string "Acaba tek kız ben miyim?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "Yenildim, ama hala gülüyorum.\n"
    .string "Acaba tek kız ben miyim?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "BÖCEK POKéMON'ları toplamaya devam\n"
    .string "edeceğim.\p"
    .string "Acaba tek kız ben miyim?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "Burası iyi bir yer.\n"
    .string "Çadırımı burada kuracağım.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "Korkaklık ettim…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "Burada gece gökyüzünü\n"
    .string "gözlemleyeceğim.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "İğrenç! Bir böcek ısırdı beni!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "Bir böcek değildi.\n"
    .string "Çimde dizimi kestim.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "Küçük bir kesik bu… Onu\n"
    .string "iyileştirmeye biraz tükürük yeter!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "Bu bölgede garip bir şeyler\n"
    .string "olduğunu fark ettin mi?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "Ayaklarının altındaki çimlere iyi\n"
    .string "bak!$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "LABİRENT ÇALI'da çimlerin\n"
    .string "büyümeyeceği yerler var.\p"
    .string "Böyle bir olayı neye\n"
    .string "bağlayabiliriz?$"
