SilphCo_10F_Text_GruntIntro::
    .string "10. kata hoş geldiniz!\n"
    .string "Katılmanız çok iyi oldu!$"

SilphCo_10F_Text_GruntDefeat::
    .string "Şaşkına döndüm!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "İyi deneme, ancak yönetim katı bir\n"
    .string "kat daha yukarıda.$"

SilphCo_10F_Text_TravisIntro::
    .string "Yeterince aptalca oyun oynadın!$"

SilphCo_10F_Text_TravisDefeat::
    .string "Devam etmek için takatim kalmadı!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "Beni yenmekten memnun musun?\n"
    .string "O zaman eve git!$"

SilphCo_10F_Text_WaaaImScared::
    .string "Waaaaa!\n"
    .string "Korkuyorum!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "Ağlamam hakkında…\n"
    .string "Lütfen bunu bir sır olarak sakla.$"

SilphCo_10F_Text_FloorSign::
    .string "SILPH ŞTİ. MERKEZ OFİS\n"
    .string "10. Kat$"

