SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: Merhaba!\n"
    .string "POKéMON'ları sever misin?\p"
    .string "{PLAYER}: Eh, hayır, ben sadece sordum.\p"
    .string "{PLAYER}: Hmm?\n"
    .string "Çok garipsin!\p"
    .string "TAKLİTÇİ: Hmm? Taklit etmeyi\n"
    .string "bırakmamı mı istiyorsun?\p"
    .string "Ama bu benim en sevdiğim hobim!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: Merhaba.\n"
    .string "POKéMON'ları seviyor olmalısın.\p"
    .string "{PLAYER}: Hayır, ben değil.\n"
    .string "Sana sormuştum.\p"
    .string "{PLAYER}: Affedersin?\n"
    .string "Çok garipsin!\p"
    .string "TAKLİTÇİ: Hmm? Taklit etmeyi\n"
    .string "bırakmamı mı istiyorsun?\p"
    .string "Ama bu benim en sevdiğim hobim!$"

Text_MimicTeach::
    .string "Vay canına!\n"
    .string "Bir POKé BEBEK!\p"
    .string "Bana mı?\n"
    .string "Teşekkürler!\p"
    .string "Biliyor musun?\n"
    .string "MİMİK hareketini öğretebilirim.$"

Text_MimicDeclined::
    .string "MİMİK hareketini beğenmedin mi?$"

Text_MimicWhichMon::
    .string "MİMİK hareketini çok seviyorum!\n"
    .string "Hangi POKéMON öğrenecek?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Merhaba!\n"
    .string "Daha önce yardımın için teşekkürler.\p"
    .string "{PLAYER}: Affedersin?\p"
    .string "{PLAYER}: Her hareketimi taklit\n"
    .string "etmek gerçekten bu kadar\l"
    .string "eğlenceli mi?\p"
    .string "TAKLİTÇİ: Kesinlikle!\n"
    .string "Çok komik!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Merhaba!\n"
    .string "Bize yardımın için teşekkürler.\p"
    .string "{PLAYER}: Affedersin?\p"
    .string "{PLAYER}: Her söylediğimi\n"
    .string "ve yaptığımı\l"
    .string "taklit etmek gerçekten\l"
    .string "bu kadar eğlenceli mi?\p"
    .string "TAKLİTÇİ: Kesinlikle!\n"
    .string "Çok komik!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "Çantam çok dolu!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“Merhaba! Nasılsın?\n"
    .string "POKéMON'ları sever misin?\p"
    .string "{PLAYER}“Ben değil, sana soruyorum\n"
    .string "ama.\p"
    .string "{PLAYER}“... Niye böyle yapıyorsun!\n"
    .string "Çok garipsin!\p"
    .string "TAKLİTÇİ KIZ“... Ne?\n"
    .string "Beni taklit etmememi mi istiyorsun?\p"
    .string "Ama taklit etmek benim hobim!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“Merhaba!\n"
    .string "POKéMON'ları seviyorsun, değil mi?\p"
    .string "{PLAYER}“Ben değil, sana soruyorum\n"
    .string "ama.\p"
    .string "{PLAYER}“... Niye böyle yapıyorsun!\n"
    .string "Çok garipsin!\p"
    .string "TAKLİTÇİ KIZ“... Ne?\n"
    .string "Beni taklit etmememi mi istiyorsun?\p"
    .string "Ama taklit etmek benim hobim!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "GÜZEL AYNA BAK BANA, NE\n"
    .string "KADAR GÜZEL OLABİLECEĞİMİ GÖR!?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "Bu nadir bulunan bir POKéMON!\n"
    .string "Hey, bu sadece bir oyuncak!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "MARIO'nun bir oyunu!\n"
    .string "Başında kovayla oynuyor!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "Sırlarım!\p"
    .string "Yetenek: Taklit!\n"
    .string "Hobi: Bebek toplamak!\l"
    .string "Favori Pokemon: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "Ne? Görünmüyor...$"
