PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "ANNE: …Doğru.\n"
    .string "Tüm çocuklar bir gün evden ayrılır.\l"
    .string "Bunu televizyonda görmüştüm.\p"
    .string "Ah, evet. Komşumuz PROF. OAK,\n"
    .string "seni arıyordu.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "ANNE: …Doğru.\n"
    .string "Tüm kızların seyahat hayali vardır.\l"
    .string "Bunu televizyonda görmüştüm.\p"
    .string "Ah, evet. Komşumuz PROF. OAK,\n"
    .string "seni arıyordu.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "ANNE: {PLAYER}!\n"
    .string "Kısa bir dinlenmeye ihtiyacın var gibi.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "ANNE: Oh, harika! Sen ve\n"
    .string "POKéMON'un çok iyi görünüyorsunuz.\l"
    .string "Kendinize dikkat edin!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Televizyonda bir film var.\n"
    .string "Dört çocuk demiryolu raylarında\l"
    .string "yürüyor.\p"
    .string "…Ben de gitmeliyim.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Televizyonda bir film var.\n"
    .string "İki örgülü kız, tuğla bir yolda\l"
    .string "yürüyor.\p"
    .string "…Ben de gitmeliyim.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Aa, yanlış taraf…$"
