LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Merhaba, merhaba!\n"
    .string "Ben İSİM DEĞERLENDİRİCİ'yim!\p"
    .string "POKéMON'larının takma adlarını\n"
    .string "değerlendirmemi ister misin?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Hangi POKéMON'un takma adını\n"
    .string "değerlendirmemi istersin?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, öyle mi?\n"
    .string "Bu oldukça iyi bir takma ad!\p"
    .string "Fakat, daha güzel bir isim\n"
    .string "koymamı ister misin?\p"
    .string "Ne dersin?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Peki, yeni takma adı ne olsun?\n"
    .string "Bunu söyle!$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Tamam! Bundan böyle, bu POKéMON\n"
    .string "{STR_VAR_1} olarak anılacak!\p"
    .string "Önceki isminden daha iyi!\n"
    .string "Ne kadar şanslısın!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Anladım.\n"
    .string "Tekrar gelmeyi unutma.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Tamam! Bundan böyle, bu POKéMON\n"
    .string "{STR_VAR_1} olarak anılacak!\p"
    .string "Öncekiyle aynı gibi görünse de,\n"
    .string "bu çok daha iyi!\p"
    .string "Ne kadar şanslısın!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, öyle mi?\n"
    .string "Bu gerçekten kusursuz bir isim!\p"
    .string "{STR_VAR_1}'e iyi bak!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Şimdi, şimdi.\n"
    .string "Bu sadece bir YUMURTA!$"
