RocketHideout_B3F_Text_Grunt1Intro::
    .string "ROKET TAKIMI işlerine\n"
    .string "karışmayı kes yoksa!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "Of!\n"
    .string "Yenildik!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "SILPH GÖZLÜK?\n"
    .string "Ah, patronun çaldığı\p"
    .string "o makine. Buralarda bir yerde.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "Yukarıdan senin gelmekte\n"
    .string "olduğun haberini almıştık!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "Ne?\n"
    .string "Yenildim mi? Hayır!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "İstediğin yere git!\p"
    .string "Ama asansörü ANAHTAR\n"
    .string "olmadan çalıştıramazsın.$"

