SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .string "POKéMON'ların büyüme hızları\n"
    .string "türden türe değişir.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .string "SILPH ŞTİ. herkesçe bilinir.\p"
    .string "Kendi şöhretinin kurbanı oldu\n"
    .string "ROKET TAKIMI'nı kendine çekti.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .string "Of…\n"
    .string "Ne güzel olurdu, değil mi?\p"
    .string "Eğer ELİT DÖRTLÜ gelse ve\n"
    .string "ROKET TAKIMI'nı yense?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .string "ROKET TAKIMI kaçtı!\n"
    .string "Güvenle dışarı çıkabiliriz!\l"
    .string "Harika!$"
