Route16_House_Text_FoundMySecretRetreat::
    .string "Aman Tanrım!\n"
    .string "Gizli sığınağımı bulmuşsun.\p"
    .string "Lütfen kimseye burada olduğumu\n"
    .string "söyleme. Bunu sana telafi edeceğim!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER}, kızdan\n"
    .string "HM02 aldı.$"

Route16_House_Text_ExplainHM02::
    .string "HM02, UÇ hareketidir.\n"
    .string "Çok kullanışlı bir hareket.\p"
    .string "Lütfen, bunu iyi değerlendir.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "Bunun için yerin yok.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"
