PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON KULESİ, ölen POKéMON'ların\n"
    .string "anısına inşa edildi.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Saygılarını sunmaya mı geldin?\p"
    .string "POKéMON seven yüreğine bereket,\n"
    .string "oğlum.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Saygılarını sunmaya mı geldin?\p"
    .string "POKéMON seven yüreğine bereket,\n"
    .string "kızım.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Sevgili CLEFAIRY'im için dua etmeye\n"
    .string "geldim.\p"
    .string "Hıçkıra hıçkıra ağlıyorum…\n"
    .string "Gözyaşlarım sel oldu aktı.$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Zavallı GROWLITHE'im…\n"
    .string "Neden öldün?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "Ben bir MEDYUM'um.\p"
    .string "Şeytanca ruhlar var.\n"
    .string "KULE'de onları hissedebiliyorum.$"
