FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "Biz BEKÇİ'ye “SLOWPOKE” lakabı\n"
    .string "taktık.\p"
    .string "Neden biliyor musun?\p"
    .string "Çünkü SLOWPOKE gibi boş\nbakışları var.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .string "BEKÇİ SLOWPOKE, POKéMON\n"
    .string "konusunda çok bilgili.\p"
    .string "Nadir, yok olmuş POKéMON\n"
    .string "fosillerine bile sahip.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "BEKÇİ SLOWPOKE içeri girdi ama\n"
    .string "onu hiç anlayamadım.\p"
    .string "Sanırım konuşma problemi var!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "BEKÇİ SLOWPOKE şu anda bir\n"
    .string "tanıtım kampanyası yürütüyor.\p"
    .string "SAFARİ BÖLGESİ'nin en uzak\n"
    .string "köşesine ulaşmaya çalış.\p"
    .string "Eğer başarırsan, çok kullanışlı\n"
    .string "bir ödül kazanacaksın.$"
