Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "POKéMON türleri birbirlerine\n"
    .string "karşı farklı eşleşmelere sahiptir.\p"
    .string "Her tür, bazılarına karşı üstündür\n"
    .string "ama bazı türlere karşı zayıftır.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "KÜLÇE tamamen işe yaramaz.\n"
    .string "Bunu 5000¥'ye sattım.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "LAVENDER KASABASI'nı hayaletlerin\n"
    .string "sardığını duydum.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "Oh… {PLAYER}!\n"
    .string "Seni arıyordum!\p"
    .string "PROF. OAK'ın sürekli\n"
    .string "YARDIMCI'larından biriyim.\p"
    .string "POKéDEX'in 20 türde tam veriye\n"
    .string "sahipse, PROF. OAK sana bir ödül\l"
    .string "vermemi istedi.\p"
    .string "Bana bu SABİTTAŞ'ı emanet\n"
    .string "etti.\p"
    .string "Öyleyse, {PLAYER}, sana sorayım.\p"
    .string "En az yirmi çeşit POKéMON\n"
    .string "verisi topladın mı?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "Harika! {STR_VAR_3} çeşit POKéMON\n"
    .string "yakaladın ya da sahip oldun!\p"
    .string "Tebrikler!\n"
    .string "İşte bu senin!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} yardımcısından SABİTTAŞ\n"
    .string "aldı.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "POKéMON'u evrimleştirmek onu\n"
    .string "POKéDEX'e ekler.\p"
    .string "Ancak bazen, bir POKéMON'un\n"
    .string "evrimleşmesini istemeyebilirsiniz.\p"
    .string "O zaman, o POKéMON'a SABİTTAŞ\n"
    .string "verin.\p"
    .string "PROFESÖR'e göre, bu evrimleşmeyi\n"
    .string "engelleyecektir.$"
