SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "POKéMON'la çok oyna ve uzun yaşa!\p"
    .string "Mesela AGATHA.\p"
    .string "ELİT DÖRTLÜ'nün en yaşlı üyesi\n"
    .string "olarak bir rekor kırdı.\p"
    .string "Bana daha büyük şeyler yapmam için\n"
    .string "motivasyon kaynağı oluyor.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "MEKTUP almalıyım ve ona bir\n"
    .string "yazıp göndermeliyim…$"
