CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Hey! {PLAYER}!\p"
    .string "Burada hâlâ zorlanıyor musun?\p"
    .string "Ben harika gidiyorum! Bir sürü\n"
    .string "akıllı ve güçlü POKéMON yakaladım!\p"
    .string "Bakalım sen neler yakaladın,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Ağır ol!\l"
    .string "Zaten sen kazandın!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, bir şey\n"
    .string "söyleyeyim mi?\p"
    .string "BILL'in yanına gittim ve bana\n" 
    .string "nadir POKéMON'larını gösterdi.\p"
    .string "Bu, POKéDEX'ime bir sürü\n" 
    .string "sayfa ekledi!\p"
    .string "Çünkü BILL, dünya çapında ünlü\n"
    .string "bir POKéMANYAK.\p"
    .string "Ayrıca, PC'deki\n"
    .string "POKéMON Depolama Sistemini de\l"
    .string "icat etti.\p"
    .string "Sen de sistemini kullandığın için\n"
    .string "ona teşekkür etmelisin.\p"
    .string "Tamam, gitsem iyi olur!\n"
    .string "Hadi bay bay!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Ah evet, doğru.\p"
    .string "Senin için üzgünüm. Gerçekten.\n"
    .string "Her zaman arkamdan geliyorsun.\p"
    .string "İşte sana küçük bir hediye,\n"
    .string "bir iyilik olarak.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "Senin gibi bir dedikoducu için…\n"
    .string "Bu şey harika.\p"
    .string "Ben başkalarını umursamadığım\n"
    .string "için buna ihtiyacım yok.\p"
    .string "Tamam, bu sefer gerçekten gidiyorum.\n"
    .string "Görüşürüz!$"

@ RB translation: "Heh! Benim dehamın karşısında hiç şansın yok!$"
CeruleanCity_Text_RivalVictory::
    .string "Bana bak!\n"
    .string "Ben bir dahiyim!$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Uzak dur!\n"
    .string "Burası senin arazin değil!\p"
    .string "…Ne?\n"
    .string "Ben mi?\p"
    .string "Ben masum bir vatandaşım!\n"
    .string "Bana inanmıyor musun?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Dur! Pes ettim!\n"
    .string "Sessizce gideceğim!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Tamam.\n"
    .string "Çaldığım TM'yi geri vereceğim.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER}, GRUNT'tan TM28'i\ngeri aldı.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "Ben en iyisi gideyim!\n"
    .string "Bay bay!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Bunun için yer aç!\n"
    .string "Gitmem için bunu sana vermem lazım!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "Sen de mi bir EĞİTMEN'sin?\p"
    .string "Toplamak, savaşmak…\n"
    .string "Zor bir yaşam, değil mi?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Küçük ağaçları KESEBİLECEĞİNİ\n"
    .string "biliyor muydun?\p"
    .string "Mağazanın önündeki küçük çalıyı\n"
    .string "bile kesebilirsin.\p"
    .string "Sanırım geçmenin başka bir\nyolu daha var…$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Eğer orada SLOWBRO olmasaydı,\n"
    .string "küçük ağacı kesebilirdin.\p"
    .string "Böylece, diğer tarafa geçebilirdin.\p"
    .string "Sanırım geçmenin başka bir\n"
    .string "yolu daha var…$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "Bir POKéMON ansiklopedisi mi\n"
    .string "hazırlıyorsun? Bu eğlenceliymiş.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "Buradaki insanlar soyuldu.\p"
    .string "Bu iğrenç suçun arkasında\n"
    .string "ROKET TAKIMI'nın olduğu çok açık!\p"
    .string "POLİS bile onlarla başa çıkamıyor!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Tamam! SLOWBRO!\n"
    .string "SONICBOOM kullan!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "Hadi, SLOWBRO, dikkat et!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, vur!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "Hayır!\n"
    .string "Yeniden mahvettin!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO, geri çekil!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "Hayır! Bu yanlış!\n"
    .string "POKéMON'ları kontrol etmek zor!\p"
    .string "POKéMON'unun itaatkârlığı senin\n"
    .string "EĞİTMEN becerilerine bağlı.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO uykuya daldı…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO aylak aylak geziyor…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO döndü…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO emirleri umursamadı…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Parlak kırmızı bir\n"
    .string "bisiklet istiyorum.\p"
    .string "Evde duracak, böylece\n"
    .string "kirlenmeyecek.$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "Burası CERULEAN MAĞARASI.\p"
    .string "İçeride korkunç derecede\n"
    .string "güçlü POKéMON'lar yaşıyor.\p"
    .string "İçeri girmek için çok özel bir\n"
    .string "EĞİTMEN olman gerekiyor.\p"
    .string "İlk olarak, POKéMON LİGİ şampiyonu\n"
    .string "olacak kadar güçlü olmalısın.\p"
    .string "Ve, büyük bir başarı\n"
    .string "elde etmiş olmalısın.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN ŞEHRİ\n"
    .string "Onu Çeviren Gizemli, Mavi Bir Aura$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "EĞİTMEN İPUCU\p"
    .string "Bir POKéMON'a eşya verebilirsin.\p"
    .string "Bazı eşyalar, savaş sırasında\n"
    .string "POKéMON tarafından kullanılabilir.$"

CeruleanCity_Text_BikeShopSign::
    .string "Çimleri ve mağaraları kolayca geç!\n"
    .string "BİSİKLET MAĞAZASI$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN ŞEHRİ POKéMON SALONU\n"
    .string "LİDER: MISTY\l"
    .string "Maskülen Denizkızı!$"
