CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "Merhaba!\n"
    .string "Mağazamıza hoş geldiniz.\p"
    .string "Sizin için mükemmel bir\n"
    .string "BİSİKLET'imiz var!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "Üzgünüm!\n"
    .string "Onu alacak paranız yok!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "Aa, bu…\p"
    .string "Bir BİSİKLET KUPONU!\p"
    .string "Tamam!\n"
    .string "Bunu alabilirsin!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} BİSİKLET KUPONU vererek\n"
    .string "yeni bir BİSİKLET aldı.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "Teşekkürler!\n"
    .string "Yine bekleriz!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "Yeni BİSİKLETİ nasıl buldunuz?\n"
    .string "Kullanımı hoşunuza gitti mi?\p"
    .string "Onu sürmek için BİSİKLET YOLU'na\n"
    .string "gidebilir ve hatta mağaralarda bile\l"
    .string "sürebilirsiniz!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "BİSİKLET için yer açın lütfen!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "Sade bir şehir bisikleti\n"
    .string "benim için yeterli.\p"
    .string "Sonuçta, dağ bisikletine bir\n"
    .string "sepet takamazsın.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "Bu bisikletler çok havalı ama\n"
    .string "çok pahalılar!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "Vay canına.\n"
    .string "BİSİKLETİN gerçekten çok havalı!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "Parlak, yeni bir BİSİKLET!$"
