FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
.string "Burada kafese kilitli çok sayıda\n"
.string "POKéMON var…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
.string "Kafes kapısı açık.\n"
.string "POKéMON'ların kaçmış gibi görünüyor.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
.string "Burada ROKET TAKIMI'nın DEPOSU\n"
.string "olduğunu biliyor musunuz?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
.string "Ne yaptığını sanıyorsun?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
.string "ROKET TAKIMI dağıldı mı?\n"
.string "Hangi gezegenden geldin sen?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
.string "Oh, şimdi POKéMON'ların\n"
.string "güçlü görünüyor.\p"
.string "Onları satmaya mı geldin?\p"
.string "Oh?\n"
.string "Savaşmak mı istiyorsun?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
.string "Ama...\n"
.string "Çok fazla!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
.string "Size iyi bir fiyat verebiliriz.\n"
.string "Bize POKéMON'larınızı satın!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
.string "Diğerlerinden senin hakkında\nhaber aldım.\p"
.string "Ama senin gibi bir çocuğun\n"
.string "PATRON GIOVANNI'yi\l"
.string "tanıma ihtimali yok!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
.string "Gülme…\n"
.string "Sakın gülme…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
.string "Yetişkinlerin işlerine karışma,\n"
.string "küçük serseri!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
.string "Doğru ya da yanlış yaptığımı\n"
.string "bilmem veya umursamam.\p"
.string "Sadece GIOVANNI'ye güveniyorum\n"
.string "ve bana söylenenleri yapıyorum.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
.string "Ben…\n"
.string "Parçalandım…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
.string "İnançlarınıza ve ahlaki\n"
.string "değerlerinize göre davranıyorsunuz\p"
.string "Şimdi anlıyorum…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
.string "Oradan geri dönebileceğiniz bir\n"
.string "yol açtım.\p"
.string "İlerideki zorluklara hazırlanmak\n"
.string "için dinlenmeye ve\l"
.string "tazelenmeye ne dersin?\p"
.string "Sonraki YÖNETİCİ, benden çok daha\n"
.string "üstün bir EĞİTMEN.\p"
.string "Kendini zorlu bir mücadele\n"
.string "için hazırla.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
.string "Kahramanlık numaranı yeterince\n"
.string "oynadın, çocuk.\p"
.string "ROKET TAKIMI'nın dağıldığı\n"
.string "yalanını yaymaya çalışıyorsun…\p"
.string "Bu, saflarımızı karıştırmak\n"
.string "için açık bir girişim.\p"
.string "Ne yazık ki bir çocuğun\n"
.string "yalanlarına kanacak kadar\l"
.string "cahil değiliz!\p"
.string "Ve şimdi, öfkeli bir yetişkinin ne\n"
.string "kadar korkutucu olabileceğini\l"
.string "sana göstereceğim!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
.string "Urgh…\n"
.string "Çok güçlüsün…\p"
.string "…\n"
.string "O, GIOVANNI'nin rozeti!\p"
.string "O zaman doğru mu?\n"
.string "ROKET TAKIMI gerçekten dağıldı mı?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
.string "Bu DEPO'yu terk edeceğiz…\p"
.string "Ama bunun bittiğini düşünme.\n"
.string "Bunu sona erdirmeyeceğim.\p"
.string "GIOVANNI'yi bulacağım.\p"
.string "Ve ROKET TAKIMI'nı yeniden\n"
.string "kuracağım! Bunu yapacağım…\p"
.string "O zamana kadar, hoşça kal!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
.string "Rapor, grafikler ve metinlerle\n"
.string "birlikte PC ekranında.\p"
.string "“Manyetik Dalgaların POKéMON\n"
.string "Evrimi Üzerindeki Etkisi”…\p"
.string "… … … … … …\p"
.string "Anlamak çok zor…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
.string "Neredeyse SAFİR'i yüksek\n"
.string "fiyata satmayı başarmıştım…\p"
.string "Sonra sen geldin ve her şeyi\n"
.string "berbat ettin!\p"
.string "Fufu… Fufufufu…\n"
.string "Affedilmeyecek bir hata yaptın!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
.string "Aaaah! Harika!\n"
.string "Harika!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
.string "Eğer satamazsam, değersiz!\n"
.string "Al, al!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
.string "Şimdi ne istiyorsun?\n"
.string "Defol, beni yalnız bırak.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
.string "Ne, yine sen mi?\p"
.string "Sen… Sen GIOVANNI'nin çocuğu\n"
.string "değilsin, değil mi?\p"
.string "Hayır, bu doğru olamaz!\n"
.string "GIOVANNI'nin çocuğu kızıl saçlı.\p"
.string "Beni rahatsız edecek hiçbir neden\n"
.string "yok. Beni yalnız bırak!$"
