#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Düşmanı ön\nayaklarıyla ya da\nkuyruğuyla döver.");
const u8 gMoveDescription_KarateChop[] = _("Yüksek kritik\noranına sahip bir\nsaldırı.");
const u8 gMoveDescription_DoubleSlap[] = _("Düşmana 2 ila 5\nkez tokat atar.");
const u8 gMoveDescription_CometPunch[] = _("Düşmana 2 ila 5\nkez tekrar tekrar\nyumruk atar.");
const u8 gMoveDescription_MegaPunch[] = _("İnanılmaz bir\ngüçle atılan güçlü\nbir yumruk.");
const u8 gMoveDescription_PayDay[] = _("Düşmana para\nfırlatır. Para\ndaha sonra alınır.");
const u8 gMoveDescription_FirePunch[] = _("Düşmanı\nyakabilecek ateşli\nbir yumruk.");
const u8 gMoveDescription_IcePunch[] = _("Düşmanı\ndondurabilecek buz\ngibi bir yumruk.");
const u8 gMoveDescription_ThunderPunch[] = _("Düşmanı felç\nedebilecek\nelektrikli bir\nyumruk.");
const u8 gMoveDescription_Scratch[] = _("Düşmanı keskin\npençeleriyle\ntırmalar.");
const u8 gMoveDescription_ViceGrip[] = _("Düşmanı büyük ve\ngüçlü kıskaçlarla\nkavrar.");
const u8 gMoveDescription_Guillotine[] = _("Bayıltabilen bir\nkıskaç saldırısı.");
const u8 gMoveDescription_RazorWind[] = _("Düşmanı 2. turda\nvuran 2 turluk bir\nhamle.");
const u8 gMoveDescription_SwordsDance[] = _("SALDIRIYI çokça\nyükselten bir\ndövüş dansı.");
const u8 gMoveDescription_Cut[] = _("Düşmanı keskin\ntırpanlarla,\npençelerle vb.\nkeser.");
const u8 gMoveDescription_Gust[] = _("Düşmana\nkanatlarından\nçıkan bir rüzgarla\nvurur.");
const u8 gMoveDescription_WingAttack[] = _("Düşmana\nkanatlarını açarak\nsaldırır.");
const u8 gMoveDescription_Whirlwind[] = _("Düşmanı rüzgarla\nsavurur ve savaşı\nbitirir.");
const u8 gMoveDescription_Fly[] = _("İlk dönüşte uçar,\nsonraki dönüşte\nvurur.");
const u8 gMoveDescription_Bind[] = _("Düşmanı 2 ila 5\ntur boyunca bağlar\nve sıkıştırır.");
const u8 gMoveDescription_Slam[] = _("Düşmanı uzun bir\nkuyruk, asma vb.\nile vurur.");
const u8 gMoveDescription_VineWhip[] = _("Düşmana ince,\nkırbaç gibi\nsarmaşıklarla\nvurur.");
const u8 gMoveDescription_Stomp[] = _("Düşmanı büyük bir\nayakla ezer.\nDüşman ürkebilir.");
const u8 gMoveDescription_DoubleKick[] = _("Düşmana iki kez\nvuran çift tekme\nsaldırısı.");
const u8 gMoveDescription_MegaKick[] = _("Yoğun kuvvete\nsahip son derece\ngüçlü bir tekme.");
const u8 gMoveDescription_JumpKick[] = _("Güçlü bir zıplama\ntekmesi.\nIskalayabilir.");
const u8 gMoveDescription_RollingKick[] = _("Hızlı bir dönüşle\natılan hızlı bir\ntekme.");
const u8 gMoveDescription_SandAttack[] = _("Düşmanın yüzüne\nkum fırlatır ve\nkesinliği azaltır.");
const u8 gMoveDescription_Headbutt[] = _("İrkilmeye neden\nolabilecek bir\nvuruş saldırısı.");
const u8 gMoveDescription_HornAttack[] = _("Düşmana keskin\nboynuzlarla vurur.");
const u8 gMoveDescription_FuryAttack[] = _("Düşmana keskin\nboynuzlarla 2 ila\n5 kez vurur, vb.");
const u8 gMoveDescription_HornDrill[] = _("Tek vuruşta nakavt\nedebilen bir\nboynuz saldırısı.");
const u8 gMoveDescription_Tackle[] = _("Düşmana tüm vücudu\nkullanarak\nsaldırır.");
const u8 gMoveDescription_BodySlam[] = _("Felce neden\nolabilecek bir tüm\nvücut vuruşu.");
const u8 gMoveDescription_Wrap[] = _("Düşmanı\nsarmaşıklar ile 2\nila 5 kez\nsıkıştırır.");
const u8 gMoveDescription_TakeDown[] = _("Kullanıcıya da\nzarar veren bir\nhücum saldırısı.");
const u8 gMoveDescription_Thrash[] = _("Kullanıcı kafasını\nkarıştıran 2 ila 3\nturluk bir\nsaldırı.");
const u8 gMoveDescription_DoubleEdge[] = _("Kullanıcıya da\nzarar veren,\nriskli bir\nsaldırı.");
const u8 gMoveDescription_TailWhip[] = _("Düşmanın\nSAVUNMASINI\ndüşürmek için\nkuyruk sallar.");
const u8 gMoveDescription_PoisonSting[] = _("Zehirleyebilecek\ndikenler ile\nzehirli bir\nsaldırı.");
const u8 gMoveDescription_Twineedle[] = _("Ön ayaklardaki\niğneler düşmana\niki kez vurur.");
const u8 gMoveDescription_PinMissile[] = _("Keskin iğneler 2\nila 5 kez vurulmak\nüzere ateşlenir.");
const u8 gMoveDescription_Leer[] = _("SAVUNMAYI düşürmek\niçin bir bakışla\ndüşmanı korkutur.");
const u8 gMoveDescription_Bite[] = _("Vahşi dişlerle\nısırır. İrkilmeye\nneden olabilir.");
const u8 gMoveDescription_Growl[] = _("Düşman SALDIRISI\nazaltmak için\nsevimli şekilde\nhırlar.");
const u8 gMoveDescription_Roar[] = _("Düşmanın savaşı\nbitirmek için\nkaçmasını sağlar.");
const u8 gMoveDescription_Sing[] = _("Sakinleştirici\nşarkısı, düşmanı\nuykuya daldırır.");
const u8 gMoveDescription_Supersonic[] = _("Kafa\nkarıştırabilecek\ntuhaf ses\ndalgaları yayar.");
const u8 gMoveDescription_SonicBoom[] = _("Her zaman 20 CAN\nhasar veren şok\ndalgaları\nfırlatır.");
const u8 gMoveDescription_Disable[] = _("Düşman\nsaldırılarından\nbirini psişik\nolarak engeller.");
const u8 gMoveDescription_Acid[] = _("Deriyi eriten bir\nasit püskürtür.\nSVN düşürebilir.");
const u8 gMoveDescription_Ember[] = _("Yanıklara yol\naçabilen zayıf bir\nateş saldırısı.");
const u8 gMoveDescription_Flamethrower[] = _("Yanıklara neden\nolabilen güçlü bir\nateş saldırısı.");
const u8 gMoveDescription_Mist[] = _("Yeteneklerin\nazalmasını\ndurduran bir sis\nyaratır.");
const u8 gMoveDescription_WaterGun[] = _("Düşmana saldırmak\niçin su fışkırtır.");
const u8 gMoveDescription_HydroPump[] = _("Düşmana saldırmak\niçin yüksek güçte\nsu püskürtür.");
const u8 gMoveDescription_Surf[] = _("Büyük bir dalga\nyaratır, sonra\ndüşman üzerine\nçökertir.");
const u8 gMoveDescription_IceBeam[] = _("Düşmanı\ndondurabilecek\nbuzlu bir ışınla\npatlatır.");
const u8 gMoveDescription_Blizzard[] = _("Düşmana onu\ndondurabilecek\nbuzlu bir fırtına\nile vurur.");
const u8 gMoveDescription_Psybeam[] = _("Kafa\nkarıştırabilen\nözel bir ışın\nyayar.");
const u8 gMoveDescription_BubbleBeam[] = _("HIZI düşürebilen\nbaloncuk\npüskürtür.");
const u8 gMoveDescription_AuroraBeam[] = _("SALDIRI\nazaltabilen\ngökkuşağı renginde\nbir ışın fırlatır.");
const u8 gMoveDescription_HyperBeam[] = _("Güçlüdür ama bir\nsonraki turda\nhareketsiz\nbırakır.");
const u8 gMoveDescription_Peck[] = _("Düşmana saplanan\nbir gaga ile\nsaldırır.");
const u8 gMoveDescription_DrillPeck[] = _("Gaga, matkap\ngörevi görerek\ndüşmana saplanır.");
const u8 gMoveDescription_Submission[] = _("Kullanıcısına da\nzarar veren bir\nvücut darbesi.");
const u8 gMoveDescription_LowKick[] = _("Düşman ne kadar\nağırsa o kadar\nhasar veren bir\nsaldırı.");
const u8 gMoveDescription_Counter[] = _("Gelen fiziksel\nsaldırılara iki\nkat güçle karşılık\nverir.");
const u8 gMoveDescription_SeismicToss[] = _("Kullanıcının\nseviyesine eşit\nhasar verir.");
const u8 gMoveDescription_Strength[] = _("Muazzam bir güç\noluşturur, sonra\ndüşmanı çarpar.");
const u8 gMoveDescription_Absorb[] = _("Verilen hasarın\nyarısını emen bir\nsaldırı.");
const u8 gMoveDescription_MegaDrain[] = _("Verilen hasarın\nyarısını emen bir\nsaldırı.");
const u8 gMoveDescription_LeechSeed[] = _("Her turda can\nçalmak için\ndüşmana bir tohum\neker.");
const u8 gMoveDescription_Growth[] = _("Vücudu büyümeye\nzorlar ve ÖZ. SLD\nyükseltir.");
const u8 gMoveDescription_RazorLeaf[] = _("Düşmanı\nyapraklarla keser.\nYüksek kritik\nvuruş oranı var.");
const u8 gMoveDescription_SolarBeam[] = _("Bir turda ışığı\nemer, sonraki\nturda saldırır.");
const u8 gMoveDescription_PoisonPowder[] = _("Düşmanı\nzehirleyebilecek\nzehirli bir toz\nsaçar.");
const u8 gMoveDescription_StunSpore[] = _("Düşmanı felç\nedebilecek bir toz\nsaçar.");
const u8 gMoveDescription_SleepPowder[] = _("Düşmanın uyumasına\nneden olabilecek\nbir toz saçar.");
const u8 gMoveDescription_PetalDance[] = _("Kafa karıştıran 2\nila 3 turluk bir\nsaldırı.");
const u8 gMoveDescription_StringShot[] = _("Hızını azaltmak\niçin düşmanı iple\nbağlar.");
const u8 gMoveDescription_DragonRage[] = _("Her zaman 40 can\nhasar veren şok\ndalgaları\nfırlatır.");
const u8 gMoveDescription_FireSpin[] = _("Düşmanı 2 ila 5\ntur boyunca ateş\nçemberi içine\nhapseder.");
const u8 gMoveDescription_ThunderShock[] = _("Düşmanı felç\nedebilen bir\nelektrik\nsaldırısı.");
const u8 gMoveDescription_Thunderbolt[] = _("Düşmanı felç\nedebilen güçlü bir\nelektrik\nsaldırısı.");
const u8 gMoveDescription_ThunderWave[] = _("Düşmanı felç eden\nzayıf bir elektrik\nsarsıntısı.");
const u8 gMoveDescription_Thunder[] = _("Felce neden\nolabilecek bir\nyıldırım\nsaldırısı.");
const u8 gMoveDescription_RockThrow[] = _("Düşmana vurmak\niçin küçük taşlar\nfırlatır.");
const u8 gMoveDescription_Earthquake[] = _("Güçlü bir\nsarsıntı, ancak\nhavadakilere\nhiçbir etkisi yok.");
const u8 gMoveDescription_Fissure[] = _("Düşmanı yarık\niçine düşüren tek\nvuruşluk nakavt\nhareketi.");
const u8 gMoveDescription_Dig[] = _("İlk turda\nyeraltını kazar ve\nsonraki turda\nsaldırır.");
const u8 gMoveDescription_Toxic[] = _("Düşmanı zararlı\nbir toksinle\nzehirler.");
const u8 gMoveDescription_Confusion[] = _("Kafa karışıklığına\nneden olabilecek\nbir saldırı.");
const u8 gMoveDescription_Psychic[] = _("ÖZ. SVN'yı\ndüşürebilen güçlü\nbir psişik\nsaldırı.");
const u8 gMoveDescription_Hypnosis[] = _("Uykuya neden\nolabilecek\nhipnotize edici\nbir hareket.");
const u8 gMoveDescription_Meditate[] = _("SALDIRI'yı\nartırmak için\nmeditasyon yapar.");
const u8 gMoveDescription_Agility[] = _("HIZI çokça\nartırmak için\nvücudu rahatlatır.");
const u8 gMoveDescription_QuickAttack[] = _("Her zaman ilk\nvuruşu yapan hızlı\nbir saldırı.");
const u8 gMoveDescription_Rage[] = _("Her vurulduğunda\nkullananın SALDIRI\ngücünü artırır.");
const u8 gMoveDescription_Teleport[] = _("Savaştan anında\nkaçmak için psişik\nbir hareket.");
const u8 gMoveDescription_NightShade[] = _("Kullanıcının\nseviyesine eşit\nhasar verir.");
const u8 gMoveDescription_Mimic[] = _("Savaş sırasında\ndüşman hareketini\nkopyalar.");
const u8 gMoveDescription_Screech[] = _("Düşmanın\nSAVUNMASINI\nazaltan bir çığlık\nyayar.");
const u8 gMoveDescription_DoubleTeam[] = _("Kesinliği artırmak\niçin hayali\nkopyalar yaratır.");
const u8 gMoveDescription_Recover[] = _("Kullananın maks.\ncanının yarısını\niyileştirir.");
const u8 gMoveDescription_Harden[] = _("Kasları\nsertleştirerek\nSAVUNMA artırır.");
const u8 gMoveDescription_Minimize[] = _("Kaçış kabiliyetini\nartırmak için\nkullanıcıyı\nküçültür.");
const u8 gMoveDescription_Smokescreen[] = _("Duman, mürekkep\nvb. ile düşmanın\nisabetini düşürür.");
const u8 gMoveDescription_ConfuseRay[] = _("Düşman kafasını\nkarıştıran bir\nışın.");
const u8 gMoveDescription_Withdraw[] = _("SAVUNMAYI artırmak\niçin vücudu kabuk\niçine çeker.");
const u8 gMoveDescription_DefenseCurl[] = _("Zayıflığını\ngizlemek için SVN\nartırır ve\nbüzülür.");
const u8 gMoveDescription_Barrier[] = _("SAVUNMAYI çokça\nyükselten bir\nbariyer oluşturur.");
const u8 gMoveDescription_LightScreen[] = _("ÖZ. SLD'yı düşüren\nbir ışık duvarı\noluşturur.");
const u8 gMoveDescription_Haze[] = _("Tüm durum\ndeğişikliklerini\nkaldıran bir pus\nyaratır.");
const u8 gMoveDescription_Reflect[] = _("Fiziksel\nsaldırıları\nzayıflatan duvar\nyaratır.");
const u8 gMoveDescription_FocusEnergy[] = _("Kritik oranını\nyükseltmek için\nodaklanır.");
const u8 gMoveDescription_Bide[] = _("İsabeti iki kat\nartırmak için 2\ntur dayanır.");
const u8 gMoveDescription_Metronome[] = _("Parmak sallayarak\nrastgele bir\nsaldırı kullanır.");
const u8 gMoveDescription_MirrorMove[] = _("Düşmanın\nsaldırısını aynı\nsaldırı ile\nkarşılar.");
const u8 gMoveDescription_SelfDestruct[] = _("Ağır hasar verir\nama kullanıcıyı\nbayıltır.");
const u8 gMoveDescription_EggBomb[] = _("Düşmana zorla bir\nyumurta\nfırlatılır.");
const u8 gMoveDescription_Lick[] = _("Uzun bir dille\nısırır. Felç\nedebilir.");
const u8 gMoveDescription_Smog[] = _("Zehirleyebilecek\nbir egzoz gazı\nsaldırısı.");
const u8 gMoveDescription_Sludge[] = _("Çamur fırlatır.\nAyrıca\nzehirleyebilir.");
const u8 gMoveDescription_BoneClub[] = _("Düşmana bir\nkemikle vurur.\nÜrkütebilir.");
const u8 gMoveDescription_FireBlast[] = _("Vurduğu her şeyi\nyakar. Yanıklara\nneden olabilir.");
const u8 gMoveDescription_Waterfall[] = _("Şelalelere\ntırmanmak için\ndüşmana hızla\nhücum eder.");
const u8 gMoveDescription_Clamp[] = _("Düşmanı 2 ila 5\ntur boyunca\nsıkıştırır.");
const u8 gMoveDescription_Swift[] = _("Asla ıskalamayan\nyıldız ışınları\nyağdırır.");
const u8 gMoveDescription_SkullBash[] = _("Kafayı içeri\nsokar, sonra bir\nsonraki turda\nsaldırır.");
const u8 gMoveDescription_SpikeCannon[] = _("2 ila 5 kez vuran\nkeskin sivri uçlar\nfırlatır.");
const u8 gMoveDescription_Constrict[] = _("Acı vermek için\ndaraltır. Hızı\ndüşürebilir.");
const u8 gMoveDescription_Amnesia[] = _("Hafızasından bir\nşey siler ve ÖZ.\nSVN yükseltir.");
const u8 gMoveDescription_Kinesis[] = _("Dikkat dağıtarak\nisabet oranını\ndüşürebilir.");
const u8 gMoveDescription_SoftBoiled[] = _("Maksimum canının\nyarısına kadar can\niyileştirir.");
const u8 gMoveDescription_HiJumpKick[] = _("Zıplayan bir diz\ntekmesi. Iskalarsa\ngeri teper.");
const u8 gMoveDescription_Glare[] = _("Düşmanı korkutur\nve felce uğratır.");
const u8 gMoveDescription_DreamEater[] = _("Uyuyan bir düşmana\nverilen hasarın\nyarısını alır.");
const u8 gMoveDescription_PoisonGas[] = _("Düşmanı\nzehirleyebilecek\nzehirli bir gazla\nsarar.");
const u8 gMoveDescription_Barrage[] = _("Düşmana 2 ila 5\nkez yuvarlak\nnesneler fırlatır.");
const u8 gMoveDescription_LeechLife[] = _("Verilen hasarın\nyarısını çalan bir\nsaldırı.");
const u8 gMoveDescription_LovelyKiss[] = _("Uykuyu tetikleyen\nkorkunç bir öpücük\nister.");
const u8 gMoveDescription_SkyAttack[] = _("Zayıf noktaları\naraştırır, sonraki\nturda saldırır.");
const u8 gMoveDescription_Transform[] = _("Düşmanın\nhücrelerini\nkopyalar ve ona\ndönüşür.");
const u8 gMoveDescription_Bubble[] = _("Baloncuk fırlatan\nbir saldırı. HIZ\ndüşürebilir.");
const u8 gMoveDescription_DizzyPunch[] = _("Kafa\nkarıştırabilen\nritmik bir yumruk.");
const u8 gMoveDescription_Spore[] = _("Her zaman uykuya\nneden olan bir\nspor bulutu saçar.");
const u8 gMoveDescription_Flash[] = _("İsabeti kesen\ngüçlü bir ışık\npatlaması yayar.");
const u8 gMoveDescription_Psywave[] = _("Değişken\nyoğunlukta psişik\nbir dalga ile\nsaldırır.");
const u8 gMoveDescription_Splash[] = _("Bu sadece bir\nsıçrama... Hiçbir\netkisi yok.");
const u8 gMoveDescription_AcidArmor[] = _("Kullanıcının\nvücudunu\nsıvılaştırarak SVN\nartırır.");
const u8 gMoveDescription_Crabhammer[] = _("Kıskaçlı çekiç.\nYüksek kritik\noranına sahiptir.");
const u8 gMoveDescription_Explosion[] = _("Ağır hasar verir\nama kullanıcıyı\nbayıltır.");
const u8 gMoveDescription_FurySwipes[] = _("Düşmanı keskin\npençeler ile 2-5\nkez tırmıklar.");
const u8 gMoveDescription_Bonemerang[] = _("İki kez vuran bir\nkemik bumerangı\nfırlatır.");
const u8 gMoveDescription_Rest[] = _("Kullanıcı 2 tur\nboyunca uyur, canı\nyenilenir.");
const u8 gMoveDescription_RockSlide[] = _("Büyük kayalar\nfırlatılır.\nİrkilmeye neden\nolabilir.");
const u8 gMoveDescription_HyperFang[] = _("Keskin dişlerle\nsaldırır.\nİrkilmeye neden\nolabilir.");
const u8 gMoveDescription_Sharpen[] = _("Poligon sayısını\nazaltır ve\nSALDIRIYI artırır.");
const u8 gMoveDescription_Conversion[] = _("Kullanıcının\ntürünü bilinen bir\nsaldırının türü\nyapar.");
const u8 gMoveDescription_TriAttack[] = _("Aynı anda üç tür\nışın ateşler.");
const u8 gMoveDescription_SuperFang[] = _("Keskin dişlerle\nsaldırır ve\ndüşmanın canını\nyarılar.");
const u8 gMoveDescription_Slash[] = _("Pençelerle keser.\nYüksek kritik\noranına sahiptir.");
const u8 gMoveDescription_Substitute[] = _("Kullananın maks.\ncanının 1/4'ü ile\nyem oluşturur.");
const u8 gMoveDescription_Struggle[] = _("Sadece tüm PP'ler\nbitmişse\nkullanılabilir.");
const u8 gMoveDescription_Sketch[] = _("Düşmanın son\nhamlesini kalıcı\nolarak kopyalar.");
const u8 gMoveDescription_TripleKick[] = _("Düşmanı artan bir\nşiddetle 3 kez\ntekmeler.");
const u8 gMoveDescription_Thief[] = _("Saldırırken,\ndüşmanın elindeki\neşyayı çalabilir.");
const u8 gMoveDescription_SpiderWeb[] = _("Düşmanın kaçmasını\nengeller.");
const u8 gMoveDescription_MindReader[] = _("Bir sonraki\nsaldırının\nisabetini artırır.");
const u8 gMoveDescription_Nightmare[] = _("Her tur uyuyan bir\ndüşmana 1/4 hasar\nverir.");
const u8 gMoveDescription_FlameWheel[] = _("Yanıklara neden\nolabilen ateşli\nbir saldırı.");
const u8 gMoveDescription_Snore[] = _("Yalnız uykuda\nkullanılabilen\nyüksek sesli bir\nsaldırı.");
const u8 gMoveDescription_Curse[] = _("Hayaletler için\nfarklı işlev gören\nbir hareket.");
const u8 gMoveDescription_Flail[] = _("Kullanıcının canı\nazaldığında gücü\nartar.");
const u8 gMoveDescription_Conversion2[] = _("Kullanıcıyı son\nsaldırının türüne\ndynklılığını\nartırır.");
const u8 gMoveDescription_Aeroblast[] = _("Güçlü bir patlama\nyaratır. Kritik\noranı yüksektir.");
const u8 gMoveDescription_CottonSpore[] = _("Sporlar düşmana\nyapışarak HIZI\nçokça azaltır.");
const u8 gMoveDescription_Reversal[] = _("Kullanıcının canı\nazaldığında hasar\nartar.");
const u8 gMoveDescription_Spite[] = _("Düşmanın son\nhamlesinin PP'sini\nçokça keser.");
const u8 gMoveDescription_PowderSnow[] = _("Düşmanı karlı bir\nrüzgarla savurur.\nDondurabilir.");
const u8 gMoveDescription_Protect[] = _("Saldırıdan kaçar,\nancak üst üste\ntutmayabilir.");
const u8 gMoveDescription_MachPunch[] = _("Saldırı önceliği\nolan bir yumruk\nsaldırısı.");
const u8 gMoveDescription_ScaryFace[] = _("HIZI yüksek bir\nşekilde azaltır.");
const u8 gMoveDescription_FaintAttack[] = _("Düşmanı yakınına\nçeker, sonra\nhatasız vurur.");
const u8 gMoveDescription_SweetKiss[] = _("Sevimli bir\nbakışla öpücük\nister. Kafa\nkarıştırabilir.");
const u8 gMoveDescription_BellyDrum[] = _("Canı feda ederken\nSLD çokça\nyükseltir.");
const u8 gMoveDescription_SludgeBomb[] = _("Hasar vermek için\nçamur fırlatır.\nZehirleyebilir.");
const u8 gMoveDescription_MudSlap[] = _("Çamur fırlatarak\ndüşman isabeti\ndüşürülür.");
const u8 gMoveDescription_Octazooka[] = _("İsabeti düşürmek\niçin mürekkep\nateşler.");
const u8 gMoveDescription_Spikes[] = _("Düşmana zarar\nveren sivri uçları\ndevreye sokar.");
const u8 gMoveDescription_ZapCannon[] = _("Oldukça güçlüdür\nve felç eder.");
const u8 gMoveDescription_Foresight[] = _("İsabet düşürme\netkilerini keser.");
const u8 gMoveDescription_DestinyBond[] = _("Kullanıcı\nbayılırsa, düşman\nda bayılır.");
const u8 gMoveDescription_PerishSong[] = _("Bu şarkıyı duyan\nPOKéMON 3 tur\niçinde bayılır.");
const u8 gMoveDescription_IcyWind[] = _("Düşmanın HIZINI\ndüşüren korkunç\nbir saldırı.");
const u8 gMoveDescription_Detect[] = _("Saldırıdan kaçar,\nancak üst üste\ntutmayabilir.");
const u8 gMoveDescription_BoneRush[] = _("Elindeki kemikle\ndüşmanına 2 ila 5\nkez vurur.");
const u8 gMoveDescription_LockOn[] = _("Bir sonraki\nhamlenin isabet\netmesi için\nkilitlenir.");
const u8 gMoveDescription_Outrage[] = _("Kullananın kafa\nkarıştıran 2-3\nturluk saldırı.");
const u8 gMoveDescription_Sandstorm[] = _("Birkaç tur boyunca\nsüren kum\nfırtınası\nBaşlatır.");
const u8 gMoveDescription_GigaDrain[] = _("Verilen hasarın\nyarısını çalan bir\nsaldırı.");
const u8 gMoveDescription_Endure[] = _("En az 1 can\nbırakarak 1 tur\nsaldırılara\ndayanır.");
const u8 gMoveDescription_Charm[] = _("Düşmanı büyüler ve\nSLD. çokça\nazaltır.");
const u8 gMoveDescription_Rollout[] = _("Yoğunluğu artan ve\n5 tur süren bir\nsaldırı.");
const u8 gMoveDescription_FalseSwipe[] = _("Düşmanı en az 1\ncan ile bırakan\nbir saldırı.");
const u8 gMoveDescription_Swagger[] = _("Düşman kafası\nkarıştırır ama SLD\nçokça yükseltir.");
const u8 gMoveDescription_MilkDrink[] = _("Kullanıcının maks\ncanının yarısını\niyileştirir.");
const u8 gMoveDescription_Spark[] = _("Düşmanı felç\nedebilecek\nelektrikli bir\nsaldırı.");
const u8 gMoveDescription_FuryCutter[] = _("Art arda her\nvuruşta\nşiddetlenen bir\nsaldırı.");
const u8 gMoveDescription_SteelWing[] = _("Düşmana sert\nkanatlarını açarak\nsaldırır.");
const u8 gMoveDescription_MeanLook[] = _("Düşmanın kaçmasını\nengelleyen sert\nbir bakış.");
const u8 gMoveDescription_Attract[] = _("Karşı cinsin\nsaldırma\nolasılığını\nazaltır.");
const u8 gMoveDescription_SleepTalk[] = _("Uykudayken\nrastgele bir\nhareket kullanır.");
const u8 gMoveDescription_HealBell[] = _("Tüm durum\nsorunlarını ses\nile iyileştirir.");
const u8 gMoveDescription_Return[] = _("Arkadaşlıkla gücü\nartan bir saldırı.");
const u8 gMoveDescription_Present[] = _("Bomba şeklinde bir\nhediye. Canı\nyenileyebilir.");
const u8 gMoveDescription_Frustration[] = _("Eğitmen\nsevilmediğinde\ndaha güçlü olan\nbir saldırı.");
const u8 gMoveDescription_Safeguard[] = _("Tüm durum\nsorunlarını\nönleyen, mistik\nbir güç.");
const u8 gMoveDescription_PainSplit[] = _("Kullanıcı ve\ndüşman canı eşit\nolarak\npaylaştırır.");
const u8 gMoveDescription_SacredFire[] = _("Yanıklara neden\nolabilen mistik\nbir ateş\nsaldırısı.");
const u8 gMoveDescription_Magnitude[] = _("Rastgele\nyoğunlukta, yeri\nsarsan bir\nsaldırı.");
const u8 gMoveDescription_DynamicPunch[] = _("Kafa karıştırır\nancak isabeti\ndüşüktür.");
const u8 gMoveDescription_Megahorn[] = _("Acımasız bir\nboynuz saldırısı.");
const u8 gMoveDescription_DragonBreath[] = _("Düşmanı inanılmaz\nbir nefes\npatlamasıyla\nvurur.");
const u8 gMoveDescription_BatonPass[] = _("Efektleri oyunda\ntutarken\nkullanıcıyı\ndeğiştirir.");
const u8 gMoveDescription_Encore[] = _("Düşmana son\nhareketini 2-6 tur\ntekrarlatır.");
const u8 gMoveDescription_Pursuit[] = _("Değişen bir düşman\nüzerinde hasarı\nyükselir.");
const u8 gMoveDescription_RapidSpin[] = _("Düşmana vurmak\niçin vücudu yüksek\nhızda döndürür.");
const u8 gMoveDescription_SweetScent[] = _("Kaçamakları\nazaltmak için\ndüşmanı cezbeder.");
const u8 gMoveDescription_IronTail[] = _("Kaya gibi sert bir\nkuyrukla saldırır.\nSVN düşürebilir.");
const u8 gMoveDescription_MetalClaw[] = _("Kullanıcının\nsaldırısını\nartırabilen bir\nsaldırı.");
const u8 gMoveDescription_VitalThrow[] = _("Kullanıcın\nsaldırıyı en son\nyapar ama\nıskalamaz.");
const u8 gMoveDescription_MorningSun[] = _("Canı iyileştirir.\nMiktar havaya göre\ndeğişir.");
const u8 gMoveDescription_Synthesis[] = _("Canı iyileştirir.\nMiktar havaya göre\ndeğişir.");
const u8 gMoveDescription_Moonlight[] = _("Canı iyileştirir.\nMiktar havaya göre\ndeğişir.");
const u8 gMoveDescription_HiddenPower[] = _("Türü kullanıcıya\ngöre değişir.");
const u8 gMoveDescription_CrossChop[] = _("Çifte doğrama\nsaldırısı. Yüksek\nkritik vuruş\noranı.");
const u8 gMoveDescription_Twister[] = _("Düşmanı parçalamak\niçin güçlü bir\nhortum çıkarır.");
const u8 gMoveDescription_RainDance[] = _("SU tipi saldırı\ngücünü 5 tur\nboyunca artırır.");
const u8 gMoveDescription_SunnyDay[] = _("ATEŞ tipi saldırı\ngücünü 5 tur\nboyunca artırır.");
const u8 gMoveDescription_Crunch[] = _("Keskin dişlerle\nsaldırır. ÖZ. SVN\ndüşürebilir.");
const u8 gMoveDescription_MirrorCoat[] = _("Düşmanın özel\nsaldırısını iki\nkat güçle\nkarşılar.");
const u8 gMoveDescription_PsychUp[] = _("Düşman etkilerini\nkopyalar ve alır.");
const u8 gMoveDescription_ExtremeSpeed[] = _("Son derece hızlı\nve güçlü bir\nsaldırı.");
const u8 gMoveDescription_AncientPower[] = _("Tüm özellikleri\nyükseltebilen bir\nsaldırı.");
const u8 gMoveDescription_ShadowBall[] = _("Düşmana ÖZ SVN\ndüşürebilen kara\nbir top fırlatır.");
const u8 gMoveDescription_FutureSight[] = _("2 tur sonra\nsaldırmak için\niçsel gücü\nartırır.");
const u8 gMoveDescription_RockSmash[] = _("SAVUNMAYI\ndüşürebilecek kaya\nkırıcı bir\nsaldırı.");
const u8 gMoveDescription_Whirlpool[] = _("Düşmanı 2 ila 5\ntur boyunca bir\ngirdaba hapseder.");
const u8 gMoveDescription_BeatUp[] = _("Saldırıya\nkatılmaları için\nPOKéMON takımını\nçağırır.");
const u8 gMoveDescription_FakeOut[] = _("İlk turda\nkullanılabilen,\nürküten, hızlı bir\nsaldırı.");
const u8 gMoveDescription_Uproar[] = _("2 ila 5 tur\nboyunca ses yapar\nve uykuyu\nengeller.");
const u8 gMoveDescription_Stockpile[] = _("Gücü 3 tura kadar\nşarj eder.");
const u8 gMoveDescription_SpitUp[] = _("Stoklanan gücü\nserbest bırakır.");
const u8 gMoveDescription_Swallow[] = _("Depolanan gücü\nemer ve canı\nyeniler.");
const u8 gMoveDescription_HeatWave[] = _("Düşmanın üzerine\nsıcak bir nefes\nüfler. Yakabilir.");
const u8 gMoveDescription_Hail[] = _("Her turda vuran\nbir dolu fırtınası\nçağırır.");
const u8 gMoveDescription_Torment[] = _("Eziyet edererek\nüst üste kullanımı\nengeller.");
const u8 gMoveDescription_Flatter[] = _("Düşman kafası\nkarıştırır, ancak\nÖZ. SLD yükseltir.");
const u8 gMoveDescription_WillOWisp[] = _("Düşmanı yoğun\nateşle yakar.");
const u8 gMoveDescription_Memento[] = _("Kullanıcı bayılır\nve düşman özlk.\nazaltır.");
const u8 gMoveDescription_Facade[] = _("Kötü bir durumda,\nSALDIRI artırır.");
const u8 gMoveDescription_FocusPunch[] = _("Güçlüdür ancak\nkullanıcı hasar\nalırsa ürker.");
const u8 gMoveDescription_SmellingSalt[] = _("Felçli düşmanlara\nkarşı x2 vurur\nancak iyileştirir.");
const u8 gMoveDescription_FollowMe[] = _("Düşmanların sadece\nkendine saldırması\niçin dikkat çeker.");
const u8 gMoveDescription_NaturePower[] = _("Saldırının türü\nbulunduğu yere\ngöre değişir.");
const u8 gMoveDescription_Charge[] = _("Bir sonraki\nelektrik saldırısı\niçin güç toplar.");
const u8 gMoveDescription_Taunt[] = _("Sadece hasar veren\nsaldırı kullanması\niçin kızdırır.");
const u8 gMoveDescription_HelpingHand[] = _("Dostun\nsaldırılarının\ngücünü artırır.");
const u8 gMoveDescription_Trick[] = _("Düşmanı elindeki\neşyaları takas\netmesi için\nkandırır.");
const u8 gMoveDescription_RolePlay[] = _("Hedefi taklit eder\nve özel yeteneğini\nkopyalar.");
const u8 gMoveDescription_Wish[] = _("Can iyileştiren\nbir dilek. Zaman\nalır.");
const u8 gMoveDescription_Assist[] = _("Ortağın\nhareketlerinden\nbiriyle rastgele\nsaldırır.");
const u8 gMoveDescription_Ingrain[] = _("Can yenileyen\nkökler salar. Yer\ndeğiştiremez.");
const u8 gMoveDescription_Superpower[] = _("Gücü çokça artırır\nama yetenekleri\nazaltır.");
const u8 gMoveDescription_MagicCoat[] = _("Özel etkileri\nsaldırgana geri\nyansıtır.");
const u8 gMoveDescription_Recycle[] = _("Kullanılmış eşyayı\ntekrar kullanım\niçin dönüştürür.");
const u8 gMoveDescription_Revenge[] = _("Düşman tarafından\nhasar alınınca\ngüçlenir.");
const u8 gMoveDescription_BrickBreak[] = _("YANSITMA gibi\nduvarları yok eder\nhasar verir.");
const u8 gMoveDescription_Yawn[] = _("Düşmanı esnetir ve\nbir sonraki turda\nuyutur.");
const u8 gMoveDescription_KnockOff[] = _("Düşmanın elindeki\neşyayı düşürerek\nengeller.");
const u8 gMoveDescription_Endeavor[] = _("Kullanıcının canı\ndüşman canından\ndüşükse güçlenir.");
const u8 gMoveDescription_Eruption[] = _("Kullanıcının canı\nne kadar yüksekse,\no kadar güçlüdür.");
const u8 gMoveDescription_SkillSwap[] = _("Kullanıcı hedefle\nözel yeteneklerini\ndeğiştirir.");
const u8 gMoveDescription_Imprison[] = _("Düşmanların kendi\nbildiği\nsaldırılarını\nengeller.");
const u8 gMoveDescription_Refresh[] = _("Zehirlenmeyi,\nfelci ya da yanığı\niyileştirir.");
const u8 gMoveDescription_Grudge[] = _("Bayılırsa düşmanın\nson saldırısının\nPP'lerini siler.");
const u8 gMoveDescription_Snatch[] = _("Hedefin bir\nsonraki etkilerini\nçalar.");
const u8 gMoveDescription_SecretPower[] = _("Etkileri konuma\ngöre değişen bir\nsaldırı.");
const u8 gMoveDescription_Dive[] = _("İlk turda su\naltına dalar ve\nbir sonraki turda\nvurur.");
const u8 gMoveDescription_ArmThrust[] = _("Düşmana 2 ila 5\nkez vuran düz kol\nyumrukları.");
const u8 gMoveDescription_Camouflage[] = _("Bulunduğu yere\ngöre POKéMON türü\ndeğiştirir.");
const u8 gMoveDescription_TailGlow[] = _("ÖZ. SLD çokça\nyükselten bir ışık\nyakıp söndürür.");
const u8 gMoveDescription_LusterPurge[] = _("Işık patlamasıyla\nsaldırır. ÖZ. SVN\ndüşürebilir.");
const u8 gMoveDescription_MistBall[] = _("Bir telaşla\nsaldırır. ÖZ. SLD\ndüşürebilir.");
const u8 gMoveDescription_FeatherDance[] = _("Düşmanın\nsaldırısını iki\nseviye düşürür.");
const u8 gMoveDescription_TeeterDance[] = _("Savaştaki\nPOKéMON'ların\nkafasını\nkarıştırır.");
const u8 gMoveDescription_BlazeKick[] = _("Kritik oranı\nyüksektir. Yanığa\nneden olabilir.");
const u8 gMoveDescription_MudSport[] = _("Elektrik direncini\nartırmak için\nçamurla kaplanır.");
const u8 gMoveDescription_IceBall[] = _("Art arda vurunca\ngüçlenen 5 turluk\nbir saldırı.");
const u8 gMoveDescription_NeedleArm[] = _("Dikenli kollarla\nsaldırır. Ürkmeye\nneden olabilir.");
const u8 gMoveDescription_SlackOff[] = _("Yavaşlar ve\nmaksimum canın\nyarısını yeniler.");
const u8 gMoveDescription_HyperVoice[] = _("Ses dalgalarını\nkullanan bir\nsaldırı.");
const u8 gMoveDescription_PoisonFang[] = _("Keskin dişli bir\nsaldırı. Ağır\nzehirleyebilir.");
const u8 gMoveDescription_CrushClaw[] = _("Keskin pençelerle\ndüşmanı keser. SVN\ndüşürebilir.");
const u8 gMoveDescription_BlastBurn[] = _("Güçlüdür ama\nkullanıcıyı\nhareketsiz\nbırakır.");
const u8 gMoveDescription_HydroCannon[] = _("Güçlüdür ama\nkullanıcıyı\nhareketsiz\nbırakır.");
const u8 gMoveDescription_MeteorMash[] = _("Meteor benzeri bir\nyumruk atar. SLD\nyükseltebilir.");
const u8 gMoveDescription_Astonish[] = _("Düşmanı şok ederek\nkorkutabilecek bir\nsaldırı.");
const u8 gMoveDescription_WeatherBall[] = _("Hareketin türü ve\ngücü hava durumuna\ngöre değişir.");
const u8 gMoveDescription_Aromatherapy[] = _("Yatıştırıcı\nkokusuyla tüm\nsorunları\niyileştirir.");
const u8 gMoveDescription_FakeTears[] = _("Düşmanın ÖZ. SVN\nkeskin bir şekilde\ndüşürür.");
const u8 gMoveDescription_AirCutter[] = _("Jilet gibi bir\nrüzgarla keser.\nKritik oran\nyüksek.");
const u8 gMoveDescription_Overheat[] = _("Tam güç saldırı\nyapar ama ÖZ. SLD\nçokça düşer.");
const u8 gMoveDescription_OdorSleuth[] = _("Düşmanın kaçınma\nçabalarını boşa\nçıkarır.");
const u8 gMoveDescription_RockTomb[] = _("Kayalarla hareketi\nengeller Hızı\ndüşürebilir.");
const u8 gMoveDescription_SilverWind[] = _("Yetenekleri\nartırabilen tozlu\nbir saldırı.");
const u8 gMoveDescription_MetalSound[] = _("ÖZ. SVN'yı çokça\ndüşüren korkunç\nbir çığlık yayar.");
const u8 gMoveDescription_GrassWhistle[] = _("Düşmanı hoş bir\nmelodiyle uyutur.");
const u8 gMoveDescription_Tickle[] = _("SLD ve SVN\ndüşürmek için\ndüşmanı güldürür.");
const u8 gMoveDescription_CosmicPower[] = _("Savunmayı ve ÖZ.\nSVN'yı mistik bir\ngüçle yükseltir.");
const u8 gMoveDescription_WaterSpout[] = _("Kullanıcının canı\nyüksek ise daha\nfazla hasar verir.");
const u8 gMoveDescription_SignalBeam[] = _("Düşman kafası\nkarıştırabilen bir\nışın saldırısı.");
const u8 gMoveDescription_ShadowPunch[] = _("Gölgelerden atılan\nkaçınılmaz bir\nyumruk.");
const u8 gMoveDescription_Extrasensory[] = _("Tuhaf bir güçle\nsaldırır.\nÜrkütmeye neden\nolabilir.");
const u8 gMoveDescription_SkyUppercut[] = _("Gökyüzüne sıçrar\ngibi atılan bir\naparkat.");
const u8 gMoveDescription_SandTomb[] = _("Düşmanı 2 ila 5\ntur boyunca\nbataklığa\nhapseder.");
const u8 gMoveDescription_SheerCold[] = _("İsabet ettiğinde\nbayılmaya neden\nolan bir saldırı.");
const u8 gMoveDescription_MuddyWater[] = _("Çamurlu su ile\nsaldırır. İsabet\noranı düşebilir.");
const u8 gMoveDescription_BulletSeed[] = _("Düşmana saldırmak\niçin arka arkaya 2\nila 5 tohum atar.");
const u8 gMoveDescription_AerialAce[] = _("Son derece hızlı\nve kaçınılmaz bir\nsaldırı.");
const u8 gMoveDescription_IcicleSpear[] = _("Arka arkaya 2 ila\n5 buz sarkıtını\nfırlatır.");
const u8 gMoveDescription_IronDefense[] = _("Vücudu\nsertleştirerek\nsavunma çokça\nartırır.");
const u8 gMoveDescription_Block[] = _("Kaçışı engellemek\niçin düşmanın\nyolunu keser.");
const u8 gMoveDescription_Howl[] = _("Ruhu yükseltmek\niçin ulur ve\nSALDIRIYI artırır.");
const u8 gMoveDescription_DragonClaw[] = _("Düşmanı keskin\npençeleriyle\nkeser.");
const u8 gMoveDescription_FrenzyPlant[] = _("Güçlüdür ama\nkullanıcıyı\nsonraki turda felç\neder.");
const u8 gMoveDescription_BulkUp[] = _("Hem SALDIRI hem de\nSAVUNMAYI artırır.");
const u8 gMoveDescription_Bounce[] = _("Zıplar, bir\nsonraki turda\naşağı iner. Felç\nedebilir.");
const u8 gMoveDescription_MudShot[] = _("Düşmana çamur\nfırlatır ve HIZI\nazaltır.");
const u8 gMoveDescription_PoisonTail[] = _("Yüksek kritik\noranına sahiptir.\nZehirleyebilir.");
const u8 gMoveDescription_Covet[] = _("Düşman elindeki\neşyayı şirin bir\nşekilde yalvarır.");
const u8 gMoveDescription_VoltTackle[] = _("Kullanıcıya\nhafifçe zarar\nveren, riskli bir\nsaldırı.");
const u8 gMoveDescription_MagicalLeaf[] = _("Kaçınılması mümkün\nolmayan bir\nyaprakla saldırır.");
const u8 gMoveDescription_WaterSport[] = _("Ateşe karşı direnç\nartırmak için\nıslanır.");
const u8 gMoveDescription_CalmMind[] = _("ÖZ. SLD ve ÖZ.\nSVN'yı zihni\nodaklayarak\nyükseltir.");
const u8 gMoveDescription_LeafBlade[] = _("Keskin bir\nyaprakla keser.\nYüksek kritik\nvuruş oranı.");
const u8 gMoveDescription_DragonDance[] = _("SALDIRI ve HIZI\nartıran mistik bir\ndans.");
const u8 gMoveDescription_RockBlast[] = _("Düşmana arka\narkaya 2 ila 5 kez\nkaya fırlatır.");
const u8 gMoveDescription_ShockWave[] = _("Hızlı ve\nkaçınılmaz bir\nelektrik\nsaldırısı.");
const u8 gMoveDescription_WaterPulse[] = _("Ultrasonik dalga\nile vurur. Kafa\nkarıştırabilir.");
const u8 gMoveDescription_DoomDesire[] = _("2 tur sonra\nsaldırmak için\ngüçlü güneş ışığı\nçağırır.");
const u8 gMoveDescription_PsychoBoost[] = _("Tam güç saldırır\nancak ÖZ. SLD\nçokça düşürür.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] =
{
    [MOVE_POUND - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT - 1] = gMoveDescription_Cut,
    [MOVE_GUST - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY - 1] = gMoveDescription_Fly,
    [MOVE_BIND - 1] = gMoveDescription_Bind,
    [MOVE_SLAM - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER - 1] = gMoveDescription_Leer,
    [MOVE_BITE - 1] = gMoveDescription_Bite,
    [MOVE_GROWL - 1] = gMoveDescription_Growl,
    [MOVE_ROAR - 1] = gMoveDescription_Roar,
    [MOVE_SING - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE - 1] = gMoveDescription_Disable,
    [MOVE_ACID - 1] = gMoveDescription_Acid,
    [MOVE_EMBER - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE - 1] = gMoveDescription_Fissure,
    [MOVE_DIG - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK - 1] = gMoveDescription_Lick,
    [MOVE_SMOG - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE - 1] = gMoveDescription_Spore,
    [MOVE_FLASH - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE - 1] = gMoveDescription_Snore,
    [MOVE_CURSE - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2 - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE - 1] = gMoveDescription_Endure,
    [MOVE_CHARM - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN - 1] = gMoveDescription_Return,
    [MOVE_PRESENT - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO - 1] = gMoveDescription_Memento,
    [MOVE_FACADE - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK - 1] = gMoveDescription_Block,
    [MOVE_HOWL - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST - 1] = gMoveDescription_PsychoBoost,
};