CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Merhaba!\n"
    .string "Celadon Mağazasına Hoş Geldiniz.\p"
    .string "Sağdaki pano, mağaza düzenini\n"
    .string "açıklar.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1. Kat: MÜŞTERİ HİZMETLERİ\p"
    .string "2. Kat: EĞİTMEN PAZARI\p"
    .string "3. Kat: TV OYUN MAĞAZASI\p"
    .string "4. Kat: BİLGELERDEN HEDİYELER\p"
    .string "5. Kat: ECZANE\p"
    .string "ÇATI KATI: OTOMAT MAKİNELERİ$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1. Kat: MÜŞTERİ HİZMETLERİ$"
