@ Kullanılmıyor
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "Kapıyı açmak için iki\n"
    .string "şifre gerekiyor gibi görünüyor.$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} bir şifre girdi.\p"
    .string "“GOLDEEN kütük istiyor.”\p"
    .string "… …  … …  … …\p"
    .string "Kapıyı açmak için\n"
    .string "başka bir şifre daha gerekli.$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} iki şifre girdi.\p"
    .string "“GOLDEEN kütük istiyor.”\n"
    .string "“Evet, hayır, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "AMBAR kapısı açıldı!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "AMBAR kapısı zaten\n"
    .string "açık.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "Bu alan kesinlikle yasak bölge!\n"
    .string "Defol buradan!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "Bu gerçek olabilir mi?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "Burada işin ne?\n"
    .string "Defol git!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "Buradan öteye bir şey yok,\n"
    .string "sadece AMBARımız var.\p"
    .string "O zaman neden buradasın?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "Bunun olması mümkün değildi…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "Bu AMBARın içinde ne olduğunu\n"
    .string "bilmek istiyorsun, değil mi?\p"
    .string "Bilmemen senin için daha iyi olurdu.\n"
    .string "Kendi iyiliğin için söylüyorum.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "Beni geçsen bile vakit kaybı olacak,\n"
    .string "çünkü şifreler olmadan giremezsin.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "Bunu yapmana çok sinirlendim!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "Şifreler olmadan\n"
    .string "içeri giremezsin.$"
