CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "Yakalanan POKéMON'lar bir ID\n"
    .string "numarası ve OE ile kaydedilir.\p"
    .string "OE, “Orijinal EĞİTMEN” anlamına\n"
    .string "gelir.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "Tamam!\p"
    .string "Arkadaşım KANGASKHAN'ını benim\n"
    .string "HAUNTER'ımla takas edecek!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "Haydi, HAUNTER!\p"
    .string "HAUNTER'ı çok seviyorum!\n"
    .string "Onları topluyorum!\p"
    .string "Hmm?\p"
    .string "HAUNTER, takas edilirken\n"
    .string "farklı bir POKéMON'a dönüştü!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "Takasla elde ettiğin POKéMON'ları\n"
    .string "ID numaralarıyla tanımlayabilirsin.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "Bu bir Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "Bir RPG!\n"
    .string "Buna zaman yok!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "Bir spor oyunu!\n"
    .string "Babam bunu sever!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "Bir bulmaca oyunu!\n"
    .string "Bağımlılık yapacak gibi görünüyor!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "Bir dövüş oyunu!\n"
    .string "Zor görünüyor!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3. Kat: TV OYUN MAĞAZASI$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Kırmızı ve Yeşil!\n"
    .string "Her ikisi de POKéMON!$"

Text_CounterTeach::
    .string "Merhaba!\n"
    .string "POKéMON'u sonunda bitirdim.\p"
    .string "Henüz bitirmedin mi?\n"
    .string "Sana iyi bir hareket öğretmemi\l"
    .string "ister misin?\p"
    .if ENG_MOVES == 1
    .string "Aklımdaki hareket COUNTER.\p"
    .string "Aklına o meşhur oyun gelmesin!$"
    .else
    .string "Aklımdaki hareket KARŞILIK.\p"
    .string "Sana karşılık vereceğimden değil!$"
    .endif

Text_CounterDeclined::
    .string "İlginç değil mi?\n"
    .string "Fikrini değiştirirsen gel bana.$"

Text_CounterWhichMon::
    .if ENG_MOVES == 1
    .string "Hangi POKéMON'a COUNTER\n"
    .else
    .string "Hangi POKéMON'a KARŞILIK\n"
    .endif
    .string "öğretmemi istersin?$"

Text_CounterTaught::
    .if ENG_MOVES == 1
    .string "Öğrettiğim COUNTER hamlesini\n"
    .else
    .string "Öğrettiğim KARŞILIK hamlesini\n"
    .endif
    .string "kullanıyor musun?$"

