Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "Merhaba! Beni hatırlıyor musun?\n"
    .string "PROF. OAK'ın asistanlarından\l"
    .string "biriyim.\p"
    .string "POKéDEX'iniz {STR_VAR_1} türde\n"
    .string "veri içeriyorsa,\l"
    .string "size bir ödül vermem gerekiyor.\l"
    .string "PROF. OAK, size vermek üzere bana\n"
    .string "{STR_VAR_2} emanet etti.\p"
    .string "Öyleyse, {PLAYER}, sana bir soru\n"
    .string "sormak istiyorum.\p"
    .string "En az {STR_VAR_1} çeşit\n"
    .string "POKéMON verisi topladın mı?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "Harika! {STR_VAR_3} çeşit POKéMON\n"
    .string "yakaladın veya sahip oldun!\p"
    .string "Tebrikler!\n"
    .string "İşte bu senin için!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER}, asistan'dan\n"
    .string "{STR_VAR_2} aldı.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "Görünmeyen bazı eşyalar\n"
    .string "yerde olabilir.\p"
    .string "EŞYABULUCU'yu yakınındaki gizli\n"
    .string "eşyaları bulmak için kullan.\p"
    .string "Alet biraz kısıtlı.\n"
    .string "Eşyaların yerini tam belirleyemez.\p"
    .string "Sadece eşyanın yönünü gösterir.\p"
    .string "Onunla yönünü bulup,\n"
    .string "etrafı kendin arayabilirsin.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "Bakın bakalım dürbünle\n"
    .string "ne göreceğiz…\p"
    .string "Büyük bir POKéMON\n"
    .string "yolun ortasında uyuyor!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "Bakın bakalım dürbünle\n"
    .string "ne göreceğiz…\p"
    .string "Ne muhteşem bir manzara!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "Bakın bakalım dürbünle ne göreceğiz…\p"
    .string "CERULEAN ŞEHRİ'nden\n"
    .string "LAVENDER KASABASI'na gitmek için…\p"
    .string "KAYA TÜNELİ iyi bir rota\n"
    .string "gibi görünüyor.$"
