PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, otur!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Bu POKéMON'umuz bir yabancı, bu\n"
    .string "yüzden huysuz ve baş etmek zor.\p"
    .string "Takasla elde edilen POKéMON'lar\n"
    .string "etrafı yabancılarlar.\p"
    .string "Hızlı gelişirler ama savaşta emir\n"
    .string "veren beceriksiz eğitmenleri\l"
    .string "dinlemeyebilirler.\p"
    .string "Keşke rozetlerimiz olsaydı…$"
