PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "NIDORAN, otur!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Bu POKéMON'umuz bir yabancı, bu\n"
    .string "yüzden huysuz ve baş etmek zor.\p"
    .string "Takasla elde edilen bir\n"
    .string "POKéMON etrafı yabancılar.\p"
    .string "Hızlı gelişir ama savaş sırasında\n"
    .string "beceriksiz bir EĞİTMEN'i\l"
    .string "dinlemeyebilir\p"
    .string "Keşke ROZETlerimiz olsaydı…$"
