PewterCity_Gym_Text_BrockIntro::
    .string "Merhaba, ben BROCK.\n"
    .string "PEWTER Salonunun Lideriyim.\p"
    .string "Çelik gibi iradem,\n" 
    .string "POKéMON'larımdan da bellidir.\p"
    .string "POKéMON'larımın hepsi kaya gibi\n"
    .string "sert ve azimlidir. Hepsi KAYA tipi!\p"
    .string "Hahaha! Kaybedeceğini bile bile\n"
    .string "meydan mı okuyorsun? Sende bir\l"
    .string "EĞİTMEN onuru görüyorum. Seni bana\l"
    .string "meydan okumaya zorlayan şey bu.\p"
    .string "Öyleyse, en iyini göster!\n"
    .string "{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

@ NOT: Bu yenilgi metni gerçekten bir tampon taşmasına neden oluyor. gDisplayedStringBattle
@ tamponunun içine konulduğu için çok uzun ve gBattleTextBuffs'ın
@ ardından, ayrıca sFlickerArray olarak adlandırılan başka bir kullanılmayan diziyi eziyor. Belki de bu dizinin var olma nedeni budur.
PewterCity_Gym_Text_BrockDefeat::
    .string "Seni hafife aldım ve yenildim.\p"
    .string "Zaferinin kanıtı olarak sana bunu\n"
    .string "veriyorum… Resmi POKéMON LİGİ\l"
    .string "KAYA ROZETİ.\p"
    .string "{FONT_NORMAL}{PLAYER} BROCK'tan KAYA ROZETİ\n"
    .string "aldı!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}Sırf KAYA ROZETİ'ne sahip olmak bile\n"
    .string "POKéMON'ları daha güçlü hale\l"
    .string "getirir.\p"
    .ifdef ENG_NAMES
    .string "Ayrıca, FLASH hamlesinin savaş dışı\n"
    .else
    .string "Ayrıca, FLAŞ hamlesinin savaş dışı\n"
    .endif
    .string "kullanılmasını sağlar.\p"
    .ifdef ENG_NAMES
    .string "Tabii ki, bir POKéMON'un FLAŞ\n"
    .else
    .string "Tabii ki, bir POKéMON'un FLAŞ\n"
    .endif
    .string "hamlesini kullanabilmesi için\l"
    .string "onu bilmesi gerekir.$"

PewterCity_Gym_Text_TakeThisWithYou::
    .string "Dur!\n"
    .string "Bunu yanında götür.$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
    .string "{PLAYER} BROCK'tan TM39 aldı."
    .string "$"

PewterCity_Gym_Text_ExplainTM39::
    .string "TM, Teknik Makine, POKéMON'lar için\n"
    .string "bir hamle içerir.\p"
    .string "Bir TM kullanmak, içinde bulunan\n"
    .string "hamleyi POKéMON'lara öğretir.\p"
    .string "Bir TM yalnızca bir kez\n"
    .string "kullanılabilir.\p"
    .string "Bu nedenle, lütfen kullandığın\n"
    .string "POKéMON'u dikkatli seç.\p"
    .string "Her neyse…\n"
    .ifdef ENG_NAMES
    .string "TM39 ROCK TOMB içerir.\p"
    .else
    .string "TM39 KAYA MEZAR içerir.\p"
    .endif
    .string "Rakibe kaya fırlatır ve HIZINI\n"
    .string "düşürür.$"

PewterCity_Gym_Text_BrockPostBattle::
    .string "Bu devasa dünyamızda her türden\n"
    .string "EĞİTMEN var.\p"
    .string "POKéMON EĞİTMENİ olarak çok\n"
    .string "yetenekli görünüyorsun.\p"
    .string "Öyleyse sana bir tavsiye vereyim.\p"
    .string "CERULEAN'daki SALON'a git ve\n"
    .string "yeteneklerini orada test et.$"

PewterCity_Gym_Text_DontHaveRoomForThis::
    .string "Bunun için yerin yok.$"

PewterCity_Gym_Text_LiamIntro::
    .string "Dur orada çocuk!\p"
    .string "BROCK'a karşı savaşmak\n" 
    .string "için çok acemisin!$"

PewterCity_Gym_Text_LiamDefeat::
    .string "Zevzek!\p"
    .string "Işık yılı zaman değil,\n"
    .string "uzunluk birimidir!$"

PewterCity_Gym_Text_LiamPostBattle::
    .string "İyi gidiyorsun.\n"
    .string "…Ama BROCK kadar değil!$"

PewterCity_Gym_Text_LetMeTakeYouToTheTop::
    .string "Merhaba!\n"
    .string "Büyük hayallerin var mı?\p"
    .string "POKéMON şampiyonu olmayı hayal\n"
    .string "ediyor musun? EĞİTMEN değilim,\l"
    .string "ama sana nasıl şampiyon olacağını\l"
    .string "gösterebilirim.\p"
    .string "Seni zirveye taşımak istiyorum!$"

PewterCity_Gym_Text_LetsGetHappening::
    .string "Tamam!\n"
    .string "Hadi tavsiyelere başlayalım!$"

PewterCity_Gym_Text_TryDifferentPartyOrders::
    .string "Bir maçta ilk çıkan POKéMON, POKéMON\n"
    .string "LİSTESİ'nin solundadır.\p"
    .string "POKéMONların sırasını değiştirerek\n"
    .string "avantaj elde edebilirsin.\p"
    .string "Rakibinin takımına uygun farklı\n"
    .string "sıralamalar deneyebilirsin.$"

PewterCity_Gym_Text_ItsFreeLetsGetHappening::
    .string "Bu ücretsiz bir hizmet!\n"
    .string "Hadi başlayalım!$"

PewterCity_Gym_Text_YoureChampMaterial::
    .string "Düşündüğüm gibi!\n"
    .string "Sen POKéMON şampiyonu olabilecek\l"
    .string "kapasiteye sahip birisin!$"

PewterCity_Gym_Text_GymStatue::
    .string "PEWTER POKéMON SALONU\n"
    .string "LİDER: BROCK\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
    .string "PEWTER POKéMON SALONU\n"
    .string "LİDER: BROCK\p"
    .string "KAZANAN EĞİTMENLER:\n"
    .string "{RIVAL}, {PLAYER}$"
