PewterCity_Gym_Text_BrockIntro::
    .string "Merhaba, ben BROCK.\n"
    .string "PEWTER Spor Salonunun Lideriyim.\p"
    .string "Çelik gibi iradem,\n" 
    .string "POKéMONlarımdan da belli.\p"
    .string "POKéMONlarımın hepsi kaya gibi sert\n"
    .string "ve azimli. Hepsi KAYA tipi!\p"
    .string "Hahaha! Kaybedeceğini bile bile mi\n"
    .string "meydan okuyorsun? Bu bir EĞİTMEN\l"
    .string "onurudur, seni bana karşı\l"
    .string "meydan okumaya zorlayan.\p"
    .string "Öyleyse, en iyini göster!\n"
    .string "{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

@ NOT: Bu yenilgi metni gerçekten bir tampon taşmasına neden oluyor. gDisplayedStringBattle
@ tamponunun içine konulduğu için çok uzun ve gBattleTextBuffs'ın
@ ardından, ayrıca sFlickerArray olarak adlandırılan başka bir kullanılmayan diziyi eziyor. Belki de bu dizinin var olma nedeni budur.
PewterCity_Gym_Text_BrockDefeat::
    .string "Seni hafife aldım ve yenildim.\p"
    .string "Zaferinin kanıtı olarak sana bunu\n"
    .string "veriyorum… Resmi POKéMON LİGİ\l"
    .string "KAYA ROZETİ.\p"
    .string "{FONT_NORMAL}{PLAYER} BROCK'tan KAYA ROZETİ\n"
    .string "aldı!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}Sırf KAYA ROZETİ'ne sahip olmak bile\n"
    .string "POKéMON'ları daha güçlü hale\l"
    .string "getirir.\p"
    .string "Ayrıca, FLAŞ hareketinin savaş dışı\n"
    .string "kullanılmasını sağlar.\p"
    .string "Tabii ki, bir POKéMON'un FLAŞ\n"
    .string "hareketini kullanabilmek için\l"
    .string "onu bilmeleri gerekir.$"

PewterCity_Gym_Text_TakeThisWithYou::
    .string "Dur!\n"
    .string "Bunu yanında götür.$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
    .string "{PLAYER} BROCK'tan TM39 aldı.\n"
    .string "$"

PewterCity_Gym_Text_ExplainTM39::
    .string "TM, Teknik Makine, POKéMON için bir\n"
    .string "hamle içerir.\p"
    .string "Bir TM kullanmak, içinde bulunan\n"
    .string "hamleyi bir POKéMON'a öğretir.\p"
    .string "Bir TM yalnızca bir kez\n"
    .string "kullanılabilir.\p"
    .string "Bu nedenle, lütfen kullandığınız\n"
    .string "POKéMON'u dikkatli seçin.\p"
    .string "Her neyse…\n"
    .string "TM39 KAYA MEZAR içerir.\p"
    .string "Rakibe kaya fırlatır\n"
    .string "ve HIZINI düşürür.$"

PewterCity_Gym_Text_BrockPostBattle::
    .string "Bu devasa dünyamızda her türden\n"
    .string "EĞİTMEN var.\p"
    .string "POKéMON EĞİTMENİ olarak çok\n"
    .string "yetenekli görünüyorsun.\p"
    .string "Öyleyse sana bir tavsiye vereyim.\p"
    .string "CERULEAN'daki SALON'a git ve\n"
    .string "yeteneklerini test et.$"

PewterCity_Gym_Text_DontHaveRoomForThis::
    .string "Bunun için yerin yok.$"

PewterCity_Gym_Text_LiamIntro::
    .string "Dur orada çocuk!\p"
    .string "BROCK'a karşı savaşmak\n" 
    .string "için çok acemisin!$"

PewterCity_Gym_Text_LiamDefeat::
    .string "Zevzek!\p"
    .string "Işık yılı zaman değil,\n"
    .string "uzunluk birimidir!$"

PewterCity_Gym_Text_LiamPostBattle::
    .string "İyi gidiyorsun.\n"
    .string "…Ama BROCK kadar değil!$"

PewterCity_Gym_Text_LetMeTakeYouToTheTop::
    .string "Merhaba!\n"
    .string "Büyük hayallerin var mı?\p"
    .string "POKéMON şampiyonu olmayı hayal\n"
    .string "ediyor musun? EĞİTMEN değilim,\l"
    .string "ama sana nasıl\l"
    .string "kazanacağını söyleyebilirim.\p"
    .string "Seni zirveye taşıyayım!$"

PewterCity_Gym_Text_LetsGetHappening::
    .string "Tamam!\n"
    .string "Hadi başlayalım!$"

PewterCity_Gym_Text_TryDifferentPartyOrders::
    .string "Bir maçta ilk çıkan POKéMON, POKéMON\n"
    .string "LISTESİ'nin solundadır.\p"
    .string "POKéMONların sırasını değiştirerek\n"
    .string "avantaj elde edebilirsin.\p"
    .string "Rakibinizin partisine uygun farklı\n"
    .string "sıralamalar deneyin.$"

PewterCity_Gym_Text_ItsFreeLetsGetHappening::
    .string "Bu ücretsiz bir hizmet!\n"
    .string "Hadi başlayalım!$"

PewterCity_Gym_Text_YoureChampMaterial::
    .string "Düşündüğüm gibi!\n"
    .string "Sen POKéMON şampiyonu olabilecek\l"
    .string "birisin!$"

PewterCity_Gym_Text_GymStatue::
    .string "PEWTER POKéMON SALONU\n"
    .string "LİDER: BROCK\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
    .string "PEWTER POKéMON SALONU\n"
    .string "LİDER: BROCK\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}, {PLAYER}$"
