Route13_Text_SebastianIntro::
    .string "POKéMON'um sizinle savaşmak\n"
    .string "istiyor!$"

Route13_Text_SebastianDefeat::
    .string "PIDGEY ve PIDGEOTTO\n"
    .string "kaybetti mi?$"

Route13_Text_SebastianPostBattle::
    .string "POKéMON'um kaybetseler bile\n"
    .string "mutlu görünüyor.$"

Route13_Text_SusieIntro::
    .string "Bana dediler ki ben\nuslu bir çocukmuşum.$"

Route13_Text_SusieDefeat::
    .string "Ohh!\n"
    .string "Kaybettim!$"

Route13_Text_SusiePostBattle::
    .string "İyi bir EĞİTMEN olmak istiyorum.\n"
    .string "Sadece izle, çok çalışacağım.$"

Route13_Text_ValerieIntro::
    .string "Vay!\n"
    .string "Rozetleriniz çok havalı!$"

Route13_Text_ValerieDefeat::
    .string "Yeterli değil!$"

Route13_Text_ValeriePostBattle::
    .string "Rozetlerinizi SALON'lardan\n"
    .string "aldığınızı biliyorum.$"

Route13_Text_GwenIntro::
    .string "Tatlı POKéMON'um sizinle tanışmak\n"
    .string "istiyor.$"

Route13_Text_GwenDefeat::
    .string "İyi gidiyorsun!\n"
    .string "Kesinlikle kazandın!$"

Route13_Text_GwenPostBattle::
    .string "POKéMON'ların güçlenmesi için\n"
    .string "savaşmaları gerekir.$"

Route13_Text_AlmaIntro::
    .string "Bir mağarayı keşfederken\n"
    .string "KARBON buldum.$"

Route13_Text_AlmaDefeat::
    .string "Ah, yazık!\n"
    .string "Batırdım!$"

Route13_Text_AlmaPostBattle::
    .string "KARBON, POKéMON'umun\n"
    .string "hızını artırdı.$"

Route13_Text_PerryIntro::
    .string "Kaybetmeyeceğim.\n"
    .string "Rüzgar benim yüzüme esiyor!$"

Route13_Text_PerryDefeat::
    .string "Rüzgar döndü!$"

Route13_Text_PerryPostBattle::
    .string "Yenildim.\n"
    .string "Sanırım eve UÇARAK gideceğim.$"

Route13_Text_LolaIntro::
    .string "Tabii ki, tatlım, seninle oynayacağım.$"

Route13_Text_LolaDefeat::
    .string "Oh!\n"
    .string "Sen küçük bir canavarsın!$"

Route13_Text_LolaPostBattle::
    .string "Merak ediyorum, hangisi daha güçlü\n"
    .string "erkek mi dişi POKéMON mu?$"

Route13_Text_SheilaIntro::
    .string "POKéMON'larımla savaşmak\n"
    .string "ister misin?$"

Route13_Text_SheilaDefeat::
    .string "Zaten bitti mi?$"

Route13_Text_SheilaPostBattle::
    .string "POKéMON'lar hakkında hiçbir şey\n"
    .string "bilmiyorum.\p"
    .string "Onları görünüşlerine göre seçtim!$"

Route13_Text_JaredIntro::
    .string "Ne bakıyorsun?$"

Route13_Text_JaredDefeat::
    .string "Ayy!\n"
    .string "Dişliler kırıldı!$"

Route13_Text_JaredPostBattle::
    .string "Defol buradan!$"

Route13_Text_RobertIntro::
    .string "Ben her zaman kuş POKéMON'ları\n"
    .string "tercih ederim.\l"
    .string "Kendimi onlara adadım.$"

Route13_Text_RobertDefeat::
    .string "Güç bitti!$"

Route13_Text_RobertPostBattle::
    .string "Keşke PIDGEY ve PIDGEOTTO gibi\n"
    .string "uçabilseydim…$"

Route13_Text_LookToLeftOfThatPost::
    .string "EĞİTMEN İPUCU\p"
    .string "Bak, bak!\n"
    .string "O direğin soluna bak!$"

Route13_Text_SelectToSwitchItems::
    .string "EĞİTMEN İPUCU\n"
    .string "EŞYA penceresindeki öğeleri\l"
    .string "değiştirmek için SELECT'e basın.$"

Route13_Text_RouteSign::
    .string "ROTA 13\n"
    .string "Kuzeyde GİZLİLİK KÖPRÜSÜ$"
