VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Aynı seviyede olsalar bile,\n"
    .string "POKéMON'ların özellikleri\l"
    .string "çok farklı olabilir.\p"
    .string "Bir EĞİTMEN tarafından eğitilen\n"
    .string "POKéMON'lar, vahşi olanlardan\l"
    .string "daha güçlüdür.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "POKéMON'um zehirlendi!\n"
    .string "Yürürken bayıldı!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "Bir POKéMON'un seviyesi ne kadar\n"
    .string "yüksek olursa, o kadar güçlü olur…\p"
    .string "Ancak, tüm POKéMON'ların belirli\n"
    .string "tiplere karşı zayıf noktaları var.\p"
    .string "Bu nedenle, evrensel olarak güçlü\n"
    .string "bir POKéMON yoktur.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "Daha önce karşılaştığın biriyle\n"
    .string "yeniden savaşma isteği…\p"
    .string "Hiç böyle bir isteğin oldu mu?\n"
    .string "Eminim ki olmuştur.\p"
    .string "Ben de bazı insanlarla tekrar\n"
    .string "ve tekrar savaşmak istedim.\p"
    .string "Bu yüzden bunları dağıtıyorum.\n"
    .string "Lütfen, birini al!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "O cihazı kullanırsan, savaş için\n"
    .string "için eğitmenler bulacaksın.\p"
    .string "Ancak, bunu yapmak için pilini\n"
    .string "şarj etmelisin.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "VS BULUCU'yu nasıl kullanacağını\n"
    .string "mı soruyorsun? Çok basit.\p"
    .string "Tuşlara bip-bip basarak kullan ve\n"
    .string "çevrendeki EĞİTMENLER gelsin.\p"
    .string "Eğer bir EĞİTMEN savaş isterse,\n"
    .string "sana hemen haber verir.\p"
    .string "Bataryasını şarj et ve yolda\n"
    .string "yürürken kullan.$"
