ViridianCity_Text_CanCarryMonsAnywhere::
    .string "O belindeki POKé TOPLARI!\n"
    .string "POKéMON'ların var değil mi?\p"
    .string "Her zaman her yerde POKéMON\n"
    .string "taşımak ve kullanmak harika.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Bu POKéMON SALONU hep kapalı.\p"
    .string "Acaba lider kim?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN SALON LİDERİ geri\ndöndü!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "İki çeşit tırtıl POKéMON hakkında\n"
    .string "bir şeyler öğrenmek ister misin?$"

ViridianCity_Text_OhOkayThen::
    .string "Ah, peki o zaman!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE zehirsizdir, WEEDLE\n"
    .string "ise zehirlidir.\p"
    .string "POKéMON'unun, WEEDLE'ın\n"
    .string "ZEHİRLİ İĞNE hamlesi ile\l"
    .string "yaralanmadığından emin ol.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Of, dede!\n"
    .string "Bu kadar kaba olma!\p"
    .string "Üzgünüm.\n"
    .string "O kahvesini henüz içemedi.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Bazen PEWTER ŞEHRİ'nde alışverişe\n"
    .string "giderim.\p"
    .string "Giderken VIRIDIAN ORMANI'ndaki\n"
    .string "dönemeçli yolu kullanmam gerekir.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Buradan geçmeni katiyen\n"
    .string "yasaklıyorum!\p"
    .string "Burası özel mülktür!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "yeni güne hazırım!\p"
    .string "Hm?\n"
    .string "O kırmızı kutu ne?\p"
    .string "Demek POKéDEX'ini tamamlamaya\n"
    .string "çalışıyorsun.\p"
    .string "O zaman sana bir tavsiye.\p"
    .string "Bir POKéMON yakaladığında,\n"
    .string "POKéDEX otomatik güncellenir.\l"
    .string "Bilmiyordun, değil mi?\p"
    .string "O zaman sana göstereyim!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "İşte bu! Şimdi söyle bana,\n"
    .string "eğiticiydi, değil mi?\p"
    .string "Ve bunu da almanı isterim.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Anlamadığın bir şey varsa, ona bak.\p"
    .string "POKéMON eğitmenin temellerini\n"
    .string "öğretir.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "yeni güne hazırım!\p"
    .string "Ama kahveyi çok koyu yapmışım.\n"
    .string "Başım ağrıyor…\p"
    .string "Bu arada, POKéDEX mi dolduruyorsun?\p"
    .string "Önce POKéMON'ları zayıflatmaya\n"
    .string "odaklan.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "yeni güne hazırım!\p"
    .string "Ama çok koyu oldu.\n"
    .string "Başım ağrıyor…\p"
    .string "Bu arada, eski REHBER TV'imin\n"
    .string "yardımı dokunuyor mu?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Vahaha!\n"
    .string "TV'de torunum var!\p"
    .string "O öğretmenin ta kendisi,\n"
    .string "kesin öğrenirsin.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… REHBER TV'ye bile zaman\n"
    .string "ayıramayacak kadar meşgulsün…\p"
    .string "Zaman para demektir ve ikisi de\n"
    .string "boşa harcanmamalı…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN ŞEHRİ\n"
    .string "Daima Yeşil Bir Cennet$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "POKéMON yakala ve koleksiyonunu\n"
    .string "genişlet.\p"
    .string "Ne kadar çok POKéMON'un varsa,\n"
    .string "savaşmak o kadar kolaylaşır.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "EĞİTMEN İPUÇLARI\p"
    .string "POKéMON savaş hareketleri\n"
    .string "GÜÇ PUANLARI, yani PP ile\l"
    .string "sınırlıdır.\p"
    .string "PP'yi yenilemek için yorgun\n"
    .string "POKéMON'larını POKéMON\l"
    .string "MERKEZİ'nde dinlendir.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN ŞEHRİ\nPOKéMON SALONU$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN SALONU'nun kapıları\nkilitli…$"
