ViridianCity_Text_CanCarryMonsAnywhere::
    .string "O belindeki POKé TOPLARI!\n"
    .string "POKéMON'ların var değil mi?\p"
    .string "Her zaman her yerde POKéMON\n"
    .string "taşımak ve kullanmak harika.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Bu POKéMON SALONU hep kapalı.\p"
    .string "Acaba lider kim?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN SALON LİDERİ geri döndü!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "İki çeşit tırtıl POKéMON hakkında\n"
    .string "bir şeyler öğrenmek ister misin?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, peki o zaman!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE zehirsizdir,\n"
    .string "ama WEEDLE zehirlidir.\p"
    .string "POKéMON'unuzun WEEDLE'ın\n"
    .string "ZEHİR İĞNE'si ile\l"
    .string "yaralanmadığından emin olun.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, Dede!\n"
    .string "Bu kadar sert olma!\p"
    .string "Üzgünüm.\n"
    .string "O hala kahvesini içemedi.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "Bazen PEWTER ŞEHRİ'nde alışverişe\n"
    .string "giderim.\p"
    .string "Giderken VIRIDIAN ORMANI'ndaki\n"
    .string "dönemeçli yolu kullanmam gerekiyor.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "Buradan geçmeni kesinlikle\n"
    .string "yasaklıyorum!\p"
    .string "Bu özel mülktür!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "bunu yapmak için hazırım!\p"
    .string "Hm?\n"
    .string "O kırmızı kutu ne?\p"
    .string "Ah, POKéDEX'ini tamamlamaya\n"
    .string "çalışıyorsun.\p"
    .string "O zaman sana bir tavsiye.\p"
    .string "Bir POKéMON yakaladığında,\n"
    .string "POKéDEX otomatik güncellenir.\l"
    .string "Bilmiyorsun, değil mi?\p"
    .string "O zaman sana göstereyim!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "İşte bu! Şimdi bana söyle,\n"
    .string "eğiticiydi, değil mi?\p"
    .string "Ve bunu da al.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Anlamadığın bir şey varsa, ona bak.\p"
    .string "POKéMON eğitmenin temellerini\n"
    .string "öğretir.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "bunu yapmak için hazırım!\p"
    .string "Ama çok koyu yaptım.\n"
    .string "Başım ağrıyor…\p"
    .string "Bu arada, POKéDEX mi dolduruyorsun?\p"
    .string "Önce POKéMON'u zayıflatmaya\n"
    .string "odaklan.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Eh, şimdi, kahvemi içtim ve\n"
    .string "bunu yapmak için hazırım!\p"
    .string "Ama çok koyu oldu.\n"
    .string "Başım ağrıyor…\p"
    .string "Bu arada, eski TEACHY TV'imin\n"
    .string "yardımı dokunuyor mu?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Vahaha!\n"
    .string "TV'de torunum var!\p"
    .string "O öğretmenin ta kendisi,\n"
    .string "kesin öğrenirsin.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… TEACHY TV'ye bile\n"
    .string "zaman ayıramayacak\l"
    .string "kadar meşgulsün…\p"
    .string "Zaman para demektir ve ikisi de\n"
    .string "boşa harcanmamalı…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN ŞEHRİ\n"
    .string "Daima Yeşil Bir Cennet$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "EĞİTMEN İPUCU\p"
    .string "POKéMON yakala ve koleksiyonunu genişlet.\p"
    .string "Ne kadar çok POKéMON'un varsa,\n"
    .string "savaşmak o kadar kolaylaşır.$"

ViridianCity_Text_MovesLimitedByPP::
    .string "EĞİTMEN İPUCU\p"
    .string "POKéMON savaş hareketleri\n"
    .string "POWER POINTS, PP\l"
    .string "ile sınırlıdır.\p"
    .string "PP'yi yenilemek için yorgun\n"
    .string "POKéMON'larını bir\l"
    .string "POKéMON MERKEZİ'nde dinlendir.$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN ŞEHRİ POKéMON SALONU$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN SALONU'nun kapıları kilitli…$"
