@ Beş metin aşağıda FourIsland_House1 olarak görünmesi gerekiyor
Text_BodySlamTeach::
    .string "Hazır mısın?\n"
    .string "Zıpla!\p"
    .string "Bir VÜCUT VURUŞU maçı yapıyoruz\n"
    .string "ilk kim pes edecek.\p"
    .string "Katılırsan, bir böcek gibi ezilirsin…\p"
    .string "VÜCUT VURUŞU hareketini bir\n"
    .string "POKéMON'una öğretmemi ister misin?$"

Text_BodySlamDeclined::
    .string "Tekrar gel!\n"
    .string "Zıpla!$"

Text_BodySlamWhichMon::
    .string "Hangi POKéMON VÜCUT VURUŞU\n"
    .string "hareketini öğrenmek ister?$"

Text_BodySlamTaught::
    .string "Zıplayarak öğrendim!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "Mağarada yaşayan nadir bir\n"
    .string "BUZ POKéMON'u var.\p"
    .string "Bu POKéMON'u görmek isteyen\n"
    .string "birçok ziyaretçimiz var.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oh? Bir POKéMON YUMURTASI mı?\n"
    .string "…Bunun hakkında hiçbir fikrim yok.\p"
    .string "…Dur, bekle.\n"
    .string "Şehirdeki GÜNDÜZ BAKIMI insanları\l"
    .string "bir şeyler söylüyordu.\p"
    .string "Mülklerinde daha önce YUMURTALAR\n"
    .string "bulduklarını söylediler.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "Bu nedir?\p"
    .string "Yeni POKéMON DERGİSİ bu adaya\n"
    .string "henüz ulaşmadı mı?$"
