CeruleanCity_House4_Text_NothingEntertaining::
.string "Ah…\n"
.string "Zaman çok, yapacak bir şey yok…\p"
.string "Acaba bir yerde eğlenceli\n"
.string "bir şeyler var mı?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
.string "Ah!\n"
.string "Yeni bir haber!\p"
.string "Hmm…\p"
.string "Demek öyle!\n"
.string "Oldukça bilgilendiriciydi!\p"
.string "Genç yaşına rağmen haberlere\n"
.string "ilgi duyduğun için seni kutlarım.\p"
.string "Bana haberleri getirdiğin için\n"
.string "teşekkürler.\p"
.string "Bunu almanı istiyorum.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
.string "Oh, oh!\n"
.string "B-bu haber raporu!\p"
.string "Hmm…\p"
.string "Muhteşem!\n"
.string "Ne inanılmaz bir haber bu!\p"
.string "Çok uzun zamandır bu kadar\n"
.string "etkileyici bir haber görmemiştim!\p"
.string "Bu harika haberi paylaştığın için\n"
.string "teşekkürler. Biraz MEYVE al!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
.string "Bu haberi başkalarıyla\n"
.string "paylaşmamak yazık olacak…\p"
.string "Keşke birine söyleyebilseydim…\n"
.string "Diğerlerini haberdar etmek isterdim…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
.string "Ah, benim için bu haberi\n"
.string "yaydın mı?\p"
.string "İyi haberler, birçok kişiyle\n"
.string "paylaşıldığında değer kazanır.\p"
.string "Bu haberi yaydığın için\n"
.string "teşekkürlerimle birlikte bunu al!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
.string "Daha da mı yaydın?\n"
.string "Muhteşem!\p"
.string "Bu haber de yayılmaktan mutlu olmalı.\p"
.string "Evet, gerçekten de!\p"
.string "Bunu, benim ve haberin takdirini\n"
.string "göstermek için kabul et.\p"
.string "Genellikle verdiğimden\n"
.string "daha fazla MEYVE vereceğim.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
.string "Tüm bu haberlerle oldukça eğleniyorum.\p"
.string "Evet, memnunum!\n"
.string "Bir süre daha sıkılmayacağım.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
.string "Hm? MEYVE KESEN dolu.\n"
.string "Öyleyse hediyemi veremeyeceğim.$"
