VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Merhaba!\n"
	.string "Bir {STR_VAR_1}'ın var mı?\p"
	.string "Onu benim {STR_VAR_2} ile\n"
	.string "takas etmek ister misin?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Yazık.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…Bu bir {STR_VAR_1} değil.\p"
	.string "Eğer bir tane bulursan, lütfen\n"
	.string "benimle takas et!$"

VermilionCity_House2_Text_ThankYou::
	.string "Teşekkürler!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Eski {STR_VAR_2}'im nasıl?\p"
	.string "{STR_VAR_1} harika!$"
