CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "CINNABAR'da KOFFING'imi aldım.\p"
    .string "Genelde iyidir, ama\n"
    .string "kızınca zehir solur.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "Heheh! Bu SALON harika!\n"
    .string "Kadınlarla dolu!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "CELADON şehri güzelleştirmek için\n"
    .string "çaba sarf ediyor.\p"
    .string "Bu yüzden yeni OYUN KÖŞESİ şehrin\n"
    .string "imajını zedeliyor.$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Ah…\n"
    .string "Tüm paramı slot\l"
    .string "makinelerine yatırdım!\p"
    .string "Paraları hediyelere çevirmeliydim!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "Bu, güvenilir dostum POLIWRATH.\p"
    .string "POLIWHIRL'im bir SU TAŞI\n"
    .string "kullandığım zaman evrimleşti.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "Niye bakıyorsun?\n"
    .string "Defol, yoksa yumruğumu yersin.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "ROKET TAKIMI'nın yolundan çekil!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "EĞİTMEN İPUCU\p"
    .string "X İSABET tekniklerin isabetini\n"
    .string "arttırır.\p"
    .string "ÖLÜMCÜL VURUŞ kritik vuruş\n"
    .string "olasılığını yükseltir.\p"
    .string "Eşyalarını CELADON\n"
    .string "MAĞAZASINDAN al!$"

CeladonCity_Text_CitySign::
    .string "CELADON ŞEHRİ\n"
    .string "Renkli Rüya Şehri$"

CeladonCity_Text_GymSign::
    .string "CELADON POKéMON SALONU\n"
    .string "LİDER: ERIKA\l"
    .string "Doğa Aşığı Prenses!$"

CeladonCity_Text_MansionSign::
    .string "CELADON KÖŞKÜ$"

CeladonCity_Text_DeptStoreSign::
    .string "İhtiyacın olan her şeyi CELADON\n"
    .string "MAĞAZASINDA bul!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "EĞİTMEN İPUCU\p"
    .string "KORUMA ÖZELLİĞİ, POKéMON'u\n"
    .string "durum düşürücü hareketlerden\l"
    .string "korur.\p"
    .string "Eşyalarını CELADON\n"
    .string "MAĞAZASINDAN al!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "JETON'larınızla hediye alın!\n"
    .string "HEDİYE DEĞİŞTİRME$"

CeladonCity_Text_GameCornerSign::
    .string "ROKET OYUN KÖŞESİ\n"
    .string "Yetişkinlerin oyun alanı!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaah, ah…\n"
    .string "Dilimi yaktım!\p"
    .string "KÖŞK'teki tatlı bir yaşlı bayan\n"
    .string "bana ÇAY verdi.\p"
    .string "Ama çok sıcaktı!\n"
    .string "İçmek için biraz soğutmak lazım.$"

Text_SoftboiledTeach::
    .string "Merhaba!\p"
    .string "Seni görüyordum, ama sohbet\n"
    .string "etmek için bir fırsatım olmadı.\p"
    .string "Bizi sonunda bir araya getiren\n"
    .string "şansın iyi olduğunu düşünüyorum.\p"
    .string "RAFADAN hareketini öğreterek\n"
    .string "kutlamak istiyorum.$"

Text_SoftboiledDeclined::
    .string "Seni her zaman göz\n"
    .string "hapsinde tutacağım.\p"
    .string "Tekrar sohbet edebilmeyi umuyorum.$"

Text_SoftboiledWhichMon::
    .string "Öyleyse RAFADAN hareketini\n"
    .string "öğrenecek POKéMON hangisi?$"

Text_SoftboiledTaught::
    .string "Bol şanslar dilerim!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "Ah, ne yapacağım…\p"
    .string "SILPH GÖZLÜĞÜMÜZÜ çaldılar.\p"
    .string "Hırsız bu yöne doğru koşuyordu,\n"
    .string "eminim.\p"
    .string "Ama gözden kaçırdım!\n"
    .string "Nereye gitti?$"
