ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "PALLET KASABASI'ndan mı geldin?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "PROF. OAK'ı tanırsın, değil mi?\p"
    .string "Siparişi geldi.\n"
    .string "Bunu ona götürebilir misin?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} POKéMON MARKET\n"
    .string "çalışanından OAK'IN PAKETİNİ aldı.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Tamam, teşekkürler!\p"
    .string "PROF. OAK'a benden selam\n"
    .string "söyle lütfen.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "Bu dükkan PANZEHİR satışında\n"
    .string "iyi iş çıkarıyormuş.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Biraz İKSİR satın almalıyım.\p"
    .string "POKéMON'umun ne zaman\n"
    .string "iyileşmeye ihtiyacı olacağını\l"
    .string "bilemem.$"
