VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, çocuk! Burada ne yaptığını\n"
    .string "sanıyorsun?\p"
    .string "Savaşta uzun süre duramazsın!\n"
    .string "Gücün çok zayıf!\p"
    .string "Sana söylüyorum, çocuk, ELEKTRİK\n"
    .string "POKéMON'ları savaşta beni kurtardı!\p"
    .string "Düşmanlarımı felce uğrattılar!\p"
    .string "Sana da aynısını yapacağım!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Bir küçük tavsiye, çocuk!\p"
    .string "Elektrik gerçekten güçlü!\p"
    .string "Ama, YER-tipi POKéMON'a karşı\n"
    .string "işe yaramaz!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "YILDIRIM ROZETİ, POKéMON'unun\n"
    .string "HIZINI arttırır!\p"
    .string "Ayrıca POKéMON'un yıldırım hızıyla\n"
    .string "UÇ kullanmasını sağlar, çocuk!\p"
    .string "Sen özel birisin, çocuk!\n"
    .string "Bunu al!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} TĞM. SURGE'dan TM34\n"
    .string "aldı.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 ŞOK DALGASI içerir!\p"
    .string "Bunu bir ELEKTRİK POKéMON'una öğret!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Hey, çocuk, çantanda yer aç!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Bu gerçekten şaşırtıcı!\p"
    .string "Sen gerçekten iyisin, çocuk!\p"
    .string "Tamam, o zaman YILDIRIM ROZETİ'ni\n"
    .string "al!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Ordudayken TĞM. SURGE\n"
    .string "benim komutanımdı.\p"
    .string "Çok zorlu eğitim verirdi.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Dur!\n"
    .string "Çok iyisin!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "O kapıyı açmak kolay değil.\p"
    .string "TĞM. SURGE ordudayken her zaman\n"
    .string "tedbirli tavrıyla tanınırdı.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Hafifim, ama elektrikle\n"
    .string "iyi anlaşırım!\p"
    .string "Bu yüzden bu SALON'a katıldım.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Kızartıldı!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Tamam, konuşacağım!\p"
    .string "TĞM. SURGE kapı düğmesini\n"
    .string "bir şeyin içine sakladığını söyledi.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Bu çocuklar için yer değil!\n"
    .string "Ne kadar iyi olursan ol!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Vay!\n"
    .string "Beni şaşırttın!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "TĞM. SURGE SALON'daki tuzakları\n"
    .string "kendi kurdu.\p"
    .string "Her yere çift kilit yerleştirdi.\n"
    .string "Bir ipucu vereyim.\p"
    .string "İlk kilidi açtığında, ikinci kilit\n"
    .string "onun hemen yanında olur.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Hey!\n"
    .string "Şampiyon olacak gibisin!\p"
    .string "TĞM. SURGE'ın bir takma adı var.\p"
    .string "İnsanlar ona Yıldırım Amerikalı\n"
    .string "diye hitap ediyorlar.\p"
    .string "Elektrikli POKéMON konusunda\n"
    .string "uzmandır.\p"
    .string "KUŞ/SU-tipi POKéMON'lar elektriğe\n"
    .string "karşı zayıf kalır.\p"
    .string "Felce de dikkat et.\p"
    .string "TĞM. SURGE çok tedbirli.\p"
    .string "Kendini kilitledi, bu yüzden ona ulaşmak\n"
    .string "kolay olmayacak.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Vay!\n"
    .string "Maç elektrikliydi!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKéMON SALONU\n"
    .string "LİDER: LT. SURGE\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKéMON SALONU\n"
    .string "LİDER: LT. SURGE\p"
    .string "KAZANAN ANTRENÖRLER:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Hayır!\n"
    .string "Burada sadece çöp var.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! Çöpün altında bir düğme var!\n"
    .string "Aç! İlk elektrikli kilit açıldı!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "İkinci elektrikli kilit açıldı!\n"
    .string "Motorlu kapı açıldı!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Hayır!\n"
    .string "Burada sadece çöp var.\p"
    .string "Hey!\n"
    .string "Elektrikli kilitler sıfırlandı!$"
