FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "SAFARİ BÖLGESİ'ne Hoş Geldiniz!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "Sadece 500¥ karşılığında,\n"
    .string "SAFARİ OYUNU'nu oynayabilirsin.\p"
    .string "Geniş safari alanında gezip\n"
    .string "dilediğin POKéMON'u\l"
    .string "yakalayabilirsin.\p"
    .string "Oyunu oynamak ister misin?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "500¥ lütfen!\p"
    .string "Burada sadece özel bir çeşit\n"
    .string "POKé TOPU kullanıyoruz.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER}, görevli tarafından\n"
    .string "30 SAFARİ TOPU aldı.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "Zamanın veya SAFARİ TOPların\n"
    .string "bittiğinde sana anons edeceğiz.\p"
    .string "O zaman, sana bol şans dilerim!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "Tamam.\n"
    .string "Tekrar gelmeyi unutma!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "Oops!\n"
    .string "Yeterli paran yok!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "SAFARİ BÖLGESİ'nden erken ayrılmak\n"
    .string "istiyor musun?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Lütfen kalan SAFARİ TOPlarını geri\n"
    .string "vermeyi unutma.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "Bol şans!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "Sana düşen payı aldın mı?\n"
    .string "Tekrar gelmeyi unutma!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "Merhaba! SAFARİ BÖLGESİ'ne ilk\n"
    .string "kez mi geliyorsun?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "SAFARİ BÖLGESİ aslında içinde\n"
    .string "dört bölgeye sahip.\p"
    .string "Her bölge farklı çeşitlerde\n"
    .string "POKéMON barındırıyor,\l"
    .string "hatta bazıları nadir bulunuyor.\p"
    .string "Verilen SAFARİ TOPlarını\n"
    .string "kullanarak onları yakalayabilirsin.\p"
    .string "Ayrıca SAFARİ TOPlarının yanı\n"
    .string "sıra YEM veya TAŞ da atabilirsin.\p"
    .string "YEM atarsan, POKéMON'un kaçma\n"
    .string "ihtimali azalır, ancak yakalamak\l"
    .string "zorlaşır.\p"
    .string "TAŞ atarsan, POKéMON'un kaçma\n"
    .string "ihtimali artar, ancak yakalamak\l"
    .string "kolaylaşır.\p"
    .string "Zamanın veya SAFARİ TOPların\n"
    .string "bittiğinde oyun sona erer!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "Üzgünüm, sen buranın müdavimisin!$"
