SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Hey?\n"
    .string "Sen misin?$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Sen misin acaba?\n"
    .string "Sen…\p"
    .string "Sen {PLAYER}sin!\p"
    .string "Senden bahsediyorduk!\p"
    .string "Çok iyi bir EĞİTMEN'in ortaya\n"
    .string "çıktığını konuşuyorduk.\p"
    .string "Ve o kişi sensin!\n"
    .string "Çok havalısın!\p"
    .string "Bu yüzden, senin FAN KULÜBÜNÜ\n"
    .string "kurmaya karar verdik!\p"
    .string "Umarız savaşmaya ve bize ne kadar\n"
    .string "havalı olduğunu göstermeye devam\l"
    .string "edersin.\p"
    .string "Böylece, belki de diğerleri senin\n"
    .string "gibi hayran olurlar.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "Her zaman senin için tezahürat\n"
    .string "edeceğim!\p"
    .string "Hadi, {PLAYER}, hadi!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "Her zaman sana inanacağım,\n"
    .string "{PLAYER}.\p"
    .string "Lütfen ciddiye aldığında nasıl\n"
    .string "savaşacağını göster.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "Üzgünüm.\n"
    .string "Önceden senin hayranındım\p"
    .string "Ama şimdi, eskiden sahip\n"
    .string "olduğun etkiyi kaybettiğini\n"
    .string "düşünüyorum.\p"
    .string "Son zamanlarda, {STR_VAR_1}ın daha\n"
    .string "havalı olduğunu düşünüyorum.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Son zamanlarda herkes seninle\n"
    .string "ilgileniyor.\p"
    .string "Bunu anlayabiliyorum.\n"
    .string "Güçlü olduğunu biliyorum.\p"
    .string "Ama, biliyor musun?\p"
    .string "{STR_VAR_1}ın hayranı oldum,\n"
    .string "artık hayranlığını bırakamam.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "EĞİTMEN'lerin savaşırken çok havalı\n"
    .string "olduklarını düşünüyorum.\p"
    .string "Siz de öyle düşünmüyor musunuz?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Oh! {PLAYER} sensin!\n"
    .string "Çok havalı!\p"
    .string "Oh!\n"
    .string "Oh, evet!\p"
    .string "Bir şey imzalayabilir misin?\n"
    .string "Şortum olur mu?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "Ne kadar sıcak olursa olsun…\p"
    .string "Ve ne kadar soğuk olursa olsun…\p"
    .string "Her zaman inandım ve şortlarımı\n"
    .string "giydim!\p"
    .string "Kazanmaya devam edeceğini umuyorum!\p"
    .string "Şortlara inandığım kadar sana\n"
    .string "inanıyorum!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "BROCK kahramanımdır!\n"
    .string "O, erkeklerin erkeğidir!\p"
    .string "Heheh, anneme bir şey yaptırdım.\p"
    .string "Şortlarıma dikişle 'BROCK'\n"
    .string "yazdırdım!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "BROCK'un hayranıyım!\p"
    .string "Eğer tek hayranı olsam bile,\n"
    .string "taş gibi irademe ve şortlarıma\l"
    .string "yemin ederim!\p"
    .string "Acı sona kadar onun hayranı\n"
    .string "olacağım!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "BROCK, adamın hammaddesidir,\n"
    .string "konu kapandı!\p"
    .string "İşte onun gibi olmak istediğim bir\n"
    .string "adam!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, seni savaşırken izlemenin\n"
    .string "keyfini çıkardım.\p"
    .string "Kendi uzun zamandır yitirilmiş\n"
    .string "gençliğimi hatırlatıyor.\p"
    .string "Başarıya devam etmenizi diliyorum.\n"
    .string "Bir hayranın daha var!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Uzun uzun yolculuk yaptım\n"
    .string "uzak topraklarda.\p"
    .string "Ama asla senin kadar muhteşem\n"
    .string "bir EĞİTMEN görmedim.\p"
    .string "Yeteneklerine güven ve\n"
    .string "savaşmaya devam et!\p"
    .string "Bana söz ver,\n"
    .string "genç idolüm!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Hmm…\n"
    .string "Sen kimsin?\p"
    .string "FAN KULÜBÜMÜZE katılmak için mi\n"
    .string "başvuruyorsunuz?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "Ah, çok bahsedilen {PLAYER} sen\n"
    .string "misin?\p"
    .string "Kesinlikle bir şampiyon aurasına\n"
    .string "sahipsin.\p"
    .string "Ama ben seni gerçek bir POKéMON\n"
    .string "ustası olarak kabul etmem için…\p"
    .string "… …\p"
    .string "Daha çok yolun var!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "Burada toplanan herkes POKéMON\n"
    .string "EĞİTMEN'lerinin hayranıdır.\p"
    .string "Savaşırken görünümleri…\n"
    .string "Soğukkanlılığın resmi onlardır.\p"
    .string "Eğer kazanmaya devam edersen,\n"
    .string "belki de burada senden bahsedilir.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "İşte {PLAYER}!\n"
    .string "İşte {PLAYER}!\p"
    .string "Bir gün senin gibi olmak istiyorum!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "Herkes {PLAYER}ın hayranı olmayı\n"
    .string "bıraktı…\p"
    .string "Ama bu {PLAYER}'ın yalnız başına\n"
    .string "olduğu anlamına gelmez!\p"
    .string "Hadi! Ben varım!\n"
    .string "{PLAYER}, göster onlara!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Biliyor musun?\n"
    .string "SABRINA gibi olmak istiyorum!\p"
    .string "Onun gibi bir psişik kız olmak\n"
    .string "istiyorum!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "Tek başıma olsam bile, SABRINA'nın\n"
    .string "hayranı olmayı bırakmam.\p"
    .string "Hayalim aynı SABRINA gibi şirin,\n"
    .string "ama aynı zamanda havalı olmak.\p"
    .string "Onun gibi bir psişik kız olmak\n"
    .string "istiyorum!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Acaba bir gün havalı bir EĞİTMEN\n"
    .string "olabilir miyim?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Oh, adamım, oh, adamım!\n"
    .string "Havalı! Çok havalı!\p"
    .string "…Ha?\n"
    .string "Hayır, sen değilsin.\p"
    .string "Sadece savaş stilin.\n"
    .string "İşte o havalı.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Yo, {PLAYER}!\p"
    .string "Sanırım tek hayranın\n"
    .string "ben kaldım.\p"
    .string "Ama bilirsin, tek hayran olmayı\n"
    .string "severim… Daha az stresli.\p"
    .string "Aynen devam!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} havalı, değil mi?\n"
    .string "Konuşma tarzını çok seviyorum.\p"
    .string "Keşke onunla bir kez tanışma\n"
    .string "şansına erişsem.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Ha, inanabiliyor musun?\n"
    .string "Burada herkes senin hayranın oldu.\p"
    .string "Onca yoldan sonra, sadece ben\n"
    .string "mi {STR_VAR_1} hayranıyım?\p"
    .string "Eh, {STR_VAR_1}'in tek hayranı\n"
    .string "olmak da bana yaraşır zaten.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Oh, aman tanrım!\n"
    .string "Gerçekten sen misin, {PLAYER}?\p"
    .string "Sana söylemeliyim ki, savaş\n"
    .string "stiline imreniyorum.\p"
    .string "Umarım böyle devam edersin.\n"
    .string "Bir numaralı hayranın olacağım!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "Oh, aman tanrım!\n"
    .string "Şu {PLAYER} değil mi!\p"
    .string "Büyük hayal kırıklığı… Farkettim\n"
    .string "ki tek hayranın ben kalmışım!\p"
    .string "Neyse, ne yaparsın ki!\n"
    .string "En azından tezahürat yapayım!\p"
    .string "Hurra, hurra, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "Şu sıralar, {STR_VAR_1}\n"
    .string "ateş gibi.\p"
    .string "Savaş stili… Aynı benim\n"
    .string "sevdiğim gibi!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Oh, merhaba!\n"
    .string "Bu {PLAYER} değil mi!\p"
    .string "Şu sıralar, herkes senden\n"
    .string "bahsediyor.\p"
    .string "Bu konuda yalnızım çünkü ben\n"
    .string "{STR_VAR_1}'ı tercih ederim.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Muazzam!\n"
    .string "{PLAYER}, sen gerçekten müthişsin!\p"
    .string "Belki de izlemek yerine, ben de\n"
    .string "bir EĞİTMEN olmalıyım.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Tek hayranın benim…\n"
    .string "Aah… Bu yalnızlık…\p"
    .string "Biraz daha çabalayıp başkalarının\n"
    .string "gözüne giremez misin?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Usta {STR_VAR_1} çok asil.\n"
    .string "Tam benim tipimden.\p"
    .string "Neden başkaları da onun akan\n"
    .string "asaletini göremiyor?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Ben Usta {STR_VAR_1}'a bütün\n"
    .string "kalbimle inanıyorum.\p"
    .string "Bir tek ben kalsam bile\n"
    .string "ona inanacağım.\p"
    .string "Asla yalnız hissetmem.\p"
    .string "Sürekli usta\n"
    .string "{STR_VAR_1}'ı düşünmedikçe.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Hiyah!\p"
    .string "Savaş stilin aşırı\n"
    .string "öğretici.\p"
    .string "Umarım bu başarılarına devam\n"
    .string "edersin, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "Başkalarını savaşırken izlemek\n"
    .string "yerine, kendin savaş!\p"
    .string "…DOJO USTASI bana bu sözleri\n"
    .string "yedirdi…\p"
    .string "Ama senin hayranın olmaktan\n"
    .string "vazgeçmem!\p"
    .string "Asla!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Hiyah! Sadece tek bir EĞİTMEN'e\n"
    .string "saygı duyarım.\p"
    .string "O da DÖVÜŞ DOJOSU USTASI'ndan\n"
    .string "başkası değildir.\p"
    .string "Bence sen de benim gibi\n"
    .string "USTA'nın hayranı ol! Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Hiyah! DÖVÜŞ DOJOSU USTA'sına\n"
    .string "saygı duyarım.\p"
    .string "USTA'dan başka kişiye\n"
    .string "asla hayran olmam!\p"
    .string "Onun büyüklüğünü yaymak için\n"
    .string "DOJO'dan gizlice kaçarım bile.\p"
    .string "Hiyah!$"

