Route8_Text_AidanIntro::
.string "POKéMON konusunda iyi görünüyorsun,\n"
.string "ama kimya notun nasıl?$"

Route8_Text_AidanDefeat::
.string "Auv!\n"
.string "Erime!$"

Route8_Text_AidanPostBattle::
.string "Okulda bundan daha iyiyim!$"

Route8_Text_StanIntro::
.string "Tamam!\n"
.string "Bir oyun oynayalım!$"

Route8_Text_StanDefeat::
.string "Vay canına!\n"
.string "Hedefime ulaşamadım!$"

Route8_Text_StanPostBattle::
.string "Bugün işler yolunda gitmedi.$"

Route8_Text_GlennIntro::
.string "Bilgili olmalısın.\n"
.string "Kazanmak için stratejiye ihtiyacın var!$"

Route8_Text_GlennDefeat::
.string "Bu mantıklı değil!$"

Route8_Text_GlennPostBattle::
.string "Önce GRIMER ile başla…\n"
.string "Ve sonra…$"

Route8_Text_PaigeIntro::
.string "NIDORAN'ı seviyorum,\n"
.string "bu yüzden onları topluyorum!$"

Route8_Text_PaigeDefeat::
.string "Neden?\n"
.string "Neden??$"

Route8_Text_PaigePostBattle::
.string "POKéMON'lar büyüdüklerinde\n"
.string "çirkinleşiyor.\p"
.string "Bence evrimleşmemeliler.$"

Route8_Text_LeslieIntro::
.string "Okul eğlenceli,\n"
.string "POKéMON'lar da öyle.$"

Route8_Text_LeslieDefeat::
.string "Okula devam etmem gerektiğini\n"
.string "açıkça gösterdin.$"

Route8_Text_LesliePostBattle::
.string "Dışarı biraz hava almaya gidecektim\n"
.string "ama SAFFRON'daki kapılar yüzünden\l"
.string "burada sıkışıp kaldık.$"

Route8_Text_AndreaIntro::
.string "MEOWTH çok tatlı, miyav, miyav,\n"
.string "miyav!$"

Route8_Text_AndreaDefeat::
.string "Miyav!$"

Route8_Text_AndreaPostBattle::
.string "PIDGEY ve RATTATA'nın da\n"
.string "tatlı olduğunu düşünüyorum!$"

Route8_Text_MeganIntro::
.string "Burada böyle dikilmek komik görünüyor.$"

Route8_Text_MeganDefeat::
.string "Tatlı POKéMON'larıma bunu yaptın!$"

Route8_Text_MeganPostBattle::
.string "SAFFRON görevlisi bizi geçirmiyor.\n"
.string "İşini yapıyor, ama bence çok katı.$"

Route8_Text_RichIntro::
.string "Ben bir gezginim, oyun delisiyim!$"

Route8_Text_RichDefeat::
.string "Büyük fırsatı kaçırdım!$"

Route8_Text_RichPostBattle::
.string "Oyun oynamak ve POKéMON yakalamak\n"
.string "fıstık yemek gibi, duramıyorum!$"

Route8_Text_JuliaIntro::
.string "Şirin, yuvarlak ve tüylü\n"
.string "POKéMON hangisidir?$"

Route8_Text_JuliaDefeat::
.string "Dur!\n"
.string "CLEFAIRY'ime karşı\l"
.string "bu kadar sert olma!$"

Route8_Text_JuliaPostBattle::
.string "CLEFAIRY'nin bir AY TAŞI'na maruz\n"
.string "kaldığında evrimleştiğini okudum.\p"
.string "Bir POKéMON dergisinde okudum,\n"
.string "doğru mu acaba?$"

Route8_Text_UndergroundPathSign::
.string "ALT YOL\n"
.string "CELADON ŞEHRİ - LAVENDER KASABASI$"

Route8_Text_EliIntro::
.string "ELI: İkiz gücü fantastiktir.\n"
.string "Biliyor muydunuz?$"

Route8_Text_EliDefeat::
.string "ELI: Ama…\n"
.string "İkiz gücümüzü kullandık…$"

Route8_Text_EliPostBattle::
.string "ELI: POKéMON'umu ANNE\n"
.string "ile yakaladım!$"

Route8_Text_EliNotEnoughMons::
.string "ELI: İki POKéMON'un yoksa\n"
.string "savaşamayız.$"

Route8_Text_AnneIntro::
.string "ANNE: İkiz gücümüzle\n"
.string "seni şaşırtacağız!$"

Route8_Text_AnneDefeat::
.string "ANNE: İkiz gücümüz…$"

Route8_Text_AnnePostBattle::
.string "ANNE: ELI ile POKéMON\n"
.string "yetiştiriyorum.$"

Route8_Text_AnneNotEnoughMons::
.string "ANNE: Merhaba, merhaba! Savaşalım!\n"
.string "Ama iki POKéMON getir.$"

Route8_Text_RicardoIntro::
.string "Bisikletim arızalandı, dostum.$"

Route8_Text_RicardoDefeat::
.string "Ayy, dostum.\n"
.string "Buna ilgi duymuyorum.$"

Route8_Text_RicardoPostBattle::
.string "Tekerlerime çimenler dolandı,\n"
.string "dostum.$"

Route8_Text_JarenIntro::
.string "Yolumu aç, yoksa seni ezerim!$"

Route8_Text_JarenDefeat::
.string "Gerçekten mi, çocuk?$"

Route8_Text_JarenPostBattle::
.string "Sırf bu yüzden kendini\n"
.string "özel ve üstün hissetme.$"
