FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "B-beni ne yapacaksın?\n"
    .string "Niyetin ne?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Oh… Sana zarar vermek\n"
    .string "istemediğine sevindim.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Burada olduğun için çok memnunum.\p"
    .string "Yürümekten sıkıldım ve yorgunum.\p"
    .string "Lütfen beni buradan eve\n"
    .string "götürür müsün?$"
