CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Kız arkadaşıma hediye\n"
    .string "alıyorum.\p"
    .string "Sanırım POKé BEBEK iyi bir hediye\n"
    .string "olur. Popüler bir şeymiş.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "Faydalı bir şey duydum.\p"
    .string "Yabani bir POKéMON çıkarsa, onu\n"
    .string "POKé BEBEK ile oyalayabilirsin.\p"
    .string "Onu oyalarken kaçabilirsin.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Hediyelerle kendini ifade et!\n"
    .string "4. Kat: BİLGİN ADAM HEDİYELERİ\p"
    .string "Evrim Özel İndirimi!\n"
    .string "Element TAŞLARI şimdi satışta!$"
