ViridianCity_House_Text_NicknamingIsFun::
    .string "Takma ad bulmak eğlenceli,\n"
    .string "ama kolay değil. Akıllıca\l"
    .string "adlar güzel, basit adlar\l"
    .string "daha kolay hatırlanır.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Babam da POKéMON seviyor.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Adı: SPEARY$"
