ViridianCity_House_Text_NicknamingIsFun::
    .string "Takma ad bulmak eğlenceli ama\n"
    .string "kolay değil. Düşünülmüş adlar\l"
    .string "güzel, basit adlar ise daha\l"
    .string "kolay hatırlanıyor.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "Babam da POKéMON'ları seviyor.$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: CİK CİK!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Adı: SPEARY$"
