SilphCo_3F_Text_WhatAmIToDo::
    .string "SILPH ŞTİ. için çalışıyorum\n"
    .string "Ne yapmalıyım?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "Sen ve POKéMON'ların bizi kurtardı!$"

SilphCo_3F_Text_GruntIntro::
    .string "Bizi rahat bırak, çocuk!$"

SilphCo_3F_Text_GruntDefeat::
    .string "Pes ediyorum!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "Bir ipucu: Kapıları bir ANAHTAR\n"
    .string "ile açabilirsin!$"

SilphCo_3F_Text_JoseIntro::
    .string "ROKET TAKIMI'nı SILPH ŞTİ'ne\n"
    .string "tercih ederim!$"

SilphCo_3F_Text_JoseDefeat::
    .string "Gerçekten yakalandım!$"

SilphCo_3F_Text_JosePostBattle::
    .string "Hıph…\p"
    .string "ROKET TAKIMI, POKéMON'ları\n"
    .string "incelememe izin vereceklerini\l"
    .string "söyledi.$"

SilphCo_3F_Text_FloorSign::
    .string "SILPH ŞTİ. GENEL MERKEZ\n"
    .string "3. Kat$"

