PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey, bekle!\n"
    .string "Çimlere basma!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: Orası güvenli değil!\n"
    .string "Vahşi POKéMONlar çimenlerde yaşar!\p"
    .string "Güvenliğin için kendi\n"
    .string "POKéMON'una ihtiyacın var.\p"
    .string "Bir fikrim var!\n"
    .string "Gel, beni takip et!$"

PalletTown_Text_RaisingMonsToo::
    .string "Ben de POKéMON yetiştiriyorum.\p"
    .string "Güçlendiklerinde beni koruyabilirler.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Teknoloji bir harika!\p"
    .string "Artık eşyalarını ve POKéMON'ları\n"
    .string "PC'den veri olarak\l"
    .string "aktarabiliyorsun.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON ARAŞTIRMA LABORATUVARI$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'ın evi$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'in evi$"

PalletTown_Text_TownSign::
    .string "PALLET KASABASI\n"
    .string "Yolculuğun için bekle!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Dönmüş olmalısın?\p"
    .string "POKéDEX'ini ne kadar doldurdun?\p"
    .string "Bakabilir miyim?\p"
    .string "Gelin bakalım…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "{STR_VAR_2} yakalamışsın…\p"
    .string "Hm, gerçekten çaba harcıyorsun.\p"
    .string "Biraz daha doldurduğunda, lütfen\n"
    .string "bana göster.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "{STR_VAR_2} yakaladın… Şaşırtıcı!\n"
    .string "Sana bir şey sormak istiyorum,\p"
    .string "{PLAYER}.\p"
    .string "Gel.\n"
    .string "Beni takip et.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Seyahat etmeyi sevmiş gözüküyorsun.\p"
    .string "Bilerek söylüyorum ki, {PLAYER},\n"
    .string "Daha egzotik yerler keşfettiğini\n"
    .string "kolayca hayal edebiliyorum.\p"
    .string "İyi, iyi.\n"
    .string "Hohoho.$"
