PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey, bekle!\n"
    .string "Çimlere basma!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: Orası güvenli değil!\n"
    .string "Vahşi POKéMON'lar çimenlerde yaşar!\p"
    .string "Güvenliğin için kendi POKéMON'una\n"
    .string "ihtiyacın var.\p"
    .string "Bir fikrim var!\n"
    .string "Gel, beni takip et!$"

PalletTown_Text_RaisingMonsToo::
    .string "Ben de POKéMON yetiştiriyorum.\n"
    .string "Böylece güçlendiklerinde beni\lkoruyabilirler.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Teknoloji bir harika!\p"
    .string "Artık eşyalarını ve POKéMON'ları\n"
    .string "PC'den veri olarak aktarabiliyorsun.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON ARAŞTIRMA LABORATUVARI$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'ın evi$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'in evi$"

PalletTown_Text_TownSign::
    .string "PALLET KASABASI\n"
    .string "Maceran seni bekliyor!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Dönmüş olmalısın?\p"
    .string "POKéDEX'ini ne kadar doldurdun?\p"
    .string "Bakabilir miyim?\p"
    .string "Bir bakalım…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "{STR_VAR_2} yakalamışsın…\p"
    .string "Hm, gerçekten çaba harcıyorsun.\p"
    .string "Biraz daha doldurduğunda, lütfen\n"
    .string "bana göster.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "{STR_VAR_2} yakaladın… Şaşırtıcı!\n"
    .string "Sana bir şey sormak istiyorum,\p"
    .string "{PLAYER}.\p"
    .string "Gel.\n"
    .string "Beni takip et.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "Seyahat etmeyi sevmiş gözüküyorsun.\p"
    .string "Çok daha egzotik yerler keşfedeceğine\n"
    .string "inancım tam, {PLAYER}.\p"
    .string "Hohoho.$"
