ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "LOSTELLE: *Hıçk*… *Burun çeker*…\n"
    .string "Ah! Lütfen yardım edin!\p"
    .string "Biraz önce orada ürkütücü\n"
    .string "bir POKéMON belirdi.\l"
    .string "Korkutmaya devam etti.\n"
    .string "LOSTELLE'yi korkuttu.\p"
    .string "Korkudan hareket edemiyorum!\n"
    .string "Ama eve gitmek istiyorum…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Ah! Tekrar geldi!\n"
    .string "Hayır! Git! Beni korkutuyor!\p"
    .string "Waaaaaaah!\n"
    .string "Babamı istiyorum!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "Ohh! O kadar korkutucuydu ki!\n"
    .string "Teşekkür ederim!\p"
    .string "LOSTELLE biraz MEYVE toplamaya\n"
    .string "gelmişti. Bunu alabilirsin!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "Adın ne?\p"
    .string "LOSTELLE korktuğu için babamın\n"
    .string "evine benimle gelebilir misin?\p"
    .string "Tamam!\n"
    .string "Eve gidelim!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "MEYVE ÇANTASI dolu.\n"
    .string "Sanırım bunu istemiyorsun.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "MEYVE ORMANINA hoş geldiniz\p"
    .string "Misafirperver olun ve MEYVE'leri\n"
    .string "başkalarıyla ve POKéMON'larla\l"
    .string "paylaşın.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Yabani, MEYVE seven POKéMON'lara\n"
    .string "dikkat edin!$"
