CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .string "POKéMON mu?\n"
    .string "Hayır, burası insanlar için bir\l"
    .string "otel.\p"
    .string "Maalesef yerimiz dolu.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "Kardeşimle ve erkek arkadaşımla\n"
    .string "tatildeyim.\p"
    .string "CELADON ne kadar güzel bir şehir!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .string "Neden?\n"
    .string "Neden erkek kardeşini getirdi ki?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yuppi! Tatildeyim!\n"
    .string "Ablam beni de getirdi! Harika!$"
