FourIsland_Text_IslandSign::
    .string "DÖRDÜNCÜ ADA\n"
    .string "Sıcak, Mavi, Buz Adası$"

FourIsland_Text_LoreleiHasReturned::
    .string "LORELEI geri döndü.\p"
    .string "Şehir hayatı ona çok mu\n"
    .string "stresli geldi, merak ediyorum?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "LORELEI geri döndü.\p"
    .string "LAPRAS'ı, çocukken karşılaştığı\n"
    .string "LAPRAS'a benziyor.\p"
    .string "Sanırım onu ICEFALL MAĞARASI'nda\n"
    .string "yakaladı.\p"
    .string "O POKéMON belki de o zamandan\n"
    .string "beri onunla.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: Hey!\n"
    .string "{PLAYER}!\p"
    .string "SEVII ADALARI'nda ne yapıyorsun?\p"
    .string "Beni taklit etmeyi bıraksan\n"
    .string "olmaz mı?\p"
    .string "Her neyse, zaten POKéMON\n"
    .string "YUMURTASI'nı aldım, bu adadan\l"
    .string "ayrılıyorum.\p"
    .string "Hehe, senin kesin POKéMON\n"
    .string "YUMURTALARI'ndan haberin\l"
    .string "bile yoktur.\p"
    .string "Böylece asla YEREL POKéDEX'ini\n"
    .string "tamamlayamayacaksın.\p"
    .string "Bu arada, burada ikimizin de\n"
    .string "tanıdığı birini gördüm.\p"
    .string "Merak ediyorsan, adada biraz\n"
    .string "dolaşmaya ne dersin?\p"
    .string "Benim vakit kaybetmeye\n"
    .string "zamanım yok.\p"
    .string "Görüşürüz!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "Oh, beni buldun!\n"
    .string "Lütfen LORELEI'ye söyleme.\p"
    .string "LORELEI'nin çok sayıda peluş\n"
    .string "oyuncağı olduğunu biliyor muydun?\p"
    .string "DÖRDÜNCÜ ADA'ya her gelişinde\n"
    .string "koleksiyonu büyüyor!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "Brr, üşüdüm!\p"
    .string "ICEFALL MAĞARASI'ndan aldığım\n"
    .string "buzu kullanarak bir içecek\l"
    .string "yaptım.\p"
    .string "Soğuk ve lezzetli!$"

FourIsland_Text_LoreleisHouse::
    .string "LORELEI'NİN EVİ$"
